// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuAccelerateOurPlans = {
  title: "Accelerate Our Plans",
  cost: 1,
  text: "Exhaust a friendly unit. If you do, attack with another unit. It gets +3/+0 for this attack.",
  unique: false,
  rules:
    "If you exhaust a friendly unit with Accelerate Our Plans, you must attack with a unit, if able. Units must be ready in order to attack.\n",
  id: "6471963627",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["plan"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 228,
  },
  setCodes: [
    {
      set: "SEC",
      number: 228,
    },
  ],
  internalName: "accelerate-our-plans",
  cardType: "event",
  canonicalId: "accelerate-our-plans",
  slug: "accelerate-our-plans",
  name: "Accelerate Our Plans",
  printings: [
    {
      id: "SEC_228",
      artId: "40515",
      setCode: "SEC",
      collectorNumber: "228",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06010228_EN_Accelerate_Our_Plans_e23b82f72e.png",
    },
    {
      id: "8702973856",
      artId: "40515",
      setCode: "SEC",
      collectorNumber: "492",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06020492_EN_Accelerate_Our_Plans_72f8878821.png",
    },
    {
      id: "2154113905",
      artId: "40515",
      setCode: "SEC",
      collectorNumber: "738",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06310738_EN_Accelerate_Our_Plans_16843427e8.png",
    },
    {
      id: "4510781403",
      artId: "40515",
      setCode: "SEC",
      collectorNumber: "984",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06320984_EN_Accelerate_Our_Plans_fd195f33fc.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Exhaust a friendly unit. If you do, attack with another unit. It gets +3/+0 for this attack.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "exhaust",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuAccelerateOurPlans;
