// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuArrest = {
  title: "Arrest",
  cost: 2,
  text: "Your base captures an enemy non-leader unit. At the start of the regroup phase, its owner rescues it.",
  unique: false,
  rules:
    "A base capturing a unit functions similarly to a unit capturing another unit. The captured unit is placed facedown under the base, out of play, and the base guards that unit. The captured unit can be rescued so long as the rescue ability doesn't specify that a unit is guarding the captured unit.\n",
  id: "1407380526",
  rarity: "rare",
  aspects: ["cunning", "villainy"],
  traits: ["law"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 195,
  },
  setCodes: [
    {
      set: "SEC",
      number: 195,
    },
  ],
  internalName: "arrest",
  cardType: "event",
  canonicalId: "arrest",
  slug: "arrest",
  name: "Arrest",
  printings: [
    {
      id: "SEC_195",
      artId: "40350",
      setCode: "SEC",
      collectorNumber: "195",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06010195_EN_Arrest_0e7dda6632.png",
    },
    {
      id: "2010869776",
      artId: "40350",
      setCode: "SEC",
      collectorNumber: "459",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06020459_EN_Arrest_28147b6fa9.png",
    },
    {
      id: "1145426396",
      artId: "40350",
      setCode: "SEC",
      collectorNumber: "705",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06310705_EN_Arrest_ef8f66425d.png",
    },
    {
      id: "0945098611",
      artId: "40350",
      setCode: "SEC",
      collectorNumber: "951",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06320951_EN_Arrest_6599298487.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Your base captures an enemy non-leader unit. At the start of the regroup phase, its owner rescues it.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "capture",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuArrest;
