// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuChargedWithEspionage = {
  title: "Charged with Espionage",
  cost: 2,
  text: "You may disclose CunningCunning (reveal cards from your hand with these aspect icons among them). If you do, look at an opponent's hand and discard a unit from it.",
  unique: false,
  id: "5521821831",
  rarity: "uncommon",
  aspects: ["cunning"],
  traits: ["law"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 230,
  },
  setCodes: [
    {
      set: "SEC",
      number: 230,
    },
  ],
  internalName: "charged-with-espionage",
  cardType: "event",
  abilities: [
    ability.action({
      text: "You may disclose CunningCunning. If you do, look at an opponent's hand and discard a unit from it.",
      optional: true,
      effects: [
        effect.lookAt(target.card({ controller: "opponent", zones: ["hand"] })),
        effect.discard(target.unit({ controller: "opponent", zones: ["hand"], limit: 1 })),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuChargedWithEspionage;
