// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuContemptForCulture = {
  title: "Contempt for Culture",
  cost: 2,
  text: "Deal 2 damage to a non-Vehicle unit.\nCreate a Spy token.",
  unique: false,
  id: "8056594889",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["innate"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 246,
  },
  setCodes: [
    {
      set: "SEC",
      number: 246,
    },
  ],
  internalName: "contempt-for-culture",
  cardType: "event",
  canonicalId: "contempt-for-culture",
  slug: "contempt-for-culture",
  name: "Contempt for Culture",
  printings: [
    {
      id: "SEC_246",
      artId: "40605",
      setCode: "SEC",
      collectorNumber: "246",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06010246_EN_Contempt_for_Culture_3ef53f6a26.png",
    },
    {
      id: "3503578856",
      artId: "40605",
      setCode: "SEC",
      collectorNumber: "510",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06020510_EN_Contempt_for_Culture_5b145e4220.png",
    },
    {
      id: "9636587657",
      artId: "40605",
      setCode: "SEC",
      collectorNumber: "756",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06310756_EN_Contempt_for_Culture_bebb0e6406.png",
    },
    {
      id: "3192121521",
      artId: "40605",
      setCode: "SEC",
      collectorNumber: "1002",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06321002_EN_Contempt_for_Culture_7f3a2b76f0.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Deal 2 damage to a non-Vehicle unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "Create a Spy token.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "spy",
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuContemptForCulture;
