// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuConveneTheSenate = {
  title: "Convene the Senate",
  cost: 3,
  text: "Search the top 8 cards of your deck for up to 2 Official units, reveal them, and draw them. (Put the other cards on the bottom of your deck in a random order.)\nCreate a Spy token.",
  unique: false,
  rules:
    "After searching, put any cards not chosen on the bottom of your deck in a random order.\n",
  id: "5001969384",
  rarity: "uncommon",
  aspects: ["command"],
  traits: ["law"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 128,
  },
  setCodes: [
    {
      set: "SEC",
      number: 128,
    },
  ],
  internalName: "convene-the-senate",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Search the top 8 cards of your deck for up to 2 Official units, reveal them, and draw them. (Put the other cards on the bottom of your deck in a random order.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "search",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          destination: "hand",
          reveal: true,
        },
      ],
    },
    {
      kind: "triggered",
      text: "Create a Spy token.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "spy",
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuConveneTheSenate;
