// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuReconnaissance = {
  title: "Reconnaissance",
  cost: 2,
  text: "If you control a ground unit and a space unit, draw 2 cards.",
  unique: false,
  id: "7947982615",
  rarity: "common",
  aspects: ["command"],
  traits: ["plan"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 125,
  },
  setCodes: [
    {
      set: "SEC",
      number: 125,
    },
  ],
  internalName: "reconnaissance",
  cardType: "event",
  abilities: [
    ability.action({
      text: "If you control a ground unit and a space unit, draw 2 cards.",
      conditions: [
        {
          type: "hasTarget",
          target: target.unit({ controller: "friendly", arena: "ground", limit: 1 }),
        },
        {
          type: "hasTarget",
          target: target.unit({ controller: "friendly", arena: "space", limit: 1 }),
        },
      ],
      effects: [effect.draw("friendly", 2)],
    }),
  ],
} satisfies SwuEventCard;

export default swuReconnaissance;
