// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuToppleTheSummit = {
  title: "Topple the Summit",
  cost: 5,
  text: "Deal 3 damage to each damaged unit.\nPlot (When you deploy a leader, you may play this card from your resources, paying its cost. Replace it with the top card of your deck.)",
  unique: false,
  id: "8401985446",
  rarity: "rare",
  aspects: ["aggression"],
  traits: ["plan"],
  keywords: ["plot"],
  types: ["event"],
  setId: {
    set: "SEC",
    number: 183,
  },
  setCodes: [
    {
      set: "SEC",
      number: 183,
    },
  ],
  internalName: "topple-the-summit",
  cardType: "event",
  canonicalId: "topple-the-summit",
  slug: "topple-the-summit",
  name: "Topple the Summit",
  printings: [
    {
      id: "SEC_183",
      artId: "40290",
      setCode: "SEC",
      collectorNumber: "183",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06010183_EN_Topple_the_Summit_9f198b6a2c.png",
    },
    {
      id: "5057131706",
      artId: "40290",
      setCode: "SEC",
      collectorNumber: "447",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06020447_EN_Topple_the_Summit_d82f3cefcb.png",
    },
    {
      id: "7252045855",
      artId: "40290",
      setCode: "SEC",
      collectorNumber: "693",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06310693_EN_Topple_the_Summit_a9963e64b4.png",
    },
    {
      id: "1721140943",
      artId: "40290",
      setCode: "SEC",
      collectorNumber: "939",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06320939_EN_Topple_the_Summit_db8017e52e.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Plot",
      keyword: "plot",
    },
    {
      kind: "triggered",
      text: "Deal 3 damage to each damaged unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 3,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuToppleTheSummit;
