// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAlexsandrKallusWithNewPurpose = {
  title: "Alexsandr Kallus",
  subtitle: "With New Purpose",
  cost: 7,
  hp: 6,
  power: 6,
  text: "While you have the initiative, each other friendly <uq> (unique) unit gains Raid 2.\nWhen Played: Deal 2 damage to each of up to 3 ground units.",
  unique: true,
  id: "6009912241",
  rarity: "rare",
  aspects: ["aggression", "heroism"],
  traits: ["rebel", "spectre"],
  arena: "ground",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 155,
  },
  setCodes: [
    {
      set: "SEC",
      number: 155,
    },
  ],
  internalName: "alexsandr-kallus#with-new-purpose",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "triggered",
      text: "When Played: Deal 2 damage to each of up to 3 ground units.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            arena: "ground",
            excludeSelf: false,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuAlexsandrKallusWithNewPurpose;
