// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCruelCommandos = {
  title: "Cruel Commandos",
  cost: 5,
  hp: 5,
  power: 5,
  text: "Sentinel (Enemy units in this arena must attack a Sentinel when they attack you.)\nOverwhelm (When attacking an enemy unit, deal excess damage to the opponent's base.)",
  unique: false,
  rules:
    "Shields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\n",
  id: "6411224332",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["republic", "clone", "trooper"],
  arena: "ground",
  keywords: ["sentinel", "overwhelm"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 86,
  },
  setCodes: [
    {
      set: "SEC",
      number: 86,
    },
  ],
  internalName: "cruel-commandos",
  cardType: "unit",
  canonicalId: "cruel-commandos",
  slug: "cruel-commandos",
  name: "Cruel Commandos",
  printings: [
    {
      id: "SEC_086",
      artId: "39805",
      setCode: "SEC",
      collectorNumber: "86",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06010086_EN_Cruel_Commandos_fb157e5aaf.png",
    },
    {
      id: "0138965703",
      artId: "39805",
      setCode: "SEC",
      collectorNumber: "350",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06020350_EN_Cruel_Commandos_967c8d03d9.png",
    },
    {
      id: "7278190216",
      artId: "39805",
      setCode: "SEC",
      collectorNumber: "596",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06310596_EN_Cruel_Commandos_d23cce5c14.png",
    },
    {
      id: "1053884592",
      artId: "39805",
      setCode: "SEC",
      collectorNumber: "842",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06320842_EN_Cruel_Commandos_92eb68b1ee.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
  ],
} satisfies SwuUnitCard;

export default swuCruelCommandos;
