// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDarthTrayaLordOfBetrayal = {
  title: "Darth Traya",
  subtitle: "Lord of Betrayal",
  cost: 3,
  hp: 5,
  power: 2,
  text: "On Attack: You may ready a non-unit leader.",
  unique: true,
  id: "4195599545",
  rarity: "legendary",
  aspects: ["cunning", "villainy"],
  traits: ["force", "sith"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 188,
  },
  setCodes: [
    {
      set: "SEC",
      number: 188,
    },
  ],
  internalName: "darth-traya#lord-of-betrayal",
  cardType: "unit",
  canonicalId: "darth-traya#lord-of-betrayal",
  slug: "darth-traya-lord-of-betrayal",
  name: "Darth Traya",
  printings: [
    {
      id: "SEC_188",
      artId: "40315",
      setCode: "SEC",
      collectorNumber: "188",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//06010188_EN_Darth_Traya_0619ce926c.png",
    },
    {
      id: "1481929823",
      artId: "40315",
      setCode: "SEC",
      collectorNumber: "452",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//06020452_EN_Darth_Traya_4dd2f259db.png",
    },
    {
      id: "7082391126",
      artId: "40315",
      setCode: "SEC",
      collectorNumber: "698",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//06310698_EN_Darth_Traya_5f50e42b69.png",
    },
    {
      id: "3372161222",
      artId: "40315",
      setCode: "SEC",
      collectorNumber: "944",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//06320944_EN_Darth_Traya_75d0525c6f.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "On Attack: You may ready a non-unit leader.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "ready",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuDarthTrayaLordOfBetrayal;
