// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDarthSionLordOfPain = {
  title: "Darth Sion",
  subtitle: "Lord of Pain",
  cost: 5,
  hp: 5,
  power: 5,
  text: "When Played: Give an Experience token to this unit for each enemy unit that was defeated this phase.\nWhen Defeated: If this unit had 7 or more power, return him to his owner's hand.",
  unique: true,
  rules:
    'Darth Sion\'s "When Defeated" ability references his power when he was defeated, which includes temporary modifiers.\nDarth Sion\'s "When Defeated" ability only returns him to hand if he is in the discard pile when it resolves.\n',
  id: "3182035434",
  rarity: "legendary",
  aspects: ["vigilance", "villainy"],
  traits: ["force", "sith"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 35,
  },
  setCodes: [
    {
      set: "SEC",
      number: 35,
    },
  ],
  internalName: "darth-sion#lord-of-pain",
  cardType: "unit",
  abilities: [
    ability.whenPlayed({
      text: "When Played: Give an Experience token to this unit for each enemy unit that was defeated this phase.",
      conditions: [
        {
          type: "unitsDefeatedThisPhase",
          controller: "opponent",
          comparison: { operator: "gte", value: 1 },
        },
      ],
      effects: [effect.distribute("experience", target.self(), 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuDarthSionLordOfPain;
