// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDedraMeeroWithVerifiableData = {
  title: "Dedra Meero",
  subtitle: "With Verifiable Data",
  cost: 6,
  hp: 5,
  power: 5,
  text: "Ambush (When you play this unit, it may attack an enemy unit.)\nOn Attack: Create a Spy token.",
  unique: true,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "8167114067",
  rarity: "uncommon",
  aspects: ["command", "villainy"],
  traits: ["imperial", "official"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 87,
  },
  setCodes: [
    {
      set: "SEC",
      number: 87,
    },
  ],
  internalName: "dedra-meero#with-verifiable-data",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
    {
      kind: "triggered",
      text: "On Attack: Create a Spy token.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "createToken",
          token: "spy",
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuDedraMeeroWithVerifiableData;
