// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDuchesssInvestigators = {
  title: "Duchess's Investigators",
  cost: 5,
  hp: 4,
  power: 4,
  text: "When Played: You may disclose Cunning (reveal a card from your hand with this aspect icon). If you do, each opponent discards a random card from their hand.",
  unique: false,
  id: "6838167753",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["mandalorian"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 223,
  },
  setCodes: [
    {
      set: "SEC",
      number: 223,
    },
  ],
  internalName: "duchesss-investigators",
  cardType: "unit",
  abilities: [
    ability.whenPlayed({
      text: "When Played: You may disclose Cunning. If you do, each opponent discards a random card from their hand.",
      optional: true,
      effects: [effect.discard(target.card({ controller: "opponent", zones: ["hand"], limit: 1 }))],
    }),
  ],
} satisfies SwuUnitCard;

export default swuDuchesssInvestigators;
