// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuEliaKaneFalseConvert = {
  title: "Elia Kane",
  subtitle: "False Convert",
  cost: 4,
  hp: 6,
  power: 3,
  text: "Raid 1 (This unit gets +1/+0 while attacking.)\nWhen Played: Look at 3 enemy resources. You may defeat 1 of them. If you do, its controller puts the top card of their deck into play as a resource and readies it.",
  unique: true,
  id: "9039562488",
  rarity: "uncommon",
  aspects: ["villainy"],
  traits: ["imperial", "new republic"],
  arena: "ground",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 242,
  },
  setCodes: [
    {
      set: "SEC",
      number: 242,
    },
  ],
  internalName: "elia-kane#false-convert",
  cardType: "unit",
  canonicalId: "elia-kane#false-convert",
  slug: "elia-kane-false-convert",
  name: "Elia Kane",
  printings: [
    {
      id: "SEC_242",
      artId: "40585",
      setCode: "SEC",
      collectorNumber: "242",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06010242_EN_Elia_Kane_3053751da0.png",
    },
    {
      id: "2746381548",
      artId: "40585",
      setCode: "SEC",
      collectorNumber: "506",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06020506_EN_Elia_Kane_5f3a90cf30.png",
    },
    {
      id: "3418551098",
      artId: "40585",
      setCode: "SEC",
      collectorNumber: "752",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06310752_EN_Elia_Kane_9aa242c917.png",
    },
    {
      id: "4975323896",
      artId: "40585",
      setCode: "SEC",
      collectorNumber: "998",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06320998_EN_Elia_Kane_970eeeeb89.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
  ],
} satisfies SwuUnitCard;

export default swuEliaKaneFalseConvert;
