// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuFulminatrixFleetKiller = {
  title: "Fulminatrix",
  subtitle: "Fleet Killer",
  cost: 8,
  hp: 7,
  power: 9,
  text: "When Played/On Attack: You may deal 4 damage to a ground unit.",
  unique: true,
  id: "2460309477",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["first order", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 142,
  },
  setCodes: [
    {
      set: "SEC",
      number: 142,
    },
  ],
  internalName: "fulminatrix#fleet-killer",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played/On Attack: You may deal 4 damage to a ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 4,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
    {
      kind: "triggered",
      text: "When Played/On Attack: You may deal 4 damage to a ground unit.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 4,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuFulminatrixFleetKiller;
