// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuHiredSlicer = {
  title: "Hired Slicer",
  cost: 3,
  hp: 4,
  power: 3,
  text: "On Attack: Reveal the top 2 cards of a deck. If you do, you may exhaust a unit that shares a Trait with one of those cards. Put those cards on the bottom of that deck in a random order.",
  unique: false,
  id: "1504187296",
  rarity: "uncommon",
  aspects: ["cunning"],
  traits: ["fringe"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 220,
  },
  setCodes: [
    {
      set: "SEC",
      number: 220,
    },
  ],
  internalName: "hired-slicer",
  cardType: "unit",
  abilities: [
    ability.onAttack({
      text: "On Attack: Reveal the top 2 cards of a deck. If you do, you may exhaust a unit that shares a Trait with one of those cards. Put those cards on the bottom of that deck in a random order.",
      effects: [
        effect.reveal(target.card({ zones: ["deck"], limit: 2 })),
        effect.exhaust(target.unit({ limit: 1 })),
        effect.reorder(target.card({ zones: ["deck"], limit: 2 }), "bottomOfDeck", "random"),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuHiredSlicer;
