// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHuttCartelStarfighter = {
  title: "Hutt Cartel Starfighter",
  cost: 3,
  hp: 5,
  power: 3,
  text: "When Played: Deal 2 damage to this unit.",
  unique: false,
  id: "4052082238",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["underworld", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 240,
  },
  setCodes: [
    {
      set: "SEC",
      number: 240,
    },
  ],
  internalName: "hutt-cartel-starfighter",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Deal 2 damage to this unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 2,
          target: {
            type: "self",
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuHuttCartelStarfighter;
