// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuJuniorSenator = {
  title: "Junior Senator",
  cost: 2,
  hp: 2,
  power: 3,
  text: "When Played: You may return an upgrade that costs 3 or less to its owner's hand.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\nAbilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "1213577854",
  rarity: "common",
  aspects: ["cunning", "heroism"],
  traits: ["republic", "official"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 200,
  },
  setCodes: [
    {
      set: "SEC",
      number: 200,
    },
  ],
  internalName: "junior-senator",
  cardType: "unit",
  canonicalId: "junior-senator",
  slug: "junior-senator",
  name: "Junior Senator",
  printings: [
    {
      id: "SEC_200",
      artId: "40375",
      setCode: "SEC",
      collectorNumber: "200",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06010200_EN_Junior_Senator_a712009db5.png",
    },
    {
      id: "5227501245",
      artId: "40375",
      setCode: "SEC",
      collectorNumber: "464",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06020464_EN_Junior_Senator_ec4490c59f.png",
    },
    {
      id: "7508398934",
      artId: "40375",
      setCode: "SEC",
      collectorNumber: "710",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06310710_EN_Junior_Senator_89a8f10ce7.png",
    },
    {
      id: "7072588597",
      artId: "40375",
      setCode: "SEC",
      collectorNumber: "956",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//06320956_EN_Junior_Senator_e98136f21b.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may return an upgrade that costs 3 or less to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "move",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["upgrade"],
                limit: 1,
              },
              to: "hand",
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuJuniorSenator;
