// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuKaydelConnixForOurSurvival = {
  title: "Kaydel Connix",
  subtitle: "For Our Survival",
  cost: 3,
  hp: 2,
  power: 3,
  text: "When Played: You may defeat all non-<uq> (non-unique) upgrades on a unit.\nPlot (When you deploy a leader, you may play this card from your resources, paying its cost. Replace it with the top card of your deck.)",
  unique: true,
  id: "0602708575",
  rarity: "uncommon",
  aspects: ["aggression", "heroism"],
  traits: ["resistance"],
  arena: "ground",
  keywords: ["plot"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 149,
  },
  setCodes: [
    {
      set: "SEC",
      number: 149,
    },
  ],
  internalName: "kaydel-connix#for-our-survival",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Plot",
      keyword: "plot",
    },
    {
      kind: "triggered",
      text: "When Played: You may defeat all non-<uq> (non-unique) upgrades on a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "defeat",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["upgrade"],
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuKaydelConnixForOurSurvival;
