// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLobotCloudCityCoordinator = {
  title: "Lobot",
  subtitle: "Cloud City Coordinator",
  cost: 2,
  hp: 4,
  power: 0,
  text: "Sentinel (Enemy units in this arena must attack a Sentinel when they attack you.)\nGrit (This unit gets +1/+0 for each damage on him.)",
  unique: true,
  id: "5843701855",
  rarity: "uncommon",
  aspects: ["vigilance"],
  traits: ["fringe"],
  arena: "ground",
  keywords: ["sentinel", "grit"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 57,
  },
  setCodes: [
    {
      set: "SEC",
      number: 57,
    },
  ],
  internalName: "lobot#cloud-city-coordinator",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
    {
      kind: "keyword",
      text: "Grit",
      keyword: "grit",
    },
  ],
} satisfies SwuUnitCard;

export default swuLobotCloudCityCoordinator;
