// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuMaarvaAndorWeveBeenSleeping = {
  title: "Maarva Andor",
  subtitle: "We've Been Sleeping",
  cost: 3,
  hp: 4,
  power: 3,
  text: "When Defeated: Give an Experience token to each friendly Rebel unit.",
  unique: true,
  id: "0390492118",
  rarity: "uncommon",
  aspects: ["heroism"],
  traits: ["rebel"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 252,
  },
  setCodes: [
    {
      set: "SEC",
      number: 252,
    },
  ],
  internalName: "maarva-andor#weve-been-sleeping",
  cardType: "unit",
  canonicalId: "maarva-andor#weve-been-sleeping",
  slug: "maarva-andor-weve-been-sleeping",
  name: "Maarva Andor",
  printings: [
    {
      id: "SEC_252",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "252",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06010252_EN_Maarva_Andor_d3bff81acb.png",
    },
    {
      id: "9615591080",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "516",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06020516_EN_Maarva_Andor_61119dce48.png",
    },
    {
      id: "8576066328",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "762",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06310762_EN_Maarva_Andor_498672dd49.png",
    },
    {
      id: "7751402260",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "1008",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06321008_EN_Maarva_Andor_4f8ca7708d.png",
    },
    {
      id: "4237768777",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "1068",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06061068_EN_Maarva_Andor_Carb_A_552b290329.png",
    },
    {
      id: "1693696663",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "1111",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06331111_EN_Maarva_Andor_Carb_B_3c1666f4a6.png",
    },
    {
      id: "1570747850",
      artId: "40635",
      setCode: "SEC",
      collectorNumber: "1154",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//06341154_EN_Maarva_Andor_Carb_C_458003bae6.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Defeated: Give an Experience token to each friendly Rebel unit.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "distribute",
          mode: "experience",
          amount: 1,
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuMaarvaAndorWeveBeenSleeping;
