// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuNubianStarSkiff = {
  title: "Nubian Star Skiff",
  cost: 4,
  hp: 4,
  power: 4,
  text: "While you control an Official unit, this unit gains Restore 2. (When this unit attacks, heal 2 damage from your base.)",
  unique: false,
  id: "7241924417",
  rarity: "common",
  aspects: ["command"],
  traits: ["naboo", "vehicle", "transport"],
  arena: "space",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 116,
  },
  setCodes: [
    {
      set: "SEC",
      number: 116,
    },
  ],
  internalName: "nubian-star-skiff",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuNubianStarSkiff;
