// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRepublicWarWalker = {
  title: "Republic War Walker",
  cost: 6,
  hp: 6,
  power: 7,
  text: "Overwhelm (When attacking an enemy unit, deal excess damage to the opponent's base.)",
  unique: false,
  rules:
    "Shields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\n",
  id: "5932264704",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["republic", "vehicle", "walker"],
  arena: "ground",
  keywords: ["overwhelm"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 173,
  },
  setCodes: [
    {
      set: "SEC",
      number: 173,
    },
  ],
  internalName: "republic-war-walker",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
  ],
} satisfies SwuUnitCard;

export default swuRepublicWarWalker;
