// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuSoullessOneSwiftAndAgile = {
  title: "Soulless One",
  subtitle: "Swift and Agile",
  cost: 3,
  hp: 3,
  power: 3,
  text: "On Attack: You may disclose CunningCunningVillainy (reveal cards from your hand with these aspect icons among them). If you do, ready 2 resources.",
  unique: true,
  id: "3595837658",
  rarity: "uncommon",
  aspects: ["cunning", "villainy"],
  traits: ["separatist", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 190,
  },
  setCodes: [
    {
      set: "SEC",
      number: 190,
    },
  ],
  internalName: "soulless-one#swift-and-agile",
  cardType: "unit",
  abilities: [
    ability.onAttack({
      text: "On Attack: You may disclose CunningCunningVillainy. If you do, ready 2 resources.",
      optional: true,
      effects: [
        effect.ready(target.card({ controller: "friendly", zones: ["resource"], limit: 2 })),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuSoullessOneSwiftAndAgile;
