// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheMandalorianCleaningUpNevarro = {
  title: "The Mandalorian",
  subtitle: "Cleaning Up Nevarro",
  cost: 8,
  hp: 8,
  power: 6,
  text: "Ambush\nWhen this unit attacks and defeats a unit: You may choose an enemy non-leader unit. This unit captures it.",
  unique: true,
  rules:
    'Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\nA unit "attacks and defeats a unit" if it defeats the defender at any point during the attack.\n',
  id: "7522568119",
  rarity: "rare",
  aspects: ["cunning", "heroism"],
  traits: ["mandalorian", "bounty hunter"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 209,
  },
  setCodes: [
    {
      set: "SEC",
      number: 209,
    },
  ],
  internalName: "the-mandalorian#cleaning-up-nevarro",
  cardType: "unit",
  canonicalId: "the-mandalorian#cleaning-up-nevarro",
  slug: "the-mandalorian-cleaning-up-nevarro",
  name: "The Mandalorian",
  printings: [
    {
      id: "SEC_209",
      artId: "40420",
      setCode: "SEC",
      collectorNumber: "209",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06010209_EN_The_Mandalorian_8fbac7ec35.png",
    },
    {
      id: "0067663542",
      artId: "40420",
      setCode: "SEC",
      collectorNumber: "473",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06020473_EN_The_Mandalorian_56b8bb69be.png",
    },
    {
      id: "6668883452",
      artId: "40420",
      setCode: "SEC",
      collectorNumber: "719",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06310719_EN_The_Mandalorian_91d4e5cd02.png",
    },
    {
      id: "3902860262",
      artId: "40420",
      setCode: "SEC",
      collectorNumber: "965",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//06320965_EN_The_Mandalorian_0657bf69c0.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuTheMandalorianCleaningUpNevarro;
