// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheChancellorsShuttleGrimHarbinger = {
  title: "The Chancellor's Shuttle",
  subtitle: "Grim Harbinger",
  cost: 2,
  hp: 3,
  power: 1,
  text: "Restore 1\nWhen Defeated: If you control Chancellor Palpatine (as a leader or unit), you may give an Experience token to a unit.",
  unique: true,
  id: "3052170248",
  rarity: "special",
  aspects: ["vigilance", "villainy"],
  traits: ["republic", "vehicle", "transport"],
  arena: "space",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "SEC",
    number: 27,
  },
  setCodes: [
    {
      set: "SEC",
      number: 27,
    },
  ],
  internalName: "the-chancellors-shuttle#grim-harbinger",
  cardType: "unit",
  canonicalId: "the-chancellors-shuttle#grim-harbinger",
  slug: "the-chancellors-shuttle-grim-harbinger",
  name: "The Chancellor's Shuttle",
  printings: [
    {
      id: "SEC_027",
      artId: "39510",
      setCode: "SEC",
      collectorNumber: "27",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06010027_EN_The_Chancellor_s_Shuttle_d28c3a68b6.png",
    },
    {
      id: "6002482873",
      artId: "39510",
      setCode: "SEC",
      collectorNumber: "291",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06020291_EN_The_Chancellor_s_Shuttle_158a624cc3.png",
    },
    {
      id: "5410742814",
      artId: "39510",
      setCode: "SEC",
      collectorNumber: "537",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06310537_EN_The_Chancellor_s_Shuttle_62b7bce188.png",
    },
    {
      id: "8040698826",
      artId: "39510",
      setCode: "SEC",
      collectorNumber: "783",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06320783_EN_The_Chancellor_s_Shuttle_fc0692d0c5.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuTheChancellorsShuttleGrimHarbinger;
