// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuCommencePatrol = {
  title: "Commence Patrol",
  cost: 1,
  text: "Put another card in a discard pile on the bottom of its owner's deck. If you do, create an X-Wing token.",
  unique: false,
  id: "8323555870",
  rarity: "uncommon",
  aspects: ["cunning", "heroism"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 205,
  },
  setCodes: [
    {
      set: "JTL",
      number: 205,
    },
  ],
  internalName: "commence-patrol",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Put another card in a discard pile on the bottom of its owner's deck. If you do, create an X-Wing token.",
      effects: [
        effect.ifYouDo(
          effect.reorder(
            target.card({ controller: "any", zones: ["discard"], excludeSelf: true, limit: 1 }),
            "bottomOfDeck",
          ),
          [effect.createToken("xWing")],
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuCommencePatrol;
