// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuCommencePatrol = {
  title: "Commence Patrol",
  cost: 1,
  text: "Put another card in a discard pile on the bottom of its owner's deck. If you do, create an X-Wing token.",
  unique: false,
  id: "8323555870",
  rarity: "uncommon",
  aspects: ["cunning", "heroism"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 205,
  },
  setCodes: [
    {
      set: "JTL",
      number: 205,
    },
  ],
  internalName: "commence-patrol",
  cardType: "event",
  canonicalId: "commence-patrol",
  slug: "commence-patrol",
  name: "Commence Patrol",
  printings: [
    {
      id: "JTL_205",
      artId: "20496",
      setCode: "JTL",
      collectorNumber: "205",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04010205_EN_Commence_Patrol_5542302f30.png",
    },
    {
      id: "5970894611",
      artId: "20496",
      setCode: "JTL",
      collectorNumber: "467",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04020467_EN_Commence_Patrol_c446b36708.png",
    },
    {
      id: "6523012029",
      artId: "20496",
      setCode: "JTL",
      collectorNumber: "703",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04310703_EN_Commence_Patrol_9fc8610c74.png",
    },
    {
      id: "8090191007",
      artId: "20496",
      setCode: "JTL",
      collectorNumber: "939",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04320939_EN_Commence_Patrol_7699ff9ff3.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Put another card in a discard pile on the bottom of its owner's deck. If you do, create an X-Wing token.",
      effects: [
        effect.ifYouDo(
          effect.reorder(
            target.card({ controller: "any", zones: ["discard"], excludeSelf: true, limit: 1 }),
            "bottomOfDeck",
          ),
          [effect.createToken("xWing")],
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuCommencePatrol;
