// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuDirectHit = {
  title: "Direct Hit",
  cost: 4,
  text: "Defeat a non-leader Vehicle unit.",
  unique: false,
  id: "5093056978",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 78,
  },
  setCodes: [
    {
      set: "JTL",
      number: 78,
    },
  ],
  internalName: "direct-hit",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Defeat a non-leader Vehicle unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuDirectHit;
