// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuJumpToLightspeed = {
  title: "Jump to Lightspeed",
  cost: 2,
  text: "Return a friendly space unit and any number of non-leader upgrades on it to their owners' hands. The next time you play a copy of that unit this phase, you may play it for free.",
  unique: false,
  rules:
    "Any upgrades on the unit not returned to their owners' hands are defeated.\n“Play for free” ignores all resource costs, including the aspect penalty, but not other additional costs.\nAbilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "5329736697",
  rarity: "rare",
  aspects: ["cunning"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 232,
  },
  setCodes: [
    {
      set: "JTL",
      number: 232,
    },
  ],
  internalName: "jump-to-lightspeed",
  cardType: "event",
  canonicalId: "jump-to-lightspeed",
  slug: "jump-to-lightspeed",
  name: "Jump to Lightspeed",
  printings: [
    {
      id: "JTL_232",
      artId: "20631",
      setCode: "JTL",
      collectorNumber: "232",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04010232_EN_Jump_to_Lightspeed_1f89ac451b.png",
    },
    {
      id: "1624454682",
      artId: "20631",
      setCode: "JTL",
      collectorNumber: "494",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04020494_EN_Jump_to_Lightspeed_326d4eafd8.png",
    },
    {
      id: "8602281749",
      artId: "20631",
      setCode: "JTL",
      collectorNumber: "730",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04310730_EN_Jump_to_Lightspeed_09d11cb481.png",
    },
    {
      id: "3789782333",
      artId: "20631",
      setCode: "JTL",
      collectorNumber: "966",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04320966_EN_Jump_to_Lightspeed_705a8b2ee7.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Return a friendly space unit and any number of non-leader upgrades on it to their owners' hands. The next time you play a copy of that unit this phase, you may play it for free.",
      effects: [
        effect.move(target.unit({ controller: "friendly", arena: "space", limit: 1 }), "hand"),
        effect.move(
          target.card({ controller: "friendly", cardTypes: ["upgrade"], limit: 1 }),
          "hand",
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuJumpToLightspeed;
