// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuPrepareForTakeoff = {
  title: "Prepare for Takeoff",
  cost: 2,
  text: "Search the top 8 cards of your deck for up to 2 Vehicle units, reveal them, and draw them. (Put the other cards on the bottom of your deck in a random order.)",
  unique: false,
  rules:
    "After searching, put any cards not chosen on the bottom of your deck in a random order.\n",
  id: "7901601022",
  rarity: "common",
  aspects: ["command"],
  traits: ["plan"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 128,
  },
  setCodes: [
    {
      set: "JTL",
      number: 128,
    },
  ],
  internalName: "prepare-for-takeoff",
  cardType: "event",
  canonicalId: "prepare-for-takeoff",
  slug: "prepare-for-takeoff",
  name: "Prepare for Takeoff",
  printings: [
    {
      id: "JTL_128",
      artId: "20111",
      setCode: "JTL",
      collectorNumber: "128",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010128_EN_Prepare_for_Takeoff_3963fb1856.png",
    },
    {
      id: "4551243752",
      artId: "20111",
      setCode: "JTL",
      collectorNumber: "390",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020390_EN_Prepare_for_Takeoff_bb26342f6a.png",
    },
    {
      id: "8232248099",
      artId: "20111",
      setCode: "JTL",
      collectorNumber: "626",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04310626_EN_Prepare_for_Takeoff_68058efcb3.png",
    },
    {
      id: "2364559743",
      artId: "20111",
      setCode: "JTL",
      collectorNumber: "862",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04320862_EN_Prepare_for_Takeoff_2c47f8abc1.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Search the top 8 cards of your deck for up to 2 Vehicle units, reveal them, and draw them. (Put the other cards on the bottom of your deck in a random order.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "search",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          destination: "hand",
          reveal: true,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuPrepareForTakeoff;
