// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuUnityOfPurpose = {
  title: "Unity of Purpose",
  cost: 6,
  text: "For each friendly unit with a different name, give each unit you control +1/+1 for this phase.",
  unique: false,
  rules: "Abilities that refer to a card’s “name” do not include the subtitle of the card.\n",
  id: "0753707056",
  rarity: "legendary",
  aspects: ["command", "command"],
  traits: ["plan"],
  types: ["event"],
  setId: {
    set: "JTL",
    number: 106,
  },
  setCodes: [
    {
      set: "JTL",
      number: 106,
    },
  ],
  internalName: "unity-of-purpose",
  cardType: "event",
  abilities: [
    ability.action({
      text: "For each friendly unit with a different name, give each unit you control +1/+1 for this phase.",
      effects: [
        effect.modifyStats(target.unit({ controller: "friendly" }), {
          power: 1,
          hp: 1,
          duration: "phase",
        }),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuUnityOfPurpose;
