// Generated by @tcg/cyberpunk-parser. Do not edit manually.
import type { ProgramCardDefinition } from "@tcg/cyberpunk-types";
import { welcomeToNightCityRetailAfterpartyAtLizzieS } from "./afterparty-at-lizzie-s.ts";
import { welcomeToNightCityRetailAllIsLost } from "./all-is-lost.ts";
import { welcomeToNightCityRetailAppetiteForDestruction } from "./appetite-for-destruction.ts";
import { welcomeToNightCityRetailBonnieAndClyde } from "./bonnie-and-clyde.ts";
import { welcomeToNightCityRetailBootlegBlackSapphireShow } from "./bootleg-black-sapphire-show.ts";
import { welcomeToNightCityRetailCarnageAtTheColosseum } from "./carnage-at-the-colosseum.ts";
import { welcomeToNightCityRetailChromeReverie } from "./chrome-reverie.ts";
import { welcomeToNightCityRetailCorporateSurveillance } from "./corporate-surveillance.ts";
import { welcomeToNightCityRetailCyberpsychosis } from "./cyberpsychosis.ts";
import { welcomeToNightCityRetailDetonate } from "./detonate.ts";
import { welcomeToNightCityRetailDonTFearTheReaper } from "./don-t-fear-the-reaper.ts";
import { welcomeToNightCityRetailFloorIt } from "./floor-it.ts";
import { welcomeToNightCityRetailFoolOnTheHill } from "./fool-on-the-hill.ts";
import { welcomeToNightCityRetailGunpointDiplomacy } from "./gunpoint-diplomacy.ts";
import { welcomeToNightCityRetailIndustrialAssembly } from "./industrial-assembly.ts";
import { welcomeToNightCityRetailLesElemens } from "./les-elemens.ts";
import { welcomeToNightCityRetailLiveWithTheAftermath } from "./live-with-the-aftermath.ts";
import { welcomeToNightCityRetailMemoryRelapse } from "./memory-relapse.ts";
import { welcomeToNightCityRetailNocturneOp55N1 } from "./nocturne-op55-n1.ts";
import { welcomeToNightCityRetailOverTheEdge } from "./over-the-edge.ts";
import { welcomeToNightCityRetailPeaceOffering } from "./peace-offering.ts";
import { welcomeToNightCityRetailPyramidSong } from "./pyramid-song.ts";
import { welcomeToNightCityRetailRebootOptics } from "./reboot-optics.ts";
import { welcomeToNightCityRetailSafetyOverride } from "./safety-override.ts";
import { welcomeToNightCityRetailShatteredMemories } from "./shattered-memories.ts";
import { welcomeToNightCityRetailSynapseBurnout } from "./synapse-burnout.ts";
import { welcomeToNightCityRetailTakeControl } from "./take-control.ts";
import { welcomeToNightCityRetailTheHeist } from "./the-heist.ts";
import { welcomeToNightCityRetailThreeMouthsOneDesire } from "./three-mouths-one-desire.ts";
import { welcomeToNightCityRetailTowerfall } from "./towerfall.ts";
import { welcomeToNightCityRetailTrustNoOne } from "./trust-no-one.ts";
import { welcomeToNightCityRetailUnlikelyBond } from "./unlikely-bond.ts";
import { welcomeToNightCityRetailWeGottaLiveTogether } from "./we-gotta-live-together.ts";
import { welcomeToNightCityRetailWildInTheStreets } from "./wild-in-the-streets.ts";

export { welcomeToNightCityRetailAfterpartyAtLizzieS } from "./afterparty-at-lizzie-s.ts";
export { welcomeToNightCityRetailAllIsLost } from "./all-is-lost.ts";
export { welcomeToNightCityRetailAppetiteForDestruction } from "./appetite-for-destruction.ts";
export { welcomeToNightCityRetailBonnieAndClyde } from "./bonnie-and-clyde.ts";
export { welcomeToNightCityRetailBootlegBlackSapphireShow } from "./bootleg-black-sapphire-show.ts";
export { welcomeToNightCityRetailCarnageAtTheColosseum } from "./carnage-at-the-colosseum.ts";
export { welcomeToNightCityRetailChromeReverie } from "./chrome-reverie.ts";
export { welcomeToNightCityRetailCorporateSurveillance } from "./corporate-surveillance.ts";
export { welcomeToNightCityRetailCyberpsychosis } from "./cyberpsychosis.ts";
export { welcomeToNightCityRetailDetonate } from "./detonate.ts";
export { welcomeToNightCityRetailDonTFearTheReaper } from "./don-t-fear-the-reaper.ts";
export { welcomeToNightCityRetailFloorIt } from "./floor-it.ts";
export { welcomeToNightCityRetailFoolOnTheHill } from "./fool-on-the-hill.ts";
export { welcomeToNightCityRetailGunpointDiplomacy } from "./gunpoint-diplomacy.ts";
export { welcomeToNightCityRetailIndustrialAssembly } from "./industrial-assembly.ts";
export { welcomeToNightCityRetailLesElemens } from "./les-elemens.ts";
export { welcomeToNightCityRetailLiveWithTheAftermath } from "./live-with-the-aftermath.ts";
export { welcomeToNightCityRetailMemoryRelapse } from "./memory-relapse.ts";
export { welcomeToNightCityRetailNocturneOp55N1 } from "./nocturne-op55-n1.ts";
export { welcomeToNightCityRetailOverTheEdge } from "./over-the-edge.ts";
export { welcomeToNightCityRetailPeaceOffering } from "./peace-offering.ts";
export { welcomeToNightCityRetailPyramidSong } from "./pyramid-song.ts";
export { welcomeToNightCityRetailRebootOptics } from "./reboot-optics.ts";
export { welcomeToNightCityRetailSafetyOverride } from "./safety-override.ts";
export { welcomeToNightCityRetailShatteredMemories } from "./shattered-memories.ts";
export { welcomeToNightCityRetailSynapseBurnout } from "./synapse-burnout.ts";
export { welcomeToNightCityRetailTakeControl } from "./take-control.ts";
export { welcomeToNightCityRetailTheHeist } from "./the-heist.ts";
export { welcomeToNightCityRetailThreeMouthsOneDesire } from "./three-mouths-one-desire.ts";
export { welcomeToNightCityRetailTowerfall } from "./towerfall.ts";
export { welcomeToNightCityRetailTrustNoOne } from "./trust-no-one.ts";
export { welcomeToNightCityRetailUnlikelyBond } from "./unlikely-bond.ts";
export { welcomeToNightCityRetailWeGottaLiveTogether } from "./we-gotta-live-together.ts";
export { welcomeToNightCityRetailWildInTheStreets } from "./wild-in-the-streets.ts";
export { welcomeToNightCityRetailAfterpartyAtLizzieSI18n } from "./afterparty-at-lizzie-s.i18n.ts";
export { welcomeToNightCityRetailAllIsLostI18n } from "./all-is-lost.i18n.ts";
export { welcomeToNightCityRetailAppetiteForDestructionI18n } from "./appetite-for-destruction.i18n.ts";
export { welcomeToNightCityRetailBonnieAndClydeI18n } from "./bonnie-and-clyde.i18n.ts";
export { welcomeToNightCityRetailBootlegBlackSapphireShowI18n } from "./bootleg-black-sapphire-show.i18n.ts";
export { welcomeToNightCityRetailCarnageAtTheColosseumI18n } from "./carnage-at-the-colosseum.i18n.ts";
export { welcomeToNightCityRetailChromeReverieI18n } from "./chrome-reverie.i18n.ts";
export { welcomeToNightCityRetailCorporateSurveillanceI18n } from "./corporate-surveillance.i18n.ts";
export { welcomeToNightCityRetailCyberpsychosisI18n } from "./cyberpsychosis.i18n.ts";
export { welcomeToNightCityRetailDetonateI18n } from "./detonate.i18n.ts";
export { welcomeToNightCityRetailDonTFearTheReaperI18n } from "./don-t-fear-the-reaper.i18n.ts";
export { welcomeToNightCityRetailFloorItI18n } from "./floor-it.i18n.ts";
export { welcomeToNightCityRetailFoolOnTheHillI18n } from "./fool-on-the-hill.i18n.ts";
export { welcomeToNightCityRetailGunpointDiplomacyI18n } from "./gunpoint-diplomacy.i18n.ts";
export { welcomeToNightCityRetailIndustrialAssemblyI18n } from "./industrial-assembly.i18n.ts";
export { welcomeToNightCityRetailLesElemensI18n } from "./les-elemens.i18n.ts";
export { welcomeToNightCityRetailLiveWithTheAftermathI18n } from "./live-with-the-aftermath.i18n.ts";
export { welcomeToNightCityRetailMemoryRelapseI18n } from "./memory-relapse.i18n.ts";
export { welcomeToNightCityRetailNocturneOp55N1I18n } from "./nocturne-op55-n1.i18n.ts";
export { welcomeToNightCityRetailOverTheEdgeI18n } from "./over-the-edge.i18n.ts";
export { welcomeToNightCityRetailPeaceOfferingI18n } from "./peace-offering.i18n.ts";
export { welcomeToNightCityRetailPyramidSongI18n } from "./pyramid-song.i18n.ts";
export { welcomeToNightCityRetailRebootOpticsI18n } from "./reboot-optics.i18n.ts";
export { welcomeToNightCityRetailSafetyOverrideI18n } from "./safety-override.i18n.ts";
export { welcomeToNightCityRetailShatteredMemoriesI18n } from "./shattered-memories.i18n.ts";
export { welcomeToNightCityRetailSynapseBurnoutI18n } from "./synapse-burnout.i18n.ts";
export { welcomeToNightCityRetailTakeControlI18n } from "./take-control.i18n.ts";
export { welcomeToNightCityRetailTheHeistI18n } from "./the-heist.i18n.ts";
export { welcomeToNightCityRetailThreeMouthsOneDesireI18n } from "./three-mouths-one-desire.i18n.ts";
export { welcomeToNightCityRetailTowerfallI18n } from "./towerfall.i18n.ts";
export { welcomeToNightCityRetailTrustNoOneI18n } from "./trust-no-one.i18n.ts";
export { welcomeToNightCityRetailUnlikelyBondI18n } from "./unlikely-bond.i18n.ts";
export { welcomeToNightCityRetailWeGottaLiveTogetherI18n } from "./we-gotta-live-together.i18n.ts";
export { welcomeToNightCityRetailWildInTheStreetsI18n } from "./wild-in-the-streets.i18n.ts";

export const programCards = [
  welcomeToNightCityRetailAfterpartyAtLizzieS,
  welcomeToNightCityRetailAllIsLost,
  welcomeToNightCityRetailAppetiteForDestruction,
  welcomeToNightCityRetailBonnieAndClyde,
  welcomeToNightCityRetailBootlegBlackSapphireShow,
  welcomeToNightCityRetailCarnageAtTheColosseum,
  welcomeToNightCityRetailChromeReverie,
  welcomeToNightCityRetailCorporateSurveillance,
  welcomeToNightCityRetailCyberpsychosis,
  welcomeToNightCityRetailDetonate,
  welcomeToNightCityRetailDonTFearTheReaper,
  welcomeToNightCityRetailFloorIt,
  welcomeToNightCityRetailFoolOnTheHill,
  welcomeToNightCityRetailGunpointDiplomacy,
  welcomeToNightCityRetailIndustrialAssembly,
  welcomeToNightCityRetailLesElemens,
  welcomeToNightCityRetailLiveWithTheAftermath,
  welcomeToNightCityRetailMemoryRelapse,
  welcomeToNightCityRetailNocturneOp55N1,
  welcomeToNightCityRetailOverTheEdge,
  welcomeToNightCityRetailPeaceOffering,
  welcomeToNightCityRetailPyramidSong,
  welcomeToNightCityRetailRebootOptics,
  welcomeToNightCityRetailSafetyOverride,
  welcomeToNightCityRetailShatteredMemories,
  welcomeToNightCityRetailSynapseBurnout,
  welcomeToNightCityRetailTakeControl,
  welcomeToNightCityRetailTheHeist,
  welcomeToNightCityRetailThreeMouthsOneDesire,
  welcomeToNightCityRetailTowerfall,
  welcomeToNightCityRetailTrustNoOne,
  welcomeToNightCityRetailUnlikelyBond,
  welcomeToNightCityRetailWeGottaLiveTogether,
  welcomeToNightCityRetailWildInTheStreets,
] satisfies ProgramCardDefinition[];
