import type { CardEffect, PilotCard } from "@tcg/gundam-types";

export const betaKiraYamato010: PilotCard = {
  cardNumber: "ST04-010",
  name: "Kira Yamato",
  type: "pilot",
  color: "white",
  traits: ["earth alliance", "coordinator"],
  id: "ST04-010_p2",
  externalId: "gundam:st04-010_p2",
  slug: "kira-yamato-st04-010-p2",
  displayName: "Kira Yamato",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "ST04-010_p2",
  printings: [
    {
      id: "ST04-010",
      collectorNumber: "ST04-010",
      cardNumber: "ST04-010",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-010.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-010_p1",
      collectorNumber: "ST04-010_p1",
      cardNumber: "ST04-010",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-010_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
    {
      id: "ST04-010_p2",
      collectorNumber: "ST04-010_p2",
      cardNumber: "ST04-010",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST04-010_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST04-010_p3",
      collectorNumber: "ST04-010_p3",
      cardNumber: "ST04-010",
      set: {
        code: "ST04",
        name: "GUNDAM CARD GAME Starter Deck Launch Event",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-010_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p3.webp?260424",
      productName: "GUNDAM CARD GAME Starter Deck Launch Event",
    },
    {
      id: "ST04-010_p4",
      collectorNumber: "ST04-010_p4",
      cardNumber: "ST04-010",
      set: {
        code: "ST04",
        name: "Newtype Challenge 2026 Mission 1",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-010_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p4.webp?260424",
      productName: "Newtype Challenge 2026 Mission 1",
    },
    {
      id: "ST04-010_p5",
      collectorNumber: "ST04-010_p5",
      cardNumber: "ST04-010",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-010_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p5.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  selectedPrintingId: "ST04-010_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST04-010_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-010_p2.webp?260424",
  legality: "legal",
  level: 4,
  cost: 1,
  apBonus: 2,
  hpBonus: 1,
  effect:
    "【Burst】Add this card to your hand.<br>【Attack】Choose 1 enemy Unit. It gets AP-2 during this battle.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["burst"],
      },
      directives: [
        {
          action: {
            action: "addSelfToHand",
          },
        },
      ],
      sourceText: "【Burst】Add this card to your hand.",
    },
    {
      type: "triggered",
      activation: {
        timing: ["attack"],
      },
      directives: [
        {
          action: {
            action: "statModifier",
            stat: "ap",
            amount: -2,
            duration: "thisBattle",
            target: {
              owner: "opponent",
              cardType: "unit",
              count: 1,
            },
          },
        },
      ],
      sourceText: "【Attack】Choose 1 enemy Unit. It gets AP-2 during this battle.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
