import type { CardEffect, CommandCard } from "@tcg/gundam-types";

export const gd01FirstContact107: CommandCard = {
  cardNumber: "GD01-107",
  name: "First Contact",
  type: "command",
  color: "green",
  traits: ["-"],
  id: "GD01-107",
  canonicalId: "GD01-107",
  externalIds: { bandai: "gundam:gd01-107" },
  slug: "first-contact-gd01-107",
  displayName: "First Contact",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-107",
  printings: [
    {
      id: "GD01-107",
      artId: "GD01-107",
      setCode: "GD01",
      collectorNumber: "GD01-107",
      cardNumber: "GD01-107",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-107.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107.webp?260715",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-107_p1",
      artId: "GD01-107_p1",
      setCode: "BETA",
      collectorNumber: "GD01-107_p1",
      cardNumber: "GD01-107",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/beta/GD01-107_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107_p1.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "GD01-107_p2",
      artId: "GD01-107_p2",
      setCode: "BETA",
      collectorNumber: "GD01-107_p2",
      cardNumber: "GD01-107",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/beta/GD01-107_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107_p2.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "GD01-107_p3",
      artId: "GD01-107_p3",
      setCode: "GD03",
      collectorNumber: "GD01-107_p3",
      cardNumber: "GD01-107",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-107_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107_p3.webp?260715",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD01-107_p4",
      artId: "GD01-107_p4",
      setCode: "SC01",
      collectorNumber: "GD01-107_p4",
      cardNumber: "GD01-107",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-107_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107_p4.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["GD01-107", "GD01-107_p1", "GD01-107_p2", "GD01-107_p3", "GD01-107_p4"],
  selectedPrintingId: "GD01-107",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-107.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-107.webp?260715",
  legality: "legal",
  level: 3,
  cost: 3,
  effect: "【Burst】Place 1 EX Resource.<br>【Main】Place 1 rested Resource.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["burst"],
      },
      directives: [
        {
          action: { action: "placeExResource", state: "active" },
        },
      ],
      sourceText: "【Burst】Place 1 EX Resource.",
    },
    {
      type: "command",
      activation: {
        timing: ["main"],
      },
      directives: [
        {
          action: {
            action: "placeResource",
            state: "rested",
          },
        },
      ],
      sourceText: "【Main】Place 1 rested Resource.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "uncommon",
};
