// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuDirectorKrennicAspiringToAuthority = {
  title: "Director Krennic",
  subtitle: "Aspiring to Authority",
  cost: 5,
  hp: 7,
  power: 2,
  text: "Each friendly damaged unit gets +1/+0. ",
  deployBox:
    "Restore 2 (When this unit attacks, heal 2 damage from your base.)\n\nEach friendly damaged unit gets +1/+0.",
  epicAction: "Epic Action: If you control 5 or more resources, deploy this leader. ",
  unique: true,
  id: "8560666697",
  rarity: "common",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "official"],
  arena: "ground",
  keywords: ["restore"],
  types: ["leader"],
  setId: {
    set: "SOR",
    number: 1,
  },
  setCodes: [
    {
      set: "SOR",
      number: 1,
    },
  ],
  internalName: "director-krennic#aspiring-to-authority",
  cardType: "leader",
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
    {
      kind: "action",
      text: "Epic Action: If you control 5 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuDirectorKrennicAspiringToAuthority;
