import type { GundamitoUnitCard } from "../../cardTypes";

export const sinanjuMSN065: GundamitoUnitCard = {
  id: "ST03-001",
  implemented: true,
  cost: 5,
  level: 6,
  number: 1,
  type: "unit",
  name: "Sinanju | MSN-06S",
  color: "red",
  set: "ST03",
  rarity: "legendary",
  zones: ["space", "earth"],
  traits: ["neo zeon"],
  linkRequirement: ["full frontal"],
  ap: 5,
  hp: 4,
  abilities: [],
};

export const gearaZuluAMS129: GundamitoUnitCard = {
  id: "ST03-003",
  implemented: true,
  cost: 2,
  level: 3,
  number: 3,
  type: "unit",
  name: "Geara Zulu | AMS-129",
  color: "red",
  set: "ST03",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["neo zeon"],
  linkRequirement: ["neo zeon trait"],
  ap: 3,
  hp: 2,
  abilities: [],
};

export const zakuIIMS06: GundamitoUnitCard = {
  id: "ST03-008",
  implemented: true,
  cost: 1,
  level: 2,
  number: 8,
  type: "unit",
  name: "Zaku II | MS-06",
  color: "green",
  set: "ST03",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["zeon"],
  linkRequirement: [],
  ap: 1,
  hp: 2,
  abilities: [],
};
