import type { UnitCard } from "@tcg/gundam-types";

export const st03AngeloSGearaZulu002: UnitCard = {
  cardNumber: "ST03-002",
  name: "Angelo's Geara Zulu",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "ST03-002",
  externalId: "gundam:st03-002",
  slug: "angelo-s-geara-zulu-st03-002",
  displayName: "Angelo's Geara Zulu",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "ST03-002",
  printings: [
    {
      id: "ST03-002",
      collectorNumber: "ST03-002",
      cardNumber: "ST03-002",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-002.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-002.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-002_p1",
      collectorNumber: "ST03-002_p1",
      cardNumber: "ST03-002",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-002_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-002_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST03-002",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-002.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-002.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 3,
  effect:
    "【Activate･Main】&lt;Support 2&gt; (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)<br>",
  keywordEffects: [{ keyword: "Support", value: 2 }],
  rarity: "common",
};
