import type { UnitCard } from "@tcg/gundam-types";

export const st03GearaZulu003: UnitCard = {
  cardNumber: "ST03-003",
  name: "Geara Zulu",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "ST03-003",
  externalId: "gundam:st03-003",
  slug: "geara-zulu-st03-003",
  displayName: "Geara Zulu",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "ST03-003",
  printings: [
    {
      id: "ST03-003",
      collectorNumber: "ST03-003",
      cardNumber: "ST03-003",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-003.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-003_p1",
      collectorNumber: "ST03-003_p1",
      cardNumber: "ST03-003",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-003_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST03-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-003.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
