import type { UnitCard } from "@tcg/gundam-types";

export const st03GazaDSleeves004: UnitCard = {
  cardNumber: "ST03-004",
  name: "Gaza D (Sleeves)",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "ST03-004",
  externalId: "gundam:st03-004",
  slug: "gaza-d-sleeves-st03-004",
  displayName: "Gaza D (Sleeves)",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "ST03-004",
  printings: [
    {
      id: "ST03-004",
      collectorNumber: "ST03-004",
      cardNumber: "ST03-004",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-004.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-004.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-004_p1",
      collectorNumber: "ST03-004_p1",
      cardNumber: "ST03-004",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-004_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-004_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST03-004",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-004.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-004.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 1,
  effect:
    "【Activate･Main】&lt;Support 2&gt; (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)<br>",
  keywordEffects: [{ keyword: "Support", value: 2 }],
  rarity: "common",
};
