import type { UnitCard } from "@tcg/gundam-types";

export const st03DraCSleeves005: UnitCard = {
  cardNumber: "ST03-005",
  name: "Dra-C (Sleeves)",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "ST03-005",
  externalId: "gundam:st03-005",
  slug: "dra-c-sleeves-st03-005",
  displayName: "Dra-C (Sleeves)",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "ST03-005",
  printings: [
    {
      id: "ST03-005",
      collectorNumber: "ST03-005",
      cardNumber: "ST03-005",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-005.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-005_p1",
      collectorNumber: "ST03-005_p1",
      cardNumber: "ST03-005",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-005_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST03-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-005.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
