// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuHansGoldenDice = {
  title: "Han's Golden Dice",
  cost: 1,
  text: "Attached unit gains: “On Attack: Discard a card from your deck. If its cost is odd, create a Credit token.”",
  unique: true,
  rules: "Always discard from the top of a deck, unless an ability specifies otherwise.\n",
  upgradePower: 0,
  upgradeHp: 0,
  id: "6269526870",
  rarity: "uncommon",
  aspects: ["cunning", "heroism"],
  traits: ["item"],
  types: ["upgrade"],
  setId: {
    set: "LAW",
    number: 225,
  },
  setCodes: [
    {
      set: "LAW",
      number: 225,
    },
  ],
  internalName: "hans-golden-dice",
  cardType: "upgrade",
  abilities: [
    ability.triggered(
      { event: "attack" },
      {
        text: "Attached unit gains: “On Attack: Discard a card from your deck. If its cost is odd, create a Credit token.”",
        effects: [
          effect.ifYouDo(
            effect.discard(target.card({ controller: "friendly", zones: ["deck"], limit: 1 })),
            [effect.createToken("credit", 1)],
          ),
        ],
      },
    ),
  ],
} satisfies SwuUpgradeCard;

export default swuHansGoldenDice;
