import type { UnitCard } from "@tcg/gundam-types";

export const st07GundamExia002: UnitCard = {
  cardNumber: "ST07-002",
  name: "Gundam Exia",
  type: "unit",
  color: "purple",
  traits: ["cb", "gn drive"],
  id: "ST07-002",
  canonicalId: "ST07-002",
  externalIds: { bandai: "gundam:st07-002" },
  slug: "gundam-exia/st07-002",
  displayName: "Gundam Exia",
  set: { code: "ST07", name: "Celestial Drive [ST07]", packageId: "616007" },
  printNumber: "ST07-002",
  printings: [
    {
      id: "ST07-002",
      artId: "ST07-002",
      setCode: "ST07",
      collectorNumber: "ST07-002",
      cardNumber: "ST07-002",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07]",
        packageId: "616007",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st07/ST07-002.webp",
      productName: "Celestial Drive [ST07]",
    },
    {
      id: "ST07-002_p1",
      artId: "ST07-002_p1",
      setCode: "ST07",
      collectorNumber: "ST07-002_p1",
      cardNumber: "ST07-002",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07] Bonus Pack",
        packageId: "616007",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st07/ST07-002_p1.webp",
      productName: "Celestial Drive [ST07] Bonus Pack",
    },
    {
      id: "ST07-002_p2",
      artId: "ST07-002_p2",
      setCode: "ST07",
      collectorNumber: "ST07-002_p2",
      cardNumber: "ST07-002",
      set: {
        code: "ST07",
        name: "Starter Deck [ST07]/[ST08] Release Event",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st07/ST07-002_p2.webp",
      productName: "Starter Deck [ST07]/[ST08] Release Event",
    },
  ],
  reprints: ["ST07-002", "ST07-002_p1", "ST07-002_p2"],
  selectedPrintingId: "ST07-002",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st07/ST07-002.webp",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "[Setsuna F. Seiei]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
