import type { UnitCard } from "@tcg/gundam-types";

export const st07GundamVirtue003: UnitCard = {
  cardNumber: "ST07-003",
  name: "Gundam Virtue",
  type: "unit",
  color: "purple",
  traits: ["cb", "gn drive"],
  id: "ST07-003",
  externalId: "gundam:st07-003",
  slug: "gundam-virtue-st07-003",
  displayName: "Gundam Virtue",
  set: { code: "ST07", name: "Celestial Drive [ST07]", packageId: "616007" },
  printNumber: "ST07-003",
  printings: [
    {
      id: "ST07-003",
      collectorNumber: "ST07-003",
      cardNumber: "ST07-003",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07]",
        packageId: "616007",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-003.webp?260424",
      productName: "Celestial Drive [ST07]",
    },
    {
      id: "ST07-003_p1",
      collectorNumber: "ST07-003_p1",
      cardNumber: "ST07-003",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07] Bonus Pack",
        packageId: "616007",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-003_p1.webp?260424",
      productName: "Celestial Drive [ST07] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST07-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-003.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Tieria Erde]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
