import type { UnitCard } from "@tcg/gundam-types";

export const st07GundamDynames006: UnitCard = {
  cardNumber: "ST07-006",
  name: "Gundam Dynames",
  type: "unit",
  color: "green",
  traits: ["cb", "gn drive"],
  id: "ST07-006",
  externalId: "gundam:st07-006",
  slug: "gundam-dynames-st07-006",
  displayName: "Gundam Dynames",
  set: { code: "ST07", name: "Celestial Drive [ST07]", packageId: "616007" },
  printNumber: "ST07-006",
  printings: [
    {
      id: "ST07-006",
      collectorNumber: "ST07-006",
      cardNumber: "ST07-006",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07]",
        packageId: "616007",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-006.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-006.webp?260424",
      productName: "Celestial Drive [ST07]",
    },
    {
      id: "ST07-006_p1",
      collectorNumber: "ST07-006_p1",
      cardNumber: "ST07-006",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07] Bonus Pack",
        packageId: "616007",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-006_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-006_p1.webp?260424",
      productName: "Celestial Drive [ST07] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST07-006",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-006.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-006.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "[Lockon Stratos]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
