import type { UnitCard } from "@tcg/gundam-types";

export const st07GundamKyriosFlightMode008: UnitCard = {
  cardNumber: "ST07-008",
  name: "Gundam Kyrios (Flight Mode)",
  type: "unit",
  color: "green",
  traits: ["cb", "gn drive"],
  id: "ST07-008",
  externalId: "gundam:st07-008",
  slug: "gundam-kyrios-flight-mode-st07-008",
  displayName: "Gundam Kyrios (Flight Mode)",
  set: { code: "ST07", name: "Celestial Drive [ST07]", packageId: "616007" },
  printNumber: "ST07-008",
  printings: [
    {
      id: "ST07-008",
      collectorNumber: "ST07-008",
      cardNumber: "ST07-008",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07]",
        packageId: "616007",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-008.webp?260424",
      productName: "Celestial Drive [ST07]",
    },
    {
      id: "ST07-008_p1",
      collectorNumber: "ST07-008_p1",
      cardNumber: "ST07-008",
      set: {
        code: "ST07",
        name: "Celestial Drive [ST07] Bonus Pack",
        packageId: "616007",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-008_p1.webp?260424",
      productName: "Celestial Drive [ST07] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST07-008",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st07/ST07-008.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST07-008.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 1,
  linkCondition: "[Allelujah Haptism] / [Hallelujah Haptism]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
