# These are supported funding model platforms

github: [eduardomoroni,leonardomosiah]
patreon: https://www.patreon.com/TheCardGoat
ko_fi: https://ko-fi.com/lorcanito
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
