// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuNevarroCityRestored = {
  title: "Nevarro City, Restored",
  hp: 30,
  unique: false,
  id: "3973342702",
  rarity: "common",
  aspects: ["vigilance"],
  types: ["base"],
  setId: {
    set: "ASH",
    number: 20,
  },
  setCodes: [
    {
      set: "ASH",
      number: 20,
    },
  ],
  internalName: "nevarro-city-restored",
  cardType: "base",
} satisfies SwuBaseCard;

export default swuNevarroCityRestored;
