import type { FabGameEventName } from "./events.ts";

export type FabEventProductionSupport =
  | { readonly status: "production"; readonly producer: string }
  | { readonly status: "unsupported"; readonly mechanic: string };

const production = (producer: string): FabEventProductionSupport => ({
  status: "production",
  producer,
});

/**
 * Completeness gate for the runtime migration. An event is marked production
 * only after an ordinary player move or game procedure proposes it through
 * executeFabEventTransaction. Reducer-only support is not production support.
 */
export const FAB_EVENT_PRODUCTION_SUPPORT = {
  "announce-card": production("reversible play-card procedure journal"),
  "announce-activation": production("reversible activation procedure journal"),
  "spend-assets": production("play and activation procedure journals"),
  "resolve-combat-damage": production("event-native combat damage procedure"),
  "advance-combat-step": production("event-native combat step procedure"),
  "defense-declaration-complete": production("event-native defense declaration procedure"),
  "declare-triggered-layer": production("persisted simultaneous trigger declaration"),
  "remove-rules-layer": production("normal layer resolution and state-condition ceasing"),
  "consume-random-index": production("persisted random declaration and ordering choices"),
  "expire-replacement-effects": production("event-boundary replacement expiry"),
  "consume-replacement-effects": production("one-shot replacement application"),
  "consume-delayed-triggers": production("delayed trigger collection"),
  "register-delayed-trigger": production("event-native delayed-trigger effect resolution"),
  "register-replacement": production("event-native replacement and prevention effect resolution"),
  "continuous-effect-generated": production("compiled continuous-effect generation"),
  "continuous-effect-ceased": production("compiled continuous-effect cessation"),
  "continuous-effect-applied": production("continuous application reconciliation"),
  "continuous-effect-changed": production("continuous contribution reconciliation"),
  "continuous-effect-stopped-applying": production("continuous application reconciliation"),
  "continuous-effect-future-object-observed": production(
    "future-object applicability reconciliation",
  ),
  "gain-assets": production("event-native asset effect resolution"),
  "pay-resources": production("event-native pay effect resolution"),
  "counter-added": production("event-native counter effect and enter-arena replacement resolution"),
  "turn-face-down": production("event-native face-change effect resolution"),
  "shuffle-zone": production("event-native shuffle effect resolution"),
  "random-token-request": production("deterministic random token effect resolution"),
  "roll-request": production("deterministic roll effect resolution"),
  "lose-game": production("event-native terminal effect resolution"),
  "reset-turn-assets": production("persisted end-turn procedure"),
  "advance-turn": production("persisted end-turn procedure"),
  "set-status": production("event-native status effect resolution"),
  "set-tapped": production("event-native tap effects and activation costs"),
  attack: production("event-native attack card-layer resolution"),
  "attack-target-declared": production("reversible attack play declaration journal"),
  hit: production("event-native combat damage procedure"),
  "deal-damage": production("event-native rules-layer effect resolution"),
  "dealt-damage": production("damage reducer resulting-event emission"),
  prevent: production("replacement engine prevention resulting event"),
  defend: production("event-native hand defender declaration batch"),
  play: production("reversible play-card procedure journal"),
  pitch: production("one-at-a-time play asset-payment journal"),
  discard: production("event-native rules-layer effect resolution"),
  draw: production("event-native rules-layer effect resolution"),
  banish: production("event-native rules-layer effect resolution"),
  destroy: production("event-native rules-layer effect resolution"),
  search: production("persisted event-native search effect resolution"),
  boost: production("reversible play-card procedure boost keyword journal (CR 8.3.31)"),
  fuse: production("reversible play-card procedure fuse keyword journal (CR 8.3.32)"),
  "clash-win": production("clash resolution resulting event"),
  "clash-lose": production("clash resolution resulting event"),
  "clash-outcome": production("replaceable provisional clash result"),
  "clash-prize": production("final clash-winner prize branch"),
  "reclash-request": production("persisted fresh-clash continuation"),
  wager: production("reversible play-card procedure wager keyword journal"),
  "wager-win": production("wager resolution resulting event"),
  "enter-arena": production("permanent card-layer resolution cleanup"),
  "leave-arena": production("resulting event from event-native arena zone changes"),
  "enter-or-leave-arena": production("resulting event from event-native arena zone changes"),
  "put-into-graveyard": production("resulting event from event-native graveyard zone changes"),
  "chain-link-resolve": production("event-native combat-close procedure journal"),
  "combat-chain-close": production("event-native combat-close procedure journal"),
  "start-phase": production("persisted end-turn procedure"),
  "end-phase": production("persisted end-turn procedure"),
  "action-phase-start": production("persisted end-turn procedure"),
  "reaction-step": production("event-native combat step procedure"),
  "counter-removed": production("event-native remove-counters effect resolution"),
  "numeric-counter-added": production(
    "event-native combat-close keyword counters (battleworn, guardwell, temper)",
  ),
  "numeric-counter-removed": production(
    "event-native remove-counters for +1{p}/−1{d} property counters",
  ),
  sharpen: production(
    "event-native CR 8.5.58 sharpen (+1{p} counters + sharpened-this-turn; replaceable)",
  ),
  usurp: production("Usurp additional-cost payment journal"),
  crank: production(
    "reversible play-card procedure journal with enter-arena resolution (CR 8.3.29)",
  ),
  transcend: production("reversible play-card procedure transcend keyword journal (CR 8.5.48)"),
  create: production("event-native create-token effect resolution"),
  "complete-contract": production("delayed contract trigger resolution"),
  trigger: production("trigger-matcher observation journal"),
  fragment: production("event-native defender-declaration procedure journal (CR 8.3.43)"),
  equip: production("event-native equip effect resolution"),
  "turn-face-up": production("event-native face-change effect resolution"),
  awaken: production("event-native CR 8.5.43 awaken effect resolution (figment flip)"),
  "change-active-face": production("event-native CR 9.1 structural active-face selection"),
  "activation-limit-modifier-generated": production(
    "event-native persisted CR 5.2.3 attack activation-limit modifier",
  ),
  charge: production("reversible play-card procedure charge keyword journal (CR 8.5.29)"),
  activate: production("typed asset-cost activation procedure journal"),
  "beat-chest": production("reversible play-card procedure journal (CR 8.3.33)"),
  clash: production("reversible play-card procedure clash keyword journal"),
  "move-zone": production("card-layer cleanup and move-card effect resolution"),
  "crowd-cheers": production("event-native crowd-cheers effect resolution"),
  protect: production("defense step protect keyword journal"),
  "crowd-boos": production("event-native crowd-boos effect resolution"),
  intimidate: production("CR 8.5.10 discrete intimidate effect, including an empty hand"),
  "go-again": production("event-native combat resolution-step procedure"),
  "gain-keyword": production("observation: continuous grant of a keyword onto a subject"),
  dies: production("resulting event when an ally moves from the arena to the graveyard"),
  become: production("hero transformation effect resolution"),
  transform: production("object transformation effect resolution"),
  "gain-life": production("event-native rules-layer effect resolution"),
  "lose-life": production("event-native rules-layer effect resolution"),
  opt: production("persisted event-native opt partition resolution"),
  reveal: production("event-native at-resolution reveal effect"),
  look: production("event-native at-resolution look effect"),
  "modify-power": production("event-native modify-numeric power effect resolution"),
  roll: production("deterministic roll-request reducer resulting event"),
  "wager-loss": production("replaceable CR 8.5.46 wager outcome before winner and prize"),
  "choose-opponent": production(
    "1v1 auto-bind sole opponent (opponentOf) — multiplayer out of product scope",
  ),
  "retarget-attack": production(
    "CR 1.8.5f choose-new-targets replaces the live attack's declared target",
  ),
} as const satisfies Record<FabGameEventName, FabEventProductionSupport>;
