/**
 * Inventory of every `FabKeyword` name and every `FabEffect` type discriminant
 * from `packages/types/src/abilities/`, mapped to CR test coverage.
 *
 * Status:
 * - `tested` — happy + edge (and interaction when CR/notes define one) via
 *   production `FabMatchRuntime` / `FabTestEngine` moves
 * - `meta` — deck-construction / registration only (plan Non-goal)
 * - `noop` — CR-defined no-op (stealth)
 * - `label-shell` — label-keyword wrapper; labels covered only when runtime-backed
 * - `unsupported` — classified and fail-closed pending the discrete-effect interpreter
 *
 * Completeness is enforced by `keyword-effect-inventory.test.ts`.
 */

export type InventoryStatus =
  | "tested"
  | "meta"
  | "noop"
  | "label-shell"
  | "unsupported"
  /** Behavior exists for one card/shape but the CR keyword is not generally modeled. */
  | "partial"
  /** Classified gap; intentionally out of current scope with a tracked reason. */
  | "deferred";

export interface InventoryRow {
  readonly id: string;
  readonly kind: "keyword" | "effect";
  readonly status: InventoryStatus;
  /** CR citation(s), Chapter.Section.Rule form */
  readonly cr: string;
  /** Primary suite / describe block that owns the row */
  readonly suite: string;
  readonly notes?: string;
}

/** Every `FabKeyword` `name` discriminant (types union). */
export const FAB_KEYWORD_NAMES = [
  "go-again",
  "dominate",
  "overpower",
  "arcane-barrier",
  "spellvoid",
  "arcane-shelter",
  "ward",
  "shadow-resist",
  "quell",
  "piercing",
  "amp",
  "battleworn",
  "blade-break",
  "temper",
  "guardwell",
  "blood-debt",
  "phantasm",
  "mirage",
  "spectra",
  "ephemeral",
  "watery-grave",
  "suspense",
  "crank",
  "stealth",
  "universal",
  "cloaked",
  "protect",
  "ambush",
  "modular",
  "perched",
  "rune-gate",
  "scrap",
  "beat-chest",
  "boost",
  "meld",
  "fragment",
  "usurp",
  "decay",
  "incarnate",
  "traverse",
  "unique",
  "sharpen",
  "awaken",
  "reload",
  "crush",
  "combo",
  "fusion",
  "heave",
  "opt",
  "legendary",
  "unlimited",
  "specialization",
  "essence",
  "pairs",
  "label-keyword",
] as const;

export type FabKeywordInventoryName = (typeof FAB_KEYWORD_NAMES)[number];

/** Every `FabEffect` `type` discriminant (structural + leaf). */
export const FAB_EFFECT_TYPES = [
  // structural
  "sequence",
  "if-you-do",
  "self-replacement",
  "choice",
  "conditional",
  "optional",
  "for-each",
  "remove-counters",
  "repeat",
  "delayed-trigger",
  "inline-trigger",
  "unless",
  // leaf (8.5)
  "deal-damage",
  "gain-life",
  "lose-life",
  "gain-action-points",
  "gain-resources",
  "gain-chi",
  "draw",
  "take-extra-turn",
  "lose-game",
  "discard",
  "banish",
  "destroy",
  "negate",
  "turn-face-down",
  "turn-face-up",
  "move-card",
  "reorder-deck",
  "search",
  "shuffle",
  "reveal",
  "look",
  "opt",
  "amp",
  "sharpen",
  "crowd-boos",
  "crowd-cheers",
  "awaken",
  "win-clash",
  "guess",
  "choose-color",
  "choose-option",
  "choose-and-create-token",
  "choose-number",
  "choose-card",
  "choose-new-targets",
  "choose-same-name-group",
  "contract-task",
  "contract-watch",
  "start-game",
  "remove-all-counters",
  "choose-opponent",
  "create-token",
  "create-card",
  "cancel-event",
  "ignore",
  "create-extra",
  "add-counter",
  "move-counter",
  "distribute-counters",
  "roll",
  "clash",
  "reclash",
  "swap-clash-reveals",
  "name-card",
  "intimidate",
  "charge",
  "pitch-card",
  "equip",
  "retrieve",
  "transform",
  "transcend",
  "transform-into-resolving-card",
  "copy",
  "exchange",
  "gain-control",
  "give",
  "steal",
  "mark",
  "set-status",
  "freeze",
  "unfreeze",
  "tap",
  "untap",
  "add-defending",
  "attack-with",
  "play-card",
  "pay",
  "wager",
  "win-wager",
  "become",
  "bind-aura",
  "return-to-brood",
  "modify-numeric",
  "modify-activation-cost",
  "modify-activation-limit",
  "grant-property",
  "remove-property",
  "can-be-attacked",
  "replacement",
  "prevention",
  "rule-modification",
] as const;

export type FabEffectInventoryType = (typeof FAB_EFFECT_TYPES)[number];

const kw = (
  name: FabKeywordInventoryName,
  status: InventoryStatus,
  cr: string,
  suite: string,
  notes?: string,
): InventoryRow => ({
  id: name,
  kind: "keyword",
  status,
  cr,
  suite,
  notes,
});

const fx = (
  type: FabEffectInventoryType,
  status: InventoryStatus,
  cr: string,
  suite: string,
  notes?: string,
): InventoryRow => ({
  id: type,
  kind: "effect",
  status,
  cr,
  suite,
  notes,
});

/**
 * Full inventory. Non-deferred rows must have `status: "tested"` and real
 * match-state tests in the named suite.
 */
export const KEYWORD_EFFECT_INVENTORY: readonly InventoryRow[] = [
  // ── Keywords (CR 8.3) ───────────────────────────────────────────────────
  kw("go-again", "tested", "8.3.5", "08-keywords / release-notes"),
  kw("dominate", "tested", "8.3.4", "08-keywords / release-notes"),
  kw("overpower", "tested", "8.3.22", "08-keywords"),
  kw("battleworn", "tested", "8.3.2", "08-keywords"),
  kw("blade-break", "tested", "8.3.3", "08-keywords / release-notes-expanded"),
  kw("temper", "tested", "8.3.10", "08-keywords"),
  kw("guardwell", "tested", "8.3.34", "08-keywords"),
  kw("fragment", "tested", "8.3.43", "release-notes"),
  kw("piercing", "tested", "8.3.23", "08-keywords"),
  kw("blood-debt", "tested", "8.3.11", "08-keywords"),
  kw("phantasm", "tested", "8.3.13", "08-keywords"),
  kw("mirage", "tested", "8.3.25", "08-keywords"),
  kw("spectra", "tested", "8.3.14", "08-keywords"),
  kw("boost", "tested", "8.3.9", "08-keywords"),
  kw("fusion", "tested", "8.3.17", "08-keywords"),
  kw("heave", "tested", "8.3.18", "08-keywords"),
  kw("opt", "tested", "8.3 / 8.5.22", "08-keywords / 06-effects"),
  kw("amp", "tested", "8.3 / 8.5.47", "08-keywords / 06-effects"),
  kw("arcane-barrier", "tested", "8.3.8", "08-keywords"),
  kw("spellvoid", "tested", "8.3.15", "08-keywords"),
  kw("arcane-shelter", "tested", "8.3.37", "08-keywords"),
  kw("ward", "tested", "8.3.20", "08-keywords"),
  kw("shadow-resist", "tested", "UST notes", "keyword-shadow-resist / dark-arcanite-boots"),
  kw("quell", "tested", "8.3.19", "08-keywords"),
  kw("crank", "tested", "8.3.29", "08-keywords"),
  kw("scrap", "tested", "8.3.32", "08-keywords"),
  kw("beat-chest", "tested", "8.3.33", "08-keywords"),
  kw("rune-gate", "tested", "8.3.27", "08-keywords"),
  kw("ambush", "tested", "8.3.28", "08-keywords"),
  kw("protect", "tested", "8.3.31", "08-keywords"),
  kw("modular", "tested", "8.3.30", "08-keywords"),
  kw("cloaked", "tested", "8.3.36", "08-keywords"),
  kw("perched", "tested", "8.3.39", "08-keywords"),
  kw("universal", "tested", "8.3.35", "08-keywords"),
  kw("watery-grave", "tested", "8.3.41", "08-keywords"),
  kw("suspense", "tested", "8.3.42", "08-keywords"),
  kw("meld", "tested", "8.3.38", "08-keywords"),
  kw("pairs", "tested", "8.3.26", "08-keywords"),
  kw("reload", "tested", "8.5.23", "08-keywords / 06-effects"),
  kw("sharpen", "tested", "8.5.58", "08-keywords / 06-effects"),
  kw("awaken", "tested", "8.5.43", "08-keywords / 06-effects"),
  kw("usurp", "tested", "8.3", "08-keywords"),
  kw("decay", "tested", "8.3", "08-keywords"),
  kw("incarnate", "tested", "8.3", "08-keywords"),
  kw("traverse", "tested", "8.3", "08-keywords"),
  kw("unique", "tested", "8.3", "08-keywords"),
  kw("crush", "tested", "8.5 / WTR", "08-keywords / release-notes-expanded"),
  kw(
    "combo",
    "tested",
    "8.4.1",
    "combo-abilities",
    "last-attack-this-combat-chain condition + AAA games (combo-abilities)",
  ),
  // meta / no-op
  kw("legendary", "meta", "8.3.6", "09-additional-rules", "registration only"),
  kw("unlimited", "meta", "8.3.40", "08-keywords", "registration only"),
  kw("specialization", "meta", "8.3.7", "08-keywords", "registration only"),
  kw("essence", "meta", "8.3.16", "08-keywords", "registration only"),
  kw(
    "ephemeral",
    "tested",
    "8.3.21",
    "08-keywords",
    "cease-to-exist graveyard replacement (CR 8.3.21b)",
  ),
  kw("stealth", "noop", "8.3.24", "08-keywords", "CR: means nothing"),
  kw(
    "label-keyword",
    "label-shell",
    "8.4",
    "08-keywords / has-status-coverage",
    "umbrella: mechanics modeled per-label via structured conditions (crush promoted to keyword; combo/surge/tower/reprise/etc. rewired off dead has-status markers)",
  ),

  // ── Effects (CR 6 / 8.5) ────────────────────────────────────────────────
  fx("draw", "tested", "8.5.6", "06-effects"),
  fx("gain-life", "tested", "8.5.7", "06-effects"),
  fx("lose-life", "tested", "8.5.12", "06-effects"),
  fx("deal-damage", "tested", "8.5.3", "06-effects"),
  fx("discard", "tested", "8.5.5", "06-effects / release-notes"),
  fx("banish", "tested", "8.5.1", "06-effects / release-notes"),
  fx("destroy", "tested", "8.5.4", "06-effects / release-notes"),
  fx("intimidate", "tested", "8.5.10", "06-effects / release-notes-expanded"),
  fx("gain-action-points", "tested", "8.5.7", "06-effects"),
  fx("gain-resources", "tested", "8.5.7", "06-effects"),
  fx("gain-chi", "tested", "8.5.7", "06-effects"),
  fx(
    "move-card",
    "tested",
    "8.5.15",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "modify-numeric",
    "tested",
    "8.5.8",
    "06-effects",
    "immediate numeric mutation is replaced by compiled continuous atoms",
  ),
  fx("modify-activation-cost", "tested", "6.3", "activation-cost-modifier"),
  fx("modify-activation-limit", "tested", "6.3", "activation-limit-modifiers"),
  fx("grant-property", "tested", "8.5.9", "06-effects"),
  fx(
    "add-counter",
    "tested",
    "8.5.14",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),

  fx(
    "remove-counters",
    "tested",
    "8.5.16",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "remove-all-counters",
    "tested",
    "8.5.16",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "move-counter",
    "tested",
    "8.5.42",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "distribute-counters",
    "tested",
    "8.5.30",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("create-token", "tested", "8.5.2", "06-effects"),
  fx(
    "create-card",
    "tested",
    "8.5.40",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("cancel-event", "tested", "6.4", "event-kernel"),
  fx(
    "ignore",
    "partial",
    "8.5.33",
    "06-effects / replacement-engine",
    "Whole-event ignore via replacement-engine (8.5.33a); 8.5.33b part-of-event deferred.",
  ),
  fx(
    "create-extra",
    "tested",
    "8.5.2",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "search",
    "tested",
    "8.5.19",
    "06-effects",
    "selection suspension requires the unified interpreter",
  ),
  fx("shuffle", "tested", "8.5.20", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("reveal", "tested", "8.5.17", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("look", "tested", "8.5.11", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "reorder-deck",
    "tested",
    "3.7.1",
    "card behavior",
    "Sutcliffe's Research Notes and Song of Sinew ordering decisions",
  ),
  fx(
    "opt",
    "tested",
    "8.5.22",
    "06-effects",
    "partition suspension requires the unified interpreter",
  ),
  fx("negate", "tested", "8.5.26", "release-notes-set-keywords (Aetherize)"),
  fx("roll", "tested", "8.5.18", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("clash", "tested", "8.5.45", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "reclash",
    "tested",
    "8.5.45",
    "replacement-opportunity",
    "Victor public clash-outcome replacement acceptance",
  ),
  fx(
    "swap-clash-reveals",
    "tested",
    "8.5.45",
    "replacement-opportunity",
    "The Old Switcheroo swapped clash reveals",
  ),
  fx(
    "name-card",
    "tested",
    "8.5.21",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("charge", "tested", "8.5.29", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "pitch-card",
    "tested",
    "8.5.44",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("equip", "tested", "8.5.41", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "retrieve",
    "partial",
    "8.5.51",
    "06-effects / proven-effect",
    "Composes pay + equip with 8.5.51a equippability gate; GY->hand salvage label reconciliation deferred.",
  ),
  fx(
    "transform",
    "tested",
    "8.5.36",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "transcend",
    "tested",
    "8.5.48",
    "06-effects / proven-trigger",
    "First-class FabEffect (emits transcend event; reducer flips back-face + move-to-hand). Replaces label-driven play-procedure path.",
  ),
  fx(
    "transform-into-resolving-card",
    "tested",
    "8.2.13",
    "invocation-construct-transform",
    "Construct/Invocation resolving-flip transform (CR 8.2.13/8.2.14).",
  ),
  fx("copy", "tested", "8.5.25", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("exchange", "tested", "8.5.49", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "gain-control",
    "tested",
    "8.5.35",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "give",
    "tested",
    "8.5.53",
    "06-effects / proven-effect",
    "Shares the gain-control primitive; stamps move-zone reason 'give' (8.5.53a provenance).",
  ),
  fx(
    "steal",
    "tested",
    "8.5.54",
    "06-effects / proven-effect",
    "Shares the gain-control primitive; stamps move-zone reason 'steal' (8.5.54a provenance).",
  ),
  fx("mark", "tested", "8.5.50", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("set-status", "tested", "6.2", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("freeze", "tested", "8.5.34", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("unfreeze", "tested", "8.5.37", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("tap", "tested", "8.5.55", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("untap", "tested", "8.5.56", "06-effects"),
  fx(
    "add-defending",
    "tested",
    "8.5.32",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "attack-with",
    "tested",
    "8.5.38",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("play-card", "tested", "5.1", "06-effects"),
  fx("pay", "tested", "8.5.31", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("wager", "tested", "8.5.46", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "win-wager",
    "unsupported",
    "8.5.46",
    "06-effects",
    "Replacement-only continuation; PEN169 owns the public wager-outcome proof",
  ),
  fx("become", "tested", "8.5.25", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "bind-aura",
    "tested",
    "8.5.19",
    "cards/instants/mark-of-*",
    "Moves the resolving Aura beneath one controlled Ally; the three Usurp Marks prove binding, granted abilities, and cleanup.",
  ),
  fx(
    "return-to-brood",
    "tested",
    "8.5.52",
    "acceptance/heroes (Arakni)",
    "Ceases become/copy on the controller's hero; proven via Arakni hero acceptance.",
  ),
  fx("amp", "tested", "8.5.47", "06-effects"),
  fx("sharpen", "tested", "8.5.58", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("awaken", "tested", "8.5.43", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "crowd-cheers",
    "tested",
    "8.5.57",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "crowd-boos",
    "tested",
    "8.5.57",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "win-clash",
    "tested",
    "8.5.45",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("guess", "tested", "6", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("choose-color", "tested", "6", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("choose-option", "tested", "6", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "choose-and-create-token",
    "tested",
    "8.5.2",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("choose-number", "tested", "6", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("choose-card", "tested", "6", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx(
    "choose-new-targets",
    "tested",
    "1.8.5f",
    "cards/heroes/taipanis-dracai-of-judgement.test.ts",
    "Optional discard-red then retarget a lethal attack; unique legal alternative auto-binds; no other legal target is a no-op.",
  ),
  fx(
    "choose-same-name-group",
    "tested",
    "1.8.5c, 2.7.5, 8.5.15c",
    "06-effects",
    "public Righteous Cleansing same-name cohort and private remainder ordering",
  ),
  fx(
    "choose-opponent",
    "tested",
    "6",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx(
    "contract-task",
    "tested",
    "8.5.39",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("contract-watch", "deferred", "8.5.39", "06-effects", "condition+effect contract watch"),
  fx("start-game", "meta", "4.1", "06-effects", "pre-game placement meta"),
  fx(
    "take-extra-turn",
    "tested",
    "6",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("lose-game", "tested", "6", "06-effects"),
  fx(
    "turn-face-down",
    "tested",
    "8.5.24",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("turn-face-up", "tested", "8.5.24", "06-effects"),
  fx("remove-property", "tested", "8.5.13", "06-effects"),
  fx(
    "can-be-attacked",
    "tested",
    "6.2",
    "06-effects",
    "AAA leaf contract (06-effects-leaf-contracts)",
  ),
  fx("replacement", "tested", "6.4", "06-effects"),
  fx("prevention", "tested", "6.4", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("rule-modification", "tested", "6.3.1", "06-effects"),
  // structural
  fx("sequence", "tested", "6.1", "06-effects"),
  fx("if-you-do", "tested", "6.1", "06-effects", "do X; if you do, Y"),
  fx("self-replacement", "tested", "6.4.7", "tome-of-divinity-alternatives"),
  fx("choice", "tested", "6.1", "06-effects"),
  fx("conditional", "tested", "6.1", "06-effects"),
  fx("optional", "tested", "6.1", "06-effects"),
  fx("for-each", "tested", "6.1", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
  fx("repeat", "tested", "8.5.27", "06-effects"),
  fx("delayed-trigger", "tested", "6.6", "06-effects"),
  fx(
    "inline-trigger",
    "tested",
    "6.6.2",
    "trigger-matcher",
    "generation-window inline trigger (CR 6.6.2/6.6.2a)",
  ),
  fx("unless", "tested", "6.1", "06-effects", "AAA leaf contract (06-effects-leaf-contracts)"),
];

export function inventoryByKind(kind: "keyword" | "effect"): readonly InventoryRow[] {
  return KEYWORD_EFFECT_INVENTORY.filter((r) => r.kind === kind);
}

export function inventoryIds(kind: "keyword" | "effect"): string[] {
  return inventoryByKind(kind).map((r) => r.id);
}

export function deferredInventory(): readonly InventoryRow[] {
  return KEYWORD_EFFECT_INVENTORY.filter((r) => r.status !== "tested");
}
