// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuMoffGideonIndomitableWarlord = {
  title: "Moff Gideon",
  subtitle: "Indomitable Warlord",
  cost: 7,
  hp: 8,
  power: 5,
  text: "Action [Exhaust]: If a friendly Imperial unit was defeated this phase, play a unit from your hand. It costs 1 resource less.",
  deployBox:
    "This unit gains each of the following keywords if it is on an Imperial unit in your discard pile: Ambush, Grit, Hidden, Overwhelm, Saboteur, Sentinel, Shielded, Support.",
  epicAction: "Epic Action: If you control 7 or more resources, deploy this leader.",
  unique: true,
  id: "3621912835",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["imperial", "official"],
  arena: "ground",
  keywords: [
    "ambush",
    "grit",
    "hidden",
    "overwhelm",
    "saboteur",
    "sentinel",
    "shielded",
    "support",
  ],
  types: ["leader"],
  setId: {
    set: "ASH",
    number: 8,
  },
  setCodes: [
    {
      set: "ASH",
      number: 8,
    },
  ],
  internalName: "moff-gideon#indomitable-warlord",
  cardType: "leader",
  canonicalId: "moff-gideon#indomitable-warlord",
  slug: "moff-gideon-indomitable-warlord",
  name: "Moff Gideon",
  printings: [
    {
      id: "ASH_008",
      artId: "51722",
      setCode: "ASH",
      collectorNumber: "8",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010008_EN_Moff_Gideon_Leader_b939d8621a.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
    {
      kind: "keyword",
      text: "Grit",
      keyword: "grit",
    },
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
    {
      kind: "keyword",
      text: "Support",
      keyword: "support",
    },
    {
      kind: "action",
      text: "Epic Action: If you control 7 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuMoffGideonIndomitableWarlord;
