// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuSabineWrenBargainingOnBelief = {
  title: "Sabine Wren",
  subtitle: "Bargaining on Belief",
  cost: 5,
  hp: 5,
  power: 3,
  text: "Action [Exhaust]: An opponent gives 2 Advantage tokens to a unit they control. If they do, the next unit you play this phase gains Shielded for this phase. (When you play that unit, give a Shield token to it.)",
  deployBox: "On Attack: The next unit you play this phase gains Shielded for this phase.",
  epicAction: "Epic Action: If you control 5 or more resources, deploy this leader.",
  unique: true,
  id: "6706120928",
  rarity: "common",
  aspects: ["vigilance", "heroism"],
  traits: ["jedi", "mandalorian", "spectre"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["leader"],
  setId: {
    set: "ASH",
    number: 6,
  },
  setCodes: [
    {
      set: "ASH",
      number: 6,
    },
  ],
  internalName: "sabine-wren#bargaining-on-belief",
  cardType: "leader",
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
    {
      kind: "action",
      text: "Epic Action: If you control 5 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuSabineWrenBargainingOnBelief;
