// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuMasterstroke = {
  title: "Masterstroke",
  cost: 2,
  text: "Attack with a unit. It gets +1/+0 for this attack for each unit the defending player controls in its arena.",
  unique: false,
  id: "6315733621",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "ASH",
    number: 234,
  },
  setCodes: [
    {
      set: "ASH",
      number: 234,
    },
  ],
  internalName: "masterstroke",
  cardType: "event",
  canonicalId: "masterstroke",
  slug: "masterstroke",
  name: "Masterstroke",
  printings: [
    {
      id: "ASH_234",
      artId: "52849",
      setCode: "ASH",
      collectorNumber: "234",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010234_EN_Masterstroke_27f2348b22.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Attack with a unit. It gets +1/+0 for this attack for each unit the defending player controls in its arena.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "attack",
          attacker: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          defender: {
            type: "base",
            controller: "opponent",
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuMasterstroke;
