// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuTurningTheTide = {
  title: "Turning the Tide",
  cost: 3,
  text: "Choose a unit. Deal 1 damage to it for each friendly unit.",
  unique: false,
  id: "1886651714",
  rarity: "common",
  aspects: ["command"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "ASH",
    number: 138,
  },
  setCodes: [
    {
      set: "ASH",
      number: 138,
    },
  ],
  internalName: "turning-the-tide",
  cardType: "event",
  canonicalId: "turning-the-tide",
  slug: "turning-the-tide",
  name: "Turning the Tide",
  printings: [
    {
      id: "ASH_138",
      artId: "52371",
      setCode: "ASH",
      collectorNumber: "138",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010138_EN_Turning_the_Tide_f2f6ea3cb5.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Choose a unit. Deal 1 damage to it for each friendly unit.",
      effects: [
        effect.damagePerTargetCount(
          target.unit({ limit: 1 }),
          target.unit({ controller: "friendly" }),
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuTurningTheTide;
