// This file is generated by @tcg/cyberpunk-parser. Do not edit manually.
// Seeded from the scraped catalog text; future generator versions will
// preserve hand-authored non-en locales alongside the en seed.
import type { CyberpunkCardLocale, CyberpunkLocale } from "@tcg/cyberpunk-types";

export const welcomeToNightCityRetailKiroshiOpticsI18n: Record<
  CyberpunkLocale,
  CyberpunkCardLocale
> = {
  en: {
    name: "Kiroshi Optics",
    displayName: "Kiroshi Optics",
    rulesText:
      "(Equip to a friendly Unit or face-up Legend.)\n{Attack} Look at a friendly face-down Legend. (Don't reveal it.)",
  },
};
