// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuEncouragingLeadership = {
  title: "Encouraging Leadership",
  cost: 3,
  text: "Give each friendly unit +1/+1 for this phase.",
  unique: false,
  id: "4916334670",
  rarity: "common",
  aspects: ["command"],
  traits: ["learned"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 126,
  },
  setCodes: [
    {
      set: "TWI",
      number: 126,
    },
  ],
  internalName: "encouraging-leadership",
  cardType: "event",
  canonicalId: "encouraging-leadership",
  slug: "encouraging-leadership",
  name: "Encouraging Leadership",
  printings: [
    {
      id: "TWI_126",
      artId: "14816",
      setCode: "TWI",
      collectorNumber: "126",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0301126_EN_Encouraging_Leadership_2a83f746c7.png",
    },
    {
      id: "8281858123",
      artId: "14816",
      setCode: "TWI",
      collectorNumber: "126",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0331126_EN_Encouraging_Leadership_74ef92e5bd.png",
    },
    {
      id: "2508150013",
      artId: "14816",
      setCode: "TWI",
      collectorNumber: "394",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0302394_EN_Encouraging_Leadership_42501ab7af.png",
    },
    {
      id: "3451902671",
      artId: "14816",
      setCode: "TWI",
      collectorNumber: "394",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0332394_EN_Encouraging_Leadership_f57f51bb7f.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Give each friendly unit +1/+1 for this phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
          power: 1,
          hp: 1,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuEncouragingLeadership;
