// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuEqualize = {
  title: "Equalize",
  cost: 3,
  text: "Give a unit –2/–2 for this phase. Then, if you control fewer units than that unit's controller, give another unit –2/–2 for this phase.",
  unique: false,
  id: "5013214638",
  rarity: "rare",
  aspects: ["vigilance", "vigilance"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 55,
  },
  setCodes: [
    {
      set: "TWI",
      number: 55,
    },
  ],
  internalName: "equalize",
  cardType: "event",
  canonicalId: "equalize",
  slug: "equalize",
  name: "Equalize",
  printings: [
    {
      id: "TWI_055",
      artId: "14476",
      setCode: "TWI",
      collectorNumber: "55",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301055_EN_Equalize_2689b468bb.png",
    },
    {
      id: "8505911216",
      artId: "14476",
      setCode: "TWI",
      collectorNumber: "55",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0331055_EN_Equalize_b82600c48f.png",
    },
    {
      id: "6066006237",
      artId: "14476",
      setCode: "TWI",
      collectorNumber: "328",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302328_EN_Equalize_8b43b07db5.png",
    },
    {
      id: "6580779842",
      artId: "14476",
      setCode: "TWI",
      collectorNumber: "328",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0332328_EN_Equalize_4bdcbf5c67.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Give a unit -2/-2 for this phase. Then, if you control fewer units than that unit's controller, give another unit -2/-2 for this phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          power: -2,
          hp: -2,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuEqualize;
