// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuHelloThere = {
  title: "Hello There",
  cost: 3,
  text: "Choose a unit that entered play this phase. It gets –4/–4 for this phase.",
  unique: false,
  id: "4036958275",
  rarity: "uncommon",
  aspects: ["vigilance", "heroism"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 52,
  },
  setCodes: [
    {
      set: "TWI",
      number: 52,
    },
  ],
  internalName: "hello-there",
  cardType: "event",
  canonicalId: "hello-there",
  slug: "hello-there",
  name: "Hello There",
  printings: [
    {
      id: "TWI_052",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "52",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0301052_EN_Hello_There_1c6d0b81e3.png",
    },
    {
      id: "6923902016",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "18",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0360018_EN_Hello_There_a884512d61.png",
    },
    {
      id: "8292836685",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "18",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0335018_EN_Hello_There_c249f3d1b7.png",
    },
    {
      id: "3479421547",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "52",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0331052_EN_Hello_There_5303c3f176.png",
    },
    {
      id: "7962790148",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "325",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0302325_EN_Hello_There_1a07936731.png",
    },
    {
      id: "9567865063",
      artId: "14461",
      setCode: "TWI",
      collectorNumber: "325",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0332325_EN_Hello_There_97064a1184.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Choose a unit that entered play this phase. It gets -4/-4 for this phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            limit: 1,
          },
          power: -4,
          hp: -4,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuHelloThere;
