// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuIHaveTheHighGround = {
  title: "I Have the High Ground",
  cost: 1,
  text: "Choose a friendly unit. Each enemy unit gets –4/–0 while attacking that unit this phase.",
  unique: false,
  rules:
    "(ERRATA) Choose a friendly unit. For this phase, while that unit is defending, the attacker gets –4/–0.\n",
  id: "9399634203",
  rarity: "rare",
  aspects: ["vigilance"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 72,
  },
  setCodes: [
    {
      set: "TWI",
      number: 72,
    },
  ],
  internalName: "i-have-the-high-ground",
  cardType: "event",
  canonicalId: "i-have-the-high-ground",
  slug: "i-have-the-high-ground",
  name: "I Have the High Ground",
  printings: [
    {
      id: "TWI_072",
      artId: "14561",
      setCode: "TWI",
      collectorNumber: "72",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0301072_EN_I_Have_the_High_Ground_a8b2b84adb.png",
    },
    {
      id: "7453380854",
      artId: "14561",
      setCode: "TWI",
      collectorNumber: "72",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0331072_EN_I_Have_the_High_Ground_64723ca9f5.png",
    },
    {
      id: "3912560221",
      artId: "14561",
      setCode: "TWI",
      collectorNumber: "345",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0302345_EN_I_Have_the_High_Ground_6ae1250ada.png",
    },
    {
      id: "6242921441",
      artId: "14561",
      setCode: "TWI",
      collectorNumber: "345",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0332345_EN_I_Have_the_High_Ground_c6f0d01617.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Choose a friendly unit. Each enemy unit gets –4/–0 while attacking that unit this phase.",
      effects: [
        effect.modifyStats(target.unit({ controller: "opponent" }), {
          power: -4,
          duration: "phase",
        }),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuIHaveTheHighGround;
