// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect } from "../../../helpers/index.ts";

export const swuPetitionTheSenate = {
  title: "Petition the Senate",
  cost: 3,
  text: "If you control 3 or more Official units, draw 3 cards.",
  unique: false,
  id: "3500129784",
  rarity: "rare",
  aspects: ["command", "heroism"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 100,
  },
  setCodes: [
    {
      set: "TWI",
      number: 100,
    },
  ],
  internalName: "petition-the-senate",
  cardType: "event",
  canonicalId: "petition-the-senate",
  slug: "petition-the-senate",
  name: "Petition the Senate",
  printings: [
    {
      id: "TWI_100",
      artId: "14691",
      setCode: "TWI",
      collectorNumber: "100",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301100_EN_Petition_the_Senate_036057d28d.png",
    },
    {
      id: "5875616516",
      artId: "14691",
      setCode: "TWI",
      collectorNumber: "100",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0331100_EN_Petition_the_Senate_3660f47b8c.png",
    },
    {
      id: "5735442734",
      artId: "14691",
      setCode: "TWI",
      collectorNumber: "371",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302371_EN_Petition_the_Senate_f586f392ff.png",
    },
    {
      id: "9584417421",
      artId: "14691",
      setCode: "TWI",
      collectorNumber: "371",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0332371_EN_Petition_the_Senate_37ea106641.png",
    },
  ],
  abilities: [
    ability.action({
      text: "If you control 3 or more Official units, draw 3 cards.",
      conditions: [
        {
          type: "controlsTrait",
          controller: "friendly",
          trait: "Official",
          comparison: { operator: "gte", value: 3 },
        },
      ],
      effects: [effect.draw("friendly", 3)],
    }),
  ],
} satisfies SwuEventCard;

export default swuPetitionTheSenate;
