// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuUnmaskingTheConspiracy = {
  title: "Unmasking the Conspiracy",
  cost: 1,
  text: "Discard a card from your hand. If you do, look at an opponent's hand and discard a card from it.",
  unique: false,
  id: "0959549331",
  rarity: "rare",
  aspects: ["cunning"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 223,
  },
  setCodes: [
    {
      set: "TWI",
      number: 223,
    },
  ],
  internalName: "unmasking-the-conspiracy",
  cardType: "event",
  canonicalId: "unmasking-the-conspiracy",
  slug: "unmasking-the-conspiracy",
  name: "Unmasking the Conspiracy",
  printings: [
    {
      id: "TWI_223",
      artId: "15291",
      setCode: "TWI",
      collectorNumber: "223",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0301223_EN_Unmasking_the_Conspiracy_71690697e9.png",
    },
    {
      id: "3765843083",
      artId: "15291",
      setCode: "TWI",
      collectorNumber: "223",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0331223_EN_Unmasking_the_Conspiracy_7f032c8fef.png",
    },
    {
      id: "7010471270",
      artId: "15291",
      setCode: "TWI",
      collectorNumber: "488",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0332488_EN_Unmasking_the_Conspiracy_af8adb0e60.png",
    },
    {
      id: "8641645709",
      artId: "15291",
      setCode: "TWI",
      collectorNumber: "488",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0302488_EN_Unmasking_the_Conspiracy_553d9ec5d5.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Discard a card from your hand. If you do, look at an opponent's hand and discard a card from it.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "discard",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["hand"],
            limit: 1,
          },
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuUnmaskingTheConspiracy;
