// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuWaylay = {
  title: "Waylay",
  cost: 3,
  text: "Return a non-leader unit to its owner's hand.",
  unique: false,
  id: "5190917242",
  rarity: "special",
  aspects: ["cunning"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "TWI",
    number: 226,
  },
  setCodes: [
    {
      set: "TWI",
      number: 226,
    },
  ],
  internalName: "waylay",
  cardType: "event",
  canonicalId: "waylay",
  slug: "waylay",
  name: "Waylay",
  printings: [
    {
      id: "TWI_226",
      artId: "15306",
      setCode: "TWI",
      collectorNumber: "226",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//0301226_EN_Waylay_75bb2cb8f9.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Return a non-leader unit to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          to: "hand",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuWaylay;
