import type { CardEffect, CommandCard } from "@tcg/gundam-types";

export const betaAShowOfResolve100: CommandCard = {
  cardNumber: "GD01-100",
  name: "A Show of Resolve",
  type: "command",
  color: "blue",
  traits: ["-"],
  id: "GD01-100_p2",
  canonicalId: "GD01-100",
  externalIds: { bandai: "gundam:gd01-100_p2" },
  slug: "a-show-of-resolve/gd01-100",
  displayName: "A Show of Resolve",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-100_p2",
  printings: [
    {
      id: "GD01-100",
      artId: "GD01-100",
      setCode: "GD01",
      collectorNumber: "GD01-100",
      cardNumber: "GD01-100",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-100.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-100_p1",
      artId: "GD01-100_p1",
      setCode: "GD01",
      collectorNumber: "GD01-100_p1",
      cardNumber: "GD01-100",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-100_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p1.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-100_p2",
      artId: "GD01-100_p2",
      setCode: "BETA",
      collectorNumber: "GD01-100_p2",
      cardNumber: "GD01-100",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-100_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "GD01-100_p3",
      artId: "GD01-100_p3",
      setCode: "BETA",
      collectorNumber: "GD01-100_p3",
      cardNumber: "GD01-100",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-100_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p3.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "GD01-100_p4",
      artId: "GD01-100_p4",
      setCode: "PB01",
      collectorNumber: "GD01-100_p4",
      cardNumber: "GD01-100",
      set: {
        code: "PB01",
        name: "Premium Accessory Set -Mobile Suit Gundam Wing- [PB01]",
        packageId: "616701",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-100_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p4.webp?260424",
      productName: "Premium Accessory Set -Mobile Suit Gundam Wing- [PB01]",
    },
    {
      id: "GD01-100_p5",
      artId: "GD01-100_p5",
      setCode: "GD03",
      collectorNumber: "GD01-100_p5",
      cardNumber: "GD01-100",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-100_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p5.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  reprints: ["GD01-100", "GD01-100_p1", "GD01-100_p2", "GD01-100_p3", "GD01-100_p4", "GD01-100_p5"],
  selectedPrintingId: "GD01-100_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-100_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-100_p2.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  effect: "【Main】Draw 2.<br>",
  effects: [
    {
      type: "command",
      activation: {
        timing: ["main"],
      },
      directives: [
        {
          action: {
            action: "draw",
            count: 2,
          },
        },
      ],
      sourceText: "【Main】Draw 2.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "uncommon",
};
