import type { CardEffect, CommandCard } from "@tcg/gundam-types";

export const betaOverflowingAffection118: CommandCard = {
  cardNumber: "GD01-118",
  name: "Overflowing Affection",
  type: "command",
  color: "white",
  traits: ["-"],
  id: "GD01-118_p2",
  canonicalId: "GD01-118",
  externalIds: { bandai: "gundam:gd01-118_p2" },
  slug: "overflowing-affection/gd01-118",
  displayName: "Overflowing Affection",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-118_p2",
  printings: [
    {
      id: "GD01-118",
      artId: "GD01-118",
      setCode: "GD01",
      collectorNumber: "GD01-118",
      cardNumber: "GD01-118",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-118.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-118_p1",
      artId: "GD01-118_p1",
      setCode: "GD01",
      collectorNumber: "GD01-118_p1",
      cardNumber: "GD01-118",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-118_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p1.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-118_p2",
      artId: "GD01-118_p2",
      setCode: "BETA",
      collectorNumber: "GD01-118_p2",
      cardNumber: "GD01-118",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-118_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "GD01-118_p3",
      artId: "GD01-118_p3",
      setCode: "BETA",
      collectorNumber: "GD01-118_p3",
      cardNumber: "GD01-118",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-118_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p3.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "GD01-118_p4",
      artId: "GD01-118_p4",
      setCode: "GD01",
      collectorNumber: "GD01-118_p4",
      cardNumber: "GD01-118",
      set: {
        code: "GD01",
        name: "Newtype Challenge 2025 Mission1",
        packageId: "616901",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-118_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p4.webp?260424",
      productName: "Newtype Challenge 2025 Mission1",
    },
    {
      id: "GD01-118_p5",
      artId: "GD01-118_p5",
      setCode: "GD03",
      collectorNumber: "GD01-118_p5",
      cardNumber: "GD01-118",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-118_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p5.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD01-118_p6",
      artId: "GD01-118_p6",
      setCode: "ST09",
      collectorNumber: "GD01-118_p6",
      cardNumber: "GD01-118",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-118_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p6.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  reprints: [
    "GD01-118",
    "GD01-118_p1",
    "GD01-118_p2",
    "GD01-118_p3",
    "GD01-118_p4",
    "GD01-118_p5",
    "GD01-118_p6",
  ],
  selectedPrintingId: "GD01-118_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-118_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-118_p2.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  effect: "【Main】Draw 2. Then, discard 1.<br>",
  effects: [
    {
      type: "command",
      activation: {
        timing: ["main"],
      },
      directives: [
        {
          action: {
            action: "drawThenDiscard",
            drawCount: 2,
            discardCount: 1,
          },
        },
      ],
      sourceText: "【Main】Draw 2. Then, discard 1.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "uncommon",
};
