import type { CardEffect, UnitCard } from "@tcg/gundam-types";

export const st04StrikeGundam002: UnitCard = {
  cardNumber: "ST04-002",
  name: "Strike Gundam",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "ST04-002",
  externalId: "gundam:st04-002",
  slug: "strike-gundam-st04-002",
  displayName: "Strike Gundam",
  set: { code: "ST04", name: "SEED Strike [ST04]", packageId: "616004" },
  printNumber: "ST04-002",
  printings: [
    {
      id: "ST04-002",
      collectorNumber: "ST04-002",
      cardNumber: "ST04-002",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-002.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-002_p1",
      collectorNumber: "ST04-002_p1",
      cardNumber: "ST04-002",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-002_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
    {
      id: "ST04-002_p2",
      collectorNumber: "ST04-002_p2",
      cardNumber: "ST04-002",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST04-002_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST04-002_p3",
      collectorNumber: "ST04-002_p3",
      cardNumber: "ST04-002",
      set: {
        code: "ST04",
        name: "GUNDAM CARD GAME Starter Deck Launch Event",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-002_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002_p3.webp?260424",
      productName: "GUNDAM CARD GAME Starter Deck Launch Event",
    },
    {
      id: "ST04-002_p4",
      collectorNumber: "ST04-002_p4",
      cardNumber: "ST04-002",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-002_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002_p4.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  selectedPrintingId: "ST04-002",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-002.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-002.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "【Deploy】Draw 1. Then, discard 1.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["deploy"],
      },
      directives: [
        {
          action: {
            action: "draw",
            count: 1,
          },
        },
        {
          action: {
            action: "discard",
            count: 1,
          },
        },
      ],
      sourceText: "【Deploy】Draw 1. Then, discard 1.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
