import type { UnitCard } from "@tcg/gundam-types";

export const st04MoebiusZero003: UnitCard = {
  cardNumber: "ST04-003",
  name: "Moebius Zero",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "ST04-003",
  externalId: "gundam:st04-003",
  slug: "moebius-zero-st04-003",
  displayName: "Moebius Zero",
  set: { code: "ST04", name: "SEED Strike [ST04]", packageId: "616004" },
  printNumber: "ST04-003",
  printings: [
    {
      id: "ST04-003",
      collectorNumber: "ST04-003",
      cardNumber: "ST04-003",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-003.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-003_p1",
      collectorNumber: "ST04-003_p1",
      cardNumber: "ST04-003",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-003_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST04-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-003.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
