import type { UnitCard } from "@tcg/gundam-types";

export const st04Moebius004: UnitCard = {
  cardNumber: "ST04-004",
  name: "Moebius",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "ST04-004",
  canonicalId: "ST04-004",
  externalIds: { bandai: "gundam:st04-004" },
  slug: "moebius/st04-004",
  displayName: "Moebius",
  set: { code: "ST04", name: "SEED Strike [ST04]", packageId: "616004" },
  printNumber: "ST04-004",
  printings: [
    {
      id: "ST04-004",
      artId: "ST04-004",
      setCode: "ST04",
      collectorNumber: "ST04-004",
      cardNumber: "ST04-004",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st04/ST04-004.webp",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-004_p1",
      artId: "ST04-004_p1",
      setCode: "ST04",
      collectorNumber: "ST04-004_p1",
      cardNumber: "ST04-004",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st04/ST04-004_p1.webp",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
  ],
  reprints: ["ST04-004", "ST04-004_p1"],
  selectedPrintingId: "ST04-004",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st04/ST04-004.webp",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 1,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
