import type { UnitCard } from "@tcg/gundam-types";

export const st04AegisGundamMaMode007: UnitCard = {
  cardNumber: "ST04-007",
  name: "Aegis Gundam (MA Mode)",
  type: "unit",
  color: "red",
  traits: ["zaft"],
  id: "ST04-007",
  externalId: "gundam:st04-007",
  slug: "aegis-gundam-ma-mode-st04-007",
  displayName: "Aegis Gundam (MA Mode)",
  set: { code: "ST04", name: "SEED Strike [ST04]", packageId: "616004" },
  printNumber: "ST04-007",
  printings: [
    {
      id: "ST04-007",
      collectorNumber: "ST04-007",
      cardNumber: "ST04-007",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-007.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-007_p1",
      collectorNumber: "ST04-007_p1",
      cardNumber: "ST04-007",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-007_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
    {
      id: "ST04-007_p2",
      collectorNumber: "ST04-007_p2",
      cardNumber: "ST04-007",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-007_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-007_p2.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  selectedPrintingId: "ST04-007",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-007.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-007.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  effect:
    "&lt;Breach 3&gt; (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to the first card in that opponent's shield area.)<br>",
  keywordEffects: [{ keyword: "Breach", value: 3 }],
  rarity: "common",
};
