import type { UnitCard } from "@tcg/gundam-types";

export const st04Ginn008: UnitCard = {
  cardNumber: "ST04-008",
  name: "Ginn",
  type: "unit",
  color: "red",
  traits: ["zaft"],
  id: "ST04-008",
  externalId: "gundam:st04-008",
  slug: "ginn-st04-008",
  displayName: "Ginn",
  set: { code: "ST04", name: "SEED Strike [ST04]", packageId: "616004" },
  printNumber: "ST04-008",
  printings: [
    {
      id: "ST04-008",
      collectorNumber: "ST04-008",
      cardNumber: "ST04-008",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-008.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-008_p1",
      collectorNumber: "ST04-008_p1",
      cardNumber: "ST04-008",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-008_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST04-008",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-008.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-008.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
