import type { UnitCard } from "@tcg/gundam-types";

export const gd02CoreBooster012: UnitCard = {
  cardNumber: "GD02-012",
  name: "Core Booster",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "GD02-012",
  externalId: "gundam:gd02-012",
  slug: "core-booster-gd02-012",
  displayName: "Core Booster",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-012",
  printings: [
    {
      id: "GD02-012",
      collectorNumber: "GD02-012",
      cardNumber: "GD02-012",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-012.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-012.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-012",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-012.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-012.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
