import type { UnitCard } from "@tcg/gundam-types";

export const gd02CoreBooster012: UnitCard = {
  cardNumber: "GD02-012",
  name: "Core Booster",
  type: "unit",
  color: "blue",
  battlefieldZones: ["space", "earth"],
  traits: ["earth federation", "white base team"],
  id: "GD02-012",
  canonicalId: "GD02-012",
  externalIds: { bandai: "gundam:gd02-012" },
  slug: "core-booster/gd02-012",
  displayName: "Core Booster",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-012",
  printings: [
    {
      id: "GD02-012",
      artId: "GD02-012",
      setCode: "GD02",
      collectorNumber: "GD02-012",
      cardNumber: "GD02-012",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-012.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-012"],
  selectedPrintingId: "GD02-012",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-012.webp",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  linkCondition: "(White Base Team) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
