import type { UnitCard } from "@tcg/gundam-types";

export const gd02Hizack013: UnitCard = {
  cardNumber: "GD02-013",
  name: "Hizack",
  type: "unit",
  color: "blue",
  battlefieldZones: ["space", "earth"],
  traits: ["titans"],
  id: "GD02-013",
  canonicalId: "GD02-013",
  externalIds: { bandai: "gundam:gd02-013" },
  slug: "hizack/gd02-013",
  displayName: "Hizack",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-013",
  printings: [
    {
      id: "GD02-013",
      artId: "GD02-013",
      setCode: "GD02",
      collectorNumber: "GD02-013",
      cardNumber: "GD02-013",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-013.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-013.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-013"],
  selectedPrintingId: "GD02-013",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-013.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-013.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
