import type { UnitCard } from "@tcg/gundam-types";

export const gd02Marasai015: UnitCard = {
  cardNumber: "GD02-015",
  name: "Marasai",
  type: "unit",
  color: "blue",
  traits: ["titans"],
  id: "GD02-015",
  externalId: "gundam:gd02-015",
  slug: "marasai-gd02-015",
  displayName: "Marasai",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-015",
  printings: [
    {
      id: "GD02-015",
      collectorNumber: "GD02-015",
      cardNumber: "GD02-015",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-015.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-015.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-015",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-015.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-015.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
