import type { UnitCard } from "@tcg/gundam-types";

export const gd02RaiderGundamMaMode019: UnitCard = {
  cardNumber: "GD02-019",
  name: "Raider Gundam (MA Mode)",
  type: "unit",
  color: "blue",
  traits: ["earth alliance"],
  id: "GD02-019",
  externalId: "gundam:gd02-019",
  slug: "raider-gundam-ma-mode-gd02-019",
  displayName: "Raider Gundam (MA Mode)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-019",
  printings: [
    {
      id: "GD02-019",
      collectorNumber: "GD02-019",
      cardNumber: "GD02-019",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-019.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-019.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-019",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-019.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-019.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
