import type { UnitCard } from "@tcg/gundam-types";

export const gd02AbdulSMaganac028: UnitCard = {
  cardNumber: "GD02-028",
  name: "Abdul's Maganac",
  type: "unit",
  color: "green",
  traits: ["maganac corps"],
  id: "GD02-028",
  externalId: "gundam:gd02-028",
  slug: "abdul-s-maganac-gd02-028",
  displayName: "Abdul's Maganac",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-028",
  printings: [
    {
      id: "GD02-028",
      collectorNumber: "GD02-028",
      cardNumber: "GD02-028",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-028.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-028.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-028",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-028.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-028.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
