import type { UnitCard } from "@tcg/gundam-types";

export const gd02AbdulSMaganac028: UnitCard = {
  cardNumber: "GD02-028",
  name: "Abdul's Maganac",
  type: "unit",
  color: "green",
  battlefieldZones: ["space", "earth"],
  traits: ["maganac corps"],
  id: "GD02-028",
  canonicalId: "GD02-028",
  externalIds: { bandai: "gundam:gd02-028" },
  slug: "abdul-s-maganac/gd02-028",
  displayName: "Abdul's Maganac",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-028",
  printings: [
    {
      id: "GD02-028",
      artId: "GD02-028",
      setCode: "GD02",
      collectorNumber: "GD02-028",
      cardNumber: "GD02-028",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-028.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-028"],
  selectedPrintingId: "GD02-028",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-028.webp",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "(Maganac Corps) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
