import type { UnitCard } from "@tcg/gundam-types";

export const gd02GundamAge1Normal029: UnitCard = {
  cardNumber: "GD02-029",
  name: "Gundam AGE-1 Normal",
  type: "unit",
  color: "green",
  traits: ["earth federation", "age system"],
  id: "GD02-029",
  externalId: "gundam:gd02-029",
  slug: "gundam-age-1-normal-gd02-029",
  displayName: "Gundam AGE-1 Normal",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-029",
  printings: [
    {
      id: "GD02-029",
      collectorNumber: "GD02-029",
      cardNumber: "GD02-029",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-029.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-029.webp?260424",
      productName: "Dual Impact [GD02]",
    },
    {
      id: "GD02-029_p1",
      collectorNumber: "GD02-029_p1",
      cardNumber: "GD02-029",
      set: {
        code: "GD02",
        name: "Store Tournament Participant Pack 02",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-029_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-029_p1.webp?260424",
      productName: "Store Tournament Participant Pack 02",
    },
    {
      id: "GD02-029_p2",
      collectorNumber: "GD02-029_p2",
      cardNumber: "GD02-029",
      set: {
        code: "GD02",
        name: "Store Tournament Winner Pack 02",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-029_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-029_p2.webp?260424",
      productName: "Store Tournament Winner Pack 02",
    },
    {
      id: "GD02-029_p3",
      collectorNumber: "GD02-029_p3",
      cardNumber: "GD02-029",
      set: {
        code: "GD02",
        name: "Booster Release Event",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-029_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-029_p3.webp?260424",
      productName: "Booster Release Event",
    },
  ],
  selectedPrintingId: "GD02-029",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-029.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-029.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
