import type { UnitCard } from "@tcg/gundam-types";

export const gd02Genoace030: UnitCard = {
  cardNumber: "GD02-030",
  name: "Genoace",
  type: "unit",
  color: "green",
  traits: ["earth federation"],
  id: "GD02-030",
  externalId: "gundam:gd02-030",
  slug: "genoace-gd02-030",
  displayName: "Genoace",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-030",
  printings: [
    {
      id: "GD02-030",
      collectorNumber: "GD02-030",
      cardNumber: "GD02-030",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-030.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-030.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-030",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-030.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-030.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
