import type { UnitCard } from "@tcg/gundam-types";

export const gd02WhiteGundam032: UnitCard = {
  cardNumber: "GD02-032",
  name: "White Gundam",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD02-032",
  externalId: "gundam:gd02-032",
  slug: "white-gundam-gd02-032",
  displayName: "White Gundam",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-032",
  printings: [
    {
      id: "GD02-032",
      collectorNumber: "GD02-032",
      cardNumber: "GD02-032",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-032.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-032.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-032",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-032.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-032.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
