import type { UnitCard } from "@tcg/gundam-types";

export const gd02ZakuSleeves048: UnitCard = {
  cardNumber: "GD02-048",
  name: "Zaku Ⅲ (Sleeves)",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "GD02-048",
  externalId: "gundam:gd02-048",
  slug: "zaku-sleeves-gd02-048",
  displayName: "Zaku Ⅲ (Sleeves)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-048",
  printings: [
    {
      id: "GD02-048",
      collectorNumber: "GD02-048",
      cardNumber: "GD02-048",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-048.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-048.webp?260424",
      productName: "Dual Impact [GD02]",
    },
    {
      id: "GD02-048_p1",
      collectorNumber: "GD02-048_p1",
      cardNumber: "GD02-048",
      set: {
        code: "GD02",
        name: "Store Tournament Participant Pack 02",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-048_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-048_p1.webp?260424",
      productName: "Store Tournament Participant Pack 02",
    },
    {
      id: "GD02-048_p2",
      collectorNumber: "GD02-048_p2",
      cardNumber: "GD02-048",
      set: {
        code: "GD02",
        name: "Store Tournament Winner Pack 02",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-048_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-048_p2.webp?260424",
      productName: "Store Tournament Winner Pack 02",
    },
  ],
  selectedPrintingId: "GD02-048",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-048.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-048.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
