import type { UnitCard } from "@tcg/gundam-types";

export const gd02GaZowmnSleeves050: UnitCard = {
  cardNumber: "GD02-050",
  name: "Ga-Zowmn (Sleeves)",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "GD02-050",
  externalId: "gundam:gd02-050",
  slug: "ga-zowmn-sleeves-gd02-050",
  displayName: "Ga-Zowmn (Sleeves)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-050",
  printings: [
    {
      id: "GD02-050",
      collectorNumber: "GD02-050",
      cardNumber: "GD02-050",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-050.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-050.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-050",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-050.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-050.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
