import type { UnitCard } from "@tcg/gundam-types";

export const gd0201Gundam051: UnitCard = {
  cardNumber: "GD02-051",
  name: "01 Gundam",
  type: "unit",
  color: "red",
  traits: ["earth federation"],
  id: "GD02-051",
  externalId: "gundam:gd02-051",
  slug: "01-gundam-gd02-051",
  displayName: "01 Gundam",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-051",
  printings: [
    {
      id: "GD02-051",
      collectorNumber: "GD02-051",
      cardNumber: "GD02-051",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-051.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-051.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-051",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-051.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-051.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
