import type { UnitCard } from "@tcg/gundam-types";

export const gd02GuncannonGq052: UnitCard = {
  cardNumber: "GD02-052",
  name: "Guncannon (GQ)",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "red",
  traits: ["earth federation"],
  id: "GD02-052",
  canonicalId: "GD02-052",
  externalIds: { bandai: "gundam:gd02-052" },
  slug: "guncannon-gq/gd02-052",
  displayName: "Guncannon (GQ)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-052",
  printings: [
    {
      id: "GD02-052",
      artId: "GD02-052",
      setCode: "GD02",
      collectorNumber: "GD02-052",
      cardNumber: "GD02-052",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-052.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-052"],
  selectedPrintingId: "GD02-052",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-052.webp",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
