import type { UnitCard } from "@tcg/gundam-types";

export const gd02GundamAirmaster059: UnitCard = {
  cardNumber: "GD02-059",
  name: "Gundam Airmaster",
  type: "unit",
  color: "purple",
  traits: ["vulture"],
  id: "GD02-059",
  externalId: "gundam:gd02-059",
  slug: "gundam-airmaster-gd02-059",
  displayName: "Gundam Airmaster",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-059",
  printings: [
    {
      id: "GD02-059",
      collectorNumber: "GD02-059",
      cardNumber: "GD02-059",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-059.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-059.webp?260424",
      productName: "Dual Impact [GD02]",
    },
    {
      id: "GD02-059_p1",
      collectorNumber: "GD02-059_p1",
      cardNumber: "GD02-059",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-059_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-059_p1.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-059",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-059.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-059.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 4,
  hp: 3,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
