import type { UnitCard } from "@tcg/gundam-types";

export const gd02AmidaSHyakuren062: UnitCard = {
  cardNumber: "GD02-062",
  name: "Amida's Hyakuren",
  type: "unit",
  color: "purple",
  traits: ["teiwaz"],
  id: "GD02-062",
  externalId: "gundam:gd02-062",
  slug: "amida-s-hyakuren-gd02-062",
  displayName: "Amida's Hyakuren",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-062",
  printings: [
    {
      id: "GD02-062",
      collectorNumber: "GD02-062",
      cardNumber: "GD02-062",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-062.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-062.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-062",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-062.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-062.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
