import type { UnitCard } from "@tcg/gundam-types";

export const gd02AmidaSHyakuren062: UnitCard = {
  cardNumber: "GD02-062",
  name: "Amida's Hyakuren",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "purple",
  traits: ["teiwaz"],
  id: "GD02-062",
  canonicalId: "GD02-062",
  externalIds: { bandai: "gundam:gd02-062" },
  slug: "amida-s-hyakuren/gd02-062",
  displayName: "Amida's Hyakuren",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-062",
  printings: [
    {
      id: "GD02-062",
      artId: "GD02-062",
      setCode: "GD02",
      collectorNumber: "GD02-062",
      cardNumber: "GD02-062",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-062.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-062"],
  selectedPrintingId: "GD02-062",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-062.webp",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "(Teiwaz) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
