import type { UnitCard } from "@tcg/gundam-types";

export const gd02GundamAirmasterFighterMode063: UnitCard = {
  cardNumber: "GD02-063",
  name: "Gundam Airmaster (Fighter Mode)",
  type: "unit",
  color: "purple",
  traits: ["vulture"],
  id: "GD02-063",
  externalId: "gundam:gd02-063",
  slug: "gundam-airmaster-fighter-mode-gd02-063",
  displayName: "Gundam Airmaster (Fighter Mode)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-063",
  printings: [
    {
      id: "GD02-063",
      collectorNumber: "GD02-063",
      cardNumber: "GD02-063",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-063.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-063.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-063",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-063.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-063.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
