import type { UnitCard } from "@tcg/gundam-types";

export const gd02GundamAirmasterFighterMode063: UnitCard = {
  cardNumber: "GD02-063",
  name: "Gundam Airmaster (Fighter Mode)",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "purple",
  traits: ["vulture"],
  id: "GD02-063",
  canonicalId: "GD02-063",
  externalIds: { bandai: "gundam:gd02-063" },
  slug: "gundam-airmaster-fighter-mode/gd02-063",
  displayName: "Gundam Airmaster (Fighter Mode)",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-063",
  printings: [
    {
      id: "GD02-063",
      artId: "GD02-063",
      setCode: "GD02",
      collectorNumber: "GD02-063",
      cardNumber: "GD02-063",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-063.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-063"],
  selectedPrintingId: "GD02-063",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-063.webp",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "(Vulture) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
