import type { UnitCard } from "@tcg/gundam-types";

export const gd02JeniceCustom065: UnitCard = {
  cardNumber: "GD02-065",
  name: "Jenice Custom",
  type: "unit",
  battlefieldZones: ["earth"],
  color: "purple",
  traits: ["vulture"],
  id: "GD02-065",
  canonicalId: "GD02-065",
  externalIds: { bandai: "gundam:gd02-065" },
  slug: "jenice-custom/gd02-065",
  displayName: "Jenice Custom",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-065",
  printings: [
    {
      id: "GD02-065",
      artId: "GD02-065",
      setCode: "GD02",
      collectorNumber: "GD02-065",
      cardNumber: "GD02-065",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-065.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-065"],
  selectedPrintingId: "GD02-065",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-065.webp",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
