import type { UnitCard } from "@tcg/gundam-types";

export const gd02Baqto067: UnitCard = {
  cardNumber: "GD02-067",
  name: "Baqto",
  type: "unit",
  color: "purple",
  traits: ["ue", "vagan"],
  id: "GD02-067",
  externalId: "gundam:gd02-067",
  slug: "baqto-gd02-067",
  displayName: "Baqto",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-067",
  printings: [
    {
      id: "GD02-067",
      collectorNumber: "GD02-067",
      cardNumber: "GD02-067",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-067.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-067.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-067",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-067.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-067.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
