import type { UnitCard } from "@tcg/gundam-types";

export const gd02EinSSchwalbeGraze077: UnitCard = {
  cardNumber: "GD02-077",
  name: "Ein's Schwalbe Graze",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "white",
  traits: ["gjallarhorn"],
  id: "GD02-077",
  canonicalId: "GD02-077",
  externalIds: { bandai: "gundam:gd02-077" },
  slug: "ein-s-schwalbe-graze/gd02-077",
  displayName: "Ein's Schwalbe Graze",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-077",
  printings: [
    {
      id: "GD02-077",
      artId: "GD02-077",
      setCode: "GD02",
      collectorNumber: "GD02-077",
      cardNumber: "GD02-077",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-077.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-077.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-077"],
  selectedPrintingId: "GD02-077",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-077.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-077.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Gjallarhorn) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
