import type { UnitCard } from "@tcg/gundam-types";

export const gd02GundamPharact078: UnitCard = {
  cardNumber: "GD02-078",
  name: "Gundam Pharact",
  type: "unit",
  color: "white",
  traits: ["academy"],
  id: "GD02-078",
  externalId: "gundam:gd02-078",
  slug: "gundam-pharact-gd02-078",
  displayName: "Gundam Pharact",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-078",
  printings: [
    {
      id: "GD02-078",
      collectorNumber: "GD02-078",
      cardNumber: "GD02-078",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-078.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-078.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-078",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-078.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-078.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
