import type { UnitCard } from "@tcg/gundam-types";

export const gd02RickDias079: UnitCard = {
  cardNumber: "GD02-079",
  name: "Rick Dias",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "white",
  traits: ["aeug"],
  id: "GD02-079",
  canonicalId: "GD02-079",
  externalIds: { bandai: "gundam:gd02-079" },
  slug: "rick-dias/gd02-079",
  displayName: "Rick Dias",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-079",
  printings: [
    {
      id: "GD02-079",
      artId: "GD02-079",
      setCode: "GD02",
      collectorNumber: "GD02-079",
      cardNumber: "GD02-079",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-079.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-079"],
  selectedPrintingId: "GD02-079",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-079.webp",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
