import type { UnitCard } from "@tcg/gundam-types";

export const gd02Nemo080: UnitCard = {
  cardNumber: "GD02-080",
  name: "Nemo",
  type: "unit",
  color: "white",
  traits: ["aeug"],
  id: "GD02-080",
  externalId: "gundam:gd02-080",
  slug: "nemo-gd02-080",
  displayName: "Nemo",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-080",
  printings: [
    {
      id: "GD02-080",
      collectorNumber: "GD02-080",
      cardNumber: "GD02-080",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-080.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-080.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-080",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-080.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-080.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
