import type { UnitCard } from "@tcg/gundam-types";

export const gd02LaudaSDilanza084: UnitCard = {
  cardNumber: "GD02-084",
  name: "Lauda's Dilanza",
  type: "unit",
  color: "white",
  traits: ["academy"],
  id: "GD02-084",
  externalId: "gundam:gd02-084",
  slug: "lauda-s-dilanza-gd02-084",
  displayName: "Lauda's Dilanza",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-084",
  printings: [
    {
      id: "GD02-084",
      collectorNumber: "GD02-084",
      cardNumber: "GD02-084",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-084.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-084.webp?260424",
      productName: "Dual Impact [GD02]",
    },
  ],
  selectedPrintingId: "GD02-084",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/GD02-084.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD02-084.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 1,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
