import type { UnitCard } from "@tcg/gundam-types";

export const gd02LaudaSDilanza084: UnitCard = {
  cardNumber: "GD02-084",
  name: "Lauda's Dilanza",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "white",
  traits: ["academy"],
  id: "GD02-084",
  canonicalId: "GD02-084",
  externalIds: { bandai: "gundam:gd02-084" },
  slug: "lauda-s-dilanza/gd02-084",
  displayName: "Lauda's Dilanza",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "GD02-084",
  printings: [
    {
      id: "GD02-084",
      artId: "GD02-084",
      setCode: "GD02",
      collectorNumber: "GD02-084",
      cardNumber: "GD02-084",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-084.webp",
      productName: "Dual Impact [GD02]",
    },
  ],
  reprints: ["GD02-084"],
  selectedPrintingId: "GD02-084",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/GD02-084.webp",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 1,
  hp: 3,
  linkCondition: "(Academy) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
