import type { UnitCard } from "@tcg/gundam-types";

export const gd03Messala003: UnitCard = {
  cardNumber: "GD03-003",
  name: "Messala",
  type: "unit",
  color: "blue",
  traits: ["titans", "jupitris"],
  id: "GD03-003",
  externalId: "gundam:gd03-003",
  slug: "messala-gd03-003",
  displayName: "Messala",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-003",
  printings: [
    {
      id: "GD03-003",
      collectorNumber: "GD03-003",
      cardNumber: "GD03-003",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "rare",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-003.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD03-003_p1",
      collectorNumber: "GD03-003_p1",
      cardNumber: "GD03-003",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "rare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-003_p1.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-003.webp?260424",
  legality: "legal",
  level: 6,
  cost: 4,
  ap: 5,
  hp: 4,
  linkCondition: "(Jupitris) Trait",
  effect:
    "<Blocker> (Rest this Unit to change the attack target to it.)\n<Repair 1> (At the end of your turn, this Unit recovers the specified number of HP.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }, { keyword: "Repair", value: 1 }],
  rarity: "rare",
};
