import type { UnitCard } from "@tcg/gundam-types";

export const gd03FullArmorUnicornGundamDestroyMode010: UnitCard = {
  cardNumber: "GD03-010",
  name: "Full Armor Unicorn Gundam (Destroy Mode)",
  type: "unit",
  color: "blue",
  traits: ["civilian"],
  id: "GD03-010",
  externalId: "gundam:gd03-010",
  slug: "full-armor-unicorn-gundam-destroy-mode-gd03-010",
  displayName: "Full Armor Unicorn Gundam (Destroy Mode)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-010",
  printings: [
    {
      id: "GD03-010",
      collectorNumber: "GD03-010",
      cardNumber: "GD03-010",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-010.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-010.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD03-010_p1",
      collectorNumber: "GD03-010_p1",
      cardNumber: "GD03-010",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-010_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-010_p1.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD03-010_p2",
      collectorNumber: "GD03-010_p2",
      cardNumber: "GD03-010",
      set: {
        code: "GD03",
        name: "Store Tournament Participant Pack 03",
        packageId: "616901",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-010_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-010_p2.webp?260424",
      productName: "Store Tournament Participant Pack 03",
    },
    {
      id: "GD03-010_p3",
      collectorNumber: "GD03-010_p3",
      cardNumber: "GD03-010",
      set: {
        code: "GD03",
        name: "Store Tournament Winner Pack 03",
        packageId: "616901",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-010_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-010_p3.webp?260424",
      productName: "Store Tournament Winner Pack 03",
    },
  ],
  selectedPrintingId: "GD03-010",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-010.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-010.webp?260424",
  legality: "legal",
  level: 8,
  cost: 6,
  ap: 6,
  hp: 6,
  linkCondition: "[Banagher Links]",
  effect: "<Repair 3> (At the end of your turn, this Unit recovers the specified number of HP.)",
  keywordEffects: [{ keyword: "Repair", value: 3 }],
  rarity: "uncommon",
};
