import type { UnitCard } from "@tcg/gundam-types";

export const gd03GmSniperIi011: UnitCard = {
  cardNumber: "GD03-011",
  name: "GM Sniper II",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "GD03-011",
  externalId: "gundam:gd03-011",
  slug: "gm-sniper-ii-gd03-011",
  displayName: "GM Sniper II",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-011",
  printings: [
    {
      id: "GD03-011",
      collectorNumber: "GD03-011",
      cardNumber: "GD03-011",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-011.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-011.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-011",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-011.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-011.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
