import type { UnitCard } from "@tcg/gundam-types";

export const gd03MessalaMaMode012: UnitCard = {
  cardNumber: "GD03-012",
  name: "Messala (MA Mode)",
  type: "unit",
  color: "blue",
  traits: ["titans", "jupitris"],
  id: "GD03-012",
  externalId: "gundam:gd03-012",
  slug: "messala-ma-mode-gd03-012",
  displayName: "Messala (MA Mode)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-012",
  printings: [
    {
      id: "GD03-012",
      collectorNumber: "GD03-012",
      cardNumber: "GD03-012",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-012.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-012.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-012",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-012.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-012.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 2,
  linkCondition: "(Jupitris) Trait",
  effect: "<Repair 1> (At the end of your turn, this Unit recovers the specified number of HP.)",
  keywordEffects: [{ keyword: "Repair", value: 1 }],
  rarity: "common",
};
