import type { UnitCard } from "@tcg/gundam-types";

export const gd03FullArmorUnicornGundamUnicornMode016: UnitCard = {
  cardNumber: "GD03-016",
  name: "Full Armor Unicorn Gundam (Unicorn Mode)",
  type: "unit",
  color: "blue",
  traits: ["civilian"],
  id: "GD03-016",
  externalId: "gundam:gd03-016",
  slug: "full-armor-unicorn-gundam-unicorn-mode-gd03-016",
  displayName: "Full Armor Unicorn Gundam (Unicorn Mode)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-016",
  printings: [
    {
      id: "GD03-016",
      collectorNumber: "GD03-016",
      cardNumber: "GD03-016",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-016.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-016.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-016",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-016.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-016.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Banagher Links]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
