import type { UnitCard } from "@tcg/gundam-types";

export const gd03ZGokE027: UnitCard = {
  cardNumber: "GD03-027",
  name: "Z’Gok E",
  type: "unit",
  color: "green",
  traits: ["zeon", "cyclops team"],
  id: "GD03-027",
  externalId: "gundam:gd03-027",
  slug: "z-gok-e-gd03-027",
  displayName: "Z’Gok E",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-027",
  printings: [
    {
      id: "GD03-027",
      collectorNumber: "GD03-027",
      cardNumber: "GD03-027",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-027.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-027.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "GD03-027_p1",
      collectorNumber: "GD03-027_p1",
      cardNumber: "GD03-027",
      set: {
        code: "GD03",
        name: "WORLD CHAMPIONSHIPS 26-27 Participation Pack 26-27 Vol.1",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-027_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-027_p1.webp?260424",
      productName: "WORLD CHAMPIONSHIPS 26-27 Participation Pack 26-27 Vol.1",
    },
  ],
  selectedPrintingId: "GD03-027",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-027.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-027.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "(Cyclops Team) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
