import type { UnitCard } from "@tcg/gundam-types";

export const gd03GundamAge1Flat031: UnitCard = {
  cardNumber: "GD03-031",
  name: "Gundam AGE-1 Flat",
  type: "unit",
  color: "green",
  traits: ["earth federation", "age system"],
  id: "GD03-031",
  externalId: "gundam:gd03-031",
  slug: "gundam-age-1-flat-gd03-031",
  displayName: "Gundam AGE-1 Flat",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-031",
  printings: [
    {
      id: "GD03-031",
      collectorNumber: "GD03-031",
      cardNumber: "GD03-031",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-031.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-031.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-031",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-031.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-031.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Asuno Family) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
