import type { UnitCard } from "@tcg/gundam-types";

export const gd03ZakuFourSnakeEyesYetiGq032: UnitCard = {
  cardNumber: "GD03-032",
  name: "Zaku (Four Snake Eyes') [YETI] (GQ)",
  type: "unit",
  color: "green",
  traits: ["clan"],
  id: "GD03-032",
  externalId: "gundam:gd03-032",
  slug: "zaku-four-snake-eyes-yeti-gq-gd03-032",
  displayName: "Zaku (Four Snake Eyes') [YETI] (GQ)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-032",
  printings: [
    {
      id: "GD03-032",
      collectorNumber: "GD03-032",
      cardNumber: "GD03-032",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-032.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-032.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-032",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-032.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-032.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
