import type { UnitCard } from "@tcg/gundam-types";

export const gd03Cgue046: UnitCard = {
  cardNumber: "GD03-046",
  name: "CGUE",
  type: "unit",
  color: "red",
  traits: ["zaft"],
  id: "GD03-046",
  externalId: "gundam:gd03-046",
  slug: "cgue-gd03-046",
  displayName: "CGUE",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-046",
  printings: [
    {
      id: "GD03-046",
      collectorNumber: "GD03-046",
      cardNumber: "GD03-046",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-046.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-046.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-046",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-046.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-046.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
