import type { UnitCard } from "@tcg/gundam-types";

export const gd03DinnCommanderType047: UnitCard = {
  cardNumber: "GD03-047",
  name: "DINN (Commander Type)",
  type: "unit",
  color: "red",
  traits: ["zaft"],
  id: "GD03-047",
  externalId: "gundam:gd03-047",
  slug: "dinn-commander-type-gd03-047",
  displayName: "DINN (Commander Type)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-047",
  printings: [
    {
      id: "GD03-047",
      collectorNumber: "GD03-047",
      cardNumber: "GD03-047",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-047.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-047.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-047",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-047.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-047.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "[Rau Le Creuset]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
