import type { UnitCard } from "@tcg/gundam-types";

export const gd03GnArmorTypeE057: UnitCard = {
  cardNumber: "GD03-057",
  name: "GN Armor (Type-E)",
  type: "unit",
  color: "purple",
  traits: ["cb", "gn drive"],
  id: "GD03-057",
  externalId: "gundam:gd03-057",
  slug: "gn-armor-type-e-gd03-057",
  displayName: "GN Armor (Type-E)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-057",
  printings: [
    {
      id: "GD03-057",
      collectorNumber: "GD03-057",
      cardNumber: "GD03-057",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-057.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-057.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-057",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-057.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-057.webp?260424",
  legality: "legal",
  level: 6,
  cost: 4,
  ap: 5,
  hp: 4,
  linkCondition: "(CB) Trait",
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
