import type { UnitCard } from "@tcg/gundam-types";

export const gd030Gundam063: UnitCard = {
  cardNumber: "GD03-063",
  name: "0 Gundam",
  type: "unit",
  color: "purple",
  traits: ["cb", "gn drive"],
  id: "GD03-063",
  externalId: "gundam:gd03-063",
  slug: "0-gundam-gd03-063",
  displayName: "0 Gundam",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-063",
  printings: [
    {
      id: "GD03-063",
      collectorNumber: "GD03-063",
      cardNumber: "GD03-063",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-063.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-063.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-063",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-063.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-063.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
