import type { UnitCard } from "@tcg/gundam-types";

export const gd03ZedasM065: UnitCard = {
  cardNumber: "GD03-065",
  name: "Zedas M",
  type: "unit",
  color: "purple",
  traits: ["vagan"],
  id: "GD03-065",
  externalId: "gundam:gd03-065",
  slug: "zedas-m-gd03-065",
  displayName: "Zedas M",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-065",
  printings: [
    {
      id: "GD03-065",
      collectorNumber: "GD03-065",
      cardNumber: "GD03-065",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-065.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-065.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-065",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-065.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-065.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "(X-Rounder) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
