import type { UnitCard } from "@tcg/gundam-types";

export const gd03GundamBarbatos5thFormGroundType066: UnitCard = {
  cardNumber: "GD03-066",
  name: "Gundam Barbatos 5th Form (Ground Type)",
  type: "unit",
  color: "purple",
  traits: ["tekkadan", "gundam frame"],
  id: "GD03-066",
  externalId: "gundam:gd03-066",
  slug: "gundam-barbatos-5th-form-ground-type-gd03-066",
  displayName: "Gundam Barbatos 5th Form (Ground Type)",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "GD03-066",
  printings: [
    {
      id: "GD03-066",
      collectorNumber: "GD03-066",
      cardNumber: "GD03-066",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-066.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-066.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "GD03-066",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd03/GD03-066.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD03-066.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Mikazuki Augus]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
