// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAtstRaider = {
  title: "AT-ST Raider",
  cost: 4,
  hp: 5,
  power: 4,
  text: "While you control another non-<uq> unit, this unit gains Ambush. (When you play this unit, it may attack an enemy unit.)",
  unique: false,
  id: "2614961429",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["vehicle", "walker"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 98,
  },
  setCodes: [
    {
      set: "ASH",
      number: 98,
    },
  ],
  internalName: "atst-raider",
  cardType: "unit",
  canonicalId: "atst-raider",
  slug: "atst-raider",
  name: "AT-ST Raider",
  printings: [
    {
      id: "ASH_098",
      artId: "52172",
      setCode: "ASH",
      collectorNumber: "98",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010098_EN_AT_ST_Raider_f5927a4a79.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuAtstRaider;
