// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuBarrissOffeeRedeemingHerself = {
  title: "Barriss Offee",
  subtitle: "Redeeming Herself",
  cost: 3,
  hp: 4,
  power: 3,
  text: "When Played: Heal up to 2 damage from a unit. Give an Advantage token to it for each damage healed this way.",
  unique: true,
  id: "1853815084",
  rarity: "uncommon",
  aspects: ["cunning", "vigilance"],
  traits: ["force", "fringe"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 44,
  },
  setCodes: [
    {
      set: "ASH",
      number: 44,
    },
  ],
  internalName: "barriss-offee#redeeming-herself",
  cardType: "unit",
  canonicalId: "barriss-offee#redeeming-herself",
  slug: "barriss-offee-redeeming-herself",
  name: "Barriss Offee",
  printings: [
    {
      id: "ASH_044",
      artId: "51902",
      setCode: "ASH",
      collectorNumber: "44",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010044_EN_Barriss_Offee_405ca30947.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Heal up to 2 damage from a unit. Give an Advantage token to it for each damage healed this way.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "heal",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuBarrissOffeeRedeemingHerself;
