// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuBatteredHaulcraft = {
  title: "Battered Haulcraft",
  cost: 2,
  hp: 3,
  power: 2,
  text: "When Played: Deal 1 damage to this unit and 1 damage to an enemy space unit.",
  unique: false,
  id: "3515403989",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 71,
  },
  setCodes: [
    {
      set: "ASH",
      number: 71,
    },
  ],
  internalName: "battered-haulcraft",
  cardType: "unit",
  canonicalId: "battered-haulcraft",
  slug: "battered-haulcraft",
  name: "Battered Haulcraft",
  printings: [
    {
      id: "ASH_071",
      artId: "52037",
      setCode: "ASH",
      collectorNumber: "71",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010071_EN_Battered_Haulcraft_59a7c5d8c6.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played: Deal 1 damage to this unit and 1 damage to an enemy space unit.",
      effects: [
        effect.sequential([
          effect.damage(target.self(), 1),
          effect.damage(target.unit({ controller: "opponent", arena: "space", limit: 1 }), 1),
        ]),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuBatteredHaulcraft;
