// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuBladeThreeBaneOfTheDevastator = {
  title: "Blade Three",
  subtitle: "Bane of the Devastator",
  cost: 3,
  hp: 4,
  power: 2,
  text: "When your base is dealt damage: Give an Advantage token to this unit.",
  unique: true,
  id: "7634552408",
  rarity: "uncommon",
  aspects: ["cunning", "heroism"],
  traits: ["rebel", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 204,
  },
  setCodes: [
    {
      set: "ASH",
      number: 204,
    },
  ],
  internalName: "blade-three#bane-of-the-devastator",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "when", name: "your base is dealt damage" },
      {
        text: "When your base is dealt damage: Give an Advantage token to this unit.",
        effects: [effect.distribute("advantage", target.self(), 1)],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuBladeThreeBaneOfTheDevastator;
