// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCarsonTevaTheresSomethingGoingOn = {
  title: "Carson Teva",
  subtitle: "There's Something Going On",
  cost: 2,
  hp: 4,
  power: 1,
  text: "Support (When you play this unit, you may attack with another unit. It gains this unit's other abilities for this attack.)\nWhile attacking, this unit deals combat damage before the defender.",
  unique: true,
  id: "7521690984",
  rarity: "rare",
  aspects: ["cunning", "heroism"],
  traits: ["new republic"],
  arena: "ground",
  keywords: ["support"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 202,
  },
  setCodes: [
    {
      set: "ASH",
      number: 202,
    },
  ],
  internalName: "carson-teva#theres-something-going-on",
  cardType: "unit",
  canonicalId: "carson-teva#theres-something-going-on",
  slug: "carson-teva-theres-something-going-on",
  name: "Carson Teva",
  printings: [
    {
      id: "ASH_202",
      artId: "52691",
      setCode: "ASH",
      collectorNumber: "202",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//08010202_EN_Carson_Teva_b5c9b36ee1.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Support",
      keyword: "support",
    },
  ],
} satisfies SwuUnitCard;

export default swuCarsonTevaTheresSomethingGoingOn;
