// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuChildrenOfTheWatch = {
  title: "Children of the Watch",
  cost: 6,
  hp: 3,
  power: 3,
  text: "When Played: Create 2 Mandalorian tokens.",
  unique: false,
  id: "5980742717",
  rarity: "common",
  aspects: ["command", "heroism"],
  traits: ["mandalorian"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 111,
  },
  setCodes: [
    {
      set: "ASH",
      number: 111,
    },
  ],
  internalName: "children-of-the-watch",
  cardType: "unit",
  canonicalId: "children-of-the-watch",
  slug: "children-of-the-watch",
  name: "Children of the Watch",
  printings: [
    {
      id: "ASH_111",
      artId: "52236",
      setCode: "ASH",
      collectorNumber: "111",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//08010111_EN_Children_of_the_Watch_9dd8f42cb4.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Create 2 Mandalorian tokens.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "mandalorian",
          amount: 2,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuChildrenOfTheWatch;
