// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDarthVaderMeetYourDestiny = {
  title: "Darth Vader",
  subtitle: "Meet Your Destiny",
  cost: 5,
  hp: 6,
  power: 4,
  text: "Shielded\nWhile this unit is ready, he gains Sentinel.",
  unique: true,
  id: "2759135991",
  rarity: "special",
  aspects: ["villainy"],
  traits: ["force", "imperial", "sith"],
  arena: "ground",
  keywords: ["shielded", "sentinel"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 243,
  },
  setCodes: [
    {
      set: "ASH",
      number: 243,
    },
  ],
  internalName: "darth-vader#meet-your-destiny",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuDarthVaderMeetYourDestiny;
