// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuGallofreeTransport = {
  title: "Gallofree Transport",
  cost: 4,
  hp: 5,
  power: 3,
  text: "When Defeated: Give 2 Advantage tokens to a friendly unit.",
  unique: false,
  id: "9397308249",
  rarity: "common",
  aspects: ["heroism"],
  traits: ["rebel", "vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 254,
  },
  setCodes: [
    {
      set: "ASH",
      number: 254,
    },
  ],
  internalName: "gallofree-transport",
  cardType: "unit",
  canonicalId: "gallofree-transport",
  slug: "gallofree-transport",
  name: "Gallofree Transport",
  printings: [
    {
      id: "ASH_254",
      artId: "52949",
      setCode: "ASH",
      collectorNumber: "254",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010254_EN_Gallofree_Transport_6c54bb42f2.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "defeated" },
      {
        text: "When Defeated: Give 2 Advantage tokens to a friendly unit.",
        effects: [
          effect.distribute("advantage", target.unit({ controller: "friendly", limit: 1 }), 2),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuGallofreeTransport;
