// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHuyangYourAptitudeFallsShort = {
  title: "Huyang",
  subtitle: "Your Aptitude Falls Short",
  cost: 2,
  hp: 4,
  power: 2,
  text: "On Attack: You may give an upgraded unit –4/–0 for this phase.",
  unique: true,
  id: "5606840637",
  rarity: "uncommon",
  aspects: ["vigilance", "heroism"],
  traits: ["jedi", "droid"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 56,
  },
  setCodes: [
    {
      set: "ASH",
      number: 56,
    },
  ],
  internalName: "huyang#your-aptitude-falls-short",
  cardType: "unit",
  canonicalId: "huyang#your-aptitude-falls-short",
  slug: "huyang-your-aptitude-falls-short",
  name: "Huyang",
  printings: [
    {
      id: "ASH_056",
      artId: "51962",
      setCode: "ASH",
      collectorNumber: "56",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010056_EN_Huyang_edbfc19172.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "On Attack: You may give an upgraded unit -4/-0 for this phase.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "modifyStats",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
              power: -4,
              hp: 0,
              duration: "phase",
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuHuyangYourAptitudeFallsShort;
