// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuJodNaNawoodKeepingSecrets = {
  title: "Jod Na Nawood",
  subtitle: "Keeping Secrets",
  cost: 3,
  hp: 3,
  power: 4,
  text: "Sentinel\nWhen Played: You may pay 4 resources. If you do, choose an arena. Exhaust each unit in that arena.",
  unique: true,
  id: "8838303580",
  rarity: "rare",
  aspects: ["cunning"],
  traits: ["force", "underworld"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 219,
  },
  setCodes: [
    {
      set: "ASH",
      number: 219,
    },
  ],
  internalName: "jod-na-nawood#keeping-secrets",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuJodNaNawoodKeepingSecrets;
