// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuKachirhoMilitia = {
  title: "Kachirho Militia",
  cost: 5,
  hp: 6,
  power: 4,
  text: "Hidden (This unit can't be attacked if it was played this phase.)\nWhen an enemy ground unit attacks your base: Ready this unit. Use this ability only once each round.",
  unique: false,
  id: "6989468664",
  rarity: "uncommon",
  aspects: ["aggression", "heroism"],
  traits: ["wookiee", "trooper"],
  arena: "ground",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 160,
  },
  setCodes: [
    {
      set: "ASH",
      number: 160,
    },
  ],
  internalName: "kachirho-militia",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuKachirhoMilitia;
