// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuKelleranBeqWhereAreTheOthers = {
  title: "Kelleran Beq",
  subtitle: "Where are the Others?",
  cost: 4,
  hp: 5,
  power: 3,
  text: "Ambush\nThis unit gets +1/+0 for each other unit (friendly and enemy) with 0 power.",
  unique: true,
  id: "2037046615",
  rarity: "legendary",
  aspects: ["cunning", "heroism"],
  traits: ["force", "jedi"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 206,
  },
  setCodes: [
    {
      set: "ASH",
      number: 206,
    },
  ],
  internalName: "kelleran-beq#where-are-the-others",
  cardType: "unit",
  canonicalId: "kelleran-beq#where-are-the-others",
  slug: "kelleran-beq-where-are-the-others",
  name: "Kelleran Beq",
  printings: [
    {
      id: "ASH_206",
      artId: "52711",
      setCode: "ASH",
      collectorNumber: "206",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//08010206_EN_Kelleran_Beq_1f3ab3634d.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuKelleranBeqWhereAreTheOthers;
