// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLukeSkywalkerAnsweringTheCall = {
  title: "Luke Skywalker",
  subtitle: "Answering the Call",
  cost: 6,
  hp: 5,
  power: 5,
  text: "Restore 1\nWhen Played: If you control at least 4 units, deal 3 damage to each enemy unit.",
  unique: true,
  id: "5301694614",
  rarity: "legendary",
  aspects: ["command", "heroism"],
  traits: ["force", "jedi"],
  arena: "ground",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 112,
  },
  setCodes: [
    {
      set: "ASH",
      number: 112,
    },
  ],
  internalName: "luke-skywalker#answering-the-call",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuLukeSkywalkerAnsweringTheCall;
