// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuMortarTrooper = {
  title: "Mortar Trooper",
  cost: 2,
  hp: 4,
  power: 1,
  text: "Action [Exhaust]: Deal 1 damage to each of up to 3 ground units.",
  unique: false,
  id: "0538012086",
  rarity: "uncommon",
  aspects: ["aggression", "villainy"],
  traits: ["imperial", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 142,
  },
  setCodes: [
    {
      set: "ASH",
      number: 142,
    },
  ],
  internalName: "mortar-trooper",
  cardType: "unit",
  abilities: [
    {
      kind: "action",
      text: "Action [Exhaust]: Deal 1 damage to each of up to 3 ground units.",
      trigger: {
        event: "action",
      },
      effects: [
        {
          type: "damage",
          amount: 1,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            arena: "ground",
            excludeSelf: false,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuMortarTrooper;
