// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuNinthSisterHulkingInquisitor = {
  title: "Ninth Sister",
  subtitle: "Hulking Inquisitor",
  cost: 7,
  hp: 7,
  power: 8,
  text: "Overwhelm\nWhen Played: An opponent discards a card from their hand. You may deal damage equal to its cost divided as you choose among any number of units.",
  unique: true,
  id: "7852298661",
  rarity: "legendary",
  aspects: ["aggression", "villainy"],
  traits: ["force", "imperial", "inquisitor"],
  arena: "ground",
  keywords: ["overwhelm"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 148,
  },
  setCodes: [
    {
      set: "ASH",
      number: 148,
    },
  ],
  internalName: "ninth-sister#hulking-inquisitor",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
    {
      kind: "triggered",
      text: "When Played: An opponent discards a card from their hand. You may deal damage equal to its cost divided as you choose among any number of units.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "discard",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["hand"],
            limit: 1,
          },
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuNinthSisterHulkingInquisitor;
