// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuNotiNomad = {
  title: "Noti Nomad",
  cost: 1,
  hp: 2,
  power: 1,
  text: "Shielded (When you play this unit, give a Shield token to it.)",
  unique: false,
  id: "3444968285",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["fringe"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 69,
  },
  setCodes: [
    {
      set: "ASH",
      number: 69,
    },
  ],
  internalName: "noti-nomad",
  cardType: "unit",
  canonicalId: "noti-nomad",
  slug: "noti-nomad",
  name: "Noti Nomad",
  printings: [
    {
      id: "ASH_069",
      artId: "52027",
      setCode: "ASH",
      collectorNumber: "69",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010069_EN_Noti_Nomad_386e2cec17.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuNotiNomad;
