// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuOutcastMercenaryStarship = {
  title: "Outcast",
  subtitle: "Mercenary Starship",
  cost: 2,
  hp: 4,
  power: 1,
  text: "When a friendly unit enters play (including this one): It gets +1/+0 for this phase.",
  unique: true,
  id: "5394891260",
  rarity: "uncommon",
  aspects: ["aggression", "cunning"],
  traits: ["underworld", "vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 41,
  },
  setCodes: [
    {
      set: "ASH",
      number: 41,
    },
  ],
  internalName: "outcast#mercenary-starship",
  cardType: "unit",
  canonicalId: "outcast#mercenary-starship",
  slug: "outcast-mercenary-starship",
  name: "Outcast",
  printings: [
    {
      id: "ASH_041",
      artId: "51887",
      setCode: "ASH",
      collectorNumber: "41",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010041_EN_Outcast_cf03f42271.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "when", name: "a friendly unit enters play" },
      {
        text: "When a friendly unit enters play (including this one): It gets +1/+0 for this phase.",
        effects: [
          effect.modifyStats(target.unit({ controller: "friendly", limit: 1 }), {
            power: 1,
            duration: "phase",
          }),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuOutcastMercenaryStarship;
