// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRebelInfiltrators = {
  title: "Rebel Infiltrators",
  cost: 5,
  hp: 6,
  power: 4,
  text: "Restore 1 (When this unit attacks, heal 1 damage from your base.)\nSaboteur (When this unit attacks, ignore Sentinel and defeat the defender's Shields.)",
  unique: false,
  id: "0144344845",
  rarity: "common",
  aspects: ["heroism"],
  traits: ["rebel", "trooper"],
  arena: "ground",
  keywords: ["restore", "saboteur"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 256,
  },
  setCodes: [
    {
      set: "ASH",
      number: 256,
    },
  ],
  internalName: "rebel-infiltrators",
  cardType: "unit",
  canonicalId: "rebel-infiltrators",
  slug: "rebel-infiltrators",
  name: "Rebel Infiltrators",
  printings: [
    {
      id: "ASH_256",
      artId: "52959",
      setCode: "ASH",
      collectorNumber: "256",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010256_EN_Rebel_Infiltrators_4a928026f2.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
  ],
} satisfies SwuUnitCard;

export default swuRebelInfiltrators;
