// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuShinHatiGoingSomewhere = {
  title: "Shin Hati",
  subtitle: "Going Somewhere?",
  cost: 5,
  hp: 6,
  power: 6,
  text: "While this is the only friendly non-leader ground unit, she gains Sentinel. (Enemy units in this arena must attack a Sentinel when they attack you.)",
  unique: true,
  id: "1043323645",
  rarity: "uncommon",
  aspects: ["vigilance", "villainy"],
  traits: ["force"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 49,
  },
  setCodes: [
    {
      set: "ASH",
      number: 49,
    },
  ],
  internalName: "shin-hati#going-somewhere",
  cardType: "unit",
  canonicalId: "shin-hati#going-somewhere",
  slug: "shin-hati-going-somewhere",
  name: "Shin Hati",
  printings: [
    {
      id: "ASH_049",
      artId: "51927",
      setCode: "ASH",
      collectorNumber: "49",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010049_EN_Shin_Hati_75f77c75b1.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuShinHatiGoingSomewhere;
