// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuShydoppPirateSkiff = {
  title: "Shydopp Pirate Skiff",
  cost: 4,
  hp: 5,
  power: 4,
  text: "Saboteur (When this unit attacks, ignore Sentinel and defeat the defender's Shields.)",
  unique: false,
  id: "4513422222",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["underworld", "vehicle", "transport"],
  arena: "ground",
  keywords: ["saboteur"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 173,
  },
  setCodes: [
    {
      set: "ASH",
      number: 173,
    },
  ],
  internalName: "shydopp-pirate-skiff",
  cardType: "unit",
  canonicalId: "shydopp-pirate-skiff",
  slug: "shydopp-pirate-skiff",
  name: "Shydopp Pirate Skiff",
  printings: [
    {
      id: "ASH_173",
      artId: "52546",
      setCode: "ASH",
      collectorNumber: "173",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//08010173_EN_Shydopp_Pirate_Skiff_3c94855825.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
  ],
} satisfies SwuUnitCard;

export default swuShydoppPirateSkiff;
