// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuStolenEtaShuttle = {
  title: "Stolen Eta Shuttle",
  cost: 4,
  hp: 5,
  power: 3,
  text: "Hidden (This unit can't be attacked if it was played this phase.)\nWhile you have the initiative, this unit gets +2/+0.",
  unique: false,
  id: "7063302069",
  rarity: "uncommon",
  aspects: ["command"],
  traits: ["vehicle", "transport"],
  arena: "space",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 125,
  },
  setCodes: [
    {
      set: "ASH",
      number: 125,
    },
  ],
  internalName: "stolen-eta-shuttle",
  cardType: "unit",
  canonicalId: "stolen-eta-shuttle",
  slug: "stolen-eta-shuttle",
  name: "Stolen Eta Shuttle",
  printings: [
    {
      id: "ASH_125",
      artId: "52306",
      setCode: "ASH",
      collectorNumber: "125",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010125_EN_Stolen_Eta_Shuttle_01b8cf8b00.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "While you have the initiative, this unit gets +2/+0.",
      conditions: [
        {
          type: "hasInitiative",
          controller: "friendly",
        },
      ],
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "self",
          },
          power: 2,
          hp: 0,
          duration: "phase",
        },
      ],
    },
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuStolenEtaShuttle;
