// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTieStriker = {
  title: "TIE Striker",
  cost: 1,
  hp: 1,
  power: 2,
  text: "Saboteur (When this unit attacks, ignore Sentinel and defeat the defender's Shields.)",
  unique: false,
  id: "9922783781",
  rarity: "common",
  aspects: ["aggression", "villainy"],
  traits: ["imperial", "vehicle", "fighter"],
  arena: "space",
  keywords: ["saboteur"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 141,
  },
  setCodes: [
    {
      set: "ASH",
      number: 141,
    },
  ],
  internalName: "tie-striker",
  cardType: "unit",
  canonicalId: "tie-striker",
  slug: "tie-striker",
  name: "TIE Striker",
  printings: [
    {
      id: "ASH_141",
      artId: "52386",
      setCode: "ASH",
      collectorNumber: "141",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010141_EN_TIE_Striker_f3ee8761d7.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
  ],
} satisfies SwuUnitCard;

export default swuTieStriker;
