// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuVanesSnubFighterBrashAndProud = {
  title: "Vane's Snub Fighter",
  subtitle: "Brash and Proud",
  cost: 3,
  hp: 4,
  power: 2,
  text: "When a friendly unit's attack ends: If it dealt combat damage to a base, give an Advantage token to this unit.",
  unique: true,
  id: "3024525867",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["underworld", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 144,
  },
  setCodes: [
    {
      set: "ASH",
      number: 144,
    },
  ],
  internalName: "vanes-snub-fighter#brash-and-proud",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "When a friendly unit's attack ends: If it dealt combat damage to a base, give an Advantage token to this unit.",
        effects: [effect.distribute("advantage", target.self(), 1)],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuVanesSnubFighterBrashAndProud;
