// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuYellowAcesBomber = {
  title: "Yellow Aces Bomber",
  cost: 3,
  hp: 4,
  power: 2,
  text: "Support (When you play this unit, you may attack with another unit. It gains this unit's other abilities for this attack.)\nOn Attack: If this unit is upgraded, deal 2 damage to a base.",
  unique: false,
  id: "6234240452",
  rarity: "uncommon",
  aspects: ["heroism"],
  traits: ["new republic", "vehicle", "fighter"],
  arena: "space",
  keywords: ["support"],
  types: ["unit"],
  setId: {
    set: "ASH",
    number: 253,
  },
  setCodes: [
    {
      set: "ASH",
      number: 253,
    },
  ],
  internalName: "yellow-aces-bomber",
  cardType: "unit",
  canonicalId: "yellow-aces-bomber",
  slug: "yellow-aces-bomber",
  name: "Yellow Aces Bomber",
  printings: [
    {
      id: "ASH_253",
      artId: "52944",
      setCode: "ASH",
      collectorNumber: "253",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//08010253_EN_Yellow_Aces_Bomber_d6842f3f55.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Support",
      keyword: "support",
    },
  ],
} satisfies SwuUnitCard;

export default swuYellowAcesBomber;
