import type { BaseCard } from "@tcg/gundam-types";

export const exbpExBase001: BaseCard = {
  cardNumber: "EXBP-001",
  name: "EX Base",
  type: "base",
  traits: [],
  id: "EXBP-001",
  externalId: "gundam:exbp-001",
  slug: "ex-base-exbp-001",
  displayName: "EX Base",
  set: { code: "EXBP", name: "Edition Beta Early Trial Event, other events", packageId: "616901" },
  printNumber: "EXBP-001",
  printings: [
    {
      id: "EXBP-001",
      collectorNumber: "EXBP-001",
      cardNumber: "EXBP-001",
      set: {
        code: "EXBP",
        name: "Edition Beta Early Trial Event, other events",
        packageId: "616901",
      },
      rarity: "promo",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exbp/EXBP-001.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXBP-001.webp?260424",
      productName: "Edition Beta Early Trial Event, other events",
    },
  ],
  selectedPrintingId: "EXBP-001",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/exbp/EXBP-001.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXBP-001.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  hp: 3,
  effect: "(At the start of the game, place 1 active EX Base as your shield area's base.)",
  effects: [],
  keywordEffects: [],
  rarity: "promo",
};
