import type { BaseCard } from "@tcg/gundam-types";

export const exbpExBase007: BaseCard = {
  cardNumber: "EXBP-007",
  name: "EX Base",
  type: "base",
  traits: [],
  id: "EXBP-007",
  canonicalId: "EXBP-007",
  externalIds: { bandai: "gundam:exbp-007" },
  slug: "ex-base/exbp-007",
  displayName: "EX Base",
  set: {
    code: "EXBP",
    name: "SD Gundam G Generation ETERNAL Collaboration Pack",
    packageId: "616901",
  },
  printNumber: "EXBP-007",
  printings: [
    {
      id: "EXBP-007",
      artId: "EXBP-007",
      setCode: "EXBP",
      collectorNumber: "EXBP-007",
      cardNumber: "EXBP-007",
      set: {
        code: "EXBP",
        name: "SD Gundam G Generation ETERNAL Collaboration Pack",
        packageId: "616901",
      },
      rarity: "promo",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exbp/EXBP-007.webp",
      productName: "SD Gundam G Generation ETERNAL Collaboration Pack",
    },
  ],
  reprints: ["EXBP-007"],
  selectedPrintingId: "EXBP-007",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/exbp/EXBP-007.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  hp: 3,
  effect: "(At the start of the game, place 1 active EX Base as your shield area's base.)",
  effects: [],
  keywordEffects: [],
  rarity: "promo",
};
