// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuMorganElsbethFollowingTheCall = {
  title: "Morgan Elsbeth",
  subtitle: "Following the Call",
  cost: 5,
  hp: 6,
  power: 3,
  text: "Action [Exhaust]: Choose a friendly unit that attacked this phase. Play a unit from your hand that shares a keyword with the chosen unit. It costs 1 resource less.",
  deployBox:
    "On Attack: The next unit you play this phase costs 1 resource less if it shares a keyword with a friendly unit.",
  epicAction: "Epic Action: If you control 5 or more resources, deploy this leader.",
  unique: true,
  rules:
    'In order to benefit from Morgan\'s cost reduction, the unit being played must already have a shared keyword while paying its cost. Effects that grant keywords like Ambush to units when you play them typically only grant them at the moment of play, which occurs after costs are paid.\nThe cost reduction from Morgan\'s "On Attack" ability remains active even if she is defeated.\nMorgan\'s On Attack ability can discount the cost of a unit that is played and granted a keyword by a modified Play a Card action (e.g. "Play a unit and give it Ambush for this phase.").\n',
  id: "5045607736",
  rarity: "rare",
  aspects: ["command", "villainy"],
  traits: ["force", "imperial", "night"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "LOF",
    number: 5,
  },
  setCodes: [
    {
      set: "LOF",
      number: 5,
    },
  ],
  internalName: "morgan-elsbeth#following-the-call",
  cardType: "leader",
  canonicalId: "morgan-elsbeth#following-the-call",
  slug: "morgan-elsbeth-following-the-call",
  name: "Morgan Elsbeth",
  printings: [
    {
      id: "LOF_005",
      artId: "27049",
      setCode: "LOF",
      collectorNumber: "5",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05010005_EN_Morgan_Elsbeth_Leader_d765f46b93.png",
    },
    {
      id: "9740773208",
      artId: "27049",
      setCode: "LOF",
      collectorNumber: "269",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05020269_EN_Morgan_Elsbeth_Leader_421beded85.png",
    },
    {
      id: "9863053625",
      artId: "27049",
      setCode: "LOF",
      collectorNumber: "1009",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05031009_EN_Morgan_Elsbeth_Leader_9057ebb285.png",
    },
  ],
  abilities: [
    {
      kind: "action",
      text: "Epic Action: If you control 5 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuMorganElsbethFollowingTheCall;
