/**
 * Hyperia City (set 014) characters: parsed card data vs. printed source data.
 *
 * Expected values are derived from the downloaded source inputs
 * (data/inputs/ravensburger-input.json + data/inputs/lorcast-input.json),
 * so these tests fail when generation, parser normalization, or upstream
 * source data drift away from the printed cards.
 */

import { describe, expect, it } from "bun:test";
import { fruFruVipGuest } from "./001-fru-fru-vip-guest";
import { abuelitaLovingGrandmother } from "./002-abuelita-loving-grandmother";
import { maxGoofMusicLover } from "./003-max-goof-music-lover";
import { gazellePopDiva } from "./004-gazelle-pop-diva";
import { peteSuaveShowoff } from "./005-pete-suave-showoff";
import { miriamMendelsohnFrontrowFan } from "./006-miriam-mendelsohn-front-row-fan";
import { priyaMangalImmovableFan } from "./007-priya-mangal-immovable-fan";
import { yaxConcertGoer } from "./008-yax-concert-goer";
import { judyHoppsHelpfulOfficer } from "./009-judy-hopps-helpful-officer";
import { miguelRiveraPromisingMusician } from "./010-miguel-rivera-promising-musician";
import { nickWildeInquisitiveHarbormaster } from "./011-nick-wilde-inquisitive-harbormaster";
import { pjPeteDevotedFan } from "./012-pj-pete-devoted-fan";
import { mrManchasServiceWithASmile } from "./013-mr-manchas-service-with-a-smile";
import { hctorRiveraGoneToPiecesD23 } from "./d23-013-hector-rivera-gone-to-pieces";
import { nickWildeToyDriveOfficer } from "./014-nick-wilde-toy-drive-officer";
import { clawhauserSafetyOfficer } from "./015-clawhauser-safety-officer";
import { elisaMazaHardworkingDetective } from "./016-elisa-maza-hardworking-detective";
import { powerlineMegastar } from "./017-powerline-megastar";
import { lionheartIncumbentMayor } from "./018-lionheart-incumbent-mayor";
import { auroraDelightfulMusician } from "./019-aurora-delightful-musician";
import { russellFindingAdventure } from "./020-russell-finding-adventure";
import { miguelRiveraStreetMusician } from "./021-miguel-rivera-street-musician";
import { goofyKnowsTheBand } from "./022-goofy-knows-the-band";
import { mickeyMouseBestInTown } from "./023-mickey-mouse-best-in-town";
import { judyHoppsAlwaysVigilant } from "./024-judy-hopps-always-vigilant";
import { nickWildeProvidingBackup } from "./025-nick-wilde-providing-backup";
import { miguelRiveraAccomplishedMusician } from "./026-miguel-rivera-accomplished-musician";
import { owenBurnettXanatossAssistant } from "./035-owen-burnett-xanatoss-assistant";
import { scuttleDirectingTraffic } from "./036-scuttle-directing-traffic";
import { davidXanatosArcaneIndustrialist } from "./037-david-xanatos-arcane-industrialist";
import { lexingtonFearlessFlier } from "./038-lexington-fearless-flier";
import { merlinBaubleExpert } from "./039-merlin-bauble-expert";
import { pepitaWatchfulAlebrije } from "./040-pepita-watchful-alebrije";
import { archimedesHasHadEnough } from "./041-archimedes-has-had-enough";
import { taVictoriaDisapprovingAncestor } from "./042-tia-victoria-disapproving-ancestor";
import { danteEnthusiasticStray } from "./043-dante-enthusiastic-stray";
import { mamCocoVisitingThePark } from "./044-mama-coco-visiting-the-park";
import { tinkerBellCuriousFairy } from "./045-tinker-bell-curious-fairy";
import { madamMimBaubleChaser } from "./046-madam-mim-bauble-chaser";
import { peterPansShadowElusivePrankster } from "./047-peter-pans-shadow-elusive-prankster";
import { danteStrangeAndEndearing } from "./048-dante-strange-and-endearing";
import { foxXanatosCharismaticOutlaw } from "./049-fox-xanatos-charismatic-outlaw";
import { brooklynFullThrottle } from "./050-brooklyn-full-throttle";
import { mamImeldaNononsenseAncestor } from "./051-mama-imelda-no-nonsense-ancestor";
import { merlinInkDropTinkerer } from "./052-merlin-ink-drop-tinkerer";
import { goliathTransformedWarrior } from "./053-goliath-transformed-warrior";
import { danteLoyalAlebrije } from "./054-dante-loyal-alebrije";
import { rapunzelOutgoingArtist } from "./055-rapunzel-outgoing-artist";
import { demonaImperiousSpellcaster } from "./056-demona-imperious-spellcaster";
import { merlinProfoundlyCurious } from "./057-merlin-profoundly-curious";
import { archimedesMessengerOwl } from "./058-archimedes-messenger-owl";
import { madamMimResourcefulTrickster } from "./059-madam-mim-resourceful-trickster";
import { trustyAlongForTheRide } from "./069-trusty-along-for-the-ride";
import { donKarnageKhansCourier } from "./070-don-karnage-khans-courier";
import { hiroHamadaVersatileInventor } from "./071-hiro-hamada-versatile-inventor";
import { goGoTomagoExtremeTester } from "./072-go-go-tomago-extreme-tester";
import { mollyCunninghamRemembersToShare } from "./073-molly-cunningham-remembers-to-share";
import { kitCloudkickerIrrepressibleBear } from "./074-kit-cloudkicker-irrepressible-bear";
import { belleReflectiveWriter } from "./075-belle-reflective-writer";
import { fredAssemblingTheTeam } from "./076-fred-assembling-the-team";
import { captainHookConcernedCaptain } from "./077-captain-hook-concerned-captain";
import { jockEnjoyingTheSights } from "./078-jock-enjoying-the-sights";
import { ladyRelaxedAndRested } from "./079-lady-relaxed-and-rested";
import { rebeccaCunninghamSavvyManager } from "./080-rebecca-cunningham-savvy-manager";
import { shereKhanOpportunisticTycoon } from "./081-shere-khan-opportunistic-tycoon";
import { horaceClumsyClod } from "./082-horace-clumsy-clod";
import { shereKhanRuthlessEntrepreneur } from "./083-shere-khan-ruthless-entrepreneur";
import { bobbyZimuruskiSoundboardWhiz } from "./084-bobby-zimuruski-soundboard-whiz";
import { baymaxLabAssistant } from "./085-baymax-lab-assistant";
import { fredAwesomeBoss } from "./086-fred-awesome-boss";
import { lesterThePossumParkMascot } from "./087-lester-the-possum-park-mascot";
import { donKarnageDebonairPirate } from "./088-don-karnage-debonair-pirate";
import { maxGoofKaraokeStar } from "./089-max-goof-karaoke-star";
import { belleExceptionalWriter } from "./090-belle-exceptional-writer";
import { fredBigStomper } from "./091-fred-big-stomper";
import { minnieMouseBusyGogetter } from "./092-minnie-mouse-busy-go-getter";
import { honeyLemonTestingTheLimits } from "./093-honey-lemon-testing-the-limits";
import { heiheiAtTheCrosswalk } from "./103-heihei-at-the-crosswalk";
import { abbyParkIntenseFan } from "./104-abby-park-intense-fan";
import { goofyDancingSuperstar } from "./105-goofy-dancing-superstar";
import { hctorRiveraWorldwideSensation } from "./106-hector-rivera-worldwide-sensation";
import { yamaNotoriousCriminal } from "./107-yama-notorious-criminal";
import { abigailCallaghanSeasonedTestPilot } from "./108-abigail-callaghan-seasoned-test-pilot";
import { pepitaSweetKitty } from "./109-pepita-sweet-kitty";
import { donaldDuckTaxiDriver } from "./110-donald-duck-taxi-driver";
import { goofyEnthusiasticTourist } from "./111-goofy-enthusiastic-tourist";
import { tadashiHamadaMakingWaves } from "./112-tadashi-hamada-making-waves";
import { cruellaDeVilDodgingTraffic } from "./113-cruella-de-vil-dodging-traffic";
import { jasperDodgyBoater } from "./114-jasper-dodgy-boater";
import { pegLatenightVocalist } from "./115-peg-late-night-vocalist";
import { staceyPowerlineSuperfan } from "./116-stacey-powerline-superfan";
import { hctorRiveraStreetMusician } from "./117-hector-rivera-street-musician";
import { ernestoDeLaCruzIdolOfMillions } from "./118-ernesto-de-la-cruz-idol-of-millions";
import { pepitaImeldasRightHand } from "./119-pepita-imeldas-right-hand";
import { ernestoDeLaCruzRuthlessMusician } from "./120-ernesto-de-la-cruz-ruthless-musician";
import { hctorRiveraGoneToPieces } from "./121-hector-rivera-gone-to-pieces";
import { trampQuickOnHisFeet } from "./122-tramp-quick-on-his-feet";
import { meilinLeeEcstaticFan } from "./123-meilin-lee-ecstatic-fan";
import { roxanneConcertLover } from "./124-roxanne-concert-lover";
import { wasabiCalledIntoBattle } from "./125-wasabi-called-into-battle";
import { ladyTremaineScornfulSnob } from "./126-lady-tremaine-scornful-snob";
import { mulanMartialArtsMaster } from "./127-mulan-martial-arts-master";
import { carlFredricksenWildernessGuide } from "./137-carl-fredricksen-wilderness-guide";
import { cinderellaHomespunDressmaker } from "./138-cinderella-homespun-dressmaker";
import { wasabiFutureThinker } from "./139-wasabi-future-thinker";
import { baymaxQualifiedPhysician } from "./140-baymax-qualified-physician";
import { kingLouieIceCreamVirtuoso } from "./141-king-louie-ice-cream-virtuoso";
import { lafayetteAllEars } from "./142-lafayette-all-ears";
import { abigailAmeliaGossipingGeese } from "./143-abigail-amelia-gossiping-geese";
import { honeyLemonIngeniousResearcher } from "./144-honey-lemon-ingenious-researcher";
import { goGoTomagoWorkingLate } from "./145-go-go-tomago-working-late";
import { madamMimNosyNeighbor } from "./146-madam-mim-nosy-neighbor";
import { lionheartCleaningUpTheCity } from "./147-lionheart-cleaning-up-the-city";
import { priscillaEfficientClerk } from "./148-priscilla-efficient-clerk";
import { daisyDuckSavvyInvestor } from "./149-daisy-duck-savvy-investor";
import { hiroHamadaPioneeringInventor } from "./150-hiro-hamada-pioneering-inventor";
import { honeyLemonEndlesslyCurious } from "./151-honey-lemon-endlessly-curious";
import { thomasOmalleySavvyVagabond } from "./152-thomas-omalley-savvy-vagabond";
import { duchessCosmopolitanCat } from "./153-duchess-cosmopolitan-cat";
import { judyHoppsDayCampInstructor } from "./154-judy-hopps-day-camp-instructor";
import { minnieMouseUrbanVisionary } from "./155-minnie-mouse-urban-visionary";
import { arielCollectorOfOddities } from "./156-ariel-collector-of-oddities";
import { cinderellaUnintentionalIcon } from "./157-cinderella-unintentional-icon";
import { baymaxAmpedUp } from "./158-baymax-amped-up";
import { bellwetherHighlyQualified } from "./159-bellwether-highly-qualified";
import { clarabelleOutForAStroll } from "./160-clarabelle-out-for-a-stroll";
import { dougLyingInWait } from "./161-doug-lying-in-wait";
import { flashEfficientClerk } from "./171-flash-efficient-clerk";
import { arthurMerlinsAssistant } from "./172-arthur-merlins-assistant";
import { edgarBalthazarLongsufferingButler } from "./173-edgar-balthazar-long-suffering-butler";
import { kitCloudkickerUnpredictableCourier } from "./174-kit-cloudkicker-unpredictable-courier";
import { ticktockCanalCroc } from "./175-tick-tock-canal-croc";
import { tianaRestauranteur } from "./176-tiana-restauranteur";
import { rayaDeterminedExplorer } from "./177-raya-determined-explorer";
import { woolterJesseBellwethersHenchmen } from "./178-woolter-jesse-bellwethers-henchmen";
import { napoleonPatientWatchdog } from "./179-napoleon-patient-watchdog";
import { wildcatUnconventionalMechanic } from "./180-wildcat-unconventional-mechanic";
import { sirKayDeterminedToWin } from "./181-sir-kay-determined-to-win";
import { toulouseRoughAndTumble } from "./182-toulouse-rough-and-tumble";
import { chiefBogoPoliceCommissioner } from "./183-chief-bogo-police-commissioner";
import { sirPellinoreTougherThanHeLooks } from "./184-sir-pellinore-tougher-than-he-looks";
import { arthurNoviceBlacksmith } from "./185-arthur-novice-blacksmith";
import { berliozTinyRascal } from "./186-berlioz-tiny-rascal";
import { marieCaughtInTheAct } from "./187-marie-caught-in-the-act";
import { balooDeliveryPilot } from "./188-baloo-delivery-pilot";
import { koslovImposingEnforcer } from "./189-koslov-imposing-enforcer";
import { sirEctorBlusteryKnight } from "./190-sir-ector-blustery-knight";
import { balooFreightPilot } from "./191-baloo-freight-pilot";
import { kitCloudkickerSureShot } from "./192-kit-cloudkicker-sure-shot";
import { arthurJoustingKnight } from "./193-arthur-jousting-knight";
import { mrBigDistributionMagnate } from "./194-mr-big-distribution-magnate";
import { shereKhanKhanIndustriesCeo } from "./195-shere-khan-khan-industries-ceo";
import { tianaPartyHostess } from "./196-tiana-party-hostess";
import { mickeyMouseBestInTownIconic } from "./241-mickey-mouse-best-in-town-iconic";
import { cinderellaUnintentionalIconIconic } from "./242-cinderella-unintentional-icon-iconic";

interface ExpectedCard {
  card: unknown;
  name: string;
  version?: string;
  cost: number;
  inkTypes: string[];
  inkable: boolean;
  strength?: number;
  willpower?: number;
  lore?: number;
  rarity: string;
  sourceRarity: string;
  classifications: string[];
  franchise?: string;
  set: string;
  collectorNumber: string;
  vanilla: boolean;
  hasSourceText: boolean;
  externalIdKeys: string[];
  keywords: string[];
}

function cardText(card: unknown): string {
  const text = (card as { text?: string | Array<{ title?: string; description?: string }> }).text;
  if (!text) return "";
  if (typeof text === "string") return text;
  return text.map((entry) => [entry.title, entry.description].filter(Boolean).join(" ")).join("\n");
}

function expectCardMatchesSource(entry: ExpectedCard): void {
  const card = entry.card as {
    name: string;
    version?: string;
    cardType: string;
    cost: number;
    inkType: string[];
    inkable: boolean;
    strength?: number;
    willpower?: number;
    lore?: number;
    rarity: string;
    classifications?: string[];
    franchise?: string;
    set: string;
    cardNumber: number;
    vanilla?: boolean;
    externalIds?: Record<string, string>;
    printings: Array<{ setCode: string; collectorNumber: string }>;
  };

  // Identity
  expect(card.name).toBe(entry.name);
  expect(card.version).toBe(entry.version);
  expect(card.set).toBe(entry.set);
  expect(card.cardNumber).toBe(Number(entry.collectorNumber));
  expect(card.printings[0].setCode).toBe("set14");
  expect(card.printings[0].collectorNumber).toBe(entry.collectorNumber);

  // Ink & cost
  expect(card.cost).toBe(entry.cost);
  expect([...card.inkType].sort()).toEqual([...entry.inkTypes].sort());
  expect(card.inkable).toBe(entry.inkable);

  // Stats (characters/locations only carry the printed values)
  expect(card.strength).toBe(entry.strength);
  expect(card.willpower).toBe(entry.willpower);
  expect(card.lore).toBe(entry.lore);

  // Rarity & classifications
  expect(card.rarity).toBe(entry.rarity);
  expect(card.rarity).toBe(entry.sourceRarity);
  expect(card.classifications ?? []).toEqual(entry.classifications);
  expect(card.franchise).toBe(entry.franchise);

  // Printed text: vanilla cards have no printed ability, all others do
  expect(card.vanilla ?? false).toBe(entry.vanilla);
  expect(Boolean(cardText(card).trim())).toBe(entry.hasSourceText);
  for (const keyword of entry.keywords) {
    expect(cardText(card).toLowerCase()).toContain(keyword.toLowerCase());
  }

  // Source reference ids survived the parse
  expect(Object.keys(card.externalIds ?? {}).sort()).toEqual([...entry.externalIdKeys].sort());
}

const expectedCards: ExpectedCard[] = [
  {
    card: fruFruVipGuest,
    name: "Fru Fru",
    version: "VIP Guest",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "1",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: abuelitaLovingGrandmother,
    name: "Abuelita",
    version: "Loving Grandmother",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 3,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "2",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: maxGoofMusicLover,
    name: "Max Goof",
    version: "Music Lover",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 4,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Hero"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "3",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Singer 5"],
  },
  {
    card: gazellePopDiva,
    name: "Gazelle",
    version: "Pop Diva",
    cost: 2,
    inkTypes: ["amber"],
    inkable: false,
    strength: 3,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "4",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: peteSuaveShowoff,
    name: "Pete",
    version: "Suave Showoff",
    cost: 4,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 6,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "5",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: miriamMendelsohnFrontrowFan,
    name: "Miriam Mendelsohn",
    version: "Front-Row Fan",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 2,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Turning Red",
    set: "014",
    collectorNumber: "6",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: priyaMangalImmovableFan,
    name: "Priya Mangal",
    version: "Immovable Fan",
    cost: 2,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Turning Red",
    set: "014",
    collectorNumber: "7",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: yaxConcertGoer,
    name: "Yax",
    version: "Concert Goer",
    cost: 7,
    inkTypes: ["amber"],
    inkable: true,
    strength: 7,
    willpower: 9,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "8",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: judyHoppsHelpfulOfficer,
    name: "Judy Hopps",
    version: "Helpful Officer",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "9",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: miguelRiveraPromisingMusician,
    name: "Miguel Rivera",
    version: "Promising Musician",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "10",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: nickWildeInquisitiveHarbormaster,
    name: "Nick Wilde",
    version: "Inquisitive Harbormaster",
    cost: 6,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 5,
    lore: 3,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Ally", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "11",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 4"],
  },
  {
    card: pjPeteDevotedFan,
    name: "P.J. Pete",
    version: "Devoted Fan",
    cost: 5,
    inkTypes: ["amber"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "12",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: mrManchasServiceWithASmile,
    name: "Mr. Manchas",
    version: "Service with a Smile",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "13",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: hctorRiveraGoneToPiecesD23,
    name: "Héctor Rivera",
    version: "Gone to Pieces",
    cost: 4,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 5,
    willpower: 3,
    lore: 1,
    rarity: "special",
    sourceRarity: "special",
    classifications: ["Storyborn", "Mentor"],
    franchise: "D23",
    set: "014",
    collectorNumber: "13",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Singer 6", "Evasive"],
  },
  {
    card: nickWildeToyDriveOfficer,
    name: "Nick Wilde",
    version: "Toy Drive Officer",
    cost: 4,
    inkTypes: ["amber"],
    inkable: false,
    strength: 2,
    willpower: 4,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Ally", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "14",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Support"],
  },
  {
    card: clawhauserSafetyOfficer,
    name: "Clawhauser",
    version: "Safety Officer",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 5,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "15",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Bodyguard"],
  },
  {
    card: elisaMazaHardworkingDetective,
    name: "Elisa Maza",
    version: "Hardworking Detective",
    cost: 4,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 4,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Hero", "Detective"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "16",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: powerlineMegastar,
    name: "Powerline",
    version: "Megastar",
    cost: 6,
    inkTypes: ["amber"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Storyborn"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "17",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Singer 9"],
  },
  {
    card: lionheartIncumbentMayor,
    name: "Lionheart",
    version: "Incumbent Mayor",
    cost: 6,
    inkTypes: ["amber"],
    inkable: true,
    strength: 4,
    willpower: 7,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "18",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Bodyguard"],
  },
  {
    card: auroraDelightfulMusician,
    name: "Aurora",
    version: "Delightful Musician",
    cost: 3,
    inkTypes: ["amber"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Sleeping Beauty",
    set: "014",
    collectorNumber: "19",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: russellFindingAdventure,
    name: "Russell",
    version: "Finding Adventure",
    cost: 5,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 3,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Up",
    set: "014",
    collectorNumber: "20",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: miguelRiveraStreetMusician,
    name: "Miguel Rivera",
    version: "Street Musician",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 1,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "21",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Singer 3"],
  },
  {
    card: goofyKnowsTheBand,
    name: "Goofy",
    version: "Knows the Band",
    cost: 4,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 2,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "22",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: mickeyMouseBestInTown,
    name: "Mickey Mouse",
    version: "Best in Town",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 0,
    willpower: 4,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "23",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: judyHoppsAlwaysVigilant,
    name: "Judy Hopps",
    version: "Always Vigilant",
    cost: 4,
    inkTypes: ["amber"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Hero", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "24",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 2"],
  },
  {
    card: nickWildeProvidingBackup,
    name: "Nick Wilde",
    version: "Providing Backup",
    cost: 2,
    inkTypes: ["amber"],
    inkable: true,
    strength: 3,
    willpower: 2,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "25",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Support"],
  },
  {
    card: miguelRiveraAccomplishedMusician,
    name: "Miguel Rivera",
    version: "Accomplished Musician",
    cost: 5,
    inkTypes: ["amber"],
    inkable: false,
    strength: 4,
    willpower: 5,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "26",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 3"],
  },
  {
    card: owenBurnettXanatossAssistant,
    name: "Owen Burnett",
    version: "Xanatos's Assistant",
    cost: 3,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "35",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: scuttleDirectingTraffic,
    name: "Scuttle",
    version: "Directing Traffic",
    cost: 2,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 1,
    willpower: 3,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Little Mermaid",
    set: "014",
    collectorNumber: "36",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: davidXanatosArcaneIndustrialist,
    name: "David Xanatos",
    version: "Arcane Industrialist",
    cost: 5,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 6,
    willpower: 5,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Villain"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "37",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: lexingtonFearlessFlier,
    name: "Lexington",
    version: "Fearless Flier",
    cost: 2,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 3,
    willpower: 1,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally", "Gargoyle"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "38",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Evasive"],
  },
  {
    card: merlinBaubleExpert,
    name: "Merlin",
    version: "Bauble Expert",
    cost: 3,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Mentor", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "39",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: pepitaWatchfulAlebrije,
    name: "Pepita",
    version: "Watchful Alebrije",
    cost: 2,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "40",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: archimedesHasHadEnough,
    name: "Archimedes",
    version: "Has Had Enough",
    cost: 4,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "41",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: taVictoriaDisapprovingAncestor,
    name: "Tía Victoria",
    version: "Disapproving Ancestor",
    cost: 6,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 4,
    willpower: 7,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "42",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: danteEnthusiasticStray,
    name: "Dante",
    version: "Enthusiastic Stray",
    cost: 2,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "43",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: mamCocoVisitingThePark,
    name: "Mamá Coco",
    version: "Visiting the Park",
    cost: 4,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 3,
    willpower: 5,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "44",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: tinkerBellCuriousFairy,
    name: "Tinker Bell",
    version: "Curious Fairy",
    cost: 1,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 0,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally", "Fairy"],
    franchise: "Peter Pan",
    set: "014",
    collectorNumber: "45",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: madamMimBaubleChaser,
    name: "Madam Mim",
    version: "Bauble Chaser",
    cost: 1,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Villain", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "46",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Evasive"],
  },
  {
    card: peterPansShadowElusivePrankster,
    name: "Peter Pan's Shadow",
    version: "Elusive Prankster",
    cost: 3,
    inkTypes: ["amethyst"],
    inkable: false,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Peter Pan",
    set: "014",
    collectorNumber: "47",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Evasive"],
  },
  {
    card: danteStrangeAndEndearing,
    name: "Dante",
    version: "Strange and Endearing",
    cost: 1,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 0,
    willpower: 1,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "48",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Evasive"],
  },
  {
    card: foxXanatosCharismaticOutlaw,
    name: "Fox Xanatos",
    version: "Charismatic Outlaw",
    cost: 5,
    inkTypes: ["amethyst"],
    inkable: false,
    strength: 5,
    willpower: 6,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "49",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: brooklynFullThrottle,
    name: "Brooklyn",
    version: "Full Throttle",
    cost: 1,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 1,
    willpower: 4,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Ally", "Gargoyle"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "50",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: mamImeldaNononsenseAncestor,
    name: "Mamá Imelda",
    version: "No-Nonsense Ancestor",
    cost: 4,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Mentor"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "51",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: merlinInkDropTinkerer,
    name: "Merlin",
    version: "Ink Drop Tinkerer",
    cost: 7,
    inkTypes: ["amethyst"],
    inkable: false,
    strength: 6,
    willpower: 8,
    lore: 3,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Mentor", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "52",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 5"],
  },
  {
    card: goliathTransformedWarrior,
    name: "Goliath",
    version: "Transformed Warrior",
    cost: 4,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Hero", "Gargoyle"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "53",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: danteLoyalAlebrije,
    name: "Dante",
    version: "Loyal Alebrije",
    cost: 6,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 6,
    willpower: 4,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "54",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 4", "Evasive"],
  },
  {
    card: rapunzelOutgoingArtist,
    name: "Rapunzel",
    version: "Outgoing Artist",
    cost: 1,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 0,
    willpower: 1,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Tangled",
    set: "014",
    collectorNumber: "55",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: demonaImperiousSpellcaster,
    name: "Demona",
    version: "Imperious Spellcaster",
    cost: 3,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 4,
    willpower: 3,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Villain", "Gargoyle", "Sorcerer"],
    franchise: "Gargoyles",
    set: "014",
    collectorNumber: "56",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Rush", "Evasive"],
  },
  {
    card: merlinProfoundlyCurious,
    name: "Merlin",
    version: "Profoundly Curious",
    cost: 4,
    inkTypes: ["amethyst"],
    inkable: false,
    strength: 2,
    willpower: 3,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Mentor", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "57",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: archimedesMessengerOwl,
    name: "Archimedes",
    version: "Messenger Owl",
    cost: 3,
    inkTypes: ["amethyst"],
    inkable: false,
    strength: 3,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "58",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Rush"],
  },
  {
    card: madamMimResourcefulTrickster,
    name: "Madam Mim",
    version: "Resourceful Trickster",
    cost: 8,
    inkTypes: ["amethyst"],
    inkable: true,
    strength: 7,
    willpower: 5,
    lore: 3,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Villain", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "59",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: trustyAlongForTheRide,
    name: "Trusty",
    version: "Along for the Ride",
    cost: 5,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 7,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Lady and the Tramp",
    set: "014",
    collectorNumber: "69",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: donKarnageKhansCourier,
    name: "Don Karnage",
    version: "Khan's Courier",
    cost: 1,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Villain", "Prince", "Pirate"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "70",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: hiroHamadaVersatileInventor,
    name: "Hiro Hamada",
    version: "Versatile Inventor",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 3,
    willpower: 1,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "71",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Evasive"],
  },
  {
    card: goGoTomagoExtremeTester,
    name: "Go Go Tomago",
    version: "Extreme Tester",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "72",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: mollyCunninghamRemembersToShare,
    name: "Molly Cunningham",
    version: "Remembers to Share",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "73",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: kitCloudkickerIrrepressibleBear,
    name: "Kit Cloudkicker",
    version: "Irrepressible Bear",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "74",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: belleReflectiveWriter,
    name: "Belle",
    version: "Reflective Writer",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Beauty and the Beast",
    set: "014",
    collectorNumber: "75",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: fredAssemblingTheTeam,
    name: "Fred",
    version: "Assembling the Team",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 3,
    willpower: 2,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Super", "Hero"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "76",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: captainHookConcernedCaptain,
    name: "Captain Hook",
    version: "Concerned Captain",
    cost: 8,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 9,
    willpower: 9,
    lore: 3,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Villain", "Pirate", "Captain"],
    franchise: "Peter Pan",
    set: "014",
    collectorNumber: "77",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: jockEnjoyingTheSights,
    name: "Jock",
    version: "Enjoying the Sights",
    cost: 4,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Lady and the Tramp",
    set: "014",
    collectorNumber: "78",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: ladyRelaxedAndRested,
    name: "Lady",
    version: "Relaxed and Rested",
    cost: 1,
    inkTypes: ["emerald"],
    inkable: false,
    strength: 3,
    willpower: 1,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Hero"],
    franchise: "Lady and the Tramp",
    set: "014",
    collectorNumber: "79",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: rebeccaCunninghamSavvyManager,
    name: "Rebecca Cunningham",
    version: "Savvy Manager",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "80",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: shereKhanOpportunisticTycoon,
    name: "Shere Khan",
    version: "Opportunistic Tycoon",
    cost: 4,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 3,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Villain"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "81",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: horaceClumsyClod,
    name: "Horace",
    version: "Clumsy Clod",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "101 Dalmatians",
    set: "014",
    collectorNumber: "82",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: shereKhanRuthlessEntrepreneur,
    name: "Shere Khan",
    version: "Ruthless Entrepreneur",
    cost: 7,
    inkTypes: ["emerald"],
    inkable: false,
    strength: 7,
    willpower: 4,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Villain"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "83",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: bobbyZimuruskiSoundboardWhiz,
    name: "Bobby Zimuruski",
    version: "Soundboard Whiz",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "84",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Ward"],
  },
  {
    card: baymaxLabAssistant,
    name: "Baymax",
    version: "Lab Assistant",
    cost: 4,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 3,
    willpower: 4,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Super", "Hero", "Robot"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "85",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: fredAwesomeBoss,
    name: "Fred",
    version: "Awesome Boss",
    cost: 6,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 6,
    willpower: 5,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Super", "Hero"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "86",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 4"],
  },
  {
    card: lesterThePossumParkMascot,
    name: "Lester the Possum",
    version: "Park Mascot",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: false,
    strength: 0,
    willpower: 3,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "87",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Reckless"],
  },
  {
    card: donKarnageDebonairPirate,
    name: "Don Karnage",
    version: "Debonair Pirate",
    cost: 6,
    inkTypes: ["emerald"],
    inkable: false,
    strength: 3,
    willpower: 6,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Villain", "Prince", "Pirate"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "88",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 4"],
  },
  {
    card: maxGoofKaraokeStar,
    name: "Max Goof",
    version: "Karaoke Star",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 1,
    willpower: 3,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "89",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: belleExceptionalWriter,
    name: "Belle",
    version: "Exceptional Writer",
    cost: 5,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 4,
    willpower: 5,
    lore: 2,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Beauty and the Beast",
    set: "014",
    collectorNumber: "90",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 3"],
  },
  {
    card: fredBigStomper,
    name: "Fred",
    version: "Big Stomper",
    cost: 5,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 5,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Super", "Hero"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "91",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: minnieMouseBusyGogetter,
    name: "Minnie Mouse",
    version: "Busy Go-Getter",
    cost: 2,
    inkTypes: ["emerald"],
    inkable: false,
    strength: 1,
    willpower: 2,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "92",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: honeyLemonTestingTheLimits,
    name: "Honey Lemon",
    version: "Testing the Limits",
    cost: 3,
    inkTypes: ["emerald"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "93",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: heiheiAtTheCrosswalk,
    name: "Heihei",
    version: "At the Crosswalk",
    cost: 2,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 3,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Moana",
    set: "014",
    collectorNumber: "103",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: abbyParkIntenseFan,
    name: "Abby Park",
    version: "Intense Fan",
    cost: 4,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 3,
    willpower: 3,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Turning Red",
    set: "014",
    collectorNumber: "104",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: goofyDancingSuperstar,
    name: "Goofy",
    version: "Dancing Superstar",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 5,
    willpower: 4,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "105",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 3", "Singer 6"],
  },
  {
    card: hctorRiveraWorldwideSensation,
    name: "Héctor Rivera",
    version: "Worldwide Sensation",
    cost: 6,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 2,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Mentor"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "106",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 4"],
  },
  {
    card: yamaNotoriousCriminal,
    name: "Yama",
    version: "Notorious Criminal",
    cost: 4,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 4,
    willpower: 4,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "107",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: abigailCallaghanSeasonedTestPilot,
    name: "Abigail Callaghan",
    version: "Seasoned Test Pilot",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 7,
    willpower: 6,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "108",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: pepitaSweetKitty,
    name: "Pepita",
    version: "Sweet Kitty",
    cost: 1,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 1,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "109",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: donaldDuckTaxiDriver,
    name: "Donald Duck",
    version: "Taxi Driver",
    cost: 3,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 4,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "110",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Rush"],
  },
  {
    card: goofyEnthusiasticTourist,
    name: "Goofy",
    version: "Enthusiastic Tourist",
    cost: 1,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 0,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "111",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: tadashiHamadaMakingWaves,
    name: "Tadashi Hamada",
    version: "Making Waves",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 4,
    willpower: 3,
    lore: 3,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Mentor", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "112",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: cruellaDeVilDodgingTraffic,
    name: "Cruella De Vil",
    version: "Dodging Traffic",
    cost: 6,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 5,
    willpower: 6,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Villain"],
    franchise: "101 Dalmatians",
    set: "014",
    collectorNumber: "113",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: jasperDodgyBoater,
    name: "Jasper",
    version: "Dodgy Boater",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 5,
    willpower: 4,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "101 Dalmatians",
    set: "014",
    collectorNumber: "114",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: pegLatenightVocalist,
    name: "Peg",
    version: "Late-Night Vocalist",
    cost: 2,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Lady and the Tramp",
    set: "014",
    collectorNumber: "115",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: staceyPowerlineSuperfan,
    name: "Stacey",
    version: "Powerline Superfan",
    cost: 3,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 3,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "116",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: hctorRiveraStreetMusician,
    name: "Héctor Rivera",
    version: "Street Musician",
    cost: 1,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Mentor"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "117",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Singer 2"],
  },
  {
    card: ernestoDeLaCruzIdolOfMillions,
    name: "Ernesto de la Cruz",
    version: "Idol of Millions",
    cost: 3,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 5,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Villain"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "118",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Singer 5"],
  },
  {
    card: pepitaImeldasRightHand,
    name: "Pepita",
    version: "Imelda's Right Hand",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "119",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 3"],
  },
  {
    card: ernestoDeLaCruzRuthlessMusician,
    name: "Ernesto de la Cruz",
    version: "Ruthless Musician",
    cost: 6,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 6,
    willpower: 5,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Villain"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "120",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Singer 8"],
  },
  {
    card: hctorRiveraGoneToPieces,
    name: "Héctor Rivera",
    version: "Gone to Pieces",
    cost: 4,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 5,
    willpower: 3,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Mentor"],
    franchise: "Coco",
    set: "014",
    collectorNumber: "121",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Singer 6", "Evasive"],
  },
  {
    card: trampQuickOnHisFeet,
    name: "Tramp",
    version: "Quick on His Feet",
    cost: 2,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Lady and the Tramp",
    set: "014",
    collectorNumber: "122",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Rush"],
  },
  {
    card: meilinLeeEcstaticFan,
    name: "Meilin Lee",
    version: "Ecstatic Fan",
    cost: 3,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 3,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero", "Red Panda"],
    franchise: "Turning Red",
    set: "014",
    collectorNumber: "123",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Singer 5"],
  },
  {
    card: roxanneConcertLover,
    name: "Roxanne",
    version: "Concert Lover",
    cost: 2,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 3,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Dreamborn", "Ally"],
    franchise: "Goofy Movie",
    set: "014",
    collectorNumber: "124",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: wasabiCalledIntoBattle,
    name: "Wasabi",
    version: "Called into Battle",
    cost: 5,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 4,
    willpower: 5,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "125",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: ladyTremaineScornfulSnob,
    name: "Lady Tremaine",
    version: "Scornful Snob",
    cost: 3,
    inkTypes: ["ruby"],
    inkable: false,
    strength: 0,
    willpower: 3,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn", "Villain"],
    franchise: "Cinderella",
    set: "014",
    collectorNumber: "126",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: mulanMartialArtsMaster,
    name: "Mulan",
    version: "Martial Arts Master",
    cost: 4,
    inkTypes: ["ruby"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 2,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Mulan",
    set: "014",
    collectorNumber: "127",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Rush"],
  },
  {
    card: carlFredricksenWildernessGuide,
    name: "Carl Fredricksen",
    version: "Wilderness Guide",
    cost: 6,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 5,
    willpower: 6,
    lore: 3,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Up",
    set: "014",
    collectorNumber: "137",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: cinderellaHomespunDressmaker,
    name: "Cinderella",
    version: "Homespun Dressmaker",
    cost: 2,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Cinderella",
    set: "014",
    collectorNumber: "138",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: wasabiFutureThinker,
    name: "Wasabi",
    version: "Future Thinker",
    cost: 5,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "139",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Ward"],
  },
  {
    card: baymaxQualifiedPhysician,
    name: "Baymax",
    version: "Qualified Physician",
    cost: 3,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 2,
    willpower: 5,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Super", "Hero", "Robot"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "140",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: kingLouieIceCreamVirtuoso,
    name: "King Louie",
    version: "Ice Cream Virtuoso",
    cost: 3,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 1,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally", "King"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "141",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: lafayetteAllEars,
    name: "Lafayette",
    version: "All Ears",
    cost: 2,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 1,
    willpower: 4,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "142",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Evasive"],
  },
  {
    card: abigailAmeliaGossipingGeese,
    name: "Abigail & Amelia",
    version: "Gossiping Geese",
    cost: 2,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "143",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: honeyLemonIngeniousResearcher,
    name: "Honey Lemon",
    version: "Ingenious Researcher",
    cost: 7,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "144",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Shift 5"],
  },
  {
    card: goGoTomagoWorkingLate,
    name: "Go Go Tomago",
    version: "Working Late",
    cost: 3,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 2,
    willpower: 6,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "145",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: madamMimNosyNeighbor,
    name: "Madam Mim",
    version: "Nosy Neighbor",
    cost: 5,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 5,
    willpower: 5,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Villain", "Sorcerer"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "146",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: lionheartCleaningUpTheCity,
    name: "Lionheart",
    version: "Cleaning Up the City",
    cost: 4,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 3,
    willpower: 5,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "147",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Evasive"],
  },
  {
    card: priscillaEfficientClerk,
    name: "Priscilla",
    version: "Efficient Clerk",
    cost: 3,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 0,
    willpower: 4,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "148",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: daisyDuckSavvyInvestor,
    name: "Daisy Duck",
    version: "Savvy Investor",
    cost: 3,
    inkTypes: ["sapphire"],
    inkable: false,
    strength: 3,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "149",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: hiroHamadaPioneeringInventor,
    name: "Hiro Hamada",
    version: "Pioneering Inventor",
    cost: 4,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 3,
    willpower: 6,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "150",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: honeyLemonEndlesslyCurious,
    name: "Honey Lemon",
    version: "Endlessly Curious",
    cost: 1,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 1,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Super", "Hero", "Inventor"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "151",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: thomasOmalleySavvyVagabond,
    name: "Thomas O'Malley",
    version: "Savvy Vagabond",
    cost: 2,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "152",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: duchessCosmopolitanCat,
    name: "Duchess",
    version: "Cosmopolitan Cat",
    cost: 1,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 1,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "153",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: judyHoppsDayCampInstructor,
    name: "Judy Hopps",
    version: "Day Camp Instructor",
    cost: 2,
    inkTypes: ["sapphire"],
    inkable: false,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero", "Detective"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "154",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Support"],
  },
  {
    card: minnieMouseUrbanVisionary,
    name: "Minnie Mouse",
    version: "Urban Visionary",
    cost: 8,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 6,
    willpower: 6,
    lore: 3,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "155",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Ward"],
  },
  {
    card: arielCollectorOfOddities,
    name: "Ariel",
    version: "Collector of Oddities",
    cost: 5,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 3,
    willpower: 5,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Little Mermaid",
    set: "014",
    collectorNumber: "156",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: cinderellaUnintentionalIcon,
    name: "Cinderella",
    version: "Unintentional Icon",
    cost: 7,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 3,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Cinderella",
    set: "014",
    collectorNumber: "157",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 5"],
  },
  {
    card: baymaxAmpedUp,
    name: "Baymax",
    version: "Amped Up",
    cost: 7,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 5,
    willpower: 8,
    lore: 2,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Super", "Hero", "Robot"],
    franchise: "Big Hero 6",
    set: "014",
    collectorNumber: "158",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: bellwetherHighlyQualified,
    name: "Bellwether",
    version: "Highly Qualified",
    cost: 4,
    inkTypes: ["sapphire"],
    inkable: false,
    strength: 2,
    willpower: 2,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Villain"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "159",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: clarabelleOutForAStroll,
    name: "Clarabelle",
    version: "Out for a Stroll",
    cost: 6,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 5,
    willpower: 7,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: undefined,
    set: "014",
    collectorNumber: "160",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: dougLyingInWait,
    name: "Doug",
    version: "Lying in Wait",
    cost: 4,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 3,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "161",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: flashEfficientClerk,
    name: "Flash",
    version: "Efficient Clerk",
    cost: 2,
    inkTypes: ["steel"],
    inkable: false,
    strength: 3,
    willpower: 2,
    lore: 2,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "171",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: ["Rush"],
  },
  {
    card: arthurMerlinsAssistant,
    name: "Arthur",
    version: "Merlin's Assistant",
    cost: 3,
    inkTypes: ["steel"],
    inkable: true,
    strength: 3,
    willpower: 3,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "172",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: edgarBalthazarLongsufferingButler,
    name: "Edgar Balthazar",
    version: "Long-Suffering Butler",
    cost: 5,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Villain"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "173",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: kitCloudkickerUnpredictableCourier,
    name: "Kit Cloudkicker",
    version: "Unpredictable Courier",
    cost: 1,
    inkTypes: ["steel"],
    inkable: true,
    strength: 2,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "174",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: ticktockCanalCroc,
    name: "Tick-Tock",
    version: "Canal Croc",
    cost: 8,
    inkTypes: ["steel"],
    inkable: true,
    strength: 9,
    willpower: 9,
    lore: 3,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn"],
    franchise: "Peter Pan",
    set: "014",
    collectorNumber: "175",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: tianaRestauranteur,
    name: "Tiana",
    version: "Restauranteur",
    cost: 2,
    inkTypes: ["steel"],
    inkable: true,
    strength: 1,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Princess and the Frog",
    set: "014",
    collectorNumber: "176",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: rayaDeterminedExplorer,
    name: "Raya",
    version: "Determined Explorer",
    cost: 1,
    inkTypes: ["steel"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Hero", "Princess"],
    franchise: "Raya and the Last Dragon",
    set: "014",
    collectorNumber: "177",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: woolterJesseBellwethersHenchmen,
    name: "Woolter & Jesse",
    version: "Bellwether's Henchmen",
    cost: 3,
    inkTypes: ["steel"],
    inkable: false,
    strength: 4,
    willpower: 4,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "178",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Bodyguard"],
  },
  {
    card: napoleonPatientWatchdog,
    name: "Napoleon",
    version: "Patient Watchdog",
    cost: 3,
    inkTypes: ["steel"],
    inkable: true,
    strength: 5,
    willpower: 2,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "179",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Evasive"],
  },
  {
    card: wildcatUnconventionalMechanic,
    name: "Wildcat",
    version: "Unconventional Mechanic",
    cost: 3,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "180",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: sirKayDeterminedToWin,
    name: "Sir Kay",
    version: "Determined to Win",
    cost: 5,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Knight"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "181",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: toulouseRoughAndTumble,
    name: "Toulouse",
    version: "Rough and Tumble",
    cost: 2,
    inkTypes: ["steel"],
    inkable: true,
    strength: 1,
    willpower: 2,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Ally"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "182",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: chiefBogoPoliceCommissioner,
    name: "Chief Bogo",
    version: "Police Commissioner",
    cost: 7,
    inkTypes: ["steel"],
    inkable: true,
    strength: 6,
    willpower: 6,
    lore: 3,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "183",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: sirPellinoreTougherThanHeLooks,
    name: "Sir Pellinore",
    version: "Tougher Than He Looks",
    cost: 3,
    inkTypes: ["steel"],
    inkable: true,
    strength: 1,
    willpower: 5,
    lore: 1,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Dreamborn", "Knight"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "184",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: arthurNoviceBlacksmith,
    name: "Arthur",
    version: "Novice Blacksmith",
    cost: 2,
    inkTypes: ["steel"],
    inkable: true,
    strength: 2,
    willpower: 3,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Dreamborn", "Hero"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "185",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: berliozTinyRascal,
    name: "Berlioz",
    version: "Tiny Rascal",
    cost: 1,
    inkTypes: ["steel"],
    inkable: true,
    strength: 0,
    willpower: 1,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "186",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: marieCaughtInTheAct,
    name: "Marie",
    version: "Caught in the Act",
    cost: 1,
    inkTypes: ["steel"],
    inkable: true,
    strength: 2,
    willpower: 1,
    lore: 1,
    rarity: "rare",
    sourceRarity: "rare",
    classifications: ["Storyborn", "Ally"],
    franchise: "Aristocats",
    set: "014",
    collectorNumber: "187",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: balooDeliveryPilot,
    name: "Baloo",
    version: "Delivery Pilot",
    cost: 2,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Hero", "Captain"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "188",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: koslovImposingEnforcer,
    name: "Koslov",
    version: "Imposing Enforcer",
    cost: 4,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 2,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Ally"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "189",
    vanilla: true,
    hasSourceText: false,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: sirEctorBlusteryKnight,
    name: "Sir Ector",
    version: "Blustery Knight",
    cost: 5,
    inkTypes: ["steel"],
    inkable: true,
    strength: 6,
    willpower: 4,
    lore: 2,
    rarity: "uncommon",
    sourceRarity: "uncommon",
    classifications: ["Storyborn", "Knight"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "190",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: balooFreightPilot,
    name: "Baloo",
    version: "Freight Pilot",
    cost: 4,
    inkTypes: ["steel"],
    inkable: true,
    strength: 5,
    willpower: 4,
    lore: 1,
    rarity: "common",
    sourceRarity: "common",
    classifications: ["Storyborn", "Hero", "Captain"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "191",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: kitCloudkickerSureShot,
    name: "Kit Cloudkicker",
    version: "Sure Shot",
    cost: 5,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 4,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Ally"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "192",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 3"],
  },
  {
    card: arthurJoustingKnight,
    name: "Arthur",
    version: "Jousting Knight",
    cost: 6,
    inkTypes: ["steel"],
    inkable: true,
    strength: 3,
    willpower: 6,
    lore: 2,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Dreamborn", "Hero", "Knight"],
    franchise: "Sword in the Stone",
    set: "014",
    collectorNumber: "193",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 4"],
  },
  {
    card: mrBigDistributionMagnate,
    name: "Mr. Big",
    version: "Distribution Magnate",
    cost: 2,
    inkTypes: ["steel"],
    inkable: true,
    strength: 0,
    willpower: 2,
    lore: 1,
    rarity: "super_rare",
    sourceRarity: "super_rare",
    classifications: ["Storyborn"],
    franchise: "Zootropolis",
    set: "014",
    collectorNumber: "194",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: [],
    keywords: [],
  },
  {
    card: shereKhanKhanIndustriesCeo,
    name: "Shere Khan",
    version: "Khan Industries CEO",
    cost: 4,
    inkTypes: ["steel"],
    inkable: false,
    strength: 4,
    willpower: 2,
    lore: 1,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Storyborn", "Villain"],
    franchise: "Talespin",
    set: "014",
    collectorNumber: "195",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: tianaPartyHostess,
    name: "Tiana",
    version: "Party Hostess",
    cost: 7,
    inkTypes: ["steel"],
    inkable: true,
    strength: 4,
    willpower: 5,
    lore: 2,
    rarity: "legendary",
    sourceRarity: "legendary",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Princess and the Frog",
    set: "014",
    collectorNumber: "196",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 5"],
  },
  {
    card: mickeyMouseBestInTownIconic,
    name: "Mickey Mouse",
    version: "Best in Town",
    cost: 1,
    inkTypes: ["amber"],
    inkable: true,
    strength: 0,
    willpower: 4,
    lore: 2,
    rarity: "iconic",
    sourceRarity: "iconic",
    classifications: ["Dreamborn", "Hero"],
    franchise: undefined,
    set: "014",
    collectorNumber: "241",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: [],
  },
  {
    card: cinderellaUnintentionalIconIconic,
    name: "Cinderella",
    version: "Unintentional Icon",
    cost: 7,
    inkTypes: ["sapphire"],
    inkable: true,
    strength: 4,
    willpower: 6,
    lore: 3,
    rarity: "iconic",
    sourceRarity: "iconic",
    classifications: ["Dreamborn", "Hero", "Princess"],
    franchise: "Cinderella",
    set: "014",
    collectorNumber: "242",
    vanilla: false,
    hasSourceText: true,
    externalIdKeys: ["lorcast"],
    keywords: ["Shift 5"],
  },
];

describe("Hyperia City characters - card data vs. printed source", () => {
  it.each(expectedCards)(
    "$name - $version matches the printed card data",
    (entry: ExpectedCard) => {
      expectCardMatchesSource(entry);
    },
  );
});
