import type { UnitCard } from "@tcg/gundam-types";

export const betaStrikeDagger005: UnitCard = {
  cardNumber: "ST04-005",
  name: "Strike Dagger",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "ST04-005_p2",
  externalId: "gundam:st04-005_p2",
  slug: "strike-dagger-st04-005-p2",
  displayName: "Strike Dagger",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "ST04-005_p2",
  printings: [
    {
      id: "ST04-005",
      collectorNumber: "ST04-005",
      cardNumber: "ST04-005",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04]",
        packageId: "616004",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-005.webp?260424",
      productName: "SEED Strike [ST04]",
    },
    {
      id: "ST04-005_p1",
      collectorNumber: "ST04-005_p1",
      cardNumber: "ST04-005",
      set: {
        code: "ST04",
        name: "SEED Strike [ST04] Bonus Pack",
        packageId: "616004",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st04/ST04-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-005_p1.webp?260424",
      productName: "SEED Strike [ST04] Bonus Pack",
    },
    {
      id: "ST04-005_p2",
      collectorNumber: "ST04-005_p2",
      cardNumber: "ST04-005",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST04-005_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-005_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST04-005_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST04-005_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST04-005_p2.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
