import type { UnitCard } from "@tcg/gundam-types";

export const betaZaku007: UnitCard = {
  cardNumber: "ST03-007",
  name: "Zaku Ⅰ",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "ST03-007_p2",
  externalId: "gundam:st03-007_p2",
  slug: "zaku-st03-007-p2",
  displayName: "Zaku Ⅰ",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "ST03-007_p2",
  printings: [
    {
      id: "ST03-007",
      collectorNumber: "ST03-007",
      cardNumber: "ST03-007",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-007.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-007_p1",
      collectorNumber: "ST03-007_p1",
      cardNumber: "ST03-007",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-007_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
    {
      id: "ST03-007_p2",
      collectorNumber: "ST03-007_p2",
      cardNumber: "ST03-007",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST03-007_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-007_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST03-007_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST03-007_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-007_p2.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
