import type { UnitCard } from "@tcg/gundam-types";

export const betaDemiTrainer008: UnitCard = {
  cardNumber: "ST01-008",
  name: "Demi Trainer",
  type: "unit",
  color: "white",
  traits: ["academy"],
  id: "ST01-008_p2",
  externalId: "gundam:st01-008_p2",
  slug: "demi-trainer-st01-008-p2",
  displayName: "Demi Trainer",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "ST01-008_p2",
  printings: [
    {
      id: "ST01-008",
      collectorNumber: "ST01-008",
      cardNumber: "ST01-008",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-008.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-008_p1",
      collectorNumber: "ST01-008_p1",
      cardNumber: "ST01-008",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-008_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-008_p2",
      collectorNumber: "ST01-008_p2",
      cardNumber: "ST01-008",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST01-008_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-008_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST01-008_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST01-008_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-008_p2.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 1,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
