import type { CardEffect, UnitCard } from "@tcg/gundam-types";

export const betaZaku008: UnitCard = {
  cardNumber: "ST03-008",
  name: "Zaku Ⅱ",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "ST03-008_p2",
  externalId: "gundam:st03-008_p2",
  slug: "zaku-st03-008-p2",
  displayName: "Zaku Ⅱ",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "ST03-008_p2",
  printings: [
    {
      id: "ST03-008",
      collectorNumber: "ST03-008",
      cardNumber: "ST03-008",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "ST03-008_p1",
      collectorNumber: "ST03-008_p1",
      cardNumber: "ST03-008",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03] Bonus Pack",
        packageId: "616003",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008_p1.webp?260424",
      productName: "Zeon's Rush [ST03] Bonus Pack",
    },
    {
      id: "ST03-008_p2",
      collectorNumber: "ST03-008_p2",
      cardNumber: "ST03-008",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST03-008_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST03-008_p3",
      collectorNumber: "ST03-008_p3",
      cardNumber: "ST03-008",
      set: {
        code: "ST03",
        name: "Championship Participation Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-008_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008_p3.webp?260424",
      productName: "Championship Participation Pack 01",
    },
    {
      id: "ST03-008_p4",
      collectorNumber: "ST03-008_p4",
      cardNumber: "ST03-008",
      set: {
        code: "EVX05",
        name: "Premium Card Collection [EVX05]",
        packageId: "616701",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st03/ST03-008_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008_p4.webp?260424",
      productName: "Premium Card Collection [EVX05]",
    },
  ],
  selectedPrintingId: "ST03-008_p2",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST03-008_p2.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST03-008_p2.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "【Attack】This Unit gets AP+2 during this turn.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["attack"],
      },
      directives: [
        {
          action: {
            action: "statModifier",
            stat: "ap",
            amount: 2,
            duration: "thisTurn",
            target: {
              owner: "self",
              cardType: "unit",
            },
          },
        },
      ],
      sourceText: "【Attack】This Unit gets AP+2 during this turn.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
