import type { UnitCard } from "@tcg/gundam-types";

export const betaLoto011: UnitCard = {
  cardNumber: "GD01-011",
  name: "Loto",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "GD01-011_p1",
  externalId: "gundam:gd01-011_p1",
  slug: "loto-gd01-011-p1",
  displayName: "Loto",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-011_p1",
  printings: [
    {
      id: "GD01-011",
      collectorNumber: "GD01-011",
      cardNumber: "GD01-011",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-011.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-011.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-011_p1",
      collectorNumber: "GD01-011_p1",
      cardNumber: "GD01-011",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-011_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-011_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-011_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-011_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-011_p1.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
