import type { UnitCard } from "@tcg/gundam-types";

export const betaRezel018: UnitCard = {
  cardNumber: "GD01-018",
  name: "ReZEL",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "GD01-018_p1",
  canonicalId: "GD01-018",
  externalIds: { bandai: "gundam:gd01-018_p1" },
  slug: "rezel/gd01-018",
  displayName: "ReZEL",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-018_p1",
  printings: [
    {
      id: "GD01-018",
      artId: "GD01-018",
      setCode: "GD01",
      collectorNumber: "GD01-018",
      cardNumber: "GD01-018",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-018.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-018.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-018_p1",
      artId: "GD01-018_p1",
      setCode: "BETA",
      collectorNumber: "GD01-018_p1",
      cardNumber: "GD01-018",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-018_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-018_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  reprints: ["GD01-018", "GD01-018_p1"],
  selectedPrintingId: "GD01-018_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-018_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-018_p1.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
