import type { UnitCard } from "@tcg/gundam-types";

export const betaRickDom030: UnitCard = {
  cardNumber: "GD01-030",
  name: "Rick Dom",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD01-030_p1",
  externalId: "gundam:gd01-030_p1",
  slug: "rick-dom-gd01-030-p1",
  displayName: "Rick Dom",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-030_p1",
  printings: [
    {
      id: "GD01-030",
      collectorNumber: "GD01-030",
      cardNumber: "GD01-030",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-030.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-030.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-030_p1",
      collectorNumber: "GD01-030_p1",
      cardNumber: "GD01-030",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-030_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-030_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-030_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-030_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-030_p1.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect:
    "&lt;Breach 2&gt; (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to a card in that opponent's shield area.)<br>",
  keywordEffects: [{ keyword: "Breach", value: 2 }],
  rarity: "uncommon",
};
