import type { UnitCard } from "@tcg/gundam-types";

export const betaGelgoog031: UnitCard = {
  cardNumber: "GD01-031",
  name: "Gelgoog",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD01-031_p1",
  externalId: "gundam:gd01-031_p1",
  slug: "gelgoog-gd01-031-p1",
  displayName: "Gelgoog",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-031_p1",
  printings: [
    {
      id: "GD01-031",
      collectorNumber: "GD01-031",
      cardNumber: "GD01-031",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-031.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-031.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-031_p1",
      collectorNumber: "GD01-031_p1",
      cardNumber: "GD01-031",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-031_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-031_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-031_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-031_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-031_p1.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
