import type { UnitCard } from "@tcg/gundam-types";

export const betaShenlongGundam041: UnitCard = {
  cardNumber: "GD01-041",
  name: "Shenlong Gundam",
  type: "unit",
  color: "green",
  traits: ["operation meteor"],
  id: "GD01-041_p1",
  externalId: "gundam:gd01-041_p1",
  slug: "shenlong-gundam-gd01-041-p1",
  displayName: "Shenlong Gundam",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-041_p1",
  printings: [
    {
      id: "GD01-041",
      collectorNumber: "GD01-041",
      cardNumber: "GD01-041",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-041.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-041.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-041_p1",
      collectorNumber: "GD01-041_p1",
      cardNumber: "GD01-041",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-041_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-041_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-041_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-041_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-041_p1.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 4,
  hp: 3,
  effect:
    "&lt;Breach 3&gt; (When this Unit's attack destroys an enemy Unit, deal the specified amount of damage to a card in that opponent's shield area.)<br>",
  keywordEffects: [{ keyword: "Breach", value: 3 }],
  rarity: "common",
};
