import type { UnitCard } from "@tcg/gundam-types";

export const betaLauncherStrikeGundam072: UnitCard = {
  cardNumber: "GD01-072",
  name: "Launcher Strike Gundam",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "GD01-072_p1",
  externalId: "gundam:gd01-072_p1",
  slug: "launcher-strike-gundam-gd01-072-p1",
  displayName: "Launcher Strike Gundam",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-072_p1",
  printings: [
    {
      id: "GD01-072",
      collectorNumber: "GD01-072",
      cardNumber: "GD01-072",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-072.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-072.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-072_p1",
      collectorNumber: "GD01-072_p1",
      cardNumber: "GD01-072",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-072_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-072_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-072_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-072_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-072_p1.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
