import type { UnitCard } from "@tcg/gundam-types";

export const betaStrikeGundam077: UnitCard = {
  cardNumber: "GD01-077",
  name: "Strike Gundam",
  type: "unit",
  color: "white",
  traits: ["earth alliance"],
  id: "GD01-077_p1",
  externalId: "gundam:gd01-077_p1",
  slug: "strike-gundam-gd01-077-p1",
  displayName: "Strike Gundam",
  set: { code: "BETA", name: "Edition Beta", packageId: "616000" },
  printNumber: "GD01-077_p1",
  printings: [
    {
      id: "GD01-077",
      collectorNumber: "GD01-077",
      cardNumber: "GD01-077",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-077.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-077.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-077_p1",
      collectorNumber: "GD01-077_p1",
      cardNumber: "GD01-077",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-077_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-077_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-077_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-077_p1.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-077_p1.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
