// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuCantoBight = {
  title: "Canto Bight",
  hp: 27,
  text: "Epic Action: Play a card from your hand, ignoring 1 of its Vigilance, Command, Aggression, or Cunning aspect penalties.",
  unique: false,
  rules:
    "Abilities that let you play a card require you to pay that card’s cost unless specified otherwise.\n",
  id: "2937103129",
  rarity: "common",
  aspects: ["cunning"],
  types: ["base"],
  setId: {
    set: "LAW",
    number: 28,
  },
  setCodes: [
    {
      set: "LAW",
      number: 28,
    },
  ],
  internalName: "canto-bight",
  cardType: "base",
  abilities: [
    {
      kind: "action",
      text: "Epic Action: Play a card from your hand, ignoring 1 of its Vigilance, Command, Aggression, or Cunning aspect penalties.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "play",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["hand"],
            limit: 1,
          },
          free: false,
        },
      ],
    },
  ],
} satisfies SwuBaseCard;

export default swuCantoBight;
