// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuStygeonSpire = {
  title: "Stygeon Spire",
  hp: 27,
  text: "Epic Action: Play a card from your hand, ignoring 1 of its Vigilance, Command, Aggression, or Cunning aspect penalties.",
  unique: false,
  rules:
    "Abilities that let you play a card require you to pay that card’s cost unless specified otherwise.\n",
  id: "5020919647",
  rarity: "common",
  aspects: ["aggression"],
  types: ["base"],
  setId: {
    set: "LAW",
    number: 27,
  },
  setCodes: [
    {
      set: "LAW",
      number: 27,
    },
  ],
  internalName: "stygeon-spire",
  cardType: "base",
  canonicalId: "stygeon-spire",
  slug: "stygeon-spire",
  name: "Stygeon Spire",
  printings: [
    {
      id: "LAW_027",
      artId: "46187",
      setCode: "LAW",
      collectorNumber: "27",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07010027_EN_Stygeon_Spire_Base_79696b49ed.png",
    },
    {
      id: "9871981141",
      artId: "46187",
      setCode: "LAW",
      collectorNumber: "291",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07020291_EN_Stygeon_Spire_Base_00a427807b.png",
    },
  ],
  abilities: [
    {
      kind: "action",
      text: "Epic Action: Play a card from your hand, ignoring 1 of its Vigilance, Command, Aggression, or Cunning aspect penalties.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "play",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["hand"],
            limit: 1,
          },
          free: false,
        },
      ],
    },
  ],
} satisfies SwuBaseCard;

export default swuStygeonSpire;
