import type { ResourceCard } from "@tcg/gundam-types";

export const st02Resource001: ResourceCard = {
  cardNumber: "R-001-p1",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-001_p1",
  externalId: "gundam:r-001_p1",
  slug: "resource-r-001-p1",
  displayName: "resource",
  set: { code: "R", name: "Basic Cards" },
  printNumber: "R-001_p1",
  printings: [
    {
      id: "R-001",
      collectorNumber: "R-001",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p1",
      collectorNumber: "R-001_p1",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p2",
      collectorNumber: "R-001_p2",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p2.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p2.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p3",
      collectorNumber: "R-001_p3",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p4",
      collectorNumber: "R-001_p4",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/R-001_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p4.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p5",
      collectorNumber: "R-001_p5",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/R-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p5.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p6",
      collectorNumber: "R-001_p6",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Included in Starter Decks",
        packageId: "616801",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p6.webp?260424",
      productName: "Included in Starter Decks",
    },
  ],
  selectedPrintingId: "R-001_p1",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
  sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
