import type { ResourceCard } from "@tcg/gundam-types";

export const st04Resource001: ResourceCard = {
  cardNumber: "R-001-p3",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-001_p3",
  canonicalId: "R-001",
  externalIds: { bandai: "gundam:r-001_p3" },
  slug: "resource/r-001",
  displayName: "resource",
  set: { code: "R", name: "Basic Cards" },
  printNumber: "R-001_p3",
  printings: [
    {
      id: "R-001",
      artId: "R-001",
      setCode: "R",
      collectorNumber: "R-001",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p1",
      artId: "R-001_p1",
      setCode: "R",
      collectorNumber: "R-001_p1",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p1.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p2",
      artId: "R-001_p2",
      setCode: "R",
      collectorNumber: "R-001_p2",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p2.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p2.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p3",
      artId: "R-001_p3",
      setCode: "R",
      collectorNumber: "R-001_p3",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
      productName: "Basic Cards",
    },
    {
      id: "R-001_p4",
      artId: "R-001_p4",
      setCode: "BETA",
      collectorNumber: "R-001_p4",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/R-001_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p4.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p5",
      artId: "R-001_p5",
      setCode: "BETA",
      collectorNumber: "R-001_p5",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/R-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p5.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p6",
      artId: "R-001_p6",
      setCode: "R",
      collectorNumber: "R-001_p6",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Included in Starter Decks",
        packageId: "616801",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p6.webp?260424",
      productName: "Included in Starter Decks",
    },
  ],
  reprints: ["R-001", "R-001_p1", "R-001_p2", "R-001_p3", "R-001_p4", "R-001_p5", "R-001_p6"],
  selectedPrintingId: "R-001_p3",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
  sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-001_p3.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
