import type { ResourceCard } from "@tcg/gundam-types";

export const st04Resource001: ResourceCard = {
  cardNumber: "R-001-p3",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-001_p6",
  canonicalId: "R-001",
  externalIds: { bandai: "gundam:r-001_p6" },
  slug: "resource-r-001-p6",
  displayName: "resource",
  set: { code: "R", name: "Included in Starter Decks", packageId: "616801" },
  printNumber: "R-001_p6",
  printings: [
    {
      id: "R-001_p4",
      artId: "R-001_p4",
      setCode: "BETA",
      collectorNumber: "R-001_p4",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/beta/R-001_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p4.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p5",
      artId: "R-001_p5",
      setCode: "BETA",
      collectorNumber: "R-001_p5",
      cardNumber: "R-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/beta/R-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p5.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "R-001_p6",
      artId: "R-001_p6",
      setCode: "R",
      collectorNumber: "R-001_p6",
      cardNumber: "R-001",
      set: {
        code: "R",
        name: "Included in Starter Decks",
        packageId: "616801",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p6.webp?260715",
      productName: "Included in Starter Decks",
    },
    {
      id: "R-001_p7",
      artId: "R-001_p7",
      setCode: "SC01",
      collectorNumber: "R-001_p7",
      cardNumber: "R-001",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-001_p7.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p7.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["R-001_p4", "R-001_p5", "R-001_p6", "R-001_p7"],
  selectedPrintingId: "R-001_p6",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-001_p6.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-001_p6.webp?260715",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
