import type { ResourceCard } from "@tcg/gundam-types";

export const gd01Resource003: ResourceCard = {
  cardNumber: "R-003",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-003",
  externalId: "gundam:r-003",
  slug: "resource-r-003",
  displayName: "resource",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "R-003",
  printings: [
    {
      id: "R-003",
      collectorNumber: "R-003",
      cardNumber: "R-003",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/R-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-003.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "R-003_p1",
      collectorNumber: "R-003_p1",
      cardNumber: "R-003",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/R-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-003_p1.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "R-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/R-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-003.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
