import type { ResourceCard } from "@tcg/gundam-types";

export const gd01Resource009: ResourceCard = {
  cardNumber: "R-009",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-009",
  canonicalId: "R-009",
  externalIds: { bandai: "gundam:r-009" },
  slug: "resource/r-009",
  displayName: "resource",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "R-009",
  printings: [
    {
      id: "R-009",
      artId: "R-009",
      setCode: "GD01",
      collectorNumber: "R-009",
      cardNumber: "R-009",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/R-009.webp",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "R-009_p1",
      artId: "R-009_p1",
      setCode: "GD01",
      collectorNumber: "R-009_p1",
      cardNumber: "R-009",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/R-009_p1.webp",
      productName: "Newtype Rising [GD01]",
    },
  ],
  reprints: ["R-009", "R-009_p1"],
  selectedPrintingId: "R-009",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/R-009.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
