import type { ResourceCard } from "@tcg/gundam-types";

export const gd02Resource017: ResourceCard = {
  cardNumber: "R-017",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-017",
  externalId: "gundam:r-017",
  slug: "resource-r-017",
  displayName: "resource",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "R-017",
  printings: [
    {
      id: "R-017",
      collectorNumber: "R-017",
      cardNumber: "R-017",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-017.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-017.webp?260424",
      productName: "Dual Impact [GD02]",
    },
    {
      id: "R-017_p1",
      collectorNumber: "R-017_p1",
      cardNumber: "R-017",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-017_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-017_p1.webp?260424",
    },
  ],
  selectedPrintingId: "R-017",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-017.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-017.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
