import type { ResourceCard } from "@tcg/gundam-types";

export const gd02Resource017: ResourceCard = {
  cardNumber: "R-017",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-017",
  canonicalId: "R-017",
  externalIds: { bandai: "gundam:r-017" },
  slug: "resource/r-017",
  displayName: "resource",
  set: { code: "GD02", name: "Dual Impact [GD02]", packageId: "616102" },
  printNumber: "R-017",
  printings: [
    {
      id: "R-017",
      artId: "R-017",
      setCode: "GD02",
      collectorNumber: "R-017",
      cardNumber: "R-017",
      set: {
        code: "GD02",
        name: "Dual Impact [GD02]",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-017.webp",
      productName: "Dual Impact [GD02]",
    },
    {
      id: "R-017_p1",
      artId: "R-017_p1",
      setCode: "GD02",
      collectorNumber: "R-017_p1",
      cardNumber: "R-017",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-017_p1.webp",
    },
  ],
  reprints: ["R-017", "R-017_p1"],
  selectedPrintingId: "R-017",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-017.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
