import type { ResourceCard } from "@tcg/gundam-types";

export const gd02Resource019: ResourceCard = {
  cardNumber: "R-019",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-019",
  canonicalId: "R-019",
  externalIds: { bandai: "gundam:r-019" },
  slug: "resource/r-019",
  displayName: "resource",
  set: { code: "GD02", name: "-", packageId: "616102" },
  printNumber: "R-019",
  printings: [
    {
      id: "R-019",
      artId: "R-019",
      setCode: "GD02",
      collectorNumber: "R-019",
      cardNumber: "R-019",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-019.webp",
    },
    {
      id: "R-019_p1",
      artId: "R-019_p1",
      setCode: "GD02",
      collectorNumber: "R-019_p1",
      cardNumber: "R-019",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-019_p1.webp",
    },
  ],
  reprints: ["R-019", "R-019_p1"],
  selectedPrintingId: "R-019",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd02/R-019.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
