import type { ResourceCard } from "@tcg/gundam-types";

export const gd02Resource019: ResourceCard = {
  cardNumber: "R-019",
  name: "resource",
  type: "resource",
  traits: ["-"],
  id: "R-019",
  externalId: "gundam:r-019",
  slug: "resource-r-019",
  displayName: "resource",
  set: { code: "GD02", name: "-", packageId: "616102" },
  printNumber: "R-019",
  printings: [
    {
      id: "R-019",
      collectorNumber: "R-019",
      cardNumber: "R-019",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-019.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-019.webp?260424",
    },
    {
      id: "R-019_p1",
      collectorNumber: "R-019_p1",
      cardNumber: "R-019",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-019_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-019_p1.webp?260424",
    },
  ],
  selectedPrintingId: "R-019",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd02/R-019.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-019.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)<br>",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
