import type { ResourceCard } from "@tcg/gundam-types";

export const rResource025: ResourceCard = {
  cardNumber: "R-025",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-025",
  externalId: "gundam:r-025",
  slug: "resource-r-025",
  displayName: "Resource",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "R-025",
  printings: [
    {
      id: "R-025",
      collectorNumber: "R-025",
      cardNumber: "R-025",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-025.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-025.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "R-025_p1",
      collectorNumber: "R-025_p1",
      cardNumber: "R-025",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-025_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-025_p1.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "R-025_p2",
      collectorNumber: "R-025_p2",
      cardNumber: "R-025",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-025_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-025_p2.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "R-025",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-025.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-025.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd03Resource025 = rResource025;
