import type { ResourceCard } from "@tcg/gundam-types";

export const rResource026: ResourceCard = {
  cardNumber: "R-026",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-026",
  externalId: "gundam:r-026",
  slug: "resource-r-026",
  displayName: "Resource",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "R-026",
  printings: [
    {
      id: "R-026",
      collectorNumber: "R-026",
      cardNumber: "R-026",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-026.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-026.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "R-026_p1",
      collectorNumber: "R-026_p1",
      cardNumber: "R-026",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-026_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-026_p1.webp?260424",
      productName: "Steel Requiem[GD03]",
    },
  ],
  selectedPrintingId: "R-026",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-026.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-026.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd03Resource026 = rResource026;
