import type { ResourceCard } from "@tcg/gundam-types";

export const rResource026: ResourceCard = {
  cardNumber: "R-026",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-026",
  canonicalId: "R-026",
  externalIds: { bandai: "gundam:r-026" },
  slug: "resource/r-026",
  displayName: "Resource",
  set: { code: "GD03", name: "Steel Requiem[GD03]", packageId: "616103" },
  printNumber: "R-026",
  printings: [
    {
      id: "R-026",
      artId: "R-026",
      setCode: "GD03",
      collectorNumber: "R-026",
      cardNumber: "R-026",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-026.webp",
      productName: "Steel Requiem[GD03]",
    },
    {
      id: "R-026_p1",
      artId: "R-026_p1",
      setCode: "GD03",
      collectorNumber: "R-026_p1",
      cardNumber: "R-026",
      set: {
        code: "GD03",
        name: "Steel Requiem[GD03]",
        packageId: "616103",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-026_p1.webp",
      productName: "Steel Requiem[GD03]",
    },
  ],
  reprints: ["R-026", "R-026_p1"],
  selectedPrintingId: "R-026",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-026.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd03Resource026 = rResource026;
