import type { ResourceCard } from "@tcg/gundam-types";

export const rResource034: ResourceCard = {
  cardNumber: "R-034",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-034",
  externalId: "gundam:r-034",
  slug: "resource-r-034",
  displayName: "Resource",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "R-034",
  printings: [
    {
      id: "R-034",
      collectorNumber: "R-034",
      cardNumber: "R-034",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-034.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-034.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
    {
      id: "R-034_p1",
      collectorNumber: "R-034_p1",
      cardNumber: "R-034",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-034_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-034_p1.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "R-034",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/r/R-034.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/R-034.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd04Resource034 = rResource034;
