import type { ResourceCard } from "@tcg/gundam-types";

export const rResource037: ResourceCard = {
  cardNumber: "R-037",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-037",
  canonicalId: "R-037",
  externalIds: { bandai: "gundam:r-037" },
  slug: "resource/r-037",
  displayName: "Resource",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "R-037",
  printings: [
    {
      id: "R-037",
      artId: "R-037",
      setCode: "GD04",
      collectorNumber: "R-037",
      cardNumber: "R-037",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-037.webp",
      productName: "Phantom Aria [GD04]",
    },
    {
      id: "R-037_p1",
      artId: "R-037_p1",
      setCode: "GD04",
      collectorNumber: "R-037_p1",
      cardNumber: "R-037",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-037_p1.webp",
      productName: "Phantom Aria [GD04]",
    },
  ],
  reprints: ["R-037", "R-037_p1"],
  selectedPrintingId: "R-037",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-037.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd04Resource037 = rResource037;
