import type { ResourceCard } from "@tcg/gundam-types";

export const rResource038: ResourceCard = {
  cardNumber: "R-038",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "R-038",
  canonicalId: "R-038",
  externalIds: { bandai: "gundam:r-038" },
  slug: "resource/r-038",
  displayName: "Resource",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "R-038",
  printings: [
    {
      id: "R-038",
      artId: "R-038",
      setCode: "GD04",
      collectorNumber: "R-038",
      cardNumber: "R-038",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-038.webp",
      productName: "Phantom Aria [GD04]",
    },
    {
      id: "R-038_p1",
      artId: "R-038_p1",
      setCode: "GD04",
      collectorNumber: "R-038_p1",
      cardNumber: "R-038",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-038_p1.webp",
      productName: "Phantom Aria [GD04]",
    },
    {
      id: "R-038_p2",
      artId: "R-038_p2",
      setCode: "GD04",
      collectorNumber: "R-038_p2",
      cardNumber: "R-038",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-038_p2.webp",
      productName: "Phantom Aria [GD04]",
    },
  ],
  reprints: ["R-038", "R-038_p1", "R-038_p2"],
  selectedPrintingId: "R-038",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/r/R-038.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd04Resource038 = rResource038;
