// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDarthSidiousUnderACloakOfDarkness = {
  title: "Darth Sidious",
  subtitle: "Under a Cloak of Darkness",
  cost: 6,
  hp: 6,
  power: 4,
  text: "Hidden\nEach other friendly Separatist unit gets +1/+0.\nWhen a non-token unit is defeated: Create a Battle Droid token.",
  unique: true,
  rules:
    "If Darth Sidious is defeated simultaneously with other units, his “When a non-token unit is defeated” ability trigger for each unit defeated, including himself.\nIf a unit has Hidden and Sentinel at the same time, it can be attacked.\n",
  id: "9473986821",
  rarity: "rare",
  aspects: ["vigilance", "command", "villainy"],
  traits: ["force", "separatist", "sith"],
  arena: "ground",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "TS26",
    number: 13,
  },
  setCodes: [
    {
      set: "TS26",
      number: 13,
    },
  ],
  internalName: "darth-sidious#under-a-cloak-of-darkness",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuDarthSidiousUnderACloakOfDarkness;
