// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuWartimeMercenaries = {
  title: "Wartime Mercenaries",
  cost: 4,
  hp: 5,
  power: 5,
  text: "When Defeated: An opponent may give an Experience token to a unit.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "6507361368",
  rarity: "common",
  aspects: ["command"],
  traits: ["trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TS26",
    number: 54,
  },
  setCodes: [
    {
      set: "TS26",
      number: 54,
    },
  ],
  internalName: "wartime-mercenaries",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "defeated" },
      {
        text: "When Defeated: An opponent may give an Experience token to a unit.",
        effects: [effect.optional([effect.distribute("experience", target.unit({ limit: 1 }), 1)])],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuWartimeMercenaries;
