// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuWartimeRefugee = {
  title: "Wartime Refugee",
  cost: 1,
  hp: 3,
  power: 2,
  text: "On Attack: An opponent heals 1 damage from their base.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "1577019857",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["twi'lek"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TS26",
    number: 43,
  },
  setCodes: [
    {
      set: "TS26",
      number: 43,
    },
  ],
  internalName: "wartime-refugee",
  cardType: "unit",
  abilities: [
    ability.onAttack({
      text: "On Attack: An opponent heals 1 damage from their base.",
      effects: [effect.heal(target.base("opponent"), 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuWartimeRefugee;
