// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuWartimePirate = {
  title: "Wartime Pirate",
  cost: 3,
  hp: 4,
  power: 4,
  text: "On Attack: An opponent deals 1 damage to a unit.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "3034449380",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["underworld", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "TS26",
    number: 66,
  },
  setCodes: [
    {
      set: "TS26",
      number: 66,
    },
  ],
  internalName: "wartime-pirate",
  cardType: "unit",
  canonicalId: "wartime-pirate",
  slug: "wartime-pirate",
  name: "Wartime Pirate",
  printings: [
    {
      id: "TS26_066",
      artId: "51182",
      setCode: "TS26",
      collectorNumber: "66",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//TS_26010066_EN_Wartime_Pirate_e24d6b16e2.png",
    },
  ],
  abilities: [
    ability.onAttack({
      text: "On Attack: An opponent deals 1 damage to a unit.",
      effects: [effect.damage(target.unit({ limit: 1 }), 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuWartimePirate;
