// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuChampion = {
  title: "Champion",
  cost: 5,
  unique: false,
  upgradePower: 4,
  upgradeHp: 4,
  id: "7640352104",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["innate"],
  types: ["upgrade"],
  setId: {
    set: "TS26",
    number: 45,
  },
  setCodes: [
    {
      set: "TS26",
      number: 45,
    },
  ],
  internalName: "champion",
  cardType: "upgrade",
} satisfies SwuUpgradeCard;

export default swuChampion;
