// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuExperience = {
  title: "Experience",
  cost: 0,
  unique: false,
  upgradePower: 0,
  upgradeHp: 0,
  id: "5904064998",
  rarity: "common",
  traits: ["learned"],
  types: ["upgrade", "token"],
  setId: {
    set: "TS26",
  },
  internalName: "experience",
  cardType: "upgrade",
} satisfies SwuUpgradeCard;

export default swuExperience;
