import type { CardEffect, UnitCard } from "@tcg/gundam-types";

export const st01Gundam001: UnitCard = {
  cardNumber: "ST01-001",
  name: "Gundam",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "ST01-001",
  externalId: "gundam:st01-001",
  slug: "gundam-st01-001",
  displayName: "Gundam",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "ST01-001",
  printings: [
    {
      id: "ST01-001",
      collectorNumber: "ST01-001",
      cardNumber: "ST01-001",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "legendRare",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-001_p1",
      collectorNumber: "ST01-001_p1",
      cardNumber: "ST01-001",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-001_p2",
      collectorNumber: "ST01-001_p2",
      cardNumber: "ST01-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST01-001_p3",
      collectorNumber: "ST01-001_p3",
      cardNumber: "ST01-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p3.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST01-001_p4",
      collectorNumber: "ST01-001_p4",
      cardNumber: "ST01-001",
      set: {
        code: "EVX05",
        name: "Premium Card Collection [EVX05]",
        packageId: "616701",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p4.webp?260424",
      productName: "Premium Card Collection [EVX05]",
    },
    {
      id: "ST01-001_p5",
      collectorNumber: "ST01-001_p5",
      cardNumber: "ST01-001",
      set: {
        code: "ST01",
        name: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 3rd Place Card",
        packageId: "616901",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p5.webp?260424",
      productName: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 3rd Place Card",
    },
    {
      id: "ST01-001_p6",
      collectorNumber: "ST01-001_p6",
      cardNumber: "ST01-001",
      set: {
        code: "ST01",
        name: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 2nd Place Card",
        packageId: "616901",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p6.webp?260424",
      productName: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 2nd Place Card",
    },
    {
      id: "ST01-001_p7",
      collectorNumber: "ST01-001_p7",
      cardNumber: "ST01-001",
      set: {
        code: "ST01",
        name: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 1st Place Card",
        packageId: "616901",
      },
      rarity: "legendRare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001_p7.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001_p7.webp?260424",
      productName: "WORLD CHAMPIONSHIPS 25-26 REGIONAL CHAMPIONSHIPS 1st Place Card",
    },
  ],
  selectedPrintingId: "ST01-001",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-001.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-001.webp?260424",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  linkCondition: "[Amuro Ray]",
  effect:
    "<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)\n【During Pair】During your turn, all your Units get AP+1.",
  effects: [
    {
      type: "constant",
      activation: {
        conditions: [{ type: "duringPair" }, { type: "isTurn", whose: "friendly" }],
      },
      directives: [
        {
          action: {
            action: "statModifier",
            stat: "ap",
            amount: 1,
            duration: "permanent",
            target: {
              owner: "friendly",
              cardType: "unit",
            },
          },
        },
      ],
      sourceText: "【During Pair】During your turn, all your Units get AP+1.",
    },
  ] as CardEffect[],
  keywordEffects: [{ keyword: "Repair", value: 2 }],
  rarity: "legendRare",
};
export const evx05Gundam001 = st01Gundam001;
