import type { UnitCard } from "@tcg/gundam-types";

export const st01Guncannon003: UnitCard = {
  cardNumber: "ST01-003",
  name: "Guncannon",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "ST01-003",
  externalId: "gundam:st01-003",
  slug: "guncannon-st01-003",
  displayName: "Guncannon",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "ST01-003",
  printings: [
    {
      id: "ST01-003",
      collectorNumber: "ST01-003",
      cardNumber: "ST01-003",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-003.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-003_p1",
      collectorNumber: "ST01-003_p1",
      cardNumber: "ST01-003",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-003_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST01-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-003.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
