import type { UnitCard } from "@tcg/gundam-types";

export const st01Gm005: UnitCard = {
  cardNumber: "ST01-005",
  name: "GM",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "ST01-005",
  externalId: "gundam:st01-005",
  slug: "gm-st01-005",
  displayName: "GM",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "ST01-005",
  printings: [
    {
      id: "ST01-005",
      collectorNumber: "ST01-005",
      cardNumber: "ST01-005",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-005.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-005_p1",
      collectorNumber: "ST01-005_p1",
      cardNumber: "ST01-005",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-005_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-005_p2",
      collectorNumber: "ST01-005_p2",
      cardNumber: "ST01-005",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST01-005_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-005_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST01-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-005.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
