import type { UnitCard } from "@tcg/gundam-types";

export const st01GundamAerialBitOnForm007: UnitCard = {
  cardNumber: "ST01-007",
  name: "Gundam Aerial (Bit on Form)",
  type: "unit",
  color: "white",
  traits: ["academy"],
  id: "ST01-007",
  externalId: "gundam:st01-007",
  slug: "gundam-aerial-bit-on-form-st01-007",
  displayName: "Gundam Aerial (Bit on Form)",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "ST01-007",
  printings: [
    {
      id: "ST01-007",
      collectorNumber: "ST01-007",
      cardNumber: "ST01-007",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-007.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-007_p1",
      collectorNumber: "ST01-007_p1",
      cardNumber: "ST01-007",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-007_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-007_p2",
      collectorNumber: "ST01-007_p2",
      cardNumber: "ST01-007",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST01-007_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-007_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST01-007",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-007.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-007.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
