// This file is generated by @tcg/cyberpunk-parser. Do not edit manually.
// Seeded from the scraped catalog text; future generator versions will
// preserve hand-authored non-en locales alongside the en seed.
import type { CyberpunkCardLocale, CyberpunkLocale } from "@tcg/cyberpunk-types";

export const welcomeToNightCityRetailRuthlessLowlifeI18n: Record<
  CyberpunkLocale,
  CyberpunkCardLocale
> = {
  en: {
    name: "Ruthless Lowlife",
    displayName: "Ruthless Lowlife",
    rulesText: "This Unit can only attack rival Units. (It can't attack Gig areas.)",
  },
};
