// This file is generated by @tcg/cyberpunk-parser. Do not edit manually.
// Seeded from the scraped catalog text; future generator versions will
// preserve hand-authored non-en locales alongside the en seed.
import type { CyberpunkCardLocale, CyberpunkLocale } from "@tcg/cyberpunk-types";

export const welcomeToNightCityRetailValentinoStreetRacerI18n: Record<
  CyberpunkLocale,
  CyberpunkCardLocale
> = {
  en: {
    name: "Valentino Street Racer",
    displayName: "Valentino Street Racer",
    rulesText:
      "{Play} Give another friendly Unit with cost 5 or less {Adrenaline} this turn. (A Unit with Adrenaline can attack the turn it's played.)",
  },
};
