import type { BaseCard } from "@tcg/gundam-types";

export const exbExBase001: BaseCard = {
  cardNumber: "EXB-001",
  name: "EX Base",
  type: "base",
  traits: [],
  id: "EXB-001",
  externalId: "gundam:exb-001",
  slug: "ex-base-exb-001",
  displayName: "EX Base",
  set: { code: "EXB", name: "Basic Cards" },
  printNumber: "EXB-001",
  printings: [
    {
      id: "EXB-001",
      collectorNumber: "EXB-001",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXB-001_p1",
      collectorNumber: "EXB-001_p1",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p1.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p1.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXB-001_p2",
      collectorNumber: "EXB-001_p2",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p2.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p2.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXB-001_p3",
      collectorNumber: "EXB-001_p3",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p3.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p3.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXB-001_p4",
      collectorNumber: "EXB-001_p4",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p4.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p4.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXB-001_p5",
      collectorNumber: "EXB-001_p5",
      cardNumber: "EXB-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p5.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "EXB-001_p6",
      collectorNumber: "EXB-001_p6",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Included in Booster Packs",
        packageId: "616801",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p6.webp?260424",
      productName: "Included in Booster Packs",
    },
  ],
  selectedPrintingId: "EXB-001",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001.webp",
  sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exb/EXB-001.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  hp: 3,
  effect: "(At the start of the game, place 1 active EX Base into your shield area.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
