import type { BaseCard } from "@tcg/gundam-types";

export const exbExBase001: BaseCard = {
  cardNumber: "EXB-001",
  name: "EX Base",
  type: "base",
  traits: [],
  id: "EXB-001_p6",
  canonicalId: "EXB-001",
  externalIds: { bandai: "gundam:exb-001_p6" },
  slug: "ex-base-exb-001-p6",
  displayName: "EX Base",
  set: { code: "EXB", name: "Included in Booster Packs", packageId: "616801" },
  printNumber: "EXB-001_p6",
  printings: [
    {
      id: "EXB-001_p5",
      artId: "EXB-001_p5",
      setCode: "BETA",
      collectorNumber: "EXB-001_p5",
      cardNumber: "EXB-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p5.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "EXB-001_p6",
      artId: "EXB-001_p6",
      setCode: "EXB",
      collectorNumber: "EXB-001_p6",
      cardNumber: "EXB-001",
      set: {
        code: "EXB",
        name: "Included in Booster Packs",
        packageId: "616801",
      },
      rarity: "common",
      // Standard finish: the booster-pack art is the free default EX Base
      // token art (platform setup-slot default). The BETA (_p5) and SC01
      // (_p7) printings stay parallel (ownable alt-art).
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p6.webp?260715",
      productName: "Included in Booster Packs",
    },
    {
      id: "EXB-001_p7",
      artId: "EXB-001_p7",
      setCode: "SC01",
      collectorNumber: "EXB-001_p7",
      cardNumber: "EXB-001",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-001_p7.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p7.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["EXB-001_p5", "EXB-001_p6", "EXB-001_p7"],
  selectedPrintingId: "EXB-001_p6",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-001_p6.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXB-001_p6.webp?260715",
  legality: "legal",
  level: 0,
  cost: 0,
  hp: 3,
  effect: "(At the start of the game, place 1 active EX Base as your shield area's base.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
