import type { BaseCard } from "@tcg/gundam-types";

export const exbExBase002: BaseCard = {
  cardNumber: "EXB-002",
  name: "EX Base",
  type: "base",
  traits: [],
  id: "EXB-002",
  canonicalId: "EXB-002",
  externalIds: { bandai: "gundam:exb-002" },
  slug: "ex-base/exb-002",
  displayName: "EX Base",
  set: { code: "ST09", name: "Destiny Ignition [ST09]", packageId: "616009" },
  printNumber: "EXB-002",
  printings: [
    {
      id: "EXB-002",
      artId: "EXB-002",
      setCode: "ST09",
      collectorNumber: "EXB-002",
      cardNumber: "EXB-002",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-002.webp",
      productName: "Destiny Ignition [ST09]",
    },
    {
      id: "EXB-002_p1",
      artId: "EXB-002_p1",
      setCode: "ST09",
      collectorNumber: "EXB-002_p1",
      cardNumber: "EXB-002",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-002_p1.webp",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  reprints: ["EXB-002", "EXB-002_p1"],
  selectedPrintingId: "EXB-002",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/exb/EXB-002.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  hp: 3,
  effect: "(At the start of the game, place 1 active EX Base as your shield area's base.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st09ExBase002 = exbExBase002;
