// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuAdmiralAckbarItsATrap = {
  title: "Admiral Ackbar",
  subtitle: "It's A Trap!",
  cost: 6,
  hp: 8,
  power: 3,
  text: "Action [1 resource, Exhaust]: Exhaust a non-leader unit. If you do, its controller creates an X-Wing token.",
  deployBox:
    "On Attack: You may exhaust a unit. If you do, its controller creates an X-Wing token.",
  epicAction: "Epic Action: If you control 6 or more resources, deploy this leader.",
  unique: true,
  id: "7514405173",
  rarity: "common",
  aspects: ["cunning", "heroism"],
  traits: ["rebel", "official"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "JTL",
    number: 16,
  },
  setCodes: [
    {
      set: "JTL",
      number: 16,
    },
  ],
  internalName: "admiral-ackbar#its-a-trap",
  cardType: "leader",
  abilities: [
    {
      kind: "action",
      text: "Action [1 resource, Exhaust]: Exhaust a non-leader unit. If you do, its controller creates an X-Wing token.",
      trigger: {
        event: "action",
      },
      effects: [
        {
          type: "exhaust",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "On Attack: You may exhaust a unit. If you do, its controller creates an X-Wing token.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "exhaust",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
    {
      kind: "action",
      text: "Epic Action: If you control 6 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuAdmiralAckbarItsATrap;
