// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuCaptainPhasmaChromeDome = {
  title: "Captain Phasma",
  subtitle: "Chrome Dome",
  cost: 5,
  hp: 6,
  power: 4,
  text: "Action [Exhaust]: If you played a First Order card this phase, deal 1 damage to a base.",
  deployBox:
    "On Attack: If you played another First Order card this phase, you may deal 1 damage to a unit. If you do, deal 1 damage to a base.",
  epicAction: "Epic Action: If you control 5 or more resources, deploy this leader.",
  unique: true,
  rules:
    "Phasma’s leader ability still can be used as an action even if you haven't played a First Order card this phase (but no damage is dealt).\n",
  id: "3132453342",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["first order", "trooper"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "JTL",
    number: 10,
  },
  setCodes: [
    {
      set: "JTL",
      number: 10,
    },
  ],
  internalName: "captain-phasma#chrome-dome",
  cardType: "leader",
  abilities: [
    {
      kind: "action",
      text: "Epic Action: If you control 5 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuCaptainPhasmaChromeDome;
