// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDarthVaderVictorSquadronLeader = {
  title: "Darth Vader",
  subtitle: "Victor Squadron Leader",
  cost: 6,
  hp: 6,
  power: 5,
  text: "Action [Exhaust]: If you attacked with a non-token Vehicle unit this phase, create a TIE Fighter token.",
  deployBox:
    "\nAttached unit is a leader unit.\nWhen deployed as an upgrade: Create 2 TIE Fighter tokens.\n",
  epicAction:
    "Epic Action: If you control 6 or more resources, choose one:\nDeploy this leader.\nDeploy this leader as an upgrade on a friendly Vehicle unit without a Pilot on it.",
  unique: true,
  rules:
    "In order to deploy Vader as an upgrade, there needs to be a friendly Vehicle unit for him to attach to. You cannot deploy him as an upgrade and attach him to one of the TIE Fighter tokens he creates when deployed.\nVader’s leader ability still can be used as an action even if you haven't attacked with a non-token Vehicle unit this phase (but no TIE Fighter token is created).\n",
  upgradePower: 5,
  upgradeHp: 5,
  id: "7661383869",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["force", "imperial", "sith", "pilot"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "JTL",
    number: 6,
  },
  setCodes: [
    {
      set: "JTL",
      number: 6,
    },
  ],
  internalName: "darth-vader#victor-squadron-leader",
  cardType: "leader",
  canonicalId: "darth-vader#victor-squadron-leader",
  slug: "darth-vader-victor-squadron-leader",
  name: "Darth Vader",
  printings: [
    {
      id: "JTL_006",
      artId: "19501",
      setCode: "JTL",
      collectorNumber: "6",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010006_EN_Darth_Vader_Leader_dacc2c03a2.png",
    },
    {
      id: "3189893488",
      artId: "19501",
      setCode: "JTL",
      collectorNumber: "268",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020268_EN_Darth_Vader_Leader_01eec8a464.png",
    },
    {
      id: "6032126506",
      artId: "19501",
      setCode: "JTL",
      collectorNumber: "1002",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04031002_EN_Darth_Vader_Leader_0408d0b04c.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Action [Exhaust]: If you attacked with a non-token Vehicle unit this phase, create a TIE Fighter token.",
      costs: [{ type: "exhaust", target: target.self() }],
      effects: [effect.createToken("tieFighter")],
    }),
    ability.triggered(
      { event: "deployed" },
      {
        text: "When deployed as an upgrade: Create 2 TIE Fighter tokens.",
        effects: [effect.createToken("tieFighter", 2)],
      },
    ),
  ],
} satisfies SwuLeaderCard;

export default swuDarthVaderVictorSquadronLeader;
