// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swu000TranslationAndTorture = {
  title: "0-0-0",
  subtitle: "Translation and Torture",
  cost: 3,
  hp: 4,
  power: 4,
  text: "On Attack: You may put a Aggression card from your discard pile on the bottom of your deck. If you do, deal 1 damage to each enemy base.",
  unique: true,
  id: "7641310547",
  rarity: "uncommon",
  aspects: ["aggression", "villainy"],
  traits: ["underworld", "droid"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 174,
  },
  setCodes: [
    {
      set: "LAW",
      number: 174,
    },
  ],
  internalName: "000#translation-and-torture",
  cardType: "unit",
  abilities: [
    ability.onAttack({
      text: "On Attack: You may put a Aggression card from your discard pile on the bottom of your deck. If you do, deal 1 damage to each enemy base.",
      effects: [
        effect.optional([
          effect.ifYouDo(
            effect.reorder(
              target.card({
                controller: "friendly",
                zones: ["discard"],
                limit: 1,
              }),
              "bottomOfDeck",
            ),
            [effect.damage(target.base("opponent"), 1)],
          ),
        ]),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swu000TranslationAndTorture;
