// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAllianceXwing = {
  title: "Alliance X-Wing",
  cost: 2,
  hp: 3,
  power: 2,
  unique: false,
  id: "6060294176",
  rarity: "common",
  aspects: ["heroism"],
  traits: ["rebel", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 253,
  },
  setCodes: [
    {
      set: "LAW",
      number: 253,
    },
  ],
  internalName: "alliance-xwing",
  cardType: "unit",
  canonicalId: "alliance-xwing",
  slug: "alliance-xwing",
  name: "Alliance X-Wing",
  printings: [
    {
      id: "LAW_253",
      artId: "47317",
      setCode: "LAW",
      collectorNumber: "253",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07010253_EN_Alliance_X_Wing_1f2e1b6172.png",
    },
    {
      id: "1326525274",
      artId: "47317",
      setCode: "LAW",
      collectorNumber: "517",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07020517_EN_Alliance_X_Wing_6b3f19fd47.png",
    },
    {
      id: "3254475499",
      artId: "47317",
      setCode: "LAW",
      collectorNumber: "755",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07320755_EN_Alliance_X_Wing_69678be12b.png",
    },
  ],
} satisfies SwuUnitCard;

export default swuAllianceXwing;
