// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuBosskJoinOurMerryBand = {
  title: "Bossk",
  subtitle: "Join Our Merry Band",
  cost: 4,
  hp: 5,
  power: 3,
  text: "On Attack: Give a unit +1/+1 for this phase. You may give a unit –1/–1 for this phase.",
  unique: true,
  id: "3310848830",
  rarity: "uncommon",
  aspects: ["vigilance", "command", "villainy"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 31,
  },
  setCodes: [
    {
      set: "LAW",
      number: 31,
    },
  ],
  internalName: "bossk#join-our-merry-band",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "On Attack: Give a unit +1/+1 for this phase. You may give a unit -1/-1 for this phase.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          power: 1,
          hp: 1,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuBosskJoinOurMerryBand;
