// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCutthroatPodracer = {
  title: "Cutthroat Podracer",
  cost: 4,
  hp: 4,
  power: 4,
  text: "When Played: You may deal 2 damage to an exhausted ground unit.",
  unique: false,
  id: "7742850323",
  rarity: "common",
  aspects: ["cunning", "villainy"],
  traits: ["vehicle", "speeder"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 213,
  },
  setCodes: [
    {
      set: "LAW",
      number: 213,
    },
  ],
  internalName: "cutthroat-podracer",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may deal 2 damage to an exhausted ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuCutthroatPodracer;
