// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDoggedPursuers = {
  title: "Dogged Pursuers",
  cost: 5,
  hp: 5,
  power: 5,
  text: "When Played: You may pay 1 resource. If you do, deal 2 damage to a ground unit.",
  unique: false,
  id: "8976669004",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 198,
  },
  setCodes: [
    {
      set: "LAW",
      number: 198,
    },
  ],
  internalName: "dogged-pursuers",
  cardType: "unit",
  canonicalId: "dogged-pursuers",
  slug: "dogged-pursuers",
  name: "Dogged Pursuers",
  printings: [
    {
      id: "LAW_198",
      artId: "47042",
      setCode: "LAW",
      collectorNumber: "198",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07010198_EN_Dogged_Pursuers_a2ebba2c02.png",
    },
    {
      id: "8396586619",
      artId: "47042",
      setCode: "LAW",
      collectorNumber: "462",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07020462_EN_Dogged_Pursuers_4b7a8434ac.png",
    },
    {
      id: "0424838753",
      artId: "47042",
      setCode: "LAW",
      collectorNumber: "700",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07320700_EN_Dogged_Pursuers_0f9192d556.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may pay 1 resource. If you do, deal 2 damage to a ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuDoggedPursuers;
