// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuGalenErsoDestroyingHisCreation = {
  title: "Galen Erso",
  subtitle: "Destroying His Creation",
  cost: 3,
  hp: 5,
  power: 0,
  text: "When Played: You may have an opponent take control of this unit.\nEnemy units gain Raid 1 and Saboteur.",
  unique: true,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "5574828561",
  rarity: "rare",
  aspects: ["cunning"],
  traits: ["imperial"],
  arena: "ground",
  keywords: ["raid", "saboteur"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 233,
  },
  setCodes: [
    {
      set: "LAW",
      number: 233,
    },
  ],
  internalName: "galen-erso#destroying-his-creation",
  cardType: "unit",
  canonicalId: "galen-erso#destroying-his-creation",
  slug: "galen-erso-destroying-his-creation",
  name: "Galen Erso",
  printings: [
    {
      id: "LAW_233",
      artId: "47217",
      setCode: "LAW",
      collectorNumber: "233",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07010233_EN_Galen_Erso_e9a5703f8f.png",
    },
    {
      id: "0157967650",
      artId: "47217",
      setCode: "LAW",
      collectorNumber: "497",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07020497_EN_Galen_Erso_5cd858d23d.png",
    },
    {
      id: "9607744635",
      artId: "47217",
      setCode: "LAW",
      collectorNumber: "735",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07320735_EN_Galen_Erso_2c496c932b.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
  ],
} satisfies SwuUnitCard;

export default swuGalenErsoDestroyingHisCreation;
