// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHiddenHunters = {
  title: "Hidden Hunters",
  cost: 4,
  hp: 5,
  power: 4,
  text: "Hidden (This unit can't be attacked if it was played this phase.)",
  unique: false,
  rules: "If a unit has Hidden and Sentinel at the same time, it can be attacked.\n",
  id: "3450378734",
  rarity: "common",
  aspects: ["command"],
  traits: ["bounty hunter"],
  arena: "ground",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 160,
  },
  setCodes: [
    {
      set: "LAW",
      number: 160,
    },
  ],
  internalName: "hidden-hunters",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuHiddenHunters;
