// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuHoundsToothHuntersApproach = {
  title: "Hound's Tooth",
  subtitle: "Hunters' Approach",
  cost: 7,
  hp: 8,
  power: 4,
  text: "When Attack Ends: If this unit survived, you may defeat a unit with less power than this unit.",
  unique: true,
  rules:
    'Abilities that refer to a card’s power include temporary modifiers.\n"When Attack Ends" abilities trigger at the same time the attacking unit deals combat damage. Hound’s Tooth must survive the attack in order to defeat a unit.\n',
  id: "8331101999",
  rarity: "rare",
  aspects: ["vigilance", "command", "villainy"],
  traits: ["underworld", "vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 33,
  },
  setCodes: [
    {
      set: "LAW",
      number: 33,
    },
  ],
  internalName: "hounds-tooth#hunters-approach",
  cardType: "unit",
  canonicalId: "hounds-tooth#hunters-approach",
  slug: "hounds-tooth-hunters-approach",
  name: "Hound's Tooth",
  printings: [
    {
      id: "LAW_033",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "33",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07010033_EN_Hound_s_Tooth_11550c2eea.png",
    },
    {
      id: "1255065599",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "297",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07020297_EN_Hound_s_Tooth_f0db09b3cb.png",
    },
    {
      id: "4306084711",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "535",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07320535_EN_Hound_s_Tooth_9c4c33b22e.png",
    },
    {
      id: "6503621782",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "788",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07060788_EN_Hounds_Tooth_Carb_A_4084c4c8a1.png",
    },
    {
      id: "2667251945",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "827",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07330827_EN_Hounds_Tooth_Carb_B_76f5f6e188.png",
    },
    {
      id: "4912265511",
      artId: "46217",
      setCode: "LAW",
      collectorNumber: "866",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07340866_EN_Hounds_Tooth_Carb_C_9df57c0972.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "When Attack Ends: If this unit survived, you may defeat a unit with less power than this unit.",
        optional: true,
        effects: [
          effect.defeat(
            target.unit({ controller: "any", power: { operator: "lt", value: 4 }, limit: 1 }),
          ),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuHoundsToothHuntersApproach;
