// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuK2soLockingTheVault = {
  title: "K-2SO",
  subtitle: "Locking the Vault",
  cost: 5,
  hp: 5,
  power: 3,
  text: "Ambush\nOn Attack: You may deal 3 damage to a damaged ground unit.",
  unique: true,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. The unit does not have to be ready in order to attack.\n",
  id: "6386443776",
  rarity: "rare",
  aspects: ["aggression", "cunning", "heroism"],
  traits: ["rebel", "droid"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 79,
  },
  setCodes: [
    {
      set: "LAW",
      number: 79,
    },
  ],
  internalName: "k2so#locking-the-vault",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
    {
      kind: "triggered",
      text: "On Attack: You may deal 3 damage to a damaged ground unit.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 3,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuK2soLockingTheVault;
