// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLandoCalrissianEyesOpen = {
  title: "Lando Calrissian",
  subtitle: "Eyes Open",
  cost: 5,
  hp: 5,
  power: 4,
  text: "Sentinel (Enemy units in this arena must attack a Sentinel when they attack you.)\nWhile this unit is defending, the attacker gets –1/–0.",
  unique: true,
  id: "2254545413",
  rarity: "special",
  aspects: ["vigilance", "heroism"],
  traits: ["rebel", "underworld"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 108,
  },
  setCodes: [
    {
      set: "LAW",
      number: 108,
    },
  ],
  internalName: "lando-calrissian#eyes-open",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuLandoCalrissianEyesOpen;
