// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLibertyDrawTheirFire = {
  title: "Liberty",
  subtitle: "Draw Their Fire!",
  cost: 8,
  hp: 7,
  power: 9,
  text: "Sentinel\nWhen Played/On Attack: Exhaust an enemy unit and return all upgrades on it that cost 4 or less to their owner's hands.",
  unique: true,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\n",
  id: "9963012140",
  rarity: "legendary",
  aspects: ["cunning", "heroism"],
  traits: ["rebel", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 224,
  },
  setCodes: [
    {
      set: "LAW",
      number: 224,
    },
  ],
  internalName: "liberty#draw-their-fire",
  cardType: "unit",
  canonicalId: "liberty#draw-their-fire",
  slug: "liberty-draw-their-fire",
  name: "Liberty",
  printings: [
    {
      id: "LAW_224",
      artId: "47172",
      setCode: "LAW",
      collectorNumber: "224",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07010224_EN_Liberty_f02471eb37.png",
    },
    {
      id: "9284282010",
      artId: "47172",
      setCode: "LAW",
      collectorNumber: "488",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07020488_EN_Liberty_cced27745d.png",
    },
    {
      id: "2297112364",
      artId: "47172",
      setCode: "LAW",
      collectorNumber: "726",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07320726_EN_Liberty_2346276b1f.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuLibertyDrawTheirFire;
