// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuLieutenantGornIDeserveWorse = {
  title: "Lieutenant Gorn",
  subtitle: "I Deserve Worse",
  cost: 3,
  hp: 4,
  power: 4,
  text: "On Attack: Take control of an enemy Credit token.",
  unique: true,
  id: "8232418666",
  rarity: "rare",
  aspects: ["cunning", "heroism"],
  traits: ["imperial", "rebel"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 221,
  },
  setCodes: [
    {
      set: "LAW",
      number: 221,
    },
  ],
  internalName: "lieutenant-gorn#i-deserve-worse",
  cardType: "unit",
  abilities: [
    ability.onAttack({
      text: "On Attack: Take control of an enemy Credit token.",
      effects: [effect.createToken("credit", 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuLieutenantGornIDeserveWorse;
