// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuMidRimSharpshooter = {
  title: "Mid Rim Sharpshooter",
  cost: 3,
  hp: 3,
  power: 3,
  text: "Saboteur (When this unit attacks, ignore Sentinel and defeat the defender's Shields.)\nWhen Played: You may pay 1 resource. If you do, an opponent discards a card from their hand.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "7157450235",
  rarity: "uncommon",
  aspects: ["aggression"],
  traits: ["underworld"],
  arena: "ground",
  keywords: ["saboteur"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 193,
  },
  setCodes: [
    {
      set: "LAW",
      number: 193,
    },
  ],
  internalName: "mid-rim-sharpshooter",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
    {
      kind: "triggered",
      text: "When Played: You may pay 1 resource. If you do, an opponent discards a card from their hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "discard",
              target: {
                type: "card",
                controller: "opponent",
                zones: ["hand"],
                limit: 1,
              },
              amount: 1,
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuMidRimSharpshooter;
