// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRuthlessDuo = {
  title: "Ruthless Duo",
  cost: 4,
  hp: 5,
  power: 3,
  text: "When Played: If you control another Villainy unit, you may deal 2 damage to a ground unit.",
  unique: false,
  id: "8509242087",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 137,
  },
  setCodes: [
    {
      set: "LAW",
      number: 137,
    },
  ],
  internalName: "ruthless-duo",
  cardType: "unit",
  canonicalId: "ruthless-duo",
  slug: "ruthless-duo",
  name: "Ruthless Duo",
  printings: [
    {
      id: "LAW_137",
      artId: "46737",
      setCode: "LAW",
      collectorNumber: "137",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07010137_EN_Ruthless_Duo_0a5394018c.png",
    },
    {
      id: "2198627063",
      artId: "46737",
      setCode: "LAW",
      collectorNumber: "401",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07020401_EN_Ruthless_Duo_beb2e7bdd7.png",
    },
    {
      id: "0506591989",
      artId: "46737",
      setCode: "LAW",
      collectorNumber: "639",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07320639_EN_Ruthless_Duo_1189668cb4.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: If you control another Villainy unit, you may deal 2 damage to a ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "conditional",
          condition: {
            type: "controlsAspect",
            controller: "friendly",
            aspect: "villainy",
          },
          ifTrue: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuRuthlessDuo;
