// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuScarifLieutenant = {
  title: "Scarif Lieutenant",
  cost: 1,
  hp: 1,
  power: 2,
  text: "When Defeated: Give an Experience token to a friendly Rebel unit.",
  unique: false,
  id: "7681849188",
  rarity: "uncommon",
  aspects: ["command", "heroism"],
  traits: ["rebel", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 142,
  },
  setCodes: [
    {
      set: "LAW",
      number: 142,
    },
  ],
  internalName: "scarif-lieutenant",
  cardType: "unit",
  canonicalId: "scarif-lieutenant",
  slug: "scarif-lieutenant",
  name: "Scarif Lieutenant",
  printings: [
    {
      id: "LAW_142",
      artId: "46762",
      setCode: "LAW",
      collectorNumber: "142",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07010142_EN_Scarif_Lieutenant_39f3cbb71e.png",
    },
    {
      id: "2530143071",
      artId: "46762",
      setCode: "LAW",
      collectorNumber: "406",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07020406_EN_Scarif_Lieutenant_19b9f92dbe.png",
    },
    {
      id: "9260157139",
      artId: "46762",
      setCode: "LAW",
      collectorNumber: "644",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07320644_EN_Scarif_Lieutenant_1095b1023e.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Defeated: Give an Experience token to a friendly Rebel unit.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "distribute",
          mode: "experience",
          amount: 1,
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuScarifLieutenant;
