// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSeasonedTracker = {
  title: "Seasoned Tracker",
  cost: 4,
  hp: 4,
  power: 4,
  text: "Hidden (This unit can't be attacked if it was played this phase.)",
  unique: false,
  rules: "If a unit has Hidden and Sentinel at the same time, it can be attacked.\n",
  id: "0246299753",
  rarity: "common",
  traits: ["bounty hunter"],
  arena: "ground",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 260,
  },
  setCodes: [
    {
      set: "LAW",
      number: 260,
    },
  ],
  internalName: "seasoned-tracker",
  cardType: "unit",
  canonicalId: "seasoned-tracker",
  slug: "seasoned-tracker",
  name: "Seasoned Tracker",
  printings: [
    {
      id: "LAW_260",
      artId: "47352",
      setCode: "LAW",
      collectorNumber: "260",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07010260_EN_Seasoned_Tracker_11d65c19de.png",
    },
    {
      id: "3502640514",
      artId: "47352",
      setCode: "LAW",
      collectorNumber: "524",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07020524_EN_Seasoned_Tracker_45ef581200.png",
    },
    {
      id: "9354942349",
      artId: "47352",
      setCode: "LAW",
      collectorNumber: "762",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//07320762_EN_Seasoned_Tracker_43c146c3cc.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuSeasonedTracker;
