// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuSebulbasPodracerTakingTheLead = {
  title: "Sebulba's Podracer",
  subtitle: "Taking the Lead",
  cost: 3,
  hp: 3,
  power: 3,
  text: "When you discard a card from your deck: You may ready this unit. Use this ability only once each round.",
  unique: true,
  id: "9969121799",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["vehicle", "speeder"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 176,
  },
  setCodes: [
    {
      set: "LAW",
      number: 176,
    },
  ],
  internalName: "sebulbas-podracer#taking-the-lead",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "when", name: "you discard a card from your deck" },
      {
        text: "When you discard a card from your deck: You may ready this unit. Use this ability only once each round.",
        effects: [effect.optional([effect.ready(target.self())])],
        limit: "oncePerRound",
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuSebulbasPodracerTakingTheLead;
