// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheMandalorianLetsSeeThePuck = {
  title: "The Mandalorian",
  subtitle: "Let's See the Puck",
  cost: 6,
  hp: 5,
  power: 6,
  text: "When Played: Draw a card.\nWhen you draw 1 or more cards during the action phase: Give a Shield token to this unit.",
  unique: true,
  id: "7505293719",
  rarity: "legendary",
  aspects: ["vigilance", "aggression"],
  traits: ["mandalorian", "bounty hunter"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 52,
  },
  setCodes: [
    {
      set: "LAW",
      number: 52,
    },
  ],
  internalName: "the-mandalorian#lets-see-the-puck",
  cardType: "unit",
  canonicalId: "the-mandalorian#lets-see-the-puck",
  slug: "the-mandalorian-lets-see-the-puck",
  name: "The Mandalorian",
  printings: [
    {
      id: "LAW_052",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "52",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07010052_EN_The_Mandalorian_6f8dd46b91.png",
    },
    {
      id: "5537715540",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "316",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07020316_EN_The_Mandalorian_811d038cc4.png",
    },
    {
      id: "9971914337",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "554",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//07320554_EN_The_Mandalorian_32598ebec7.png",
    },
    {
      id: "7354277978",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "816",
      rarity: "legendary",
      imageUrl:
        "https://cdn.starwarsunlimited.com//07060816_EN_The_Mandalorian_Carb_A_997ad5d02d.png",
    },
    {
      id: "1407953277",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "855",
      rarity: "legendary",
      imageUrl:
        "https://cdn.starwarsunlimited.com//07330855_EN_The_Mandalorian_Carb_B_7ae5938fe6.png",
    },
    {
      id: "0558251251",
      artId: "46312",
      setCode: "LAW",
      collectorNumber: "894",
      rarity: "legendary",
      imageUrl:
        "https://cdn.starwarsunlimited.com//07340894_EN_The_Mandalorian_Carb_C_3c3f1ebd5a.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Draw a card.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "draw",
          controller: "friendly",
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuTheMandalorianLetsSeeThePuck;
