// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheMasterCodebreakerHighStakes = {
  title: "The Master Codebreaker",
  subtitle: "High Stakes",
  cost: 2,
  hp: 4,
  power: 1,
  text: "The first Gambit card you play each round costs 1 resource less.\nWhen Played: Search the top 8 cards of your deck for a Gambit card, reveal it, and draw it.",
  unique: true,
  rules:
    "After searching, put any cards not chosen on the bottom of your deck in a random order.\n",
  id: "4763371184",
  rarity: "rare",
  aspects: ["cunning"],
  traits: ["underworld"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 229,
  },
  setCodes: [
    {
      set: "LAW",
      number: 229,
    },
  ],
  internalName: "the-master-codebreaker#high-stakes",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Search the top 8 cards of your deck for a Gambit card, reveal it, and draw it.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "search",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          destination: "hand",
          reveal: true,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuTheMasterCodebreakerHighStakes;
