// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuValItsBeenARideBabe = {
  title: "Val",
  subtitle: "It's Been a Ride, Babe",
  cost: 2,
  hp: 4,
  power: 2,
  text: "When Played: Give a Shield token to another friendly unit.\nWhen Defeated: Give a Shield token to an enemy unit.",
  unique: true,
  id: "3075365866",
  rarity: "uncommon",
  aspects: ["cunning", "vigilance"],
  traits: ["underworld"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 91,
  },
  setCodes: [
    {
      set: "LAW",
      number: 91,
    },
  ],
  internalName: "val#its-been-a-ride-babe",
  cardType: "unit",
  canonicalId: "val#its-been-a-ride-babe",
  slug: "val-its-been-a-ride-babe",
  name: "Val",
  printings: [
    {
      id: "LAW_091",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "91",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07010091_EN_Val_0af481de02.png",
    },
    {
      id: "5137260473",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "355",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07020355_EN_Val_c0308b541e.png",
    },
    {
      id: "3971496922",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "593",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07320593_EN_Val_81c98cdc8a.png",
    },
    {
      id: "3318922389",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "791",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07060791_EN_Val_Carb_A_9dd3a4c2cb.png",
    },
    {
      id: "0909797207",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "830",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07330830_EN_Val_Carb_B_42e3477ff3.png",
    },
    {
      id: "1569948447",
      artId: "46507",
      setCode: "LAW",
      collectorNumber: "869",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//07340869_EN_Val_Carb_C_d6251bbafa.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Give a Shield token to another friendly unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "shield",
          amount: 1,
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: true,
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "When Defeated: Give a Shield token to an enemy unit.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "createToken",
          token: "shield",
          amount: 1,
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuValItsBeenARideBabe;
