// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuVermillionQirasAuctionHouse = {
  title: "Vermillion",
  subtitle: "Qi'ra's Auction House",
  cost: 6,
  hp: 7,
  power: 5,
  text: "When Attack Ends: If this unit survived, reveal the top card of a deck, then choose a player. They may play the revealed card for free. If they do, a different player creates Credit tokens equal to that card's cost.",
  unique: true,
  rules:
    'Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\n"When Attack Ends" abilities trigger at the same time the attacking unit deals combat damage.\n"Play for free" ignores all resource costs, including aspect penalties, but not other additional costs.\nThe chosen player may choose not to play the revealed card.\n',
  id: "8437499257",
  rarity: "rare",
  aspects: ["cunning", "villainy"],
  traits: ["underworld", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LAW",
    number: 215,
  },
  setCodes: [
    {
      set: "LAW",
      number: 215,
    },
  ],
  internalName: "vermillion#qiras-auction-house",
  cardType: "unit",
  canonicalId: "vermillion#qiras-auction-house",
  slug: "vermillion-qiras-auction-house",
  name: "Vermillion",
  printings: [
    {
      id: "LAW_215",
      artId: "47127",
      setCode: "LAW",
      collectorNumber: "215",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07010215_EN_Vermillion_624b650a28.png",
    },
    {
      id: "1376342764",
      artId: "47127",
      setCode: "LAW",
      collectorNumber: "479",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07020479_EN_Vermillion_05eb18afb9.png",
    },
    {
      id: "9609653607",
      artId: "47127",
      setCode: "LAW",
      collectorNumber: "717",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07320717_EN_Vermillion_c2ca192841.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "When Attack Ends: If this unit survived, reveal the top card of a deck, then choose a player. They may play the revealed card for free. If they do, a different player creates Credit tokens equal to that card's cost.",
        effects: [
          effect.reveal(target.card({ controller: "friendly", zones: ["deck"], limit: 1 })),
          effect.ifYouDo(
            effect.play(target.card({ controller: "friendly", zones: ["deck"], limit: 1 }), true),
            [effect.createToken("credit", 1, target.player("opponent"))],
          ),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuVermillionQirasAuctionHouse;
