// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuMaceWindusLightsaber = {
  title: "Mace Windu's Lightsaber",
  cost: 2,
  text: "Attach to a non-Vehicle unit.\nWhen Played: If attached unit is Mace Windu, draw 2 cards.",
  unique: true,
  upgradePower: 2,
  upgradeHp: 2,
  id: "6410481716",
  rarity: "rare",
  aspects: ["aggression", "heroism"],
  traits: ["item", "weapon", "lightsaber"],
  types: ["upgrade"],
  setId: {
    set: "TWI",
    number: 152,
  },
  setCodes: [
    {
      set: "TWI",
      number: 152,
    },
  ],
  internalName: "mace-windus-lightsaber",
  cardType: "upgrade",
  canonicalId: "mace-windus-lightsaber",
  slug: "mace-windus-lightsaber",
  name: "Mace Windu's Lightsaber",
  printings: [
    {
      id: "TWI_152",
      artId: "15561",
      setCode: "TWI",
      collectorNumber: "152",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0301152_EN_Mace_Windu_s_Lightsaber_ea382e1a81.png",
    },
    {
      id: "4944265913",
      artId: "15561",
      setCode: "TWI",
      collectorNumber: "152",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0331152_EN_Mace_Windu_s_Lightsaber_53e4bba7b0.png",
    },
    {
      id: "0252008083",
      artId: "15561",
      setCode: "TWI",
      collectorNumber: "419",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0332419_EN_Mace_Windu_s_Lightsaber_62142fd26f.png",
    },
    {
      id: "4669485230",
      artId: "15561",
      setCode: "TWI",
      collectorNumber: "419",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0302419_EN_Mace_Windu_s_Lightsaber_e929cd1c62.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "Attach to a non-Vehicle unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuMaceWindusLightsaber;
