// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuStrategicAcumen = {
  title: "Strategic Acumen",
  cost: 1,
  text: "Attached unit gains: “Action [Exhaust]: Play a unit from your hand. It costs 1 resource less.”",
  unique: false,
  upgradePower: 0,
  upgradeHp: 2,
  id: "2397845395",
  rarity: "common",
  aspects: ["command"],
  traits: ["learned"],
  types: ["upgrade"],
  setId: {
    set: "TWI",
    number: 120,
  },
  setCodes: [
    {
      set: "TWI",
      number: 120,
    },
  ],
  internalName: "strategic-acumen",
  cardType: "upgrade",
  canonicalId: "strategic-acumen",
  slug: "strategic-acumen",
  name: "Strategic Acumen",
  printings: [
    {
      id: "TWI_120",
      artId: "15546",
      setCode: "TWI",
      collectorNumber: "120",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301120_EN_Strategic_Acumen_dd76e616e7.png",
    },
    {
      id: "6881323827",
      artId: "15546",
      setCode: "TWI",
      collectorNumber: "120",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0331120_EN_Strategic_Acumen_ec4e09dd9d.png",
    },
    {
      id: "3799916920",
      artId: "15546",
      setCode: "TWI",
      collectorNumber: "390",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0332390_EN_Strategic_Acumen_a82de11ee3.png",
    },
    {
      id: "6533023508",
      artId: "15546",
      setCode: "TWI",
      collectorNumber: "390",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302390_EN_Strategic_Acumen_f07d8c8223.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Attached unit gains: “Action [Exhaust]: Play a unit from your hand. It costs 1 resource less.”",
      costs: [{ type: "exhaust", target: target.attachedUnit() }],
      effects: [effect.play(target.unit({ controller: "friendly", zones: ["hand"], limit: 1 }))],
    }),
  ],
} satisfies SwuUpgradeCard;

export default swuStrategicAcumen;
