// Generated by tools/import-card-data. Do not edit manually.
import type { SwuTokenCard } from "@tcg/star-wars-unlimited-types";

export const swuMandalorian = {
  title: "Mandalorian",
  cost: 0,
  hp: 2,
  power: 2,
  text: "Shielded (When you create this token, give a Shield token to it.)",
  unique: false,
  id: "8192010342",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["mandalorian"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["token", "unit"],
  setId: {
    set: "ASH",
  },
  internalName: "mandalorian",
  cardType: "token",
  canonicalId: "mandalorian",
  slug: "mandalorian",
  name: "Mandalorian",
  printings: [
    {
      id: "8192010342",
      artId: "53004",
      setCode: "ASH",
      collectorNumber: "",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//08010_T01_EN_Mandalorian_4b02b31511.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuTokenCard;

export default swuMandalorian;
