import type { CardEffect, CommandCard } from "@tcg/gundam-types";

export const st05UnforeseenIncident014: CommandCard = {
  cardNumber: "ST01-014-p4",
  name: "Unforeseen Incident",
  type: "command",
  color: "white",
  traits: ["-"],
  id: "ST01-014_p4",
  externalId: "gundam:st01-014_p4",
  slug: "unforeseen-incident-st01-014-p4",
  displayName: "Unforeseen Incident",
  set: { code: "ST05", name: "Iron Bloom [ST05]", packageId: "616005" },
  printNumber: "ST01-014_p4",
  printings: [
    {
      id: "ST01-014",
      collectorNumber: "ST01-014",
      cardNumber: "ST01-014",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-014_p1",
      collectorNumber: "ST01-014_p1",
      cardNumber: "ST01-014",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-014_p2",
      collectorNumber: "ST01-014_p2",
      cardNumber: "ST01-014",
      set: {
        code: "ST01",
        name: "Store Tournament Participant Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p2.webp?260424",
      productName: "Store Tournament Participant Pack 01",
    },
    {
      id: "ST01-014_p3",
      collectorNumber: "ST01-014_p3",
      cardNumber: "ST01-014",
      set: {
        code: "ST01",
        name: "Store Tournament Winner Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p3.webp?260424",
      productName: "Store Tournament Winner Pack 01",
    },
    {
      id: "ST01-014_p4",
      collectorNumber: "ST01-014_p4",
      cardNumber: "ST01-014",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05]",
        packageId: "616005",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p4.webp?260424",
      productName: "Iron Bloom [ST05]",
    },
    {
      id: "ST01-014_p5",
      collectorNumber: "ST01-014_p5",
      cardNumber: "ST01-014",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05] Bonus Pack",
        packageId: "616005",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p5.webp?260424",
      productName: "Iron Bloom [ST05] Bonus Pack",
    },
    {
      id: "ST01-014_p6",
      collectorNumber: "ST01-014_p6",
      cardNumber: "ST01-014",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p6.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
    {
      id: "ST01-014_p7",
      collectorNumber: "ST01-014_p7",
      cardNumber: "ST01-014",
      set: {
        code: "ST01",
        name: "Events",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p7.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p7.webp?260424",
      productName: "Events",
    },
  ],
  selectedPrintingId: "ST01-014_p4",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-014_p4.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-014_p4.webp?260424",
  legality: "legal",
  level: 3,
  cost: 1,
  effect:
    "【Burst】Activate this card's 【Main】.<br>【Main】/【Action】Choose 1 enemy Unit. It gets AP-3 during this turn.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["burst"],
      },
      directives: [
        {
          action: {
            action: "activateTiming",
            timing: "main",
          },
        },
      ],
      sourceText: "【Burst】Activate this card's 【Main】.",
    },
    {
      type: "command",
      activation: {
        timing: ["main", "action"],
      },
      directives: [
        {
          action: {
            action: "statModifier",
            stat: "ap",
            amount: -3,
            duration: "thisTurn",
            target: {
              owner: "opponent",
              cardType: "unit",
              count: 1,
            },
          },
        },
      ],
      sourceText: "【Main】/【Action】Choose 1 enemy Unit. It gets AP-3 during this turn.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
