import type { UnitCard } from "@tcg/gundam-types";

export const gd01Gundam013: UnitCard = {
  cardNumber: "GD01-013",
  name: "Gundam",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "GD01-013",
  externalId: "gundam:gd01-013",
  slug: "gundam-gd01-013",
  displayName: "Gundam",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-013",
  printings: [
    {
      id: "GD01-013",
      collectorNumber: "GD01-013",
      cardNumber: "GD01-013",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-013.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-013.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-013_p1",
      collectorNumber: "GD01-013_p1",
      cardNumber: "GD01-013",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-013_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-013_p1.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "GD01-013_p2",
      collectorNumber: "GD01-013_p2",
      cardNumber: "GD01-013",
      set: {
        code: "GD01",
        name: "Launch Kit 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-013_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-013_p2.webp?260424",
      productName: "Launch Kit 01",
    },
    {
      id: "GD01-013_p3",
      collectorNumber: "GD01-013_p3",
      cardNumber: "GD01-013",
      set: {
        code: "GD01",
        name: "WORLD CHAMPIONSHIPS 26-27 Participation Pack 26-27 Vol.1",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-013_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-013_p3.webp?260424",
      productName: "WORLD CHAMPIONSHIPS 26-27 Participation Pack 26-27 Vol.1",
    },
  ],
  selectedPrintingId: "GD01-013",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-013.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-013.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
