import type { UnitCard } from "@tcg/gundam-types";

export const gd01Pisces021: UnitCard = {
  cardNumber: "GD01-021",
  name: "Pisces",
  type: "unit",
  color: "blue",
  traits: ["oz"],
  id: "GD01-021",
  externalId: "gundam:gd01-021",
  slug: "pisces-gd01-021",
  displayName: "Pisces",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-021",
  printings: [
    {
      id: "GD01-021",
      collectorNumber: "GD01-021",
      cardNumber: "GD01-021",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-021.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-021.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-021",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-021.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-021.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
