import type { UnitCard } from "@tcg/gundam-types";

export const gd01Zaku035: UnitCard = {
  cardNumber: "GD01-035",
  name: "Zaku Ⅱ",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD01-035",
  externalId: "gundam:gd01-035",
  slug: "zaku-gd01-035",
  displayName: "Zaku Ⅱ",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-035",
  printings: [
    {
      id: "GD01-035",
      collectorNumber: "GD01-035",
      cardNumber: "GD01-035",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-035.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-035.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-035",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-035.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-035.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
