import type { UnitCard } from "@tcg/gundam-types";

export const gd01Zaku035: UnitCard = {
  cardNumber: "GD01-035",
  name: "Zaku Ⅱ",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "green",
  traits: ["zeon"],
  id: "GD01-035",
  canonicalId: "GD01-035",
  externalIds: { bandai: "gundam:gd01-035" },
  slug: "zaku-gd01-035",
  displayName: "Zaku Ⅱ",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-035",
  printings: [
    {
      id: "GD01-035",
      artId: "GD01-035",
      setCode: "GD01",
      collectorNumber: "GD01-035",
      cardNumber: "GD01-035",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-035.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-035.webp?260715",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-035_p1",
      artId: "GD01-035_p1",
      setCode: "SC01",
      collectorNumber: "GD01-035_p1",
      cardNumber: "GD01-035",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-035_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-035_p1.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["GD01-035", "GD01-035_p1"],
  selectedPrintingId: "GD01-035",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-035.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-035.webp?260715",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
