import type { UnitCard } from "@tcg/gundam-types";

export const gd01Gogg037: UnitCard = {
  cardNumber: "GD01-037",
  name: "Gogg",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD01-037",
  externalId: "gundam:gd01-037",
  slug: "gogg-gd01-037",
  displayName: "Gogg",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-037",
  printings: [
    {
      id: "GD01-037",
      collectorNumber: "GD01-037",
      cardNumber: "GD01-037",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-037.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-037.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-037",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-037.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-037.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
