import type { UnitCard } from "@tcg/gundam-types";

export const gd01WingGundam040: UnitCard = {
  cardNumber: "GD01-040",
  name: "Wing Gundam",
  type: "unit",
  color: "green",
  traits: ["operation meteor"],
  id: "GD01-040",
  externalId: "gundam:gd01-040",
  slug: "wing-gundam-gd01-040",
  displayName: "Wing Gundam",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-040",
  printings: [
    {
      id: "GD01-040",
      collectorNumber: "GD01-040",
      cardNumber: "GD01-040",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-040.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-040.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-040_p1",
      collectorNumber: "GD01-040_p1",
      cardNumber: "GD01-040",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/GD01-040_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-040_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "GD01-040",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-040.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-040.webp?260424",
  legality: "legal",
  level: 5,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
