import type { UnitCard } from "@tcg/gundam-types";

export const gd01Kshatriya051: UnitCard = {
  cardNumber: "GD01-051",
  name: "Kshatriya",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "GD01-051",
  externalId: "gundam:gd01-051",
  slug: "kshatriya-gd01-051",
  displayName: "Kshatriya",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-051",
  printings: [
    {
      id: "GD01-051",
      collectorNumber: "GD01-051",
      cardNumber: "GD01-051",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-051.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-051.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-051_p1",
      collectorNumber: "GD01-051_p1",
      cardNumber: "GD01-051",
      set: {
        code: "GD01",
        name: "Store Tournament Participant Pack 01",
        packageId: "616901",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-051_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-051_p1.webp?260424",
      productName: "Store Tournament Participant Pack 01",
    },
    {
      id: "GD01-051_p2",
      collectorNumber: "GD01-051_p2",
      cardNumber: "GD01-051",
      set: {
        code: "GD01",
        name: "Store Tournament Winner Pack 01",
        packageId: "616901",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-051_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-051_p2.webp?260424",
      productName: "Store Tournament Winner Pack 01",
    },
  ],
  selectedPrintingId: "GD01-051",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-051.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-051.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
