import type { UnitCard } from "@tcg/gundam-types";

export const gd01DreissenSleeves057: UnitCard = {
  cardNumber: "GD01-057",
  name: "Dreissen (Sleeves)",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "GD01-057",
  externalId: "gundam:gd01-057",
  slug: "dreissen-sleeves-gd01-057",
  displayName: "Dreissen (Sleeves)",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-057",
  printings: [
    {
      id: "GD01-057",
      collectorNumber: "GD01-057",
      cardNumber: "GD01-057",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-057.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-057.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-057",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-057.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-057.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
