import type { UnitCard } from "@tcg/gundam-types";

export const gd01ZakuMariner060: UnitCard = {
  cardNumber: "GD01-060",
  name: "Zaku Mariner",
  type: "unit",
  color: "red",
  traits: ["zeon"],
  id: "GD01-060",
  externalId: "gundam:gd01-060",
  slug: "zaku-mariner-gd01-060",
  displayName: "Zaku Mariner",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-060",
  printings: [
    {
      id: "GD01-060",
      collectorNumber: "GD01-060",
      cardNumber: "GD01-060",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-060.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-060.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-060",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-060.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-060.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
