import type { UnitCard } from "@tcg/gundam-types";

export const gd01Dinn064: UnitCard = {
  cardNumber: "GD01-064",
  name: "DINN",
  type: "unit",
  color: "red",
  traits: ["zaft"],
  id: "GD01-064",
  externalId: "gundam:gd01-064",
  slug: "dinn-gd01-064",
  displayName: "DINN",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-064",
  printings: [
    {
      id: "GD01-064",
      collectorNumber: "GD01-064",
      cardNumber: "GD01-064",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-064.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-064.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-064",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-064.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-064.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
