import type { UnitCard } from "@tcg/gundam-types";

export const gd01LauncherStrikeGundam072: UnitCard = {
  cardNumber: "GD01-072",
  name: "Launcher Strike Gundam",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "white",
  traits: ["earth alliance"],
  id: "GD01-072",
  canonicalId: "GD01-072",
  externalIds: { bandai: "gundam:gd01-072" },
  slug: "launcher-strike-gundam/gd01-072",
  displayName: "Launcher Strike Gundam",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-072",
  printings: [
    {
      id: "GD01-072",
      artId: "GD01-072",
      setCode: "GD01",
      collectorNumber: "GD01-072",
      cardNumber: "GD01-072",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-072.webp",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-072_p1",
      artId: "GD01-072_p1",
      setCode: "BETA",
      collectorNumber: "GD01-072_p1",
      cardNumber: "GD01-072",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "uncommon",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/beta/GD01-072_p1.webp",
      productName: "Edition Beta",
    },
  ],
  reprints: ["GD01-072", "GD01-072_p1"],
  selectedPrintingId: "GD01-072",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-072.webp",
  legality: "legal",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  linkCondition: "(Earth Alliance) Trait",
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
