import type { UnitCard } from "@tcg/gundam-types";

export const gd01BeguirPente084: UnitCard = {
  cardNumber: "GD01-084",
  name: "Beguir-Pente",
  type: "unit",
  color: "white",
  traits: ["academy"],
  id: "GD01-084",
  externalId: "gundam:gd01-084",
  slug: "beguir-pente-gd01-084",
  displayName: "Beguir-Pente",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-084",
  printings: [
    {
      id: "GD01-084",
      collectorNumber: "GD01-084",
      cardNumber: "GD01-084",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-084.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-084.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
  ],
  selectedPrintingId: "GD01-084",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-084.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-084.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
