import type { UnitCard } from "@tcg/gundam-types";

export const gd01GundamLfrith086: UnitCard = {
  cardNumber: "GD01-086",
  name: "Gundam Lfrith",
  type: "unit",
  battlefieldZones: ["space", "earth"],
  color: "white",
  traits: ["vanadis institute"],
  id: "GD01-086",
  canonicalId: "GD01-086",
  externalIds: { bandai: "gundam:gd01-086" },
  slug: "gundam-lfrith-gd01-086",
  displayName: "Gundam Lfrith",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-086",
  printings: [
    {
      id: "GD01-086",
      artId: "GD01-086",
      setCode: "GD01",
      collectorNumber: "GD01-086",
      cardNumber: "GD01-086",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-086.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-086.webp?260715",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-086_p1",
      artId: "GD01-086_p1",
      setCode: "GD01",
      collectorNumber: "GD01-086_p1",
      cardNumber: "GD01-086",
      set: {
        code: "GD01",
        name: "Championship Participation Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-086_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-086_p1.webp?260715",
      productName: "Championship Participation Pack 01",
    },
    {
      id: "GD01-086_p2",
      artId: "GD01-086_p2",
      setCode: "EVX05",
      collectorNumber: "GD01-086_p2",
      cardNumber: "GD01-086",
      set: {
        code: "EVX05",
        name: "Premium Card Collection [EVX05]",
        packageId: "616701",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-086_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-086_p2.webp?260715",
      productName: "Premium Card Collection [EVX05]",
    },
    {
      id: "GD01-086_p3",
      artId: "GD01-086_p3",
      setCode: "SC01",
      collectorNumber: "GD01-086_p3",
      cardNumber: "GD01-086",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-086_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-086_p3.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["GD01-086", "GD01-086_p1", "GD01-086_p2", "GD01-086_p3"],
  selectedPrintingId: "GD01-086",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd01/GD01-086.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-086.webp?260715",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 4,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
