// This file is generated by @tcg/cyberpunk-parser. Do not edit manually.
// Seeded from the scraped catalog text; future generator versions will
// preserve hand-authored non-en locales alongside the en seed.
import type { CyberpunkCardLocale, CyberpunkLocale } from "@tcg/cyberpunk-types";

export const theHeistRetailStarterDeckVCorporateExileI18n: Record<
  CyberpunkLocale,
  CyberpunkCardLocale
> = {
  en: {
    name: "V",
    subname: "Corporate Exile",
    displayName: "V: Corporate Exile",
    rulesText:
      "{Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. When it leaves the field, remove it from the game.)",
  },
};
