import type { UnitCard } from "@tcg/gundam-types";

export const eb01GundamTr1HazelRah007: UnitCard = {
  cardNumber: "EB01-007",
  name: 'Gundam TR-1 "Hazel-Rah"',
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "EB01-007",
  canonicalId: "EB01-007",
  externalIds: { bandai: "gundam:eb01-007" },
  slug: "gundam-tr-1-hazel-rah-eb01-007",
  displayName: 'Gundam TR-1 "Hazel-Rah"',
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-007",
  printings: [
    {
      id: "EB01-007",
      artId: "EB01-007",
      setCode: "EB01",
      collectorNumber: "EB01-007",
      cardNumber: "EB01-007",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-007.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-007",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-007.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "(Attack) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
