import type { UnitCard } from "@tcg/gundam-types";

export const eb01DomBeinNichts012: UnitCard = {
  cardNumber: "EB01-012",
  name: "Dom Bein Nichts",
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "EB01-012",
  canonicalId: "EB01-012",
  externalIds: { bandai: "gundam:eb01-012" },
  slug: "dom-bein-nichts-eb01-012",
  displayName: "Dom Bein Nichts",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-012",
  printings: [
    {
      id: "EB01-012",
      artId: "EB01-012",
      setCode: "EB01",
      collectorNumber: "EB01-012",
      cardNumber: "EB01-012",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-012.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-012",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-012.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  linkCondition: "(Support) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
