import type { UnitCard } from "@tcg/gundam-types";

export const eb01TornadoGundam016: UnitCard = {
  cardNumber: "EB01-016",
  name: "Tornado Gundam",
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "EB01-016",
  canonicalId: "EB01-016",
  externalIds: { bandai: "gundam:eb01-016" },
  slug: "tornado-gundam-eb01-016",
  displayName: "Tornado Gundam",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-016",
  printings: [
    {
      id: "EB01-016",
      artId: "EB01-016",
      setCode: "EB01",
      collectorNumber: "EB01-016",
      cardNumber: "EB01-016",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-016.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-016",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-016.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "(G Generation) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
