import type { UnitCard } from "@tcg/gundam-types";

export const eb01GundamAstarothOrigin026: UnitCard = {
  cardNumber: "EB01-026",
  name: "Gundam Astaroth Origin",
  type: "unit",
  color: "green",
  traits: ["g generation"],
  id: "EB01-026",
  canonicalId: "EB01-026",
  externalIds: { bandai: "gundam:eb01-026" },
  slug: "gundam-astaroth-origin-eb01-026",
  displayName: "Gundam Astaroth Origin",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-026",
  printings: [
    {
      id: "EB01-026",
      artId: "EB01-026",
      setCode: "EB01",
      collectorNumber: "EB01-026",
      cardNumber: "EB01-026",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-026.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-026",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-026.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Durability) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
