import type { UnitCard } from "@tcg/gundam-types";

export const eb01GundamEz8HighMobilityCustom032: UnitCard = {
  cardNumber: "EB01-032",
  name: "Gundam Ez8 High Mobility Custom",
  type: "unit",
  color: "green",
  traits: ["g generation"],
  id: "EB01-032",
  canonicalId: "EB01-032",
  externalIds: { bandai: "gundam:eb01-032" },
  slug: "gundam-ez8-high-mobility-custom-eb01-032",
  displayName: "Gundam Ez8 High Mobility Custom",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-032",
  printings: [
    {
      id: "EB01-032",
      artId: "EB01-032",
      setCode: "EB01",
      collectorNumber: "EB01-032",
      cardNumber: "EB01-032",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-032.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-032",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-032.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 3,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
