import type { UnitCard } from "@tcg/gundam-types";

export const eb01SGundam048: UnitCard = {
  cardNumber: "EB01-048",
  name: "S Gundam",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "EB01-048",
  canonicalId: "EB01-048",
  externalIds: { bandai: "gundam:eb01-048" },
  slug: "s-gundam-eb01-048",
  displayName: "S Gundam",
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-048",
  printings: [
    {
      id: "EB01-048",
      artId: "EB01-048",
      setCode: "EB01",
      collectorNumber: "EB01-048",
      cardNumber: "EB01-048",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-048.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-048",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-048.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 4,
  cost: 3,
  ap: 4,
  hp: 3,
  linkCondition: "(Attack) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
