import type { UnitCard } from "@tcg/gundam-types";

export const eb01ZeGok051: UnitCard = {
  cardNumber: "EB01-051",
  name: "Ze'Gok",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "EB01-051",
  canonicalId: "EB01-051",
  externalIds: { bandai: "gundam:eb01-051" },
  slug: "ze-gok-eb01-051",
  displayName: "Ze'Gok",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-051",
  printings: [
    {
      id: "EB01-051",
      artId: "EB01-051",
      setCode: "EB01",
      collectorNumber: "EB01-051",
      cardNumber: "EB01-051",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-051.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-051",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-051.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
