import type { UnitCard } from "@tcg/gundam-types";

export const eb01GundamGp00053: UnitCard = {
  cardNumber: "EB01-053",
  name: "Gundam GP00",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "EB01-053",
  canonicalId: "EB01-053",
  externalIds: { bandai: "gundam:eb01-053" },
  slug: "gundam-gp00-eb01-053",
  displayName: "Gundam GP00",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-053",
  printings: [
    {
      id: "EB01-053",
      artId: "EB01-053",
      setCode: "EB01",
      collectorNumber: "EB01-053",
      cardNumber: "EB01-053",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-053.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-053",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-053.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
