import type { UnitCard } from "@tcg/gundam-types";

export const eb01GaplantTr5HrairooUnit1054: UnitCard = {
  cardNumber: "EB01-054",
  name: 'Gaplant TR-5 "Hrairoo" Unit 1',
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "EB01-054",
  canonicalId: "EB01-054",
  externalIds: { bandai: "gundam:eb01-054" },
  slug: "gaplant-tr-5-hrairoo-unit-1-eb01-054",
  displayName: 'Gaplant TR-5 "Hrairoo" Unit 1',
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-054",
  printings: [
    {
      id: "EB01-054",
      artId: "EB01-054",
      setCode: "EB01",
      collectorNumber: "EB01-054",
      cardNumber: "EB01-054",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-054.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-054",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-054.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
