import type { UnitCard } from "@tcg/gundam-types";

export const eb01GundamGeminass01056: UnitCard = {
  cardNumber: "EB01-056",
  name: "Gundam Geminass 01",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "EB01-056",
  canonicalId: "EB01-056",
  externalIds: { bandai: "gundam:eb01-056" },
  slug: "gundam-geminass-01-eb01-056",
  displayName: "Gundam Geminass 01",
  rulesText: "-",
  set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
  printNumber: "EB01-056",
  printings: [
    {
      id: "EB01-056",
      artId: "EB01-056",
      setCode: "EB01",
      collectorNumber: "EB01-056",
      cardNumber: "EB01-056",
      set: { code: "EB01", name: "Eternal Nexus [EB01]", packageId: "616201" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-056.webp",
      productName: "Eternal Nexus [EB01]",
    },
  ],
  selectedPrintingId: "EB01-056",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/eb01/EB01-056.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 3,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
