// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAdeptArc170 = {
  title: "Adept ARC-170",
  cost: 4,
  hp: 4,
  power: 3,
  text: "Restore 2 (When this unit attacks, heal 2 damage from your base.)",
  unique: false,
  id: "7500360419",
  rarity: "common",
  aspects: ["command"],
  traits: ["republic", "vehicle", "fighter"],
  arena: "space",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 114,
  },
  setCodes: [
    {
      set: "JTL",
      number: 114,
    },
  ],
  internalName: "adept-arc170",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuAdeptArc170;
