// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuBobaFettFearedBountyHunter = {
  title: "Boba Fett",
  subtitle: "Feared Bounty Hunter",
  cost: 5,
  hp: 4,
  power: 5,
  text: "Shielded",
  unique: true,
  rules:
    'Pilots are considered units while not in play. If you use a "play a unit" ability, you may only play a Pilot as a unit. If you use a "play an upgrade" ability, you may only play a Pilot as an upgrade. If you use a "play a card" ability, you may do either.\n',
  upgradePower: 2,
  upgradeHp: 3,
  id: "7700932371",
  rarity: "rare",
  aspects: ["cunning", "villainy"],
  traits: ["underworld", "bounty hunter", "pilot"],
  arena: "ground",
  keywords: ["shielded", "piloting"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 189,
  },
  setCodes: [
    {
      set: "JTL",
      number: 189,
    },
  ],
  pilotText:
    "Piloting [2 resources Cunning Villainy] \nWhen played as an upgrade: You may deal 1 damage to a unit. If attached unit is a Transport, you may deal 2 damage instead.",
  internalName: "boba-fett#feared-bounty-hunter",
  cardType: "unit",
  canonicalId: "boba-fett#feared-bounty-hunter",
  slug: "boba-fett-feared-bounty-hunter",
  name: "Boba Fett",
  printings: [
    {
      id: "JTL_189",
      artId: "20416",
      setCode: "JTL",
      collectorNumber: "189",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04010189_EN_Boba_Fett_fe053f2a7c.png",
    },
    {
      id: "9258914604",
      artId: "20416",
      setCode: "JTL",
      collectorNumber: "451",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04020451_EN_Boba_Fett_35948cd855.png",
    },
    {
      id: "3138164440",
      artId: "20416",
      setCode: "JTL",
      collectorNumber: "687",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04310687_EN_Boba_Fett_47f17a2dbd.png",
    },
    {
      id: "3996952268",
      artId: "20416",
      setCode: "JTL",
      collectorNumber: "923",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04320923_EN_Boba_Fett_ee4f1a6999.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
    {
      kind: "keyword",
      text: "Piloting",
      keyword: "piloting",
    },
  ],
} satisfies SwuUnitCard;

export default swuBobaFettFearedBountyHunter;
