// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuClonePilot = {
  title: "Clone Pilot",
  cost: 2,
  hp: 2,
  power: 2,
  unique: false,
  rules:
    'Pilots are considered units while not in play. If you use a "play a unit" ability, you may only play a Pilot as a unit. If you use a "play an upgrade" ability, you may only play a Pilot as an upgrade. If you use a "play a card" ability, you may do either.\n',
  upgradePower: 2,
  upgradeHp: 2,
  id: "3261127126",
  rarity: "common",
  aspects: ["command"],
  traits: ["republic", "clone", "pilot"],
  arena: "ground",
  keywords: ["piloting"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 108,
  },
  setCodes: [
    {
      set: "JTL",
      number: 108,
    },
  ],
  pilotText:
    "Piloting [2 resources Command] (You may play this as an upgrade on a friendly Vehicle without a Pilot.)",
  internalName: "clone-pilot",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Piloting",
      keyword: "piloting",
    },
  ],
} satisfies SwuUnitCard;

export default swuClonePilot;
