// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCr90ReliefRunner = {
  title: "CR90 Relief Runner",
  cost: 6,
  hp: 6,
  power: 4,
  text: "Restore 2 (When this unit attacks, heal 2 damage from your base.)\nWhen Defeated: Heal up to 3 damage from a unit or base.",
  unique: false,
  id: "7610382003",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["rebel", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 71,
  },
  setCodes: [
    {
      set: "JTL",
      number: 71,
    },
  ],
  internalName: "cr90-relief-runner",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
    {
      kind: "triggered",
      text: "When Defeated: Heal up to 3 damage from a unit or base.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "heal",
          amount: 3,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuCr90ReliefRunner;
