// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDirectorKrennicOnTheVergeOfGreatness = {
  title: "Director Krennic",
  subtitle: "On the Verge of Greatness",
  cost: 2,
  hp: 2,
  power: 2,
  text: "Shielded (When you play this unit, give a Shield token to it.)\nThe first unit you play each round that has a “When Defeated” ability costs 1 resource less.",
  unique: true,
  rules:
    'Any ability whose trigger starts with "When defeated…" is considered a "When Defeated" ability.\n',
  id: "6311662442",
  rarity: "uncommon",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "official"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 32,
  },
  setCodes: [
    {
      set: "JTL",
      number: 32,
    },
  ],
  internalName: "director-krennic#on-the-verge-of-greatness",
  cardType: "unit",
  canonicalId: "director-krennic#on-the-verge-of-greatness",
  slug: "director-krennic-on-the-verge-of-greatness",
  name: "Director Krennic",
  printings: [
    {
      id: "JTL_032",
      artId: "19631",
      setCode: "JTL",
      collectorNumber: "32",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04010032_EN_Director_Krennic_6e93034c45.png",
    },
    {
      id: "4564604164",
      artId: "19631",
      setCode: "JTL",
      collectorNumber: "294",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04020294_EN_Director_Krennic_feef0e7a36.png",
    },
    {
      id: "6031334998",
      artId: "19631",
      setCode: "JTL",
      collectorNumber: "530",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04310530_EN_Director_Krennic_675c7da191.png",
    },
    {
      id: "8368735967",
      artId: "19631",
      setCode: "JTL",
      collectorNumber: "766",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//04320766_EN_Director_Krennic_c5e0fd6aee.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuDirectorKrennicOnTheVergeOfGreatness;
