// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuExecutorMightOfTheEmpire = {
  title: "Executor",
  subtitle: "Might of the Empire",
  cost: 11,
  hp: 12,
  power: 12,
  text: "Overwhelm\nWhen Played/On Attack/When Defeated: Create 3 TIE Fighter tokens.",
  unique: true,
  rules:
    "Shields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\n",
  id: "2870117979",
  rarity: "legendary",
  aspects: ["command", "villainy"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["overwhelm"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 90,
  },
  setCodes: [
    {
      set: "JTL",
      number: 90,
    },
  ],
  internalName: "executor#might-of-the-empire",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
  ],
} satisfies SwuUnitCard;

export default swuExecutorMightOfTheEmpire;
