// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuFettsFiresprayFearedSilhouette = {
  title: "Fett's Firespray",
  subtitle: "Feared Silhouette",
  cost: 4,
  hp: 4,
  power: 4,
  text: "When Played/On Attack: Deal 1 indirect damage to a player. If you control Boba Fett (as a unit, upgrade, or leader), deal 2 indirect damage instead. (They assign unpreventable damage among their base and units.)",
  unique: true,
  rules:
    "A player can't assign more indirect damage to a unit than it has remaining HP. Indirect damage is unpreventable and ignores Shields.\n",
  id: "6648978613",
  rarity: "special",
  aspects: ["villainy"],
  traits: ["underworld", "vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 240,
  },
  setCodes: [
    {
      set: "JTL",
      number: 240,
    },
  ],
  internalName: "fetts-firespray#feared-silhouette",
  cardType: "unit",
  canonicalId: "fetts-firespray#feared-silhouette",
  slug: "fetts-firespray-feared-silhouette",
  name: "Fett's Firespray",
  printings: [
    {
      id: "JTL_240",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "240",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04010240_EN_Fett_s_Firespray_1d40f01b0f.png",
    },
    {
      id: "8379678995",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "502",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04020502_EN_Fett_s_Firespray_16f1d67a48.png",
    },
    {
      id: "2328517698",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "738",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04310738_EN_Fett_s_Firespray_e77c765849.png",
    },
    {
      id: "6229024786",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "974",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04320974_EN_Fett_s_Firespray_cd9d49ded6.png",
    },
    {
      id: "2632200083",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "1046",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04061046_EN_Fetts_Firespray_91af558fe7.png",
    },
    {
      id: "8140408874",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "1082",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04331082_EN_Fetts_Firespray_86b8bd3828.png",
    },
    {
      id: "5709647281",
      artId: "20671",
      setCode: "JTL",
      collectorNumber: "1118",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//04341118_EN_Fetts_Firespray_dd5a2f6c7a.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played/On Attack: Deal 1 indirect damage to a player. If you control Boba Fett (as a unit, upgrade, or leader), deal 2 indirect damage instead. (They assign unpreventable damage among their base and units.)",
      effects: [effect.indirectDamage(target.player("opponent"), 1)],
    }),
    ability.onAttack({
      text: "When Played/On Attack: Deal 1 indirect damage to a player. If you control Boba Fett (as a unit, upgrade, or leader), deal 2 indirect damage instead. (They assign unpreventable damage among their base and units.)",
      effects: [effect.indirectDamage(target.player("opponent"), 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuFettsFiresprayFearedSilhouette;
