// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuGuerillaSoldier = {
  title: "Guerilla Soldier",
  cost: 3,
  hp: 3,
  power: 2,
  text: "When Played: Deal 3 indirect damage to a player. If a base is damaged this way, ready this unit. (That player assigns 3 unpreventable damage among their base and units.)",
  unique: false,
  rules:
    "A player can't assign more indirect damage to a unit than it has remaining HP. Indirect damage is unpreventable and ignores Shields.\n",
  id: "2711104544",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["fringe", "twi'lek", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 218,
  },
  setCodes: [
    {
      set: "JTL",
      number: 218,
    },
  ],
  internalName: "guerilla-soldier",
  cardType: "unit",
  canonicalId: "guerilla-soldier",
  slug: "guerilla-soldier",
  name: "Guerilla Soldier",
  printings: [
    {
      id: "JTL_218",
      artId: "20561",
      setCode: "JTL",
      collectorNumber: "218",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010218_EN_Guerilla_Soldier_5ac25ab7a4.png",
    },
    {
      id: "6435321109",
      artId: "20561",
      setCode: "JTL",
      collectorNumber: "480",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020480_EN_Guerilla_Soldier_a6ebb8befb.png",
    },
    {
      id: "8780966699",
      artId: "20561",
      setCode: "JTL",
      collectorNumber: "716",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04310716_EN_Guerilla_Soldier_765dc1af1c.png",
    },
    {
      id: "4488733423",
      artId: "20561",
      setCode: "JTL",
      collectorNumber: "952",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04320952_EN_Guerilla_Soldier_e20b8eaeb9.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played: Deal 3 indirect damage to a player. If a base is damaged this way, ready this unit.",
      effects: [
        effect.sequential([
          effect.indirectDamage(target.player("opponent"), 3),
          effect.ready(target.self()),
        ]),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuGuerillaSoldier;
