// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuOmicronStrikeCraft = {
  title: "Omicron Strike Craft",
  cost: 3,
  hp: 3,
  power: 2,
  text: "Sentinel (Units in this arena can't attack your non-Sentinel units or your base.)",
  unique: false,
  id: "6332346890",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["republic", "vehicle", "transport"],
  arena: "space",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 64,
  },
  setCodes: [
    {
      set: "JTL",
      number: 64,
    },
  ],
  internalName: "omicron-strike-craft",
  cardType: "unit",
  canonicalId: "omicron-strike-craft",
  slug: "omicron-strike-craft",
  name: "Omicron Strike Craft",
  printings: [
    {
      id: "JTL_064",
      artId: "19791",
      setCode: "JTL",
      collectorNumber: "64",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//04010064_EN_Omicron_Strike_Craft_444a8eacc0.png",
    },
    {
      id: "0682326830",
      artId: "19791",
      setCode: "JTL",
      collectorNumber: "326",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//04020326_EN_Omicron_Strike_Craft_eea249314d.png",
    },
    {
      id: "9205771164",
      artId: "19791",
      setCode: "JTL",
      collectorNumber: "562",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//04310562_EN_Omicron_Strike_Craft_f01bb6c9ee.png",
    },
    {
      id: "2350876739",
      artId: "19791",
      setCode: "JTL",
      collectorNumber: "798",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//04320798_EN_Omicron_Strike_Craft_a1ab18789a.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuOmicronStrikeCraft;
