// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuOnyxSquadronBrute = {
  title: "Onyx Squadron Brute",
  cost: 2,
  hp: 3,
  power: 2,
  text: "When Defeated: Heal 2 damage from a base.",
  unique: false,
  id: "1164297413",
  rarity: "common",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 33,
  },
  setCodes: [
    {
      set: "JTL",
      number: 33,
    },
  ],
  internalName: "onyx-squadron-brute",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Defeated: Heal 2 damage from a base.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "heal",
          amount: 2,
          target: {
            type: "base",
            controller: "any",
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuOnyxSquadronBrute;
