// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuOuterRimOutlaws = {
  title: "Outer Rim Outlaws",
  cost: 3,
  hp: 3,
  power: 3,
  text: "Shielded (When you play this unit, give a Shield token to it.)",
  unique: false,
  id: "3770706835",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 65,
  },
  setCodes: [
    {
      set: "JTL",
      number: 65,
    },
  ],
  internalName: "outer-rim-outlaws",
  cardType: "unit",
  canonicalId: "outer-rim-outlaws",
  slug: "outer-rim-outlaws",
  name: "Outer Rim Outlaws",
  printings: [
    {
      id: "JTL_065",
      artId: "19796",
      setCode: "JTL",
      collectorNumber: "65",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010065_EN_Outer_Rim_Outlaws_54241f2b8d.png",
    },
    {
      id: "2701948245",
      artId: "19796",
      setCode: "JTL",
      collectorNumber: "327",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020327_EN_Outer_Rim_Outlaws_88c639e9bf.png",
    },
    {
      id: "3039738945",
      artId: "19796",
      setCode: "JTL",
      collectorNumber: "563",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04310563_EN_Outer_Rim_Outlaws_1bae020490.png",
    },
    {
      id: "0836420309",
      artId: "19796",
      setCode: "JTL",
      collectorNumber: "799",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04320799_EN_Outer_Rim_Outlaws_ffaa7b6d8e.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuOuterRimOutlaws;
