// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuPhoenixSquadronAwing = {
  title: "Phoenix Squadron A-Wing",
  cost: 2,
  hp: 2,
  power: 3,
  unique: false,
  id: "7653629848",
  rarity: "common",
  aspects: ["command", "heroism"],
  traits: ["rebel", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 95,
  },
  setCodes: [
    {
      set: "JTL",
      number: 95,
    },
  ],
  internalName: "phoenix-squadron-awing",
  cardType: "unit",
} satisfies SwuUnitCard;

export default swuPhoenixSquadronAwing;
