// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuQuasarTieCarrier = {
  title: "Quasar TIE Carrier",
  cost: 6,
  hp: 7,
  power: 5,
  text: "On Attack: Create a TIE Fighter token.",
  unique: false,
  id: "2657417747",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 243,
  },
  setCodes: [
    {
      set: "JTL",
      number: 243,
    },
  ],
  internalName: "quasar-tie-carrier",
  cardType: "unit",
  canonicalId: "quasar-tie-carrier",
  slug: "quasar-tie-carrier",
  name: "Quasar TIE Carrier",
  printings: [
    {
      id: "JTL_243",
      artId: "20686",
      setCode: "JTL",
      collectorNumber: "243",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010243_EN_Quasar_TIE_Carrier_e98400d78c.png",
    },
    {
      id: "0394797127",
      artId: "20686",
      setCode: "JTL",
      collectorNumber: "505",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020505_EN_Quasar_TIE_Carrier_a1b64bb2f1.png",
    },
    {
      id: "3290712454",
      artId: "20686",
      setCode: "JTL",
      collectorNumber: "741",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04310741_EN_Quasar_TIE_Carrier_cfad90c4a4.png",
    },
    {
      id: "6032915914",
      artId: "20686",
      setCode: "JTL",
      collectorNumber: "977",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04320977_EN_Quasar_TIE_Carrier_a7d43214ff.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "On Attack: Create a TIE Fighter token.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "createToken",
          token: "tieFighter",
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuQuasarTieCarrier;
