// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuRadiantViiAmbassadorsArrival = {
  title: "Radiant VII",
  subtitle: "Ambassadors' Arrival",
  cost: 7,
  hp: 6,
  power: 5,
  text: "Each enemy non-leader unit gets –1/–0 for each damage on it.\nWhen Played: Deal 5 indirect damage to a player.",
  unique: true,
  rules:
    "A player can't assign more indirect damage to a unit than it has remaining HP. Indirect damage is unpreventable and ignores Shields.\n",
  id: "3567283316",
  rarity: "legendary",
  aspects: ["cunning"],
  traits: ["republic", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 226,
  },
  setCodes: [
    {
      set: "JTL",
      number: 226,
    },
  ],
  internalName: "radiant-vii#ambassadors-arrival",
  cardType: "unit",
  abilities: [
    ability.constant({
      text: "Each enemy non-leader unit gets -1/-0 for each damage on it.",
      effects: [
        effect.modifyStatsPer(target.unit({ controller: "opponent" }), "damageOnTarget", {
          power: -1,
          duration: "continuous",
        }),
      ],
    }),
    ability.whenPlayed({
      text: "When Played: Deal 5 indirect damage to a player.",
      effects: [effect.indirectDamage(target.player("opponent"), 5)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuRadiantViiAmbassadorsArrival;
