// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuResistanceBlueSquadron = {
  title: "Resistance Blue Squadron",
  cost: 4,
  hp: 4,
  power: 3,
  text: "When Played: You may deal damage to a unit equal to the number of friendly space units.",
  unique: false,
  id: "5941636047",
  rarity: "common",
  aspects: ["command", "heroism"],
  traits: ["resistance", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 102,
  },
  setCodes: [
    {
      set: "JTL",
      number: 102,
    },
  ],
  internalName: "resistance-blue-squadron",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      trigger: { event: "played" },
      text: "When Played: You may deal damage to a unit equal to the number of friendly space units.",
      optional: true,
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damagePer",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit"],
                limit: 1,
              },
              per: "targetCount",
              count: {
                type: "card",
                controller: "friendly",
                zones: ["spaceArena"],
                cardTypes: ["unit", "token"],
              },
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuResistanceBlueSquadron;
