// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuResupplyCarrier = {
  title: "Resupply Carrier",
  cost: 6,
  hp: 5,
  power: 4,
  text: "When Played: You may put the top card of your deck into play as a resource.",
  unique: false,
  rules: "A card put into play as a resource enters play exhausted.\n",
  id: "0926549684",
  rarity: "common",
  aspects: ["command"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 119,
  },
  setCodes: [
    {
      set: "JTL",
      number: 119,
    },
  ],
  internalName: "resupply-carrier",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may put the top card of your deck into play as a resource.",
      trigger: {
        event: "played",
      },
      optional: true,
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "resource",
              target: {
                type: "card",
                controller: "friendly",
                zones: ["deck"],
                limit: 1,
              },
              ready: false,
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuResupplyCarrier;
