// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTieDaggerVanguard = {
  title: "TIE Dagger Vanguard",
  cost: 3,
  hp: 2,
  power: 2,
  text: "When Played: You may deal 2 damage to a damaged unit.",
  unique: false,
  id: "7157369742",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["first order", "sith", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 239,
  },
  setCodes: [
    {
      set: "JTL",
      number: 239,
    },
  ],
  internalName: "tie-dagger-vanguard",
  cardType: "unit",
  canonicalId: "tie-dagger-vanguard",
  slug: "tie-dagger-vanguard",
  name: "TIE Dagger Vanguard",
  printings: [
    {
      id: "JTL_239",
      artId: "20666",
      setCode: "JTL",
      collectorNumber: "239",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04010239_EN_TIE_Dagger_Vanguard_02131d1bd0.png",
    },
    {
      id: "1272573778",
      artId: "20666",
      setCode: "JTL",
      collectorNumber: "501",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04020501_EN_TIE_Dagger_Vanguard_90b31e49a5.png",
    },
    {
      id: "2150032475",
      artId: "20666",
      setCode: "JTL",
      collectorNumber: "737",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04310737_EN_TIE_Dagger_Vanguard_efeded9151.png",
    },
    {
      id: "1118380100",
      artId: "20666",
      setCode: "JTL",
      collectorNumber: "973",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//04320973_EN_TIE_Dagger_Vanguard_c03d8aeb54.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may deal 2 damage to a damaged unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuTieDaggerVanguard;
