// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuVictorLeaderLeadingFromTheFront = {
  title: "Victor Leader",
  subtitle: "Leading from the Front",
  cost: 3,
  hp: 4,
  power: 2,
  text: "Each other friendly space unit gets +1/+1.",
  unique: true,
  id: "9811031405",
  rarity: "rare",
  aspects: ["command", "villainy"],
  traits: ["imperial", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "JTL",
    number: 85,
  },
  setCodes: [
    {
      set: "JTL",
      number: 85,
    },
  ],
  internalName: "victor-leader#leading-from-the-front",
  cardType: "unit",
  canonicalId: "victor-leader#leading-from-the-front",
  slug: "victor-leader-leading-from-the-front",
  name: "Victor Leader",
  printings: [
    {
      id: "JTL_085",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "85",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04010085_EN_Victor_Leader_ddf9a5e609.png",
    },
    {
      id: "6641629104",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "347",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04020347_EN_Victor_Leader_2e41540817.png",
    },
    {
      id: "3006977062",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "583",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04310583_EN_Victor_Leader_01618da065.png",
    },
    {
      id: "6036575012",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "819",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04320819_EN_Victor_Leader_d0c07550f5.png",
    },
    {
      id: "8518216265",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "1023",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04061023_EN_Victor_Leadera_925e8845b3.png",
    },
    {
      id: "9238617741",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "1059",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04331059_EN_Victor_Leadera_063830c25e.png",
    },
    {
      id: "4211220199",
      artId: "19896",
      setCode: "JTL",
      collectorNumber: "1095",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04341095_EN_Victor_Leadera_7d533f031a.png",
    },
  ],
  abilities: [
    ability.constant({
      text: "Each other friendly space unit gets +1/+1.",
      effects: [
        effect.modifyStats(
          target.unit({
            controller: "friendly",
            arena: "space",
            excludeSelf: true,
          }),
          { power: 1, hp: 1, duration: "continuous" },
        ),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuVictorLeaderLeadingFromTheFront;
