import type {
  LorcanaActionCardDefinition,
  LorcanaCharacterCardDefinition,
  LorcanaLocationCardDefinition,
} from "~/game-engine/engines/lorcana/src/cards/lorcana-card-repository";

export const mockCharacterCard: LorcanaCharacterCardDefinition = {
  id: "MUST_BE_UNIQUE_ID_CHAR",
  name: "Test Card",
  title: "Character",
  characteristics: [],
  text: "",
  type: "character",
  abilities: [],
  flavour: "",
  inkwell: true,
  colors: ["amber"],
  cost: 1,
  strength: 1,
  willpower: 1,
  lore: 1,
  illustrator: "",
  number: 0,
  set: "TFC",
  rarity: "common",
};

export const mockLocationCard: LorcanaLocationCardDefinition = {
  id: "MUST_BE_UNIQUE_ID_LOC",
  name: "Test Location",
  title: "Basic Location",
  characteristics: [],
  text: "",
  type: "location",
  abilities: [],
  flavour: "",
  inkwell: true,
  colors: ["amber"],
  cost: 2,
  willpower: 4,
  moveCost: 1,
  lore: 1,
  illustrator: "",
  number: 0,
  set: "TFC",
  rarity: "common",
};

export const mockActionCard: LorcanaActionCardDefinition = {
  id: "MUST_BE_UNIQUE_ID_ACTION",
  name: "Test Action",
  characteristics: [],
  text: "",
  type: "action",
  abilities: [],
  flavour: "",
  inkwell: true,
  colors: ["amber"],
  cost: 2,
  willpower: 4,
  moveCost: 1,
  lore: 1,
  illustrator: "",
  number: 0,
  set: "TFC",
  rarity: "common",
};
