// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuAdiGalliaSternAndFocused = {
  title: "Adi Gallia",
  subtitle: "Stern and Focused",
  cost: 2,
  hp: 4,
  power: 2,
  text: "When an opponent plays an event: Deal 1 damage to that player's base.",
  unique: true,
  id: "4741025404",
  rarity: "rare",
  aspects: ["aggression", "heroism"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 142,
  },
  setCodes: [
    {
      set: "LOF",
      number: 142,
    },
  ],
  internalName: "adi-gallia#stern-and-focused",
  cardType: "unit",
  canonicalId: "adi-gallia#stern-and-focused",
  slug: "adi-gallia-stern-and-focused",
  name: "Adi Gallia",
  printings: [
    {
      id: "LOF_142",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "142",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05010142_EN_Adi_Gallia_2861556753.png",
    },
    {
      id: "4837773095",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "406",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05020406_EN_Adi_Gallia_733b3d4eef.png",
    },
    {
      id: "3991472598",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "644",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05310644_EN_Adi_Gallia_60f3bb61db.png",
    },
    {
      id: "8558284176",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "882",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05320882_EN_Adi_Gallia_d817eada4a.png",
    },
    {
      id: "0829167806",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "1060",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05061060_EN_Adi_Gallia_f8a65730e5.png",
    },
    {
      id: "4186659969",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "1106",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05331106_EN_Adi_Gallia_b2440632a0.png",
    },
    {
      id: "7739701061",
      artId: "27734",
      setCode: "LOF",
      collectorNumber: "1152",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//05341152_EN_Adi_Gallia_4a23270882.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "when", name: "opponentEventPlayed" },
      {
        text: "When an opponent plays an event: Deal 1 damage to that player's base.",
        effects: [effect.damage(target.base("opponent"), 1)],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuAdiGalliaSternAndFocused;
