// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAttunedFyrnock = {
  title: "Attuned Fyrnock",
  cost: 2,
  hp: 1,
  power: 4,
  text: "Hidden (This unit can't be attacked if it was played this phase.)",
  unique: false,
  rules: "If a unit has Hidden and Sentinel at the same time, it can be attacked.\n",
  id: "1433284352",
  rarity: "common",
  aspects: ["aggression", "heroism"],
  traits: ["creature"],
  arena: "ground",
  keywords: ["hidden"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 143,
  },
  setCodes: [
    {
      set: "LOF",
      number: 143,
    },
  ],
  internalName: "attuned-fyrnock",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
  ],
} satisfies SwuUnitCard;

export default swuAttunedFyrnock;
