// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuChirrutImweBlindButNotDeaf = {
  title: "Chirrut Îmwe",
  subtitle: "Blind, but not Deaf",
  cost: 4,
  hp: 5,
  power: 3,
  text: "Sentinel\nWhen this unit is attacked (before damage is dealt): You may use the Force (lose your Force token). If you do, the attacker gets –2/–0 for this attack.",
  unique: true,
  rules: '"When this unit is attacked" triggers at the same time as "On Attack" abilities.\n',
  id: "0775347605",
  rarity: "uncommon",
  aspects: ["vigilance"],
  traits: ["force", "fringe"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 67,
  },
  setCodes: [
    {
      set: "LOF",
      number: 67,
    },
  ],
  internalName: "chirrut-imwe#blind-but-not-deaf",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuChirrutImweBlindButNotDeaf;
