// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuCuriousFlock = {
  title: "Curious Flock",
  cost: 1,
  hp: 1,
  power: 1,
  text: "When Played: Pay up to 6 resources. For each resource paid this way, give an Experience token to this unit.",
  unique: false,
  rules:
    'Curious Flock\'s "When Played" ability is not reduced by effects that reduce the cost of cards.\n',
  id: "4974236883",
  rarity: "common",
  traits: ["creature"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 255,
  },
  setCodes: [
    {
      set: "LOF",
      number: 255,
    },
  ],
  internalName: "curious-flock",
  cardType: "unit",
  abilities: [
    ability.whenPlayed({
      text: "When Played: Pay up to 6 resources. For each resource paid this way, give an Experience token to this unit.",
      effects: [effect.payResources(1), effect.distribute("experience", target.self(), 1)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuCuriousFlock;
