// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDumeRedeemTheFuture = {
  title: "Dume",
  subtitle: "Redeem the Future",
  cost: 4,
  hp: 7,
  power: 2,
  text: "When the regroup phase starts: Give an Experience token to each other friendly non-Vehicle unit.",
  unique: true,
  id: "6523135540",
  rarity: "rare",
  aspects: ["vigilance", "vigilance"],
  traits: ["force", "creature"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 55,
  },
  setCodes: [
    {
      set: "LOF",
      number: 55,
    },
  ],
  internalName: "dume#redeem-the-future",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "when", name: "regroupPhaseStarts" },
      {
        text: "When the regroup phase starts: Give an Experience token to each other friendly non-Vehicle unit.",
        effects: [
          effect.distribute(
            "experience",
            target.unit({ controller: "friendly", withoutTraits: ["vehicle"], excludeSelf: true }),
            1,
          ),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuDumeRedeemTheFuture;
