// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuGrapplingGuardian = {
  title: "Grappling Guardian",
  cost: 7,
  hp: 9,
  power: 3,
  text: "When Played: You may defeat a space unit with 6 or less remaining HP.",
  unique: false,
  id: "2404240951",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["creature"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 71,
  },
  setCodes: [
    {
      set: "LOF",
      number: 71,
    },
  ],
  internalName: "grappling-guardian",
  cardType: "unit",
  canonicalId: "grappling-guardian",
  slug: "grappling-guardian",
  name: "Grappling Guardian",
  printings: [
    {
      id: "LOF_071",
      artId: "27379",
      setCode: "LOF",
      collectorNumber: "71",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010071_EN_Grappling_Guardian_6571e3b034.png",
    },
    {
      id: "7883644218",
      artId: "27379",
      setCode: "LOF",
      collectorNumber: "335",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020335_EN_Grappling_Guardian_733842edff.png",
    },
    {
      id: "1625120154",
      artId: "27379",
      setCode: "LOF",
      collectorNumber: "573",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310573_EN_Grappling_Guardian_f881c89e7d.png",
    },
    {
      id: "4962875515",
      artId: "27379",
      setCode: "LOF",
      collectorNumber: "811",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320811_EN_Grappling_Guardian_89d5cc8b35.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may defeat a space unit with 6 or less remaining HP.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "defeat",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "space",
                excludeSelf: false,
                limit: 1,
                hp: {
                  operator: "lte",
                  value: 6,
                },
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuGrapplingGuardian;
