// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHyenaBomber = {
  title: "Hyena Bomber",
  cost: 3,
  hp: 2,
  power: 2,
  text: "When Played: If you control another Aggression unit, you may deal 2 damage to a ground unit.",
  unique: false,
  id: "1022691467",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["separatist", "droid", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 158,
  },
  setCodes: [
    {
      set: "LOF",
      number: 158,
    },
  ],
  internalName: "hyena-bomber",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: If you control another Aggression unit, you may deal 2 damage to a ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "conditional",
          condition: {
            type: "controlsAspect",
            controller: "friendly",
            aspect: "aggression",
          },
          ifTrue: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuHyenaBomber;
