// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLongbeamCruiser = {
  title: "Longbeam Cruiser",
  cost: 6,
  hp: 6,
  power: 6,
  text: "Restore 1 (When this unit attacks, heal 1 damage from your base.)",
  unique: false,
  id: "9107238716",
  rarity: "common",
  aspects: ["heroism"],
  traits: ["republic", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 253,
  },
  setCodes: [
    {
      set: "LOF",
      number: 253,
    },
  ],
  internalName: "longbeam-cruiser",
  cardType: "unit",
  canonicalId: "longbeam-cruiser",
  slug: "longbeam-cruiser",
  name: "Longbeam Cruiser",
  printings: [
    {
      id: "LOF_253",
      artId: "28289",
      setCode: "LOF",
      collectorNumber: "253",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010253_EN_Longbeam_Cruiser_b7fcac2856.png",
    },
    {
      id: "3040672689",
      artId: "28289",
      setCode: "LOF",
      collectorNumber: "517",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020517_EN_Longbeam_Cruiser_168f964035.png",
    },
    {
      id: "9561631466",
      artId: "28289",
      setCode: "LOF",
      collectorNumber: "755",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310755_EN_Longbeam_Cruiser_17db42da1b.png",
    },
    {
      id: "3776585712",
      artId: "28289",
      setCode: "LOF",
      collectorNumber: "993",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320993_EN_Longbeam_Cruiser_3e519d5c1b.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuLongbeamCruiser;
