// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuLuthenRaelMasqueradingAntiquarian = {
  title: "Luthen Rael",
  subtitle: "Masquerading Antiquarian",
  cost: 4,
  hp: 5,
  power: 4,
  text: "On Attack: Search the top 5 cards of your deck for an Item upgrade, reveal it, and draw it. (Put the other cards on the bottom of your deck in a random order.)",
  unique: true,
  rules:
    "After searching, put any cards not chosen on the bottom of your deck in a random order.\n",
  id: "5472129982",
  rarity: "uncommon",
  aspects: ["vigilance"],
  traits: ["rebel"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 68,
  },
  setCodes: [
    {
      set: "LOF",
      number: 68,
    },
  ],
  internalName: "luthen-rael#masquerading-antiquarian",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "On Attack: Search the top 5 cards of your deck for an Item upgrade, reveal it, and draw it. (Put the other cards on the bottom of your deck in a random order.)",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "search",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          destination: "hand",
          reveal: true,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuLuthenRaelMasqueradingAntiquarian;
