// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuObiwanKenobiProtectivePadawan = {
  title: "Obi-Wan Kenobi",
  subtitle: "Protective Padawan",
  cost: 3,
  hp: 5,
  power: 3,
  text: "When you play a Force unit (including this one): This unit gains Sentinel for this phase. ",
  unique: true,
  id: "6059510270",
  rarity: "special",
  aspects: ["command", "heroism"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 96,
  },
  setCodes: [
    {
      set: "LOF",
      number: 96,
    },
  ],
  internalName: "obiwan-kenobi#protective-padawan",
  cardType: "unit",
  canonicalId: "obiwan-kenobi#protective-padawan",
  slug: "obiwan-kenobi-protective-padawan",
  name: "Obi-Wan Kenobi",
  printings: [
    {
      id: "LOF_096",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "96",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05010096_EN_Obi_Wan_Kenobi_de3fe0ebd4.png",
    },
    {
      id: "8741285074",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "360",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05020360_EN_Obi_Wan_Kenobi_5574b70be3.png",
    },
    {
      id: "5349844946",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "598",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05310598_EN_Obi_Wan_Kenobi_70c4d1dcdc.png",
    },
    {
      id: "5025984417",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "836",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05320836_EN_Obi_Wan_Kenobi_fef155c2c3.png",
    },
    {
      id: "7868701921",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "1050",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05061050_EN_Obi_Wan_Kenobi_a0d9c384ce.png",
    },
    {
      id: "6440857379",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "1096",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05331096_EN_Obi_Wan_Kenobi_9d1f5f3ecf.png",
    },
    {
      id: "7506497389",
      artId: "27504",
      setCode: "LOF",
      collectorNumber: "1142",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//05341142_EN_Obi_Wan_Kenobi_5dda1db5de.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuObiwanKenobiProtectivePadawan;
