// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuQuinlanVosDarkDisciple = {
  title: "Quinlan Vos",
  subtitle: "Dark Disciple",
  cost: 4,
  hp: 5,
  power: 4,
  text: "On Attack: If this unit has 6 or more power, you may deal 2 damage to an enemy base.",
  unique: true,
  rules: "Abilities that refer to a card’s power include temporary modifiers.\n",
  id: "7008431159",
  rarity: "uncommon",
  aspects: ["aggression"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 163,
  },
  setCodes: [
    {
      set: "LOF",
      number: 163,
    },
  ],
  internalName: "quinlan-vos#dark-disciple",
  cardType: "unit",
  canonicalId: "quinlan-vos#dark-disciple",
  slug: "quinlan-vos-dark-disciple",
  name: "Quinlan Vos",
  printings: [
    {
      id: "LOF_163",
      artId: "27839",
      setCode: "LOF",
      collectorNumber: "163",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05010163_EN_Quinlan_Vos_cfd1740cbe.png",
    },
    {
      id: "7966816982",
      artId: "27839",
      setCode: "LOF",
      collectorNumber: "427",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05020427_EN_Quinlan_Vos_ab71e80860.png",
    },
    {
      id: "1887713629",
      artId: "27839",
      setCode: "LOF",
      collectorNumber: "665",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05310665_EN_Quinlan_Vos_daa930e0c3.png",
    },
    {
      id: "1310984573",
      artId: "27839",
      setCode: "LOF",
      collectorNumber: "903",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05320903_EN_Quinlan_Vos_ed24e34097.png",
    },
  ],
  abilities: [
    ability.onAttack({
      text: "On Attack: If this unit has 6 or more power, you may deal 2 damage to an enemy base.",
      optional: true,
      effects: [effect.damage(target.base("opponent"), 2)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuQuinlanVosDarkDisciple;
