// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRavenousRathtar = {
  title: "Ravenous Rathtar",
  cost: 6,
  hp: 5,
  power: 8,
  unique: false,
  id: "5796902316",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["creature"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 168,
  },
  setCodes: [
    {
      set: "LOF",
      number: 168,
    },
  ],
  internalName: "ravenous-rathtar",
  cardType: "unit",
  canonicalId: "ravenous-rathtar",
  slug: "ravenous-rathtar",
  name: "Ravenous Rathtar",
  printings: [
    {
      id: "LOF_168",
      artId: "27864",
      setCode: "LOF",
      collectorNumber: "168",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010168_EN_Ravenous_Rathtar_db7821376b.png",
    },
    {
      id: "4474841943",
      artId: "27864",
      setCode: "LOF",
      collectorNumber: "432",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020432_EN_Ravenous_Rathtar_755024b472.png",
    },
    {
      id: "6510059422",
      artId: "27864",
      setCode: "LOF",
      collectorNumber: "670",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310670_EN_Ravenous_Rathtar_8014d50d38.png",
    },
    {
      id: "0291009310",
      artId: "27864",
      setCode: "LOF",
      collectorNumber: "908",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320908_EN_Ravenous_Rathtar_d2fdff9ba8.png",
    },
  ],
} satisfies SwuUnitCard;

export default swuRavenousRathtar;
