// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuShinHatiOvereagerApprentice = {
  title: "Shin Hati",
  subtitle: "Overeager Apprentice",
  cost: 3,
  hp: 2,
  power: 4,
  text: "Hidden (This unit can't be attacked if it was played this phase.)\nShielded (When you play this unit, give a Shield token to her.)",
  unique: true,
  rules: "If a unit has Hidden and Sentinel at the same time, it can be attacked.\n",
  id: "5221323929",
  rarity: "uncommon",
  aspects: ["cunning", "villainy"],
  traits: ["force", "fringe"],
  arena: "ground",
  keywords: ["hidden", "shielded"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 183,
  },
  setCodes: [
    {
      set: "LOF",
      number: 183,
    },
  ],
  internalName: "shin-hati#overeager-apprentice",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Hidden",
      keyword: "hidden",
    },
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuShinHatiOvereagerApprentice;
