// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSorcerersOfTund = {
  title: "Sorcerers of Tund",
  cost: 6,
  hp: 6,
  power: 6,
  text: "Shielded (When you play this card, give a Shield token to it.)",
  unique: false,
  id: "0355203328",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["force", "fringe"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 214,
  },
  setCodes: [
    {
      set: "LOF",
      number: 214,
    },
  ],
  internalName: "sorcerers-of-tund",
  cardType: "unit",
  canonicalId: "sorcerers-of-tund",
  slug: "sorcerers-of-tund",
  name: "Sorcerers of Tund",
  printings: [
    {
      id: "LOF_214",
      artId: "28094",
      setCode: "LOF",
      collectorNumber: "214",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010214_EN_Sorcerers_of_Tund_00996f52f4.png",
    },
    {
      id: "8200746000",
      artId: "28094",
      setCode: "LOF",
      collectorNumber: "478",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020478_EN_Sorcerers_of_Tund_0be1962560.png",
    },
    {
      id: "3348764875",
      artId: "28094",
      setCode: "LOF",
      collectorNumber: "716",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310716_EN_Sorcerers_of_Tund_8cff3b0261.png",
    },
    {
      id: "5849544619",
      artId: "28094",
      setCode: "LOF",
      collectorNumber: "954",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320954_EN_Sorcerers_of_Tund_c75a4bce34.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuSorcerersOfTund;
