// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuStingerMantisWhereAreWeGoing = {
  title: "Stinger Mantis",
  subtitle: "Where Are We Going?",
  cost: 5,
  hp: 6,
  power: 4,
  text: "When Played: You may deal 2 damage to an exhausted unit.",
  unique: true,
  id: "1545515980",
  rarity: "uncommon",
  aspects: ["cunning", "heroism"],
  traits: ["fringe", "vehicle", "transport"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 198,
  },
  setCodes: [
    {
      set: "LOF",
      number: 198,
    },
  ],
  internalName: "stinger-mantis#where-are-we-going",
  cardType: "unit",
  canonicalId: "stinger-mantis#where-are-we-going",
  slug: "stinger-mantis-where-are-we-going",
  name: "Stinger Mantis",
  printings: [
    {
      id: "LOF_198",
      artId: "28014",
      setCode: "LOF",
      collectorNumber: "198",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05010198_EN_Stinger_Mantis_fd20e83ed6.png",
    },
    {
      id: "2248220451",
      artId: "28014",
      setCode: "LOF",
      collectorNumber: "462",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05020462_EN_Stinger_Mantis_fd7ccaffe0.png",
    },
    {
      id: "0381867473",
      artId: "28014",
      setCode: "LOF",
      collectorNumber: "700",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05310700_EN_Stinger_Mantis_e61bbe169d.png",
    },
    {
      id: "1375641336",
      artId: "28014",
      setCode: "LOF",
      collectorNumber: "938",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//05320938_EN_Stinger_Mantis_b8185e53ff.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may deal 2 damage to an exhausted unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuStingerMantisWhereAreWeGoing;
