// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSupremacyTiesf = {
  title: "Supremacy TIE/sf",
  cost: 3,
  hp: 3,
  power: 3,
  text: "Sentinel (Enemy units in this arena must attack a Sentinel when they attack you.)",
  unique: false,
  id: "6148303031",
  rarity: "common",
  aspects: ["vigilance", "villainy"],
  traits: ["first order", "vehicle", "fighter"],
  arena: "space",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 34,
  },
  setCodes: [
    {
      set: "LOF",
      number: 34,
    },
  ],
  internalName: "supremacy-tiesf",
  cardType: "unit",
  canonicalId: "supremacy-tiesf",
  slug: "supremacy-tiesf",
  name: "Supremacy TIE/sf",
  printings: [
    {
      id: "LOF_034",
      artId: "27194",
      setCode: "LOF",
      collectorNumber: "34",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010034_EN_Supremacy_TIE_sf_a931986219.png",
    },
    {
      id: "5893991415",
      artId: "27194",
      setCode: "LOF",
      collectorNumber: "298",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020298_EN_Supremacy_TIE_sf_d73322bbfc.png",
    },
    {
      id: "1422362742",
      artId: "27194",
      setCode: "LOF",
      collectorNumber: "536",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310536_EN_Supremacy_TIE_sf_8b81099ab0.png",
    },
    {
      id: "9533115430",
      artId: "27194",
      setCode: "LOF",
      collectorNumber: "774",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320774_EN_Supremacy_TIE_sf_f969454c5e.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuSupremacyTiesf;
