// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuTalzinsAssassin = {
  title: "Talzin's Assassin",
  cost: 4,
  hp: 4,
  power: 4,
  text: "When Played: You may use the Force (lose your Force token). If you do, give a unit –3/–3 for this phase.",
  unique: false,
  id: "2410965424",
  rarity: "common",
  aspects: ["vigilance", "villainy"],
  traits: ["force", "night"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "LOF",
    number: 35,
  },
  setCodes: [
    {
      set: "LOF",
      number: 35,
    },
  ],
  internalName: "talzins-assassin",
  cardType: "unit",
  canonicalId: "talzins-assassin",
  slug: "talzins-assassin",
  name: "Talzin's Assassin",
  printings: [
    {
      id: "LOF_035",
      artId: "27199",
      setCode: "LOF",
      collectorNumber: "35",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010035_EN_Talzin_s_Assassin_82a65780a2.png",
    },
    {
      id: "0024898485",
      artId: "27199",
      setCode: "LOF",
      collectorNumber: "299",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020299_EN_Talzin_s_Assassin_effa184518.png",
    },
    {
      id: "1464114601",
      artId: "27199",
      setCode: "LOF",
      collectorNumber: "537",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310537_EN_Talzin_s_Assassin_117a8fb0bf.png",
    },
    {
      id: "3144894813",
      artId: "27199",
      setCode: "LOF",
      collectorNumber: "775",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320775_EN_Talzin_s_Assassin_8d70bcf9ba.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played: You may use the Force. If you do, give a unit -3/-3 for this phase.",
      optional: true,
      effects: [
        effect.optional([
          effect.ifYouDo(effect.useForce(), [
            effect.modifyStats(target.unit({ limit: 1 }), {
              power: -3,
              hp: -3,
              duration: "phase",
            }),
          ]),
        ]),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuTalzinsAssassin;
