import type { UnitCard } from "@tcg/gundam-types";

export const st05GrazeCustom004: UnitCard = {
  cardNumber: "ST05-004",
  name: "Graze Custom",
  type: "unit",
  color: "purple",
  traits: ["tekkadan"],
  id: "ST05-004",
  externalId: "gundam:st05-004",
  slug: "graze-custom-st05-004",
  displayName: "Graze Custom",
  set: { code: "ST05", name: "Iron Bloom [ST05]", packageId: "616005" },
  printNumber: "ST05-004",
  printings: [
    {
      id: "ST05-004",
      collectorNumber: "ST05-004",
      cardNumber: "ST05-004",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05]",
        packageId: "616005",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-004.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-004.webp?260424",
      productName: "Iron Bloom [ST05]",
    },
    {
      id: "ST05-004_p1",
      collectorNumber: "ST05-004_p1",
      cardNumber: "ST05-004",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05] Bonus Pack",
        packageId: "616005",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-004_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-004_p1.webp?260424",
      productName: "Iron Bloom [ST05] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST05-004",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-004.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-004.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
