import type { UnitCard } from "@tcg/gundam-types";

export const st05Hyakuren006: UnitCard = {
  cardNumber: "ST05-006",
  name: "Hyakuren",
  type: "unit",
  color: "purple",
  traits: ["teiwaz"],
  id: "ST05-006",
  externalId: "gundam:st05-006",
  slug: "hyakuren-st05-006",
  displayName: "Hyakuren",
  set: { code: "ST05", name: "Iron Bloom [ST05]", packageId: "616005" },
  printNumber: "ST05-006",
  printings: [
    {
      id: "ST05-006",
      collectorNumber: "ST05-006",
      cardNumber: "ST05-006",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05]",
        packageId: "616005",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-006.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-006.webp?260424",
      productName: "Iron Bloom [ST05]",
    },
    {
      id: "ST05-006_p1",
      collectorNumber: "ST05-006_p1",
      cardNumber: "ST05-006",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05] Bonus Pack",
        packageId: "616005",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-006_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-006_p1.webp?260424",
      productName: "Iron Bloom [ST05] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST05-006",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-006.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-006.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
