import type { UnitCard } from "@tcg/gundam-types";

export const st05GrazeCommanderType008: UnitCard = {
  cardNumber: "ST05-008",
  name: "Graze Commander Type",
  type: "unit",
  color: "white",
  traits: ["gjallarhorn"],
  id: "ST05-008",
  externalId: "gundam:st05-008",
  slug: "graze-commander-type-st05-008",
  displayName: "Graze Commander Type",
  set: { code: "ST05", name: "Iron Bloom [ST05]", packageId: "616005" },
  printNumber: "ST05-008",
  printings: [
    {
      id: "ST05-008",
      collectorNumber: "ST05-008",
      cardNumber: "ST05-008",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05]",
        packageId: "616005",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-008.webp?260424",
      productName: "Iron Bloom [ST05]",
    },
    {
      id: "ST05-008_p1",
      collectorNumber: "ST05-008_p1",
      cardNumber: "ST05-008",
      set: {
        code: "ST05",
        name: "Iron Bloom [ST05] Bonus Pack",
        packageId: "616005",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-008_p1.webp?260424",
      productName: "Iron Bloom [ST05] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST05-008",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st05/ST05-008.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST05-008.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
