// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuVanquishTheLegion = {
  title: "Vanquish the Legion",
  cost: 4,
  text: "Give each enemy ground unit –2/–2 for this phase.",
  unique: false,
  id: "5236803699",
  rarity: "uncommon",
  aspects: ["vigilance"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "TS26",
    number: 48,
  },
  setCodes: [
    {
      set: "TS26",
      number: 48,
    },
  ],
  internalName: "vanquish-the-legion",
  cardType: "event",
  canonicalId: "vanquish-the-legion",
  slug: "vanquish-the-legion",
  name: "Vanquish the Legion",
  printings: [
    {
      id: "TS26_048",
      artId: "51092",
      setCode: "TS26",
      collectorNumber: "48",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//TS_26010048_EN_Vanquish_the_Legion_3803ed6357.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Give each enemy ground unit -2/-2 for this phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            arena: "ground",
            excludeSelf: false,
          },
          power: -2,
          hp: -2,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuVanquishTheLegion;
