import type { UnitCard } from "@tcg/gundam-types";

export const st10GundamMkIiAeug003: UnitCard = {
  cardNumber: "ST10-003",
  name: "Gundam Mk-II (AEUG)",
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "ST10-003",
  canonicalId: "ST10-003",
  externalIds: { bandai: "gundam:st10-003" },
  slug: "gundam-mk-ii-aeug-st10-003",
  displayName: "Gundam Mk-II (AEUG)",
  rulesText: "-",
  set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
  printNumber: "ST10-003",
  printings: [
    {
      id: "ST10-003",
      artId: "ST10-003",
      setCode: "ST10",
      collectorNumber: "ST10-003",
      cardNumber: "ST10-003",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-003.webp",
      productName: "Generation Pulse [ST10]",
    },
    {
      id: "ST10-003-p1",
      artId: "ST10-003_p1",
      setCode: "ST10",
      collectorNumber: "ST10-003-p1",
      cardNumber: "ST10-003",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-003_p1.webp",
      productName: "Generation Pulse [ST10]",
    },
  ],
  selectedPrintingId: "ST10-003",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-003.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  linkCondition: "[Kamille Bidan]",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
