import type { UnitCard } from "@tcg/gundam-types";

export const st10SuperGundam004: UnitCard = {
  cardNumber: "ST10-004",
  name: "Super Gundam",
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "ST10-004",
  canonicalId: "ST10-004",
  externalIds: { bandai: "gundam:st10-004" },
  slug: "super-gundam-st10-004",
  displayName: "Super Gundam",
  rulesText: "<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)",
  set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
  printNumber: "ST10-004",
  printings: [
    {
      id: "ST10-004",
      artId: "ST10-004",
      setCode: "ST10",
      collectorNumber: "ST10-004",
      cardNumber: "ST10-004",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-004.webp",
      productName: "Generation Pulse [ST10]",
    },
    {
      id: "ST10-004-p1",
      artId: "ST10-004_p1",
      setCode: "ST10",
      collectorNumber: "ST10-004-p1",
      cardNumber: "ST10-004",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-004_p1.webp",
      productName: "Generation Pulse [ST10]",
    },
  ],
  selectedPrintingId: "ST10-004",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-004.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  battlefieldZones: ["space", "earth"],
  effect: "<Repair 2> (At the end of your turn, this Unit recovers the specified number of HP.)",
  effects: [],
  keywordEffects: [{ keyword: "Repair", value: 2 }],
  rarity: "common",
};
