import type { UnitCard } from "@tcg/gundam-types";

export const st10Nemo005: UnitCard = {
  cardNumber: "ST10-005",
  name: "Nemo",
  type: "unit",
  color: "blue",
  traits: ["g generation"],
  id: "ST10-005",
  canonicalId: "ST10-005",
  externalIds: { bandai: "gundam:st10-005" },
  slug: "nemo-st10-005",
  displayName: "Nemo",
  rulesText: "-",
  set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
  printNumber: "ST10-005",
  printings: [
    {
      id: "ST10-005",
      artId: "ST10-005",
      setCode: "ST10",
      collectorNumber: "ST10-005",
      cardNumber: "ST10-005",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-005.webp",
      productName: "Generation Pulse [ST10]",
    },
    {
      id: "ST10-005-p1",
      artId: "ST10-005_p1",
      setCode: "ST10",
      collectorNumber: "ST10-005-p1",
      cardNumber: "ST10-005",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-005_p1.webp",
      productName: "Generation Pulse [ST10]",
    },
  ],
  selectedPrintingId: "ST10-005",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-005.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
