import type { UnitCard } from "@tcg/gundam-types";

export const st10GrazeDuelType009: UnitCard = {
  cardNumber: "ST10-009",
  name: "Graze Duel Type",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "ST10-009",
  canonicalId: "ST10-009",
  externalIds: { bandai: "gundam:st10-009" },
  slug: "graze-duel-type-st10-009",
  displayName: "Graze Duel Type",
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
  printNumber: "ST10-009",
  printings: [
    {
      id: "ST10-009",
      artId: "ST10-009",
      setCode: "ST10",
      collectorNumber: "ST10-009",
      cardNumber: "ST10-009",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-009.webp",
      productName: "Generation Pulse [ST10]",
    },
    {
      id: "ST10-009-p1",
      artId: "ST10-009_p1",
      setCode: "ST10",
      collectorNumber: "ST10-009-p1",
      cardNumber: "ST10-009",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-009_p1.webp",
      productName: "Generation Pulse [ST10]",
    },
  ],
  selectedPrintingId: "ST10-009",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-009.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 3,
  linkCondition: "(G Generation) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
