import type { UnitCard } from "@tcg/gundam-types";

export const st10MobileWorkerTekkadan010: UnitCard = {
  cardNumber: "ST10-010",
  name: "Mobile Worker (Tekkadan)",
  type: "unit",
  color: "white",
  traits: ["g generation"],
  id: "ST10-010",
  canonicalId: "ST10-010",
  externalIds: { bandai: "gundam:st10-010" },
  slug: "mobile-worker-tekkadan-st10-010",
  displayName: "Mobile Worker (Tekkadan)",
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
  printNumber: "ST10-010",
  printings: [
    {
      id: "ST10-010",
      artId: "ST10-010",
      setCode: "ST10",
      collectorNumber: "ST10-010",
      cardNumber: "ST10-010",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-010.webp",
      productName: "Generation Pulse [ST10]",
    },
    {
      id: "ST10-010-p1",
      artId: "ST10-010_p1",
      setCode: "ST10",
      collectorNumber: "ST10-010-p1",
      cardNumber: "ST10-010",
      set: { code: "ST10", name: "Generation Pulse [ST10]", packageId: "616010" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-010_p1.webp",
      productName: "Generation Pulse [ST10]",
    },
  ],
  selectedPrintingId: "ST10-010",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/st10/ST10-010.webp",
  legality: "legal",
  sourceTitle: "SD Gundam G Generation ETERNAL",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 1,
  battlefieldZones: ["earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
