// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAvengerHuntingTheRebels = {
  title: "Avenger",
  subtitle: "Hunting the Rebels",
  cost: 8,
  hp: 6,
  power: 8,
  text: "When Played: Deal 1 damage to each other unit (including friendly units).",
  unique: true,
  id: "4184803715",
  rarity: "special",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "IBH",
    number: 72,
  },
  setCodes: [
    {
      set: "IBH",
      number: 72,
    },
  ],
  internalName: "avenger#hunting-the-rebels",
  cardType: "unit",
  canonicalId: "avenger#hunting-the-rebels",
  slug: "avenger-hunting-the-rebels",
  name: "Avenger",
  printings: [
    {
      id: "IBH_072",
      artId: "39190",
      setCode: "IBH",
      collectorNumber: "72",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//I01010072_EN_Avenger_c0351ad512.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Deal 1 damage to each other unit (including friendly units).",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 1,
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: true,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuAvengerHuntingTheRebels;
