// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDeathSquadronStarDestroyer = {
  title: "Death Squadron Star Destroyer",
  cost: 7,
  hp: 6,
  power: 5,
  text: "Sentinel (Enemy units in this arena must attack a Sentinel when they attack you.)",
  unique: false,
  id: "0162722840",
  rarity: "special",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "IBH",
    number: 79,
  },
  setCodes: [
    {
      set: "IBH",
      number: 79,
    },
  ],
  internalName: "death-squadron-star-destroyer",
  cardType: "unit",
  canonicalId: "death-squadron-star-destroyer",
  slug: "death-squadron-star-destroyer",
  name: "Death Squadron Star Destroyer",
  printings: [
    {
      id: "IBH_079",
      artId: "39225",
      setCode: "IBH",
      collectorNumber: "79",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//I01010079_EN_Death_Squadron_Star_Destroyer_c9822d9aa1.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuDeathSquadronStarDestroyer;
