// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuEchoCoordinator = {
  title: "Echo Coordinator",
  cost: 2,
  hp: 5,
  power: 1,
  unique: false,
  id: "2982161149",
  rarity: "special",
  aspects: ["command", "heroism"],
  traits: ["rebel"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "IBH",
    number: 43,
  },
  setCodes: [
    {
      set: "IBH",
      number: 43,
    },
  ],
  internalName: "echo-coordinator",
  cardType: "unit",
} satisfies SwuUnitCard;

export default swuEchoCoordinator;
