// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuEwebGunner = {
  title: "E-Web Gunner",
  cost: 3,
  hp: 4,
  power: 0,
  text: "Raid 4 (This unit gets +4/+0 while attacking.)",
  unique: false,
  id: "6815960456",
  rarity: "special",
  aspects: ["aggression", "villainy"],
  traits: ["imperial", "trooper"],
  arena: "ground",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "IBH",
    number: 69,
  },
  setCodes: [
    {
      set: "IBH",
      number: 69,
    },
  ],
  internalName: "eweb-gunner",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
  ],
} satisfies SwuUnitCard;

export default swuEwebGunner;
