// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSurfaceAssaultBomber = {
  title: "Surface Assault Bomber",
  cost: 2,
  hp: 3,
  power: 1,
  text: "Raid 1 (This unit gets +1/+0 while attacking.)",
  unique: false,
  id: "4100796757",
  rarity: "special",
  aspects: ["aggression", "villainy"],
  traits: ["imperial", "vehicle", "fighter"],
  arena: "space",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "IBH",
    number: 93,
  },
  setCodes: [
    {
      set: "IBH",
      number: 93,
    },
  ],
  internalName: "surface-assault-bomber",
  cardType: "unit",
  canonicalId: "surface-assault-bomber",
  slug: "surface-assault-bomber",
  name: "Surface Assault Bomber",
  printings: [
    {
      id: "IBH_093",
      artId: "39295",
      setCode: "IBH",
      collectorNumber: "93",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//I01010093_EN_Surface_Assault_Bomber_cdd6751a55.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
  ],
} satisfies SwuUnitCard;

export default swuSurfaceAssaultBomber;
