// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuCapitalCity = {
  title: "Capital City",
  hp: 30,
  unique: false,
  id: "6366665313",
  rarity: "common",
  aspects: ["vigilance"],
  types: ["base"],
  setId: {
    set: "SOR",
    number: 20,
  },
  setCodes: [
    {
      set: "SOR",
      number: 20,
    },
  ],
  internalName: "capital-city",
  cardType: "base",
} satisfies SwuBaseCard;

export default swuCapitalCity;
