// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuJedhaCity = {
  title: "Jedha City",
  hp: 25,
  text: "Epic Action: Give a non-leader unit -4/-0 for this phase.",
  unique: false,
  id: "2569134232",
  rarity: "rare",
  aspects: ["cunning"],
  types: ["base"],
  setId: {
    set: "SOR",
    number: 28,
  },
  setCodes: [
    {
      set: "SOR",
      number: 28,
    },
  ],
  internalName: "jedha-city",
  cardType: "base",
  canonicalId: "jedha-city",
  slug: "jedha-city",
  name: "Jedha City",
  printings: [
    {
      id: "SOR_028",
      artId: "311",
      setCode: "SOR",
      collectorNumber: "28",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_028_Jedha_City_Base_ac20bd51d2.png",
    },
    {
      id: "0974992247",
      artId: "311",
      setCode: "SOR",
      collectorNumber: "28",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_028_Jedha_City_Base_Foil_ae714aa51b.png",
    },
    {
      id: "1746561124",
      artId: "311",
      setCode: "SOR",
      collectorNumber: "294",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_294_Jedha_City_Base_HYP_9307aee3ea.png",
    },
    {
      id: "6159110450",
      artId: "311",
      setCode: "SOR",
      collectorNumber: "294",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01fr_294_Jedha_City_Base_HYP_df46f1a0e2.png",
    },
  ],
  abilities: [
    {
      kind: "action",
      text: "Epic Action: Give a non-leader unit -4/-0 for this phase.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          power: -4,
          hp: 0,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuBaseCard;

export default swuJedhaCity;
