// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuDaringDelve = {
  title: "Daring Delve",
  cost: 1,
  text: "Discard 2 cards from your deck. You may return a Aggression card discarded this way to your hand.",
  unique: false,
  rules: "Always discard from the top of a deck, unless an ability specifies otherwise.\n",
  id: "9273364323",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "LAW",
    number: 203,
  },
  setCodes: [
    {
      set: "LAW",
      number: 203,
    },
  ],
  internalName: "daring-delve",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Discard 2 cards from your deck. You may return a Aggression card discarded this way to your hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "discard",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuDaringDelve;
