// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuThatsARock = {
  title: "That's a Rock",
  cost: 1,
  text: "Deal 1 damage to a unit.\nWhen this event is discarded from your hand or deck: You may deal 1 damage to a unit.",
  unique: false,
  id: "8051235147",
  rarity: "uncommon",
  aspects: ["aggression"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "LAW",
    number: 206,
  },
  setCodes: [
    {
      set: "LAW",
      number: 206,
    },
  ],
  internalName: "thats-a-rock",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Deal 1 damage to a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 1,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuThatsARock;
