// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuYouHoldThis = {
  title: "You Hold This",
  cost: 1,
  text: "Choose a friendly non-leader unit. An opponent takes control of it. If they do, deal 4 damage to another unit in the same arena.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "8819729767",
  rarity: "rare",
  aspects: ["aggression", "cunning"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "LAW",
    number: 85,
  },
  setCodes: [
    {
      set: "LAW",
      number: 85,
    },
  ],
  internalName: "you-hold-this",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Choose a friendly non-leader unit. An opponent takes control of it. If they do, deal 4 damage to another unit in the same arena.",
      effects: [
        effect.takeControl(target.unit({ controller: "friendly", limit: 1 })),
        effect.damage(target.unit({ controller: "any", limit: 1 }), 4),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuYouHoldThis;
