// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuYouHoldThis = {
  title: "You Hold This",
  cost: 1,
  text: "Choose a friendly non-leader unit. An opponent takes control of it. If they do, deal 4 damage to another unit in the same arena.",
  unique: false,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "8819729767",
  rarity: "rare",
  aspects: ["aggression", "cunning"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "LAW",
    number: 85,
  },
  setCodes: [
    {
      set: "LAW",
      number: 85,
    },
  ],
  internalName: "you-hold-this",
  cardType: "event",
  canonicalId: "you-hold-this",
  slug: "you-hold-this",
  name: "You Hold This",
  printings: [
    {
      id: "LAW_085",
      artId: "46477",
      setCode: "LAW",
      collectorNumber: "85",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07010085_EN_You_Hold_This_5994efb8f0.png",
    },
    {
      id: "5352988058",
      artId: "46477",
      setCode: "LAW",
      collectorNumber: "349",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07020349_EN_You_Hold_This_ab4cd6ceb6.png",
    },
    {
      id: "0837980757",
      artId: "46477",
      setCode: "LAW",
      collectorNumber: "587",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//07320587_EN_You_Hold_This_0db0eeaff6.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Choose a friendly non-leader unit. An opponent takes control of it. If they do, deal 4 damage to another unit in the same arena.",
      effects: [
        effect.takeControl(target.unit({ controller: "friendly", limit: 1 })),
        effect.damage(target.unit({ controller: "any", limit: 1 }), 4),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuYouHoldThis;
