// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuRuthlessness = {
  title: "Ruthlessness",
  cost: 1,
  text: "Attached unit gains: “When this unit attacks and defeats a unit: Deal 2 damage to the defending player's base.”",
  unique: false,
  rules:
    "A unit “attacks and defeats a unit” if it defeats the defender at any point during the attack.\n",
  upgradePower: 2,
  upgradeHp: 0,
  id: "4897501399",
  rarity: "rare",
  aspects: ["villainy", "aggression"],
  traits: ["innate"],
  types: ["upgrade"],
  setId: {
    set: "SHD",
    number: 143,
  },
  setCodes: [
    {
      set: "SHD",
      number: 143,
    },
  ],
  internalName: "ruthlessness",
  cardType: "upgrade",
  canonicalId: "ruthlessness",
  slug: "ruthlessness",
  name: "Ruthlessness",
  printings: [
    {
      id: "SHD_143",
      artId: "6021",
      setCode: "SHD",
      collectorNumber: "143",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0201143_EN_Ruthlessness_5d2d80db15.png",
    },
    {
      id: "2980365677",
      artId: "6021",
      setCode: "SHD",
      collectorNumber: "143",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0231143_EN_Ruthlessness_57e42369b5.png",
    },
    {
      id: "7980768146",
      artId: "6021",
      setCode: "SHD",
      collectorNumber: "412",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0232412_EN_Ruthlessness_251cf172d3.png",
    },
    {
      id: "8814494233",
      artId: "6021",
      setCode: "SHD",
      collectorNumber: "412",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0202412_EN_Ruthlessness_9baa942596.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "Attached unit gains: “When this unit attacks and defeats a unit: Deal 2 damage to the defending player's base.”",
        effects: [effect.damage(target.base("opponent"), 2)],
      },
    ),
  ],
} satisfies SwuUpgradeCard;

export default swuRuthlessness;
