// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDeathStarPlans = {
  title: "Death Star Plans",
  cost: 2,
  text: "When attached unit is attacked: The attacking player takes control of this upgrade and attaches it to a unit they control.\nAttached unit gains: “The first unit you play each round costs 2 resources less.”",
  unique: false,
  rules:
    "“When attached unit is attacked” triggers at the same time as “On Attack” abilities.\nMultiple players can benefit from the discount ability in the same round.\n",
  upgradePower: 0,
  upgradeHp: 0,
  id: "7501988286",
  rarity: "legendary",
  traits: ["item"],
  types: ["upgrade"],
  setId: {
    set: "JTL",
    number: 260,
  },
  setCodes: [
    {
      set: "JTL",
      number: 260,
    },
  ],
  internalName: "death-star-plans",
  cardType: "upgrade",
  abilities: [
    ability.triggered(
      { event: "attacked" },
      {
        text: "When attached unit is attacked: The attacking player takes control of this upgrade and attaches it to a unit they control.",
        effects: [effect.takeControl(target.self())],
      },
    ),
    ability.constant({
      text: "Attached unit gains: “The first unit you play each round costs 2 resources less.”",
      effects: [effect.modifyStats(target.attachedUnit(), { power: 0 })],
    }),
  ],
} satisfies SwuUpgradeCard;

export default swuDeathStarPlans;
