// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuGrimValor = {
  title: "Grim Valor",
  cost: 1,
  text: "Attached unit gains: “When Defeated: You may exhaust a unit.”",
  unique: false,
  upgradePower: 1,
  upgradeHp: 1,
  id: "3291001746",
  rarity: "uncommon",
  aspects: ["vigilance"],
  traits: ["innate"],
  types: ["upgrade"],
  setId: {
    set: "JTL",
    number: 73,
  },
  setCodes: [
    {
      set: "JTL",
      number: 73,
    },
  ],
  internalName: "grim-valor",
  cardType: "upgrade",
  abilities: [
    ability.triggered(
      { event: "defeated" },
      {
        text: "Attached unit gains: “When Defeated: You may exhaust a unit.”",
        optional: true,
        effects: [effect.exhaust(target.unit({ controller: "any", limit: 1 }))],
      },
    ),
  ],
} satisfies SwuUpgradeCard;

export default swuGrimValor;
