// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuTargetingComputer = {
  title: "Targeting Computer",
  cost: 1,
  text: "Attached unit gains: “You assign all indirect damage dealt by this unit.”",
  unique: false,
  rules:
    "A player can't assign more indirect damage to a unit than it has remaining HP. Indirect damage is unpreventable and ignores Shields.\n",
  upgradePower: 1,
  upgradeHp: 1,
  id: "7021680131",
  rarity: "rare",
  aspects: ["aggression"],
  traits: ["item", "modification"],
  types: ["upgrade"],
  setId: {
    set: "JTL",
    number: 171,
  },
  setCodes: [
    {
      set: "JTL",
      number: 171,
    },
  ],
  internalName: "targeting-computer",
  cardType: "upgrade",
  canonicalId: "targeting-computer",
  slug: "targeting-computer",
  name: "Targeting Computer",
  printings: [
    {
      id: "JTL_171",
      artId: "20326",
      setCode: "JTL",
      collectorNumber: "171",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04010171_EN_Targeting_Computer_60bbbd56df.png",
    },
    {
      id: "2807340146",
      artId: "20326",
      setCode: "JTL",
      collectorNumber: "433",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04020433_EN_Targeting_Computer_1d0ef9470d.png",
    },
    {
      id: "5165600762",
      artId: "20326",
      setCode: "JTL",
      collectorNumber: "669",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04310669_EN_Targeting_Computer_65f79ad4b1.png",
    },
    {
      id: "3176707116",
      artId: "20326",
      setCode: "JTL",
      collectorNumber: "905",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//04320905_EN_Targeting_Computer_e4c24521c1.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "when", name: "indirect damage is assigned" },
      {
        text: "Attached unit gains: “You assign all indirect damage dealt by this unit.”",
        effects: [effect.indirectDamage(target.player("opponent"), 1)],
      },
    ),
  ],
} satisfies SwuUpgradeCard;

export default swuTargetingComputer;
