// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuSavageOpressYouMustHaveYourRevenge = {
  title: "Savage Opress",
  subtitle: "You Must Have Your Revenge",
  cost: 6,
  hp: 7,
  power: 3,
  text: "Each friendly unit with the most power among friendly units gains Overwhelm. (When attacking an enemy unit, deal excess damage to the opponent's base.)",
  deployBox:
    "Raid 3 (This unit gets +3/+0 while attacking.)\nOverwhelm\nEach other friendly unit gains Overwhelm.",
  epicAction: "Epic Action: If you control 6 or more resources, deploy this leader.",
  unique: true,
  rules:
    "Shields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\nAbilities that refer to a card’s power include temporary modifiers.\nIf multiple friendly units are tied for the most power, they each gain Overwhelm.\n",
  id: "4061486636",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["force", "underworld"],
  arena: "ground",
  keywords: ["overwhelm", "raid"],
  types: ["leader"],
  setId: {
    set: "TS26",
    number: 5,
  },
  setCodes: [
    {
      set: "TS26",
      number: 5,
    },
  ],
  internalName: "savage-opress#you-must-have-your-revenge",
  cardType: "leader",
  canonicalId: "savage-opress#you-must-have-your-revenge",
  slug: "savage-opress-you-must-have-your-revenge",
  name: "Savage Opress",
  printings: [
    {
      id: "TS26_005",
      artId: "50877",
      setCode: "TS26",
      collectorNumber: "5",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//TS_26010005_EN_Savage_Opress_Leader_65f566fc07.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "action",
      text: "Epic Action: If you control 6 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuSavageOpressYouMustHaveYourRevenge;
