import type { UnitCard } from "@tcg/gundam-types";

export const st09ZakuWarrior005: UnitCard = {
  cardNumber: "ST09-005",
  name: "Zaku Warrior",
  type: "unit",
  color: "purple",
  traits: ["zaft", "minerva squad"],
  id: "ST09-005",
  externalId: "gundam:st09-005",
  slug: "zaku-warrior-st09-005",
  displayName: "Zaku Warrior",
  set: { code: "ST09", name: "Destiny Ignition [ST09]", packageId: "616009" },
  printNumber: "ST09-005",
  printings: [
    {
      id: "ST09-005",
      collectorNumber: "ST09-005",
      cardNumber: "ST09-005",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-005.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
    {
      id: "ST09-005_p1",
      collectorNumber: "ST09-005_p1",
      cardNumber: "ST09-005",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-005_p1.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  selectedPrintingId: "ST09-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-005.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
