import type { UnitCard } from "@tcg/gundam-types";

export const st09BlastImpulseGundam007: UnitCard = {
  cardNumber: "ST09-007",
  name: "Blast Impulse Gundam",
  type: "unit",
  color: "purple",
  traits: ["zaft", "minerva squad"],
  id: "ST09-007",
  externalId: "gundam:st09-007",
  slug: "blast-impulse-gundam-st09-007",
  displayName: "Blast Impulse Gundam",
  set: { code: "ST09", name: "Destiny Ignition [ST09]", packageId: "616009" },
  printNumber: "ST09-007",
  printings: [
    {
      id: "ST09-007",
      collectorNumber: "ST09-007",
      cardNumber: "ST09-007",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-007.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
    {
      id: "ST09-007_p1",
      collectorNumber: "ST09-007_p1",
      cardNumber: "ST09-007",
      set: {
        code: "ST09",
        name: "Destiny Ignition [ST09]",
        packageId: "616009",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-007_p1.webp?260424",
      productName: "Destiny Ignition [ST09]",
    },
  ],
  selectedPrintingId: "ST09-007",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st09/ST09-007.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST09-007.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 3,
  linkCondition: "[Shinn Asuka]",
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
