import {
  aWholeNewWorld,
  befuddle,
  beOurGuest,
  bePrepared,
  breakAction,
  controlYourTemper,
  cutToTheChase,
  developYourBrain,
  doItAgain,
  dragonFire,
  fanTheFlames,
  fireTheCannons,
  freeze,
  friendsOnTheOtherSide,
  grabYourSword,
  hakunaMatata,
  healingGlow,
  hesGotASword,
  ifItsNotBaroque,
  justInTime,
  letItGo,
  motherKnowsBest,
  oneJumpAhead,
  partOfYourWorld,
  ransack,
  reflection,
  smash,
  stampede,
  stealFromRich,
  suddenChill,
  tangle,
  theBeastIsMine,
  viciousBetrayal,
  workTogether,
  youHaveForgottenMe,
} from "~/game-engine/engines/lorcana/src/cards/definitions/001/actions";
import type { LorcanaCardDefinition } from "~/game-engine/engines/lorcana/src/cards/lorcana-card-repository";

export const allTFCCards: LorcanaCardDefinition[] = [
  aWholeNewWorld,
  befuddle,
  beOurGuest,
  bePrepared,
  breakAction,
  controlYourTemper,
  cutToTheChase,
  developYourBrain,
  doItAgain,
  dragonFire,
  fanTheFlames,
  fireTheCannons,
  freeze,
  friendsOnTheOtherSide,
  grabYourSword,
  hakunaMatata,
  healingGlow,
  hesGotASword,
  ifItsNotBaroque,
  justInTime,
  letItGo,
  motherKnowsBest,
  oneJumpAhead,
  partOfYourWorld,
  ransack,
  reflection,
  smash,
  stampede,
  stealFromRich,
  suddenChill,
  tangle,
  theBeastIsMine,
  viciousBetrayal,
  workTogether,
  youHaveForgottenMe,
];

export const allTFCCardsById: Record<string, LorcanaCardDefinition> = {};
for (const card of allTFCCards) {
  allTFCCardsById[card.id] = card;
}
