import type { GundamitoUnitCard } from "../../cardTypes";

export const wingGundamST02001: GundamitoUnitCard = {
  id: "ST02-001",
  implemented: true,
  cost: 4,
  level: 6,
  number: 1,
  type: "unit",
  name: "Wing Gundam | XXXG-01W",
  color: "green",
  set: "ST02",
  rarity: "legendary",
  zones: ["space", "earth"],
  traits: ["operation meteor"],
  linkRequirement: ["heero yuy"],
  ap: 4,
  hp: 5,
  abilities: [],
};

export const wingGundamBirdModeST02002: GundamitoUnitCard = {
  id: "ST02-002",
  implemented: true,
  cost: 3,
  level: 3,
  number: 2,
  type: "unit",
  name: "Wing Gundam (Bird Mode) | XXXG-01W",
  color: "green",
  set: "ST02",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["operation meteor"],
  linkRequirement: ["heero yuy"],
  ap: 2,
  hp: 2,
  abilities: [],
};

export const maganacWMS03: GundamitoUnitCard = {
  id: "ST02-005",
  implemented: true,
  cost: 2,
  level: 2,
  number: 5,
  type: "unit",
  name: "Maganac | WMS-03",
  color: "green",
  set: "ST02",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["maganac corps"],
  linkRequirement: [""],
  ap: 3,
  hp: 2,
  abilities: [],
};
