/**
 * Hero → special UI requirements for the FAB simulator.
 *
 * Scope: identities that need UI **beyond** the universal playmat (life,
 * resources, AP, hand/deck/pitch/GY/arsenal, equipment, weapons, combat chain).
 * Young/adult moniker variants share one entry unless noted.
 */

import type { FabUiModuleId } from "./modules";

export type FabHeroSpecialTier = "A" | "B" | "C";

export interface FabHeroSpecialUiRequirement {
  /** Stable id for fixtures and tests. */
  readonly id: string;
  /** Display name (family). */
  readonly hero: string;
  /** Representative catalog slugs (adult and/or young). */
  readonly slugs: readonly string[];
  /** A = dedicated special UI; B = one clear extra system; C = baseline only. */
  readonly tier: FabHeroSpecialTier;
  readonly classOrTalent: string;
  /** Human-readable what to show (UX checklist). */
  readonly mustShow: readonly string[];
  /** Shared modules to compose. */
  readonly modules: readonly FabUiModuleId[];
  /** Signature tokens / permanents (names as printed). */
  readonly signatureTokens: readonly string[];
  /** Notes for UX / product. */
  readonly notes?: string;
  /** Whether a visual text fixture is required (Tier A + B with unique chrome). */
  readonly hasTextFixture: boolean;
}

/**
 * Heroes that need special UI validation. Tier C baseline heroes are omitted —
 * they pass with the universal playmat alone.
 */
export const HERO_SPECIAL_UI_CATALOG: readonly FabHeroSpecialUiRequirement[] = [
  // ── Tier A ──────────────────────────────────────────────────────────────
  {
    id: "dromai",
    hero: "Dromai",
    slugs: ["dromai-ash-artist", "dromai"],
    tier: "A",
    classOrTalent: "Draconic Illusionist",
    mustShow: [
      "Ash token stack with count",
      "Dragon allies with power/life",
      "Ash as material under dragons (sub-cards)",
      "Played a red card this turn status (dragons get go again)",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "permanent-allies",
      "permanent-material-under",
      "hero-status-flags",
    ],
    signatureTokens: ["Ash", "Aether Ashwing", "Dragon allies"],
    notes: "Phantasm on material under dragons must be readable on the permanent.",
    hasTextFixture: true,
  },
  {
    id: "levia",
    hero: "Levia",
    slugs: ["levia-shadowborn-abomination", "levia"],
    tier: "A",
    classOrTalent: "Shadow Brute",
    mustShow: [
      "Banished zone as primary economy display",
      "Blood-debt card count (pending end-phase life loss)",
      "Mitigation active when a 6+{p} card entered banished this turn",
      "No separate blood-debt mana pool on the hero",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "banished-inspector",
      "banished-blood-debt",
      "hero-status-flags",
      "turn-status-ledger",
    ],
    signatureTokens: [],
    notes: "Blood Debt is a keyword on banished cards (CR 8.3.11), not a hero counter resource.",
    hasTextFixture: true,
  },
  {
    id: "chane",
    hero: "Chane",
    slugs: ["chane-bound-by-shadow", "chane"],
    tier: "A",
    classOrTalent: "Shadow Runeblade",
    mustShow: [
      "Soul Shackle token stack",
      "Banished zone with blood-debt cards",
      "Blood-debt pending life loss",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "banished-inspector",
      "banished-blood-debt",
      "banished-playable",
    ],
    signatureTokens: ["Soul Shackle", "Runechant (from package)"],
    hasTextFixture: true,
  },
  {
    id: "vynnset",
    hero: "Vynnset",
    slugs: ["vynnset-iron-maiden", "vynnset"],
    tier: "A",
    classOrTalent: "Shadow Runeblade",
    mustShow: [
      "Runechant stack",
      "Start-of-turn banish prompt feedback",
      "Optional pay-{h} unpreventable Runechant flag this turn",
      "Banished + blood debt",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "banished-inspector",
      "banished-blood-debt",
      "hero-status-flags",
    ],
    signatureTokens: ["Runechant"],
    hasTextFixture: true,
  },
  {
    id: "boltyn",
    hero: "Boltyn",
    slugs: ["ser-boltyn-breaker-of-dawn", "boltyn"],
    tier: "A",
    classOrTalent: "Light Warrior",
    mustShow: [
      "Soul under hero (count + inspect)",
      "Charged this turn status",
      "Banish-from-soul attack reaction affordance",
    ],
    modules: ["asset-bar-resources-ap-life", "hero-soul", "hero-signal-edge"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "prism-sculptor",
    hero: "Prism (Sculptor of Arc Light)",
    slugs: ["prism-sculptor-of-arc-light", "prism"],
    tier: "A",
    classOrTalent: "Light Illusionist",
    mustShow: [
      "Soul under hero",
      "Spectral Shield token stack",
      "Banish-from-soul → create Spectral Shield",
    ],
    modules: ["asset-bar-resources-ap-life", "hero-soul", "permanent-token-stacks"],
    signatureTokens: ["Spectral Shield"],
    hasTextFixture: true,
  },
  {
    id: "prism-awakener",
    hero: "Prism (Awakener / Advent)",
    slugs: ["prism-awakener-of-sol", "prism-advent-of-thrones"],
    tier: "A",
    classOrTalent: "Light Illusionist",
    mustShow: [
      "Soul under hero",
      "Figment permanents in arena",
      "Awaken figment interaction",
      "Herald-to-soul → search figment feedback",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "hero-soul",
      "permanent-allies",
      "permanent-token-stacks",
    ],
    signatureTokens: ["Spectral Shield", "Figments"],
    hasTextFixture: true,
  },
  {
    id: "nuu",
    hero: "Nuu",
    slugs: ["nuu-alluring-desire", "nuu"],
    tier: "A",
    classOrTalent: "Mystic Assassin",
    mustShow: [
      "Chi point asset",
      "Opponent banished (blue play-from-theirs)",
      "Chain-link resolve: defending actions banished",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "asset-bar-chi",
      "banished-inspector",
      "banished-playable",
    ],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "enigma",
    hero: "Enigma",
    slugs: ["enigma-ledger-of-ancestry", "enigma", "enigma-new-moon"],
    tier: "A",
    classOrTalent: "Mystic Illusionist",
    mustShow: [
      "Chi point asset",
      "Spectral Shield tokens (with +1{p} counters)",
      "New Moon: cloaked face-down equipment",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "asset-bar-chi",
      "permanent-token-stacks",
      "equipment-face-down",
    ],
    signatureTokens: ["Spectral Shield"],
    hasTextFixture: true,
  },
  {
    id: "zen",
    hero: "Zen",
    slugs: ["zen-tamer-of-purpose", "zen"],
    tier: "A",
    classOrTalent: "Mystic Ninja",
    mustShow: [
      "Chi point asset",
      "Crouching Tiger created into hand",
      "Combo card banished face-up may-play-this-turn",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "asset-bar-chi",
      "banished-inspector",
      "banished-playable",
      "turn-status-ledger",
    ],
    signatureTokens: ["Crouching Tiger"],
    hasTextFixture: true,
  },
  {
    id: "maxx",
    hero: "Maxx Nitro",
    slugs: ["maxx-the-hype-nitro", "maxx-nitro"],
    tier: "A",
    classOrTalent: "Mechanologist",
    mustShow: [
      "Hyper Driver items with steam counters",
      "Crank state on Hyper Drivers",
      "Boosted this turn gate for hero ability",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "permanent-allies",
      "hero-status-flags",
      "turn-status-ledger",
    ],
    signatureTokens: ["Hyper Driver"],
    notes: "Steam counters and crank are the core chrome — treat items as first-class permanents.",
    hasTextFixture: true,
  },
  {
    id: "dash",
    hero: "Dash",
    slugs: ["dash-inventor-extraordinaire", "dash", "dash-i-o", "dash-database"],
    tier: "A",
    classOrTalent: "Mechanologist",
    mustShow: [
      "Starting Mechanologist item in arena (classic)",
      "I/O: top-of-deck always peekable",
      "I/O: play cheap item from top as instant (+{r})",
      "Items with steam counters when present",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "permanent-allies",
      "turn-status-ledger",
    ],
    signatureTokens: ["Mechanologist items", "Hyper Driver (package)"],
    hasTextFixture: true,
  },
  {
    id: "teklovossen",
    hero: "Teklovossen",
    slugs: ["teklovossen-esteemed-magnate", "teklovossen", "professor-teklovossen"],
    tier: "A",
    classOrTalent: "Mechanologist",
    mustShow: [
      "Evos playable from banished",
      "Banished inspector with Evo highlights",
      "Next Evo as instant this turn flag",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "banished-inspector",
      "banished-playable",
      "permanent-allies",
      "hero-status-flags",
    ],
    signatureTokens: ["Evo constructs/equipment"],
    hasTextFixture: true,
  },
  {
    id: "data-doll",
    hero: "Data Doll MKII",
    slugs: ["data-doll-mkii"],
    tier: "A",
    classOrTalent: "Mechanologist",
    mustShow: [
      "Banished → arena auto for cheap Mechanologist items",
      "Items entering permanent zone mid-resolution",
    ],
    modules: ["asset-bar-resources-ap-life", "banished-inspector", "permanent-allies"],
    signatureTokens: ["Mechanologist items"],
    hasTextFixture: true,
  },
  {
    id: "malice",
    hero: "Malice",
    slugs: ["malice-domina-of-the-dead", "malice"],
    tier: "A",
    classOrTalent: "Necromancer",
    mustShow: [
      "Zombie allies in permanent zone",
      "On death: face-down banished + Corrupted Corpse in banished",
      "Play zombie from graveyard window",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-allies",
      "banished-inspector",
      "turn-status-ledger",
    ],
    signatureTokens: ["Zombie allies", "Corrupted Corpse"],
    hasTextFixture: true,
  },
  {
    id: "gravy-bones",
    hero: "Gravy Bones",
    slugs: ["gravy-bones-shipwrecked-looter", "gravy-bones"],
    tier: "A",
    classOrTalent: "Pirate Necromancer",
    mustShow: [
      "Gold token stack",
      "Watery grave play-from-GY when blue hit GY this turn",
      "Gold sink activation (draw then discard)",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "banished-playable",
      "hero-status-flags",
      "turn-status-ledger",
    ],
    signatureTokens: ["Gold"],
    notes: "Play-from-graveyard uses GY inspector with watery-grave legality, not banished.",
    hasTextFixture: true,
  },
  {
    id: "viserai",
    hero: "Viserai (classic)",
    slugs: ["viserai-rune-blood", "viserai"],
    tier: "A",
    classOrTalent: "Runeblade",
    mustShow: ["Runechant stack count (critical for Rune Gate packages)"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Runechant"],
    hasTextFixture: true,
  },
  {
    id: "viserai-forsaken",
    hero: "Viserai (Forsaken / Between Worlds)",
    slugs: ["viserai-the-forsaken", "viserai-between-worlds"],
    tier: "A",
    classOrTalent: "Shadow Runeblade",
    mustShow: [
      "Runechant stack",
      "Auto-banish top of deck on create Runechants",
      "3+ Runechants this turn → traverse affordance",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "banished-inspector",
      "turn-status-ledger",
      "hero-status-flags",
    ],
    signatureTokens: ["Runechant"],
    hasTextFixture: true,
  },
  {
    id: "viserai-usurper",
    hero: "Viserai Usurper",
    slugs: ["viserai-usurper"],
    tier: "A",
    classOrTalent: "Shadow Runeblade Demon",
    mustShow: [
      "Blood-debt attack package UI",
      "Gate to i'Arathael permanent / activation",
      "Traverse at end phase when gate used",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "banished-blood-debt",
      "banished-inspector",
      "permanent-allies",
      "hero-status-flags",
    ],
    signatureTokens: ["Gate to i'Arathael"],
    hasTextFixture: true,
  },
  {
    id: "baalghor",
    hero: "Baalghor",
    slugs: ["baalghor-omen-of-the-end"],
    tier: "A",
    classOrTalent: "Shadow Demon",
    mustShow: [
      "Pitch always banishes (pitch zone may stay empty)",
      "Attack actions playable from banished at +3{p}",
      "Banished as main resource display",
    ],
    modules: ["asset-bar-resources-ap-life", "banished-inspector", "banished-playable"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "arakni-chaos",
    hero: "Arakni (Chaos / Marionette)",
    slugs: ["arakni-marionette", "arakni-web-of-deceit"],
    tier: "A",
    classOrTalent: "Chaos Assassin",
    mustShow: [
      "Marked status on opponents",
      "End-phase Agent of Chaos transformation UI",
      "Stealth go-again feedback on hits",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "marked-status",
      "agent-of-chaos",
      "hero-status-flags",
    ],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "cindra",
    hero: "Cindra",
    slugs: ["cindra-dracai-of-retribution", "cindra"],
    tier: "A",
    classOrTalent: "Royal Draconic Ninja",
    mustShow: [
      "Marked opponents",
      "Fealty token stack",
      "Re-equip Draconic daggers from graveyard",
      "Draconic chain-link count for discount",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "marked-status",
      "permanent-token-stacks",
      "turn-status-ledger",
    ],
    signatureTokens: ["Fealty"],
    hasTextFixture: true,
  },
  {
    id: "fang",
    hero: "Fang",
    slugs: ["fang-dracai-of-blades", "fang"],
    tier: "A",
    classOrTalent: "Royal Draconic Warrior",
    mustShow: ["Marked opponents", "Fealty token stack (threshold 3 for dagger discount)"],
    modules: [
      "asset-bar-resources-ap-life",
      "marked-status",
      "permanent-token-stacks",
      "turn-status-ledger",
    ],
    signatureTokens: ["Fealty"],
    hasTextFixture: true,
  },
  {
    id: "blaze",
    hero: "Blaze Firemind",
    slugs: ["blaze-firemind"],
    tier: "A",
    classOrTalent: "Wizard",
    mustShow: [
      "Energy counters on the hero card",
      "Spend X energy for arcane play-as-instant",
      "Opt → add energy counters feedback",
    ],
    modules: ["asset-bar-resources-ap-life", "hero-counters", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "taylor",
    hero: "Taylor",
    slugs: ["taylor"],
    tier: "A",
    classOrTalent: "Shapeshifter",
    mustShow: [
      "Inventory of equipment (different names)",
      "Start-of-turn banish equip → equip from inventory",
    ],
    modules: ["asset-bar-resources-ap-life", "inventory-zone"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "librarian",
    hero: "The Librarian",
    slugs: ["the-librarian-magister-of-history"],
    tier: "A",
    classOrTalent: "Light Adjudicator",
    mustShow: [
      "Inventory of Tomes",
      "Reveal Tome from inventory → hand",
      "Temporary +intellect on another hero",
    ],
    modules: ["asset-bar-resources-ap-life", "inventory-zone", "hero-status-flags"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "zyggy",
    hero: "Zyggy",
    slugs: ["zyggy-starlight", "zyggy"],
    tier: "A",
    classOrTalent: "Lightning Illusionist",
    mustShow: [
      "Lightning Flow tokens",
      "Holo counters on Lightning auras",
      "Banish/return aura with holo flow",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "permanent-allies"],
    signatureTokens: ["Lightning Flow"],
    hasTextFixture: true,
  },
  {
    id: "aurora-flow",
    hero: "Aurora (Lightning Flow)",
    slugs: ["aurora-legacy-of-tempest", "aurora-emissary-of-lightning"],
    tier: "A",
    classOrTalent: "Lightning Runeblade",
    mustShow: ["Lightning Flow tokens", "Embodiment of Lightning from Flow sink"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Lightning Flow", "Embodiment of Lightning"],
    hasTextFixture: true,
  },
  {
    id: "oscilio-flow",
    hero: "Oscilio (Lightning Flow)",
    slugs: ["oscilio-forked-continuum", "oscilio-scion-of-the-third-age"],
    tier: "A",
    classOrTalent: "Lightning Wizard",
    mustShow: ["Lightning Flow tokens", "Ponder tokens", "Discarded instant may-play-this-turn"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Lightning Flow", "Ponder"],
    hasTextFixture: true,
  },
  {
    id: "pleiades",
    hero: "Pleiades",
    slugs: ["pleiades-superstar", "pleiades"],
    tier: "A",
    classOrTalent: "Guardian (Superstar)",
    mustShow: [
      "Suspense counters on auras (move between them)",
      "Confidence tokens",
      "Crowd cheers status",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "permanent-allies",
      "crowd-status",
    ],
    signatureTokens: ["Confidence", "Suspense auras"],
    hasTextFixture: true,
  },
  {
    id: "fai",
    hero: "Fai",
    slugs: ["fai-rising-rebellion", "fai"],
    tier: "A",
    classOrTalent: "Draconic Ninja",
    mustShow: [
      "Phoenix Flame in graveyard (starts there)",
      "Recycle Phoenix Flame to hand",
      "Draconic chain-link count for cost reduction",
    ],
    modules: ["asset-bar-resources-ap-life", "turn-status-ledger", "hero-status-flags"],
    signatureTokens: ["Phoenix Flame"],
    hasTextFixture: true,
  },
  {
    id: "kassai-cintari",
    hero: "Kassai (Cintari Sellsword)",
    slugs: ["kassai-cintari-sellsword"],
    tier: "A",
    classOrTalent: "Warrior",
    mustShow: [
      "Copper token stack",
      "Weapon attacks this turn / hits tracking",
      "Second sword attack cost reduction",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Copper", "Cintari Sellsword (package)"],
    hasTextFixture: true,
  },
  {
    id: "kassai-golden",
    hero: "Kassai (Golden Sand)",
    slugs: ["kassai-of-the-golden-sand", "kassai"],
    tier: "A",
    classOrTalent: "Warrior",
    mustShow: [
      "Gold token creation on weapon hit",
      "Drew a card this turn (sword discount)",
      "Graveyard banish cost for Gold setup",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "permanent-token-stacks",
      "hero-status-flags",
      "turn-status-ledger",
    ],
    signatureTokens: ["Gold"],
    hasTextFixture: true,
  },
  {
    id: "victor",
    hero: "Victor Goldmane",
    slugs: ["victor-goldmane-high-and-mighty", "victor-goldmane", "victor-goldmane-match-fixer"],
    tier: "A",
    classOrTalent: "Guardian",
    mustShow: [
      "Gold token stack",
      "Clash UI (fail → pay Gold to re-clash)",
      "First Gold created this turn → draw feedback",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Gold"],
    hasTextFixture: true,
  },
  {
    id: "olympia",
    hero: "Olympia",
    slugs: ["olympia-prized-fighter", "olympia"],
    tier: "A",
    classOrTalent: "Warrior",
    mustShow: ["Gold on first wager win per attack", "Wager resolution UI"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Gold"],
    hasTextFixture: true,
  },
  {
    id: "puffin",
    hero: "Puffin",
    slugs: ["puffin-hightail", "puffin"],
    tier: "A",
    classOrTalent: "Mechanologist Pirate",
    mustShow: [
      "Gold tokens",
      "Golden Cog with steam counters + crank",
      "Second crank this turn → draw",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Gold", "Golden Cog"],
    hasTextFixture: true,
  },
  {
    id: "marlynn",
    hero: "Marlynn",
    slugs: ["marlynn-treasure-hunter", "marlynn"],
    tier: "A",
    classOrTalent: "Ranger Pirate",
    mustShow: [
      "Gold tokens",
      "Goldfin Harpoon into hand from Gold sink",
      "Face-up arrows into arsenal from draws",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "arsenal-orientation"],
    signatureTokens: ["Gold", "Goldfin Harpoon"],
    hasTextFixture: true,
  },
  {
    id: "scurv",
    hero: "Scurv",
    slugs: ["scurv-stowaway"],
    tier: "A",
    classOrTalent: "Pirate",
    mustShow: ["Gold tokens", "Goldkiss Rum tokens", "Activate Rum → gain {r}"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Gold", "Goldkiss Rum"],
    hasTextFixture: true,
  },
  {
    id: "valda",
    hero: "Valda",
    slugs: ["valda-seismic-impact", "valda-brightaxe"],
    tier: "A",
    classOrTalent: "Guardian",
    mustShow: [
      "Seismic Surge token stack",
      "Threshold 3 → crush dominate status this turn",
      "Opponent draw during action phase feedback",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "hero-status-flags"],
    signatureTokens: ["Seismic Surge"],
    hasTextFixture: true,
  },
  {
    id: "iyslander",
    hero: "Iyslander",
    slugs: ["iyslander-stormbind", "iyslander"],
    tier: "A",
    classOrTalent: "Elemental Wizard",
    mustShow: [
      "Frostbite under opponent control",
      "Blue non-attack from arsenal as instant off-turn",
      "Arsenal orientation",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "arsenal-orientation"],
    signatureTokens: ["Frostbite"],
    hasTextFixture: true,
  },
  {
    id: "lexi",
    hero: "Lexi",
    slugs: ["lexi-livewire", "lexi"],
    tier: "A",
    classOrTalent: "Elemental Ranger",
    mustShow: [
      "Arsenal face-down → face-up flip",
      "Frostbite under target hero",
      "Lightning branch go-again flag",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "arsenal-orientation",
      "permanent-token-stacks",
      "hero-status-flags",
    ],
    signatureTokens: ["Frostbite"],
    hasTextFixture: true,
  },
  {
    id: "jarl",
    hero: "Jarl Vetreiði",
    slugs: ["jarl-vetrei-i"],
    tier: "A",
    classOrTalent: "Elemental Guardian",
    mustShow: ["Frostbite placed into opponent exposed equipment zones (head/chest/arms/legs)"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Frostbite"],
    notes: "Frostbite is not only an aura row — can occupy exposed equipment slots.",
    hasTextFixture: true,
  },
  {
    id: "briar",
    hero: "Briar",
    slugs: ["briar-warden-of-thorns", "briar"],
    tier: "A",
    classOrTalent: "Elemental Runeblade",
    mustShow: [
      "Embodiment of Earth tokens",
      "Embodiment of Lightning tokens",
      "Second non-attack this turn tracking",
    ],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "turn-status-ledger"],
    signatureTokens: ["Embodiment of Earth", "Embodiment of Lightning"],
    hasTextFixture: true,
  },
  {
    id: "aurora-classic",
    hero: "Aurora (classic)",
    slugs: ["aurora-shooting-star", "aurora"],
    tier: "A",
    classOrTalent: "Elemental Runeblade",
    mustShow: ["Embodiment of Lightning tokens", "Played a Lightning card this turn gate"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "hero-status-flags"],
    signatureTokens: ["Embodiment of Lightning"],
    hasTextFixture: true,
  },
  {
    id: "tuffnut",
    hero: "Tuffnut",
    slugs: ["tuffnut-bumbling-hulkster", "tuffnut"],
    tier: "A",
    classOrTalent: "Revered Brute",
    mustShow: ["Cheered and Booed independently when active", "Toughness tokens"],
    modules: ["asset-bar-resources-ap-life", "hero-signal-edge", "permanent-token-stacks"],
    signatureTokens: ["Toughness"],
    hasTextFixture: true,
  },
  {
    id: "lyath",
    hero: "Lyath Goldmane",
    slugs: ["lyath-goldmane-vile-savant", "lyath-goldmane"],
    tier: "A",
    classOrTalent: "Reviled Guardian",
    mustShow: ["Crowd boos status", "Might tokens", "Halved base power/defense presentation"],
    modules: ["asset-bar-resources-ap-life", "crowd-status", "permanent-token-stacks"],
    signatureTokens: ["Might"],
    hasTextFixture: true,
  },
  {
    id: "kayo-sup",
    hero: "Kayo (Super Slam)",
    slugs: ["kayo-underhanded-cheat", "kayo-strong-arm"],
    tier: "A",
    classOrTalent: "Brute",
    mustShow: [
      "Single weapon zone",
      "Crowd boos",
      "Vigor tokens",
      "Set base power 6 ability feedback",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "weapon-zone-count",
      "crowd-status",
      "permanent-token-stacks",
    ],
    signatureTokens: ["Vigor"],
    hasTextFixture: true,
  },
  {
    id: "kayo-hvy",
    hero: "Kayo (Heavy Hitters)",
    slugs: ["kayo-armed-and-dangerous", "kayo"],
    tier: "A",
    classOrTalent: "Brute",
    mustShow: [
      "Single weapon zone",
      "Might tokens from 6+ discards",
      "Power buff off combat chain",
    ],
    modules: [
      "asset-bar-resources-ap-life",
      "weapon-zone-count",
      "permanent-token-stacks",
      "turn-status-ledger",
    ],
    signatureTokens: ["Might"],
    hasTextFixture: true,
  },
  {
    id: "uzuri",
    hero: "Uzuri",
    slugs: ["uzuri-switchblade", "uzuri"],
    tier: "A",
    classOrTalent: "Assassin",
    mustShow: ["Temporary face-down banished from hand", "Reveal then swap onto active chain link"],
    modules: ["asset-bar-resources-ap-life", "banished-inspector", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "kano",
    hero: "Kano",
    slugs: ["kano-dracai-of-aether", "kano"],
    tier: "A",
    classOrTalent: "Wizard",
    mustShow: ["Top-deck look result", "Banished non-attack playable as instant this turn"],
    modules: [
      "asset-bar-resources-ap-life",
      "banished-inspector",
      "banished-playable",
      "turn-status-ledger",
    ],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "florian",
    hero: "Florian",
    slugs: ["florian-rotwood-harbinger", "florian"],
    tier: "A",
    classOrTalent: "Elemental Illusionist",
    mustShow: ["Aura tokens created (extra +1 replacement)", "Clear token stack growth on create"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Aura tokens (various)"],
    hasTextFixture: true,
  },
  {
    id: "yorick",
    hero: "Yorick",
    slugs: ["yorick-weaver-of-tales"],
    tier: "A",
    classOrTalent: "Bard",
    mustShow: ["Shared deck for all heroes", "Shared graveyard for all heroes"],
    modules: ["asset-bar-resources-ap-life", "shared-deck-gy"],
    signatureTokens: [],
    notes: "Format-breaking layout — do not hide shared zones as per-player piles.",
    hasTextFixture: true,
  },
  {
    id: "melody",
    hero: "Melody",
    slugs: ["melody-sing-along"],
    tier: "A",
    classOrTalent: "Bard",
    mustShow: ["Copper tokens equal to other heroes (multiplayer scale)"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Copper"],
    hasTextFixture: true,
  },
  {
    id: "brevant",
    hero: "Brevant",
    slugs: ["brevant-civic-protector"],
    tier: "A",
    classOrTalent: "Guardian",
    mustShow: ["Might tokens on protect", "Protect another hero multiplayer feedback"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Might"],
    hasTextFixture: true,
  },
  {
    id: "terra",
    hero: "Terra",
    slugs: ["terra"],
    tier: "A",
    classOrTalent: "Elemental Guardian",
    mustShow: ["Might from Earth in pitch at end phase"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Might"],
    hasTextFixture: true,
  },
  {
    id: "reya",
    hero: "Reya",
    slugs: ["reya-the-unyielding"],
    tier: "A",
    classOrTalent: "Guardian Pit-Fighter",
    mustShow: ["Protect keyword feedback", "Gold on protect another hero"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Gold"],
    hasTextFixture: true,
  },
  {
    id: "squizzy",
    hero: "Squizzy & Floof",
    slugs: ["squizzy-floof"],
    tier: "A",
    classOrTalent: "Merchant",
    mustShow: ["Opponent may create Cracked Bauble", "Gold when they do"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Gold", "Cracked Bauble"],
    hasTextFixture: true,
  },
  {
    id: "genis",
    hero: "Genis Wotchuneed",
    slugs: ["genis-wotchuneed"],
    tier: "A",
    classOrTalent: "Merchant",
    mustShow: ["Silver tokens from other heroes cycling hand"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Silver"],
    hasTextFixture: true,
  },
  {
    id: "kavdaen",
    hero: "Kavdaen",
    slugs: ["kavdaen-trader-of-skins"],
    tier: "A",
    classOrTalent: "Merchant",
    mustShow: ["Copper tokens", "Life equalization action feedback"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Copper"],
    hasTextFixture: true,
  },
  {
    id: "fightmaster-kox",
    hero: "Fightmaster Kox",
    slugs: ["fightmaster-kox"],
    tier: "A",
    classOrTalent: "Guardian Pit-Fighter",
    mustShow: ["Gold sink", "Event deck look / reorder"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks", "event-deck"],
    signatureTokens: ["Gold"],
    hasTextFixture: true,
  },
  {
    id: "betsy",
    hero: "Betsy",
    slugs: ["betsy-skin-in-the-game", "betsy"],
    tier: "A",
    classOrTalent: "Guardian",
    mustShow: ["Wager UI", "Optional pay {r}{r} for +1{p} overpower"],
    modules: ["asset-bar-resources-ap-life", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },

  // ── Tier B ──────────────────────────────────────────────────────────────
  {
    id: "azalea",
    hero: "Azalea",
    slugs: ["azalea-ace-in-the-hole", "azalea"],
    tier: "B",
    classOrTalent: "Ranger",
    mustShow: ["Arsenal face-up arrows", "Arsenal reload action"],
    modules: ["asset-bar-resources-ap-life", "arsenal-orientation"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "riptide",
    hero: "Riptide",
    slugs: ["riptide-lurker-of-the-deep", "riptide"],
    tier: "B",
    classOrTalent: "Ranger",
    mustShow: ["Extra arsenal load from hand", "Trap trigger damage feedback"],
    modules: ["asset-bar-resources-ap-life", "arsenal-orientation", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "dorinthea",
    hero: "Dorinthea",
    slugs: ["dorinthea-ironsong", "dorinthea", "dorinthea-quicksilver-prodigy"],
    tier: "B",
    classOrTalent: "Warrior",
    mustShow: ["Extra weapon attack this turn flag"],
    modules: ["asset-bar-resources-ap-life", "hero-status-flags", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "hala",
    hero: "Hala",
    slugs: ["hala-bladesaint-of-the-vow", "hala"],
    tier: "B",
    classOrTalent: "Warrior",
    mustShow: ["Sharpen +1{p} counters on swords (end-phase cleanup)"],
    modules: ["asset-bar-resources-ap-life", "hero-status-flags"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "rhinar",
    hero: "Rhinar",
    slugs: ["rhinar-reckless-rampage", "rhinar"],
    tier: "B",
    classOrTalent: "Brute",
    mustShow: [
      "Intimidate count this turn (including an empty opposing hand)",
      "Intimidate face-down temporary banished from hand",
    ],
    modules: ["asset-bar-resources-ap-life", "hero-signal-edge", "banished-inspector"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "katsu",
    hero: "Katsu",
    slugs: ["katsu-the-wanderer", "katsu"],
    tier: "B",
    classOrTalent: "Ninja",
    mustShow: ["Combo card banished face-up may-play-this-turn"],
    modules: [
      "asset-bar-resources-ap-life",
      "banished-inspector",
      "banished-playable",
      "turn-status-ledger",
    ],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "kayo-runt",
    hero: "Kayo (Berserker Runt)",
    slugs: ["kayo-berserker-runt"],
    tier: "B",
    classOrTalent: "Brute",
    mustShow: ["Die roll UI for 6+ power attacks (halve / double)"],
    modules: ["asset-bar-resources-ap-life", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "crix",
    hero: "Groundbreaker Crix",
    slugs: ["groundbreaker-crix"],
    tier: "B",
    classOrTalent: "Guardian Pit-Fighter",
    mustShow: ["Seismic Surge on clash vs Guardian", "Clash UI"],
    modules: ["asset-bar-resources-ap-life", "permanent-token-stacks"],
    signatureTokens: ["Seismic Surge"],
    hasTextFixture: true,
  },
  {
    id: "frankie",
    hero: "Frankie",
    slugs: ["frankie-make-ends-meat"],
    tier: "B",
    classOrTalent: "Necromancer",
    mustShow: ["Equipment banished instead of GY", "Equip from a graveyard"],
    modules: ["asset-bar-resources-ap-life", "banished-inspector"],
    signatureTokens: [],
    hasTextFixture: true,
  },
  {
    id: "oscilio-classic",
    hero: "Oscilio (classic)",
    slugs: ["oscilio-constella-intelligence", "oscilio"],
    tier: "B",
    classOrTalent: "Wizard",
    mustShow: ["Discard instant → draw (once per turn)"],
    modules: ["asset-bar-resources-ap-life", "hero-status-flags"],
    signatureTokens: [],
    hasTextFixture: false,
  },
  {
    id: "arakni-huntsman",
    hero: "Arakni (Huntsman)",
    slugs: ["arakni-huntsman", "arakni"],
    tier: "B",
    classOrTalent: "Assassin",
    mustShow: ["Contract play → look top of opponent deck"],
    modules: ["asset-bar-resources-ap-life", "turn-status-ledger"],
    signatureTokens: [],
    hasTextFixture: false,
  },
  {
    id: "arakni-stealth",
    hero: "Arakni (Solitary / CR4X)",
    slugs: ["arakni-solitary-confinement", "arakni-5l-p3d-7hru-7h3-cr4x"],
    tier: "B",
    classOrTalent: "Assassin",
    mustShow: ["First stealth attack go again status"],
    modules: ["asset-bar-resources-ap-life", "hero-status-flags"],
    signatureTokens: [],
    hasTextFixture: false,
  },
] as const;

export type FabHeroSpecialUiId = (typeof HERO_SPECIAL_UI_CATALOG)[number]["id"];

export function getHeroSpecialUi(id: string): FabHeroSpecialUiRequirement | undefined {
  return HERO_SPECIAL_UI_CATALOG.find((h) => h.id === id);
}

export function listHeroesWithTextFixtures(): readonly FabHeroSpecialUiRequirement[] {
  return HERO_SPECIAL_UI_CATALOG.filter((h) => h.hasTextFixture);
}

export function listHeroesByTier(tier: FabHeroSpecialTier): readonly FabHeroSpecialUiRequirement[] {
  return HERO_SPECIAL_UI_CATALOG.filter((h) => h.tier === tier);
}
