import type { CardEffect, UnitCard } from "@tcg/gundam-types";

export const st02WingGundamBirdMode002: UnitCard = {
  cardNumber: "ST02-002",
  name: "Wing Gundam (Bird Mode)",
  type: "unit",
  color: "green",
  traits: ["operation meteor"],
  id: "ST02-002",
  externalId: "gundam:st02-002",
  slug: "wing-gundam-bird-mode-st02-002",
  displayName: "Wing Gundam (Bird Mode)",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-002",
  printings: [
    {
      id: "ST02-002",
      collectorNumber: "ST02-002",
      cardNumber: "ST02-002",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-002.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-002_p1",
      collectorNumber: "ST02-002_p1",
      cardNumber: "ST02-002",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-002_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
    {
      id: "ST02-002_p2",
      collectorNumber: "ST02-002_p2",
      cardNumber: "ST02-002",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST02-002_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002_p2.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "ST02-002_p3",
      collectorNumber: "ST02-002_p3",
      cardNumber: "ST02-002",
      set: {
        code: "ST02",
        name: "Store Tournament Participant Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-002_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002_p3.webp?260424",
      productName: "Store Tournament Participant Pack 01",
    },
    {
      id: "ST02-002_p4",
      collectorNumber: "ST02-002_p4",
      cardNumber: "ST02-002",
      set: {
        code: "ST02",
        name: "Store Tournament Winner Pack 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-002_p4.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002_p4.webp?260424",
      productName: "Store Tournament Winner Pack 01",
    },
  ],
  selectedPrintingId: "ST02-002",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-002.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-002.webp?260424",
  legality: "legal",
  level: 3,
  cost: 3,
  ap: 2,
  hp: 2,
  effect: "【Deploy】Place 1 EX Resource.<br>",
  effects: [
    {
      type: "triggered",
      activation: {
        timing: ["deploy"],
      },
      directives: [
        {
          action: {
            action: "placeResource",
            resourceType: "EX",
            state: "active",
          },
        },
      ],
      sourceText: "【Deploy】Place 1 EX Resource.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
