import type { UnitCard } from "@tcg/gundam-types";

export const st02GundamSandrock004: UnitCard = {
  cardNumber: "ST02-004",
  name: "Gundam Sandrock",
  type: "unit",
  color: "green",
  traits: ["operation meteor"],
  id: "ST02-004",
  canonicalId: "ST02-004",
  externalIds: { bandai: "gundam:st02-004" },
  slug: "gundam-sandrock/st02-004",
  displayName: "Gundam Sandrock",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-004",
  printings: [
    {
      id: "ST02-004",
      artId: "ST02-004",
      setCode: "ST02",
      collectorNumber: "ST02-004",
      cardNumber: "ST02-004",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-004.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-004.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-004_p1",
      artId: "ST02-004_p1",
      setCode: "ST02",
      collectorNumber: "ST02-004_p1",
      cardNumber: "ST02-004",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-004_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-004_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
  ],
  reprints: ["ST02-004", "ST02-004_p1"],
  selectedPrintingId: "ST02-004",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-004.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-004.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
