import type { UnitCard } from "@tcg/gundam-types";

export const st02Maganac005: UnitCard = {
  cardNumber: "ST02-005",
  name: "Maganac",
  type: "unit",
  color: "green",
  traits: ["maganac corps"],
  id: "ST02-005",
  externalId: "gundam:st02-005",
  slug: "maganac-st02-005",
  displayName: "Maganac",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-005",
  printings: [
    {
      id: "ST02-005",
      collectorNumber: "ST02-005",
      cardNumber: "ST02-005",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-005.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-005_p1",
      collectorNumber: "ST02-005_p1",
      cardNumber: "ST02-005",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-005_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
    {
      id: "ST02-005_p2",
      collectorNumber: "ST02-005_p2",
      cardNumber: "ST02-005",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST02-005_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-005_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST02-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-005.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
