import type { UnitCard } from "@tcg/gundam-types";

export const st02Leo007: UnitCard = {
  cardNumber: "ST02-007",
  name: "Leo",
  type: "unit",
  color: "blue",
  traits: ["oz"],
  id: "ST02-007",
  externalId: "gundam:st02-007",
  slug: "leo-st02-007",
  displayName: "Leo",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-007",
  printings: [
    {
      id: "ST02-007",
      collectorNumber: "ST02-007",
      cardNumber: "ST02-007",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-007.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-007_p1",
      collectorNumber: "ST02-007_p1",
      cardNumber: "ST02-007",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-007_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST02-007",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-007.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-007.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
