import type { UnitCard } from "@tcg/gundam-types";

export const st02Aries008: UnitCard = {
  cardNumber: "ST02-008",
  name: "Aries",
  type: "unit",
  color: "blue",
  traits: ["oz"],
  id: "ST02-008",
  externalId: "gundam:st02-008",
  slug: "aries-st02-008",
  displayName: "Aries",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-008",
  printings: [
    {
      id: "ST02-008",
      collectorNumber: "ST02-008",
      cardNumber: "ST02-008",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-008.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-008_p1",
      collectorNumber: "ST02-008_p1",
      cardNumber: "ST02-008",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-008_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST02-008",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-008.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-008.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 1,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
