import type { UnitCard } from "@tcg/gundam-types";

export const st02Tragos009: UnitCard = {
  cardNumber: "ST02-009",
  name: "Tragos",
  type: "unit",
  color: "blue",
  traits: ["oz"],
  id: "ST02-009",
  externalId: "gundam:st02-009",
  slug: "tragos-st02-009",
  displayName: "Tragos",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "ST02-009",
  printings: [
    {
      id: "ST02-009",
      collectorNumber: "ST02-009",
      cardNumber: "ST02-009",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-009.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-009.webp?260424",
      productName: "Wings of Advance [ST02]",
    },
    {
      id: "ST02-009_p1",
      collectorNumber: "ST02-009_p1",
      cardNumber: "ST02-009",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02] Bonus Pack",
        packageId: "616002",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-009_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-009_p1.webp?260424",
      productName: "Wings of Advance [ST02] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST02-009",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st02/ST02-009.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST02-009.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 1,
  effect: "&lt;Blocker&gt; (Rest this Unit to change the attack target to it.)<br>",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
