import type { CoreUiComponent, HarnessFixture } from "@tcg/simulator-contract";

const coreComponents: CoreUiComponent[] = [
  {
    name: "SimulatorShell",
    responsibility: "Owns fixture routing, selected perspective, and page-level harness context.",
  },
  {
    name: "FixtureNavigator",
    responsibility:
      "Lets humans and agents choose a deterministic snapshot without knowing engine internals.",
  },
  {
    name: "SeatSummary",
    responsibility:
      "Renders player identity, perspective, active turn, and game-specific counters as data.",
  },
  {
    name: "BoardLayout",
    responsibility: "Wraps board title, summary, and harness-facing building-block notes.",
  },
  {
    name: "Board",
    responsibility:
      "Creates a customizable table from adapter-provided sections, density, labels, and flow.",
  },
  {
    name: "BoardBlock",
    responsibility:
      "Normalizes board pieces into seat, zone, stack, counter, token row, and spotlight blocks.",
  },
  {
    name: "ZoneFrame",
    responsibility:
      "Renders public, private, owner, and secret zones with counts and visible entities.",
  },
  {
    name: "Card",
    responsibility:
      "Renders cards, dice, tokens, leaders, units, and hidden entities from one entity contract.",
  },
  {
    name: "CardGrid",
    responsibility: "Arranges visible zone contents without caring which game produced them.",
  },
  {
    name: "CardRow",
    responsibility: "Renders hand, stack, spotlight, and preview rows with stable card sizing.",
  },
  {
    name: "TokenRow",
    responsibility: "Displays repeated resources such as DON!!, ink, dice, counters, or costs.",
  },
  {
    name: "InteractionPanel",
    responsibility:
      "Shows the current prompt and converts UI selections into an adapter-owned move preview.",
  },
  {
    name: "AgentRunbook",
    responsibility:
      "Keeps fixture steps and assertions visible for deterministic agent validation.",
  },
];

const boardBuildingBlocks: CoreUiComponent[] = [
  {
    name: "Seat block",
    responsibility: "Player identity, active state, and counters.",
  },
  {
    name: "Zone block",
    responsibility: "Visible board areas that contain one or more entities.",
  },
  {
    name: "Stack block",
    responsibility: "Deck, life, trash, discard, shield, score, or count-only piles.",
  },
  {
    name: "Counter block",
    responsibility: "Single game resource or score value such as lore, eddies, or Street Cred.",
  },
  {
    name: "Token row",
    responsibility: "Repeated resources such as DON!!, ink, dice, or available costs.",
  },
  {
    name: "Spotlight",
    responsibility: "Key entity such as leader, legend, base, or location.",
  },
];

export const fixtures: HarnessFixture[] = [
  {
    id: "one-piece-attack-window",
    gameSlug: "one-piece",
    name: "One Piece attack window",
    summary:
      "Leader, character, life, DON!!, and counter timing rendered from the shared contract.",
    adapterGoal:
      "Map PlayerView, ProjectedDecision, and EngineCommand without leaking native prompt names into the UI.",
    table: {
      status: {
        activeSeatId: "op-human",
        phase: "Attack step",
        turn: 5,
        stateVersion: 118,
      },
      seats: [
        {
          id: "op-agent",
          label: "Agent seat",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Life", value: "3" },
            { label: "DON!!", value: "6/10" },
            { label: "Hand", value: "4" },
          ],
        },
        {
          id: "op-human",
          label: "Human seat",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Life", value: "4" },
            { label: "DON!!", value: "8/10" },
            { label: "Hand", value: "5" },
          ],
        },
      ],
      zones: [
        {
          id: "op-agent-leader",
          label: "Leader",
          role: "leader",
          ownerId: "op-agent",
          visibility: "public",
          entityIds: ["op-kid-leader"],
          hint: "Opponent leader can be selected as an attack target.",
        },
        {
          id: "op-agent-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "op-agent",
          visibility: "public",
          entityIds: ["op-blocker"],
          hint: "Rested blockers and active characters share the battlefield role.",
        },
        {
          id: "op-human-leader",
          label: "Leader",
          role: "leader",
          ownerId: "op-human",
          visibility: "public",
          entityIds: ["op-luffy-leader"],
          hint: "The same Card primitive handles leaders and normal cards.",
        },
        {
          id: "op-human-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "op-human",
          visibility: "public",
          entityIds: ["op-zoro"],
          hint: "Game nouns stay in labels while the role stays generic.",
        },
        {
          id: "op-human-resource",
          label: "DON!! area",
          role: "resource",
          ownerId: "op-human",
          visibility: "public",
          entityIds: ["op-don-active", "op-don-rested"],
          count: 8,
          hint: "Resources can be visible entities, counters, or both.",
        },
        {
          id: "op-human-hand",
          label: "Hand",
          role: "hand",
          ownerId: "op-human",
          visibility: "owner",
          entityIds: ["op-counter-event"],
          count: 5,
          hint: "Owner zones expose visible cards only to the correct viewer.",
        },
      ],
    },
    boardLayout: {
      title: "One Piece board",
      summary:
        "Leader and character lanes sit between life, deck, trash, stage, and DON!! resource rows.",
      appearance: {
        variant: "lanes",
        density: "normal",
        labelPlacement: "rail",
      },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "op-opponent",
          label: "Opponent",
          role: "opponent",
          blocks: [
            {
              id: "op-agent-seat",
              kind: "seat",
              label: "Agent seat",
              size: "wide",
              seatId: "op-agent",
              note: "Top seat owns the upper leader, life, deck, and board lanes.",
            },
            {
              id: "op-agent-life",
              kind: "stack",
              label: "Life",
              size: "compact",
              value: "3",
              note: "Count-only hidden life stack.",
            },
            {
              id: "op-agent-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "42",
            },
            {
              id: "op-agent-trash",
              kind: "stack",
              label: "Trash",
              size: "compact",
              value: "5",
            },
            {
              id: "op-agent-leader-block",
              kind: "spotlight",
              label: "Leader",
              size: "wide",
              entityIds: ["op-kid-leader"],
            },
            {
              id: "op-agent-board-block",
              kind: "zone",
              label: "Characters",
              size: "wide",
              zoneId: "op-agent-board",
            },
            {
              id: "op-agent-stage",
              kind: "stack",
              label: "Stage",
              size: "compact",
              value: "0",
              note: "Open stage slot.",
            },
          ],
        },
        {
          id: "op-shared",
          label: "Combat lane",
          role: "shared",
          layout: {
            columns: 8,
            labelPlacement: "top",
          },
          blocks: [
            {
              id: "op-attack-focus",
              kind: "spotlight",
              label: "Current attack",
              size: "wide",
              entityIds: ["op-luffy-leader", "op-kid-leader"],
              note: "Static preview of attacker and eligible target lane.",
            },
            {
              id: "op-turn-counter",
              kind: "counter",
              label: "Attack step",
              size: "normal",
              value: "Turn 5",
              note: "Battle prompts later attach to this shared lane.",
            },
          ],
        },
        {
          id: "op-player",
          label: "Player",
          role: "player",
          blocks: [
            {
              id: "op-human-seat",
              kind: "seat",
              label: "Human seat",
              size: "wide",
              seatId: "op-human",
            },
            {
              id: "op-human-life",
              kind: "stack",
              label: "Life",
              size: "compact",
              value: "4",
            },
            {
              id: "op-human-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "39",
            },
            {
              id: "op-human-trash",
              kind: "stack",
              label: "Trash",
              size: "compact",
              value: "6",
            },
            {
              id: "op-human-leader-block",
              kind: "spotlight",
              label: "Leader",
              size: "wide",
              entityIds: ["op-luffy-leader"],
            },
            {
              id: "op-human-board-block",
              kind: "zone",
              label: "Characters",
              size: "wide",
              zoneId: "op-human-board",
            },
            {
              id: "op-human-stage",
              kind: "stack",
              label: "Stage",
              size: "compact",
              value: "0",
              note: "Open stage slot.",
            },
            {
              id: "op-human-don",
              kind: "token-row",
              label: "DON!! cost area",
              size: "full",
              tokens: [
                { label: "Ready", value: "6", state: "ready" },
                { label: "Rested", value: "2", state: "rested" },
                { label: "DON!! deck", value: "2", state: "hidden" },
              ],
            },
            {
              id: "op-human-hand-block",
              kind: "zone",
              label: "Hand",
              size: "wide",
              zoneId: "op-human-hand",
              note: "Hand anchors the bottom edge for the local player.",
            },
          ],
        },
      ],
    },
    entities: [
      {
        id: "op-kid-leader",
        title: "Eustass Kid",
        subtitle: "Leader",
        kind: "leader",
        ownerId: "op-agent",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Power", value: "5000" },
          { label: "Life", value: "3" },
        ],
        traits: ["Supernovas"],
      },
      {
        id: "op-blocker",
        title: "Blocker",
        subtitle: "Character",
        kind: "character",
        ownerId: "op-agent",
        face: "public",
        states: ["rested"],
        stats: [{ label: "Power", value: "6000" }],
        traits: ["Blocker"],
      },
      {
        id: "op-luffy-leader",
        title: "Monkey.D.Luffy",
        subtitle: "Leader",
        kind: "leader",
        ownerId: "op-human",
        face: "public",
        states: ["rested", "active"],
        stats: [
          { label: "Power", value: "5000" },
          { label: "Life", value: "4" },
        ],
        traits: ["Straw Hat Crew"],
      },
      {
        id: "op-zoro",
        title: "Roronoa Zoro",
        subtitle: "Character",
        kind: "character",
        ownerId: "op-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Power", value: "5000" }],
        traits: ["Straw Hat Crew"],
      },
      {
        id: "op-don-active",
        title: "DON!!",
        subtitle: "Resource",
        kind: "resource",
        ownerId: "op-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Count", value: "6 active" }],
        traits: ["Cost"],
      },
      {
        id: "op-don-rested",
        title: "DON!!",
        subtitle: "Resource",
        kind: "resource",
        ownerId: "op-human",
        face: "public",
        states: ["rested"],
        stats: [{ label: "Count", value: "2 rested" }],
        traits: ["Cost"],
      },
      {
        id: "op-counter-event",
        title: "Counter Event",
        subtitle: "Hand card",
        kind: "card",
        ownerId: "op-human",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "2" },
          { label: "Counter", value: "+4000" },
        ],
        traits: ["Event"],
      },
    ],
    interactions: [
      {
        id: "op-declare-attack",
        label: "Declare attack",
        prompt: "Choose an eligible target for the rested leader attack.",
        sourceEntityId: "op-luffy-leader",
        input: {
          kind: "single-target",
          min: 1,
          max: 1,
          candidateEntityIds: ["op-kid-leader", "op-blocker"],
          targetZoneIds: ["op-agent-leader", "op-agent-board"],
          options: [],
        },
        movePreview: {
          engine: "one-piece",
          command: "DECLARE_ATTACK",
          payload: "attackerId=op-luffy-leader,targetId=<selected>",
        },
      },
    ],
    guideSteps: [
      {
        title: "Read projected board",
        body: "Adapter emits seats, zones, counters, visible entities, and one active projected decision.",
      },
      {
        title: "Select target",
        body: "UI records an entity id only. The adapter owns the native EngineCommand conversion.",
      },
      {
        title: "Submit preview",
        body: "Harness confirms the command shape before a live engine executes anything.",
      },
    ],
    agentChecks: [
      "The attack target list contains the opponent leader and rested blocker.",
      "Hidden hand count is visible without exposing all private cards.",
      "No One Piece component is required to render DON!! or leader zones.",
    ],
    coreComponents,
  },
  {
    id: "gundam-pilot-pair",
    gameSlug: "gundam",
    name: "Gundam pilot pair",
    summary: "Battle area, shield, resource, base, and paired pilot metadata in one table layout.",
    adapterGoal:
      "Reuse the Gundam interaction view while moving pending controller state behind the adapter.",
    table: {
      status: {
        activeSeatId: "gd-human",
        phase: "Action step",
        turn: 3,
        stateVersion: 64,
      },
      seats: [
        {
          id: "gd-agent",
          label: "Agent seat",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Shield", value: "2" },
            { label: "Resource", value: "4" },
            { label: "Hand", value: "3" },
          ],
        },
        {
          id: "gd-human",
          label: "Human seat",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Shield", value: "3" },
            { label: "Resource", value: "5" },
            { label: "Hand", value: "5" },
          ],
        },
      ],
      zones: [
        {
          id: "gd-agent-base",
          label: "Base",
          role: "support",
          ownerId: "gd-agent",
          visibility: "public",
          entityIds: ["gd-base"],
          hint: "Bases are support zones, not special-cased by the renderer.",
        },
        {
          id: "gd-agent-shield",
          label: "Shield",
          role: "life",
          ownerId: "gd-agent",
          visibility: "secret",
          entityIds: [],
          count: 2,
          hint: "Secret zones use count-only rendering.",
        },
        {
          id: "gd-human-battle",
          label: "Battle area",
          role: "battlefield",
          ownerId: "gd-human",
          visibility: "public",
          entityIds: ["gd-aerial", "gd-suletta"],
          hint: "Pilot pairing is entity metadata and visual attachment state.",
        },
        {
          id: "gd-human-resource",
          label: "Resource area",
          role: "resource",
          ownerId: "gd-human",
          visibility: "public",
          entityIds: ["gd-resource"],
          count: 5,
          hint: "Resource count stays readable even when individual resources are collapsed.",
        },
        {
          id: "gd-human-hand",
          label: "Hand",
          role: "hand",
          ownerId: "gd-human",
          visibility: "owner",
          entityIds: ["gd-command"],
          count: 5,
          hint: "Owner hand fixtures can expose a focused card for interaction tests.",
        },
      ],
    },
    boardLayout: {
      title: "Gundam board",
      summary:
        "Base, shield, resource, battle area, paired pilots, and command hand blocks arranged as two tactical rows.",
      appearance: {
        variant: "opposed",
        density: "compact",
        labelPlacement: "rail",
      },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "gd-opponent",
          label: "Opponent",
          role: "opponent",
          blocks: [
            {
              id: "gd-agent-seat",
              kind: "seat",
              label: "Agent seat",
              size: "wide",
              seatId: "gd-agent",
            },
            {
              id: "gd-agent-base-block",
              kind: "spotlight",
              label: "Base",
              size: "wide",
              entityIds: ["gd-base"],
            },
            {
              id: "gd-agent-shield-block",
              kind: "stack",
              label: "Shield",
              size: "compact",
              zoneId: "gd-agent-shield",
            },
            {
              id: "gd-agent-resource",
              kind: "token-row",
              label: "Resource area",
              size: "wide",
              tokens: [
                { label: "Ready", value: "3", state: "ready" },
                { label: "Rested", value: "1", state: "rested" },
              ],
            },
            {
              id: "gd-agent-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "36",
            },
            {
              id: "gd-agent-discard",
              kind: "stack",
              label: "Discard",
              size: "compact",
              value: "4",
            },
          ],
        },
        {
          id: "gd-battle",
          label: "Battle line",
          role: "shared",
          layout: {
            columns: 10,
            labelPlacement: "top",
            span: "full",
          },
          blocks: [
            {
              id: "gd-human-battle-block",
              kind: "zone",
              label: "Battle area",
              size: "full",
              zoneId: "gd-human-battle",
              note: "Unit and attached pilot are rendered from the same entity list.",
            },
          ],
        },
        {
          id: "gd-player",
          label: "Player",
          role: "player",
          blocks: [
            {
              id: "gd-human-seat",
              kind: "seat",
              label: "Human seat",
              size: "wide",
              seatId: "gd-human",
            },
            {
              id: "gd-human-shield",
              kind: "stack",
              label: "Shield",
              size: "compact",
              value: "3",
              note: "Face-down damage buffer.",
            },
            {
              id: "gd-human-resource-block",
              kind: "zone",
              label: "Resource area",
              size: "wide",
              zoneId: "gd-human-resource",
            },
            {
              id: "gd-human-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "34",
            },
            {
              id: "gd-human-discard",
              kind: "stack",
              label: "Discard",
              size: "compact",
              value: "3",
            },
            {
              id: "gd-human-command-hand",
              kind: "zone",
              label: "Command hand",
              size: "wide",
              zoneId: "gd-human-hand",
            },
          ],
        },
      ],
    },
    entities: [
      {
        id: "gd-base",
        title: "White Base",
        subtitle: "Base",
        kind: "card",
        ownerId: "gd-agent",
        face: "public",
        states: ["ready"],
        stats: [{ label: "HP", value: "5" }],
        traits: ["Base"],
      },
      {
        id: "gd-aerial",
        title: "Gundam Aerial",
        subtitle: "Unit",
        kind: "unit",
        ownerId: "gd-human",
        face: "public",
        states: ["ready", "active"],
        stats: [
          { label: "AP", value: "4" },
          { label: "HP", value: "5" },
        ],
        traits: ["Witch", "Paired pilot"],
      },
      {
        id: "gd-suletta",
        title: "Suletta Mercury",
        subtitle: "Pilot",
        kind: "card",
        ownerId: "gd-human",
        face: "public",
        states: ["attached"],
        stats: [{ label: "Boost", value: "+1" }],
        traits: ["Pilot"],
      },
      {
        id: "gd-resource",
        title: "Resource stack",
        subtitle: "Resource",
        kind: "resource",
        ownerId: "gd-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Available", value: "5" }],
        traits: ["Resource"],
      },
      {
        id: "gd-command",
        title: "Battle command",
        subtitle: "Command",
        kind: "card",
        ownerId: "gd-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Cost", value: "2" }],
        traits: ["Command"],
      },
    ],
    interactions: [
      {
        id: "gd-action-select",
        label: "Choose action",
        prompt: "Select a unit and choose whether to attack the base or hold priority.",
        sourceEntityId: "gd-aerial",
        input: {
          kind: "option",
          min: 1,
          max: 1,
          candidateEntityIds: ["gd-aerial"],
          targetZoneIds: ["gd-agent-base"],
          options: [
            { id: "attack-base", label: "Attack base" },
            { id: "hold-priority", label: "Hold priority" },
          ],
        },
        movePreview: {
          engine: "gundam",
          command: "SUBMIT_INTERACTION",
          payload: "inputId=gd-action-select,optionId=<selected>",
        },
      },
    ],
    guideSteps: [
      {
        title: "Project paired entities",
        body: "Adapter marks the pilot as attached and keeps the unit as the selectable entity.",
      },
      {
        title: "Render pending choice",
        body: "UI shows options from data and never imports Gundam pending controller code.",
      },
      {
        title: "Round trip submission",
        body: "Adapter maps the selected option back to the engine interaction protocol.",
      },
    ],
    agentChecks: [
      "The pilot renders as attached metadata, not as a custom Gundam-only component.",
      "Shield cards stay count-only because their visibility is secret.",
      "Option inputs render without a board-specific click target.",
    ],
    coreComponents,
  },
  {
    id: "cyberpunk-steal-gig",
    gameSlug: "cyberpunk",
    name: "Cyberpunk steal gig",
    summary: "Legend, eddies, gear, dice, and gig targeting without React or Mantine dependencies.",
    adapterGoal:
      "Keep zoneViews and dropMapping logic adapter-owned while the UI handles entities and interactions generically.",
    table: {
      status: {
        activeSeatId: "cp-human",
        phase: "Run phase",
        turn: 4,
        stateVersion: 91,
      },
      seats: [
        {
          id: "cp-agent",
          label: "Agent seat",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Street Cred", value: "12" },
            { label: "Eddies", value: "2" },
            { label: "Hand", value: "3" },
          ],
        },
        {
          id: "cp-human",
          label: "Human seat",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Street Cred", value: "9" },
            { label: "Eddies", value: "5" },
            { label: "Hand", value: "4" },
          ],
        },
      ],
      zones: [
        {
          id: "cp-agent-gigs",
          label: "Gigs",
          role: "score",
          ownerId: "cp-agent",
          visibility: "public",
          entityIds: ["cp-gig-secure"],
          hint: "Score-like zones can still be targeted by attack effects.",
        },
        {
          id: "cp-human-legend",
          label: "Legend",
          role: "leader",
          ownerId: "cp-human",
          visibility: "public",
          entityIds: ["cp-v"],
          hint: "Legends use the shared leader role.",
        },
        {
          id: "cp-human-field",
          label: "Field",
          role: "battlefield",
          ownerId: "cp-human",
          visibility: "public",
          entityIds: ["cp-dying-night", "cp-program"],
          hint: "Programs, gear, and characters are entities with traits.",
        },
        {
          id: "cp-human-eddies",
          label: "Eddies",
          role: "resource",
          ownerId: "cp-human",
          visibility: "public",
          entityIds: ["cp-eddies"],
          count: 5,
          hint: "Currency can be rendered as an entity stack.",
        },
        {
          id: "cp-fixer-dice",
          label: "Fixer dice",
          role: "custom",
          visibility: "public",
          entityIds: ["cp-fixer-die"],
          hint: "Non-card objects share Card with kind=die.",
        },
      ],
    },
    boardLayout: {
      title: "Cyberpunk board",
      summary:
        "Legends, gigs, eddies, field cards, programs, and dice are arranged as a dense run console.",
      appearance: {
        variant: "dashboard",
        density: "compact",
        labelPlacement: "top",
      },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "cp-opponent",
          label: "Opponent",
          role: "opponent",
          blocks: [
            {
              id: "cp-agent-seat",
              kind: "seat",
              label: "Agent seat",
              size: "wide",
              seatId: "cp-agent",
            },
            {
              id: "cp-agent-gig-stack",
              kind: "zone",
              label: "Scored gigs",
              size: "wide",
              zoneId: "cp-agent-gigs",
            },
            {
              id: "cp-agent-street-cred",
              kind: "counter",
              label: "Street Cred",
              size: "compact",
              value: "12",
            },
            {
              id: "cp-agent-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "31",
            },
            {
              id: "cp-agent-trash",
              kind: "stack",
              label: "Trash",
              size: "compact",
              value: "7",
            },
          ],
        },
        {
          id: "cp-shared",
          label: "Run lane",
          role: "shared",
          layout: {
            columns: 8,
            flow: "row",
            span: "full",
          },
          blocks: [
            {
              id: "cp-fixer-dice-block",
              kind: "zone",
              label: "Fixer dice",
              size: "normal",
              zoneId: "cp-fixer-dice",
            },
            {
              id: "cp-steal-preview",
              kind: "spotlight",
              label: "Gig target",
              size: "wide",
              entityIds: ["cp-v", "cp-gig-secure"],
              note: "Static view of the run target before UI-to-move conversion.",
            },
          ],
        },
        {
          id: "cp-player",
          label: "Player",
          role: "player",
          blocks: [
            {
              id: "cp-human-seat",
              kind: "seat",
              label: "Human seat",
              size: "wide",
              seatId: "cp-human",
            },
            {
              id: "cp-human-legend-block",
              kind: "spotlight",
              label: "Legend",
              size: "normal",
              entityIds: ["cp-v"],
            },
            {
              id: "cp-human-field-block",
              kind: "zone",
              label: "Field and programs",
              size: "wide",
              zoneId: "cp-human-field",
            },
            {
              id: "cp-human-eddies-block",
              kind: "zone",
              label: "Eddies",
              size: "normal",
              zoneId: "cp-human-eddies",
            },
            {
              id: "cp-human-gig-dice",
              kind: "token-row",
              label: "Gig dice",
              size: "wide",
              tokens: [
                { label: "Attack", value: "4", state: "active" },
                { label: "Tech", value: "2", state: "ready" },
                { label: "Cool", value: "1", state: "rested" },
              ],
            },
            {
              id: "cp-human-hand",
              kind: "stack",
              label: "Hand",
              size: "compact",
              value: "4",
            },
            {
              id: "cp-human-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "29",
            },
            {
              id: "cp-human-trash",
              kind: "stack",
              label: "Trash",
              size: "compact",
              value: "8",
            },
          ],
        },
      ],
    },
    entities: [
      {
        id: "cp-gig-secure",
        title: "Secure the Client",
        subtitle: "Gig",
        kind: "card",
        ownerId: "cp-agent",
        face: "public",
        states: ["active"],
        stats: [{ label: "Cred", value: "3" }],
        traits: ["Gig"],
      },
      {
        id: "cp-v",
        title: "V",
        subtitle: "Legend",
        kind: "leader",
        ownerId: "cp-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Cred", value: "9" }],
        traits: ["Solo"],
      },
      {
        id: "cp-dying-night",
        title: "Dying Night",
        subtitle: "Gear",
        kind: "card",
        ownerId: "cp-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Power", value: "+2" }],
        traits: ["Weapon", "Attached"],
      },
      {
        id: "cp-program",
        title: "Breach Protocol",
        subtitle: "Program",
        kind: "card",
        ownerId: "cp-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Cost", value: "1" }],
        traits: ["Program"],
      },
      {
        id: "cp-eddies",
        title: "Eddies",
        subtitle: "Currency",
        kind: "resource",
        ownerId: "cp-human",
        face: "public",
        states: ["ready"],
        stats: [{ label: "Available", value: "5" }],
        traits: ["Currency"],
      },
      {
        id: "cp-fixer-die",
        title: "Fixer die",
        subtitle: "Die",
        kind: "die",
        ownerId: "cp-human",
        face: "public",
        states: ["active"],
        stats: [{ label: "Face", value: "4" }],
        traits: ["Dice"],
      },
    ],
    interactions: [
      {
        id: "cp-steal-gig",
        label: "Steal gig",
        prompt: "Choose an opponent gig after resolving Go Solo.",
        sourceEntityId: "cp-v",
        input: {
          kind: "single-target",
          min: 1,
          max: 1,
          candidateEntityIds: ["cp-gig-secure"],
          targetZoneIds: ["cp-agent-gigs"],
          options: [],
        },
        movePreview: {
          engine: "cyberpunk",
          command: "SUBMIT_INTERACTION",
          payload: "inputId=cp-steal-gig,targetId=<selected>",
        },
      },
    ],
    guideSteps: [
      {
        title: "Render unusual zones",
        body: "Gigs, legends, eddies, and fixer dice are labels and roles, not new components.",
      },
      {
        title: "Select gig target",
        body: "Interaction candidates point at entity ids while the adapter validates native legality.",
      },
      {
        title: "Keep drops adapter-owned",
        body: "Spatial gestures can submit the same interaction draft after adapter mapping.",
      },
    ],
    agentChecks: [
      "The fixer die renders with the same entity primitive as cards.",
      "The target prompt highlights only the opponent gig zone.",
      "Cyberpunk-specific drop mapping is absent from the page renderer.",
    ],
    coreComponents,
  },
  {
    id: "lorcana-ordering",
    gameSlug: "lorcana",
    name: "Lorcana ordering prompt",
    summary:
      "Characters, ink, locations, lore, and ordering prompts through the same fixture harness.",
    adapterGoal:
      "Use Lorcana as the rich prompt reference while avoiding a parallel simulator prompt model.",
    table: {
      status: {
        activeSeatId: "lc-human",
        phase: "Main phase",
        turn: 6,
        stateVersion: 204,
      },
      seats: [
        {
          id: "lc-agent",
          label: "Agent seat",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Lore", value: "13" },
            { label: "Ink", value: "5" },
            { label: "Hand", value: "2" },
          ],
        },
        {
          id: "lc-human",
          label: "Human seat",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Lore", value: "11" },
            { label: "Ink", value: "6" },
            { label: "Hand", value: "3" },
          ],
        },
      ],
      zones: [
        {
          id: "lc-agent-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "lc-agent",
          visibility: "public",
          entityIds: ["lc-elsa"],
          hint: "Opposing characters use the same battlefield role.",
        },
        {
          id: "lc-human-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "lc-human",
          visibility: "public",
          entityIds: ["lc-mickey", "lc-location"],
          hint: "Locations can live beside characters but keep their own traits.",
        },
        {
          id: "lc-human-ink",
          label: "Inkwell",
          role: "resource",
          ownerId: "lc-human",
          visibility: "owner",
          entityIds: ["lc-ink"],
          count: 6,
          hint: "Owner-visible resource zones preserve Lorcana masking rules.",
        },
        {
          id: "lc-human-deck",
          label: "Deck top",
          role: "deck",
          ownerId: "lc-human",
          visibility: "owner",
          entityIds: ["lc-scry-one", "lc-scry-two"],
          count: 36,
          hint: "Ordering prompts can expose a temporary owner-only deck view.",
        },
        {
          id: "lc-human-discard",
          label: "Discard",
          role: "discard",
          ownerId: "lc-human",
          visibility: "public",
          entityIds: [],
          count: 4,
          hint: "Empty zones still render stable layout and count metadata.",
        },
      ],
    },
    boardLayout: {
      title: "Lorcana board",
      summary:
        "Lore race, characters, locations, ink, deck, discard, and ordering preview share one tabletop.",
      appearance: {
        variant: "theater",
        density: "spacious",
        labelPlacement: "top",
      },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "lc-opponent",
          label: "Opponent",
          role: "opponent",
          blocks: [
            {
              id: "lc-agent-seat",
              kind: "seat",
              label: "Agent seat",
              size: "wide",
              seatId: "lc-agent",
            },
            {
              id: "lc-agent-lore",
              kind: "counter",
              label: "Lore",
              size: "compact",
              value: "13",
            },
            {
              id: "lc-agent-board-block",
              kind: "zone",
              label: "Characters",
              size: "wide",
              zoneId: "lc-agent-board",
            },
            {
              id: "lc-agent-deck",
              kind: "stack",
              label: "Deck",
              size: "compact",
              value: "34",
            },
            {
              id: "lc-agent-discard",
              kind: "stack",
              label: "Discard",
              size: "compact",
              value: "6",
            },
          ],
        },
        {
          id: "lc-shared",
          label: "Quest lane",
          role: "shared",
          layout: {
            columns: 8,
            flow: "row",
            span: "full",
          },
          blocks: [
            {
              id: "lc-location-focus",
              kind: "spotlight",
              label: "Location lane",
              size: "wide",
              entityIds: ["lc-location"],
              note: "Locations stay normal entities with location traits.",
            },
            {
              id: "lc-lore-race",
              kind: "token-row",
              label: "Lore race",
              size: "wide",
              tokens: [
                { label: "Opponent", value: "13", state: "active" },
                { label: "Player", value: "11", state: "ready" },
                { label: "Goal", value: "20", state: "hidden" },
              ],
            },
          ],
        },
        {
          id: "lc-player",
          label: "Player",
          role: "player",
          blocks: [
            {
              id: "lc-human-seat",
              kind: "seat",
              label: "Human seat",
              size: "wide",
              seatId: "lc-human",
            },
            {
              id: "lc-human-board-block",
              kind: "zone",
              label: "Characters and locations",
              size: "wide",
              zoneId: "lc-human-board",
            },
            {
              id: "lc-human-ink-block",
              kind: "zone",
              label: "Inkwell",
              size: "normal",
              zoneId: "lc-human-ink",
            },
            {
              id: "lc-human-deck-block",
              kind: "zone",
              label: "Deck preview",
              size: "wide",
              zoneId: "lc-human-deck",
              note: "Ordering prompts can temporarily show deck-top entities.",
            },
            {
              id: "lc-human-discard-block",
              kind: "stack",
              label: "Discard",
              size: "compact",
              zoneId: "lc-human-discard",
            },
            {
              id: "lc-human-hand",
              kind: "stack",
              label: "Hand",
              size: "compact",
              value: "3",
            },
          ],
        },
      ],
    },
    entities: [
      {
        id: "lc-elsa",
        title: "Elsa",
        subtitle: "Character",
        kind: "character",
        ownerId: "lc-agent",
        face: "public",
        states: ["rested"],
        stats: [
          { label: "Strength", value: "3" },
          { label: "Willpower", value: "4" },
        ],
        traits: ["Storyborn"],
      },
      {
        id: "lc-mickey",
        title: "Mickey Mouse",
        subtitle: "Character",
        kind: "character",
        ownerId: "lc-human",
        face: "public",
        states: ["ready", "active"],
        stats: [
          { label: "Strength", value: "2" },
          { label: "Lore", value: "2" },
        ],
        traits: ["Dreamborn", "Sorcerer"],
      },
      {
        id: "lc-location",
        title: "Ariel's Grotto",
        subtitle: "Location",
        kind: "card",
        ownerId: "lc-human",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Move cost", value: "1" },
          { label: "Lore", value: "1" },
        ],
        traits: ["Location"],
      },
      {
        id: "lc-ink",
        title: "Ink stack",
        subtitle: "Resource",
        kind: "resource",
        ownerId: "lc-human",
        face: "hidden",
        states: ["hidden"],
        stats: [{ label: "Available", value: "4" }],
        traits: ["Ink"],
      },
      {
        id: "lc-scry-one",
        title: "Top card A",
        subtitle: "Deck preview",
        kind: "card",
        ownerId: "lc-human",
        face: "public",
        states: ["active"],
        stats: [{ label: "Order", value: "1" }],
        traits: ["Preview"],
      },
      {
        id: "lc-scry-two",
        title: "Top card B",
        subtitle: "Deck preview",
        kind: "card",
        ownerId: "lc-human",
        face: "public",
        states: ["active"],
        stats: [{ label: "Order", value: "2" }],
        traits: ["Preview"],
      },
    ],
    interactions: [
      {
        id: "lc-order-deck",
        label: "Order cards",
        prompt: "Put the revealed cards back on top of the deck in any order.",
        input: {
          kind: "ordering",
          min: 2,
          max: 2,
          candidateEntityIds: ["lc-scry-one", "lc-scry-two"],
          targetZoneIds: ["lc-human-deck"],
          options: [],
        },
        movePreview: {
          engine: "lorcana",
          command: "SUBMIT_PLAYER_INTERACTION",
          payload: "inputId=lc-order-deck,orderedIds=<ordered>",
        },
      },
    ],
    guideSteps: [
      {
        title: "Expose temporary cards",
        body: "Adapter adds owner-only deck entities for the active ordering prompt.",
      },
      {
        title: "Render ordering input",
        body: "UI displays ordered candidates without knowing the originating Lorcana effect.",
      },
      {
        title: "Submit ordered ids",
        body: "Adapter converts the ordered ids into the native player interaction submission.",
      },
    ],
    agentChecks: [
      "The deck preview cards are owner-visible and explicitly tied to the ordering prompt.",
      "Locations render as normal entities with location traits.",
      "The prompt can be represented without Lorcana-only modal code.",
    ],
    coreComponents,
  },
  // ============================================================
  // Rich subsystem demonstration fixtures
  // ============================================================
  {
    id: "lorcana-rich-demo",
    gameSlug: "lorcana",
    name: "Lorcana Rich UI Demo",
    summary:
      "Demonstrates hand fan layout, card images, frame styles, overlay badges, event log, and targeting intents.",
    adapterGoal: "Showcase all Phase 1-3 UI subsystems in a single fixture.",
    table: {
      status: {
        activeSeatId: "p1",
        phase: "Challenge",
        turn: 7,
        stateVersion: 42,
      },
      seats: [
        {
          id: "p1",
          label: "Player 1",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Lore", value: "18" },
            { label: "Ink", value: "5" },
          ],
          timerMs: 45000,
          timerState: "running",
          avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=p1",
          connectionStatus: "online",
        },
        {
          id: "p2",
          label: "Player 2",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Lore", value: "14" },
            { label: "Ink", value: "3" },
          ],
          timerMs: 60000,
          timerState: "paused",
          connectionStatus: "thinking",
        },
      ],
      zones: [
        {
          id: "p1-hand",
          label: "Hand",
          role: "hand",
          ownerId: "p1",
          visibility: "owner",
          entityIds: ["h1", "h2", "h3", "h4", "h5", "h6"],
          layoutHint: "fan",
          hint: "Fan layout with dynamic rotation",
        },
        {
          id: "p1-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "p1",
          visibility: "public",
          entityIds: ["b1", "b2"],
          hint: "Characters ready for challenge",
        },
        {
          id: "p2-board",
          label: "Characters",
          role: "battlefield",
          ownerId: "p2",
          visibility: "public",
          entityIds: ["b3"],
          hint: "Opponent characters",
        },
        {
          id: "p1-deck",
          label: "Deck",
          role: "deck",
          ownerId: "p1",
          visibility: "secret",
          entityIds: [],
          count: 32,
          hint: "Remaining deck cards",
        },
      ],
    },
    boardLayout: {
      title: "Lorcana Demo Board",
      summary: "Full-featured demo with all new UI subsystems.",
      appearance: { variant: "opposed", density: "normal", labelPlacement: "rail" },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "opponent",
          label: "P2",
          role: "opponent",
          blocks: [
            { id: "p2-seat", kind: "seat", label: "Player 2", size: "wide" },
            { id: "p2-board", kind: "zone", label: "Characters", size: "wide", zoneId: "p2-board" },
          ],
        },
        {
          id: "player",
          label: "P1",
          role: "player",
          blocks: [
            { id: "p1-board", kind: "zone", label: "Characters", size: "wide", zoneId: "p1-board" },
            { id: "p1-hand", kind: "zone", label: "Hand", size: "full", zoneId: "p1-hand" },
            { id: "p1-seat", kind: "seat", label: "Player 1", size: "wide" },
          ],
        },
      ],
    },
    entities: [
      {
        id: "h1",
        title: "Ariel",
        subtitle: "On Human Legs",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "4" },
          { label: "Strength", value: "3" },
          { label: "Willpower", value: "4" },
        ],
        traits: ["Dreamborn", "Heroine", "Princess"],
        imageUrl: "https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=300&h=420&fit=crop",
        frameStyle: { color: "#6d4cc2", pattern: "amethyst" },
      },
      {
        id: "h2",
        title: "Mickey Mouse",
        subtitle: "Wayward Sorcerer",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "6" },
          { label: "Strength", value: "4" },
          { label: "Willpower", value: "5" },
        ],
        traits: ["Floodborn", "Hero", "Sorcerer"],
        frameStyle: { color: "#2563eb", pattern: "sapphire" },
      },
      {
        id: "h3",
        title: "Elsa",
        subtitle: "Spirit of Winter",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "5" },
          { label: "Strength", value: "3" },
          { label: "Willpower", value: "5" },
        ],
        traits: ["Dreamborn", "Heroine", "Queen"],
        frameStyle: { color: "#0891b2", pattern: "steel" },
      },
      {
        id: "h4",
        title: "Rapunzel",
        subtitle: "Gifted with Healing",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "3" },
          { label: "Strength", value: "2" },
          { label: "Willpower", value: "4" },
        ],
        traits: ["Dreamborn", "Heroine", "Princess"],
        frameStyle: { color: "#d97706", pattern: "amber" },
      },
      {
        id: "h5",
        title: "Stitch",
        subtitle: "Rock Star",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "4" },
          { label: "Strength", value: "3" },
          { label: "Willpower", value: "3" },
        ],
        traits: ["Floodborn", "Hero", "Alien"],
        frameStyle: { color: "#dc2626", pattern: "ruby" },
      },
      {
        id: "h6",
        title: "Genie",
        subtitle: "Wonderful Trickster",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "7" },
          { label: "Strength", value: "5" },
          { label: "Willpower", value: "5" },
        ],
        traits: ["Storyborn", "Hero"],
        frameStyle: { color: "#16a34a", pattern: "emerald" },
      },
      {
        id: "b1",
        title: "Ariel",
        subtitle: "On Human Legs",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "4" },
          { label: "Strength", value: "3" },
          { label: "Willpower", value: "4" },
        ],
        traits: ["Dreamborn", "Heroine", "Princess"],
        imageUrl: "https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=300&h=420&fit=crop",
        frameStyle: { color: "#6d4cc2" },
        overlayBadges: [{ label: "+1", color: "#16a34a", position: "br" }],
      },
      {
        id: "b2",
        title: "Mickey Mouse",
        subtitle: "Wayward Sorcerer",
        kind: "character",
        ownerId: "p1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "6" },
          { label: "Strength", value: "4" },
          { label: "Willpower", value: "5" },
        ],
        traits: ["Floodborn", "Hero", "Sorcerer"],
        frameStyle: { color: "#2563eb" },
        overlayBadges: [{ label: "DMG", color: "#dc2626", position: "tr" }],
      },
      {
        id: "b3",
        title: "Captain Hook",
        subtitle: "Force of Will",
        kind: "character",
        ownerId: "p2",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "5" },
          { label: "Strength", value: "4" },
          { label: "Willpower", value: "4" },
        ],
        traits: ["Dreamborn", "Villain", "Pirate"],
        frameStyle: { color: "#dc2626" },
        overlayBadges: [{ label: "2", color: "#d97706", position: "tl" }],
      },
    ],
    interactions: [
      {
        id: "challenge-intent",
        label: "Declare Challenge",
        prompt: "Select a character to challenge an opposing character.",
        sourceEntityId: "b1",
        input: {
          kind: "single-target",
          candidateEntityIds: ["b3"],
          targetZoneIds: ["p2-board"],
          options: [],
        },
        movePreview: {
          engine: "lorcana",
          command: "challenge",
          payload: '{"source":"b1","target":"b3"}',
        },
      },
    ],
    guideSteps: [
      { title: "Hand fan layout", body: "Hand zone uses layoutHint: fan for arc layout." },
      { title: "Card images", body: "Entities with imageUrl show real card art." },
      { title: "Overlay badges", body: "Counters and status badges render in corners." },
    ],
    agentChecks: ["Fan layout renders correctly", "Badges are positioned per corner"],
    coreComponents,
    eventLog: [
      {
        id: "e1",
        turn: 1,
        phase: "Ink",
        seatId: "p1",
        timestamp: "2024-01-01T10:00:00Z",
        message: "Player 1 played Ariel to the board",
        tags: ["move"],
        entityIds: ["b1"],
      },
      {
        id: "e2",
        turn: 2,
        phase: "Quest",
        seatId: "p1",
        timestamp: "2024-01-01T10:01:00Z",
        message: "Ariel quested for 2 lore",
        tags: ["move"],
        entityIds: ["b1"],
      },
      {
        id: "e3",
        turn: 3,
        phase: "Challenge",
        seatId: "p2",
        timestamp: "2024-01-01T10:02:00Z",
        message: "Captain Hook challenged Mickey Mouse",
        tags: ["combat"],
        entityIds: ["b3", "b2"],
      },
      {
        id: "e4",
        turn: 4,
        phase: "Ink",
        seatId: "p1",
        timestamp: "2024-01-01T10:03:00Z",
        message: "Player 1 inked a card",
        tags: ["move"],
      },
      {
        id: "e5",
        turn: 5,
        phase: "Challenge",
        seatId: "p1",
        timestamp: "2024-01-01T10:04:00Z",
        message: "Ariel challenged Captain Hook",
        tags: ["combat"],
        entityIds: ["b1", "b3"],
      },
      {
        id: "e6",
        turn: 6,
        phase: "Main",
        seatId: "p2",
        timestamp: "2024-01-01T10:05:00Z",
        message: "Player 2 used ability: Force of Will",
        tags: ["ability"],
        entityIds: ["b3"],
      },
      {
        id: "e7",
        turn: 7,
        phase: "Challenge",
        seatId: "p1",
        timestamp: "2024-01-01T10:06:00Z",
        message: "Player 1 is choosing a challenge target",
        tags: ["system"],
      },
    ],
    targetingIntents: [
      {
        id: "ti1",
        sourceEntityId: "b1",
        targetEntityIds: ["b3"],
        targetZoneIds: [],
        preview: { damage: 2, banish: false },
      },
    ],
  },
  {
    id: "gundam-targeting-demo",
    gameSlug: "gundam",
    name: "Gundam Targeting Demo",
    summary: "Demonstrates targeting overlays, chess clocks, and prompt banners.",
    adapterGoal: "Showcase targeting and timer subsystems.",
    table: {
      status: {
        activeSeatId: "g1",
        phase: "Battle",
        turn: 3,
        stateVersion: 12,
      },
      seats: [
        {
          id: "g1",
          label: "Federation",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "AP", value: "4" },
            { label: "Morale", value: "8" },
          ],
          timerMs: 120000,
          timerState: "running",
          avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=fed",
          connectionStatus: "online",
        },
        {
          id: "g2",
          label: "Zeon",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "AP", value: "3" },
            { label: "Morale", value: "6" },
          ],
          timerMs: 95000,
          timerState: "running",
          connectionStatus: "online",
        },
      ],
      zones: [
        {
          id: "g1-field",
          label: "Field",
          role: "battlefield",
          ownerId: "g1",
          visibility: "public",
          entityIds: ["gm1", "gm2"],
          hint: "Mobile suits on field",
        },
        {
          id: "g2-field",
          label: "Field",
          role: "battlefield",
          ownerId: "g2",
          visibility: "public",
          entityIds: ["gm3"],
          hint: "Opponent mobile suits",
        },
      ],
    },
    boardLayout: {
      title: "Gundam Demo Board",
      summary: "Targeting overlays and chess clock demo.",
      appearance: { variant: "opposed", density: "normal", labelPlacement: "rail" },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "zeon",
          label: "Zeon",
          role: "opponent",
          blocks: [
            { id: "g2-seat", kind: "seat", label: "Zeon", size: "wide" },
            { id: "g2-field", kind: "zone", label: "Field", size: "wide", zoneId: "g2-field" },
          ],
        },
        {
          id: "fed",
          label: "Federation",
          role: "player",
          blocks: [
            { id: "g1-field", kind: "zone", label: "Field", size: "wide", zoneId: "g1-field" },
            { id: "g1-seat", kind: "seat", label: "Federation", size: "wide" },
          ],
        },
      ],
    },
    entities: [
      {
        id: "gm1",
        title: "RX-78-2 Gundam",
        subtitle: "White Devil",
        kind: "unit",
        ownerId: "g1",
        face: "public",
        states: ["active"],
        stats: [
          { label: "Cost", value: "5" },
          { label: "ATK", value: "8000" },
          { label: "DEF", value: "6000" },
        ],
        traits: ["Mobile Suit", "Federation"],
        frameStyle: { color: "#1f5faa" },
        overlayBadges: [{ label: "ATK+", color: "#2563eb", position: "tr" }],
      },
      {
        id: "gm2",
        title: "Guncannon",
        subtitle: "Heavy Support",
        kind: "unit",
        ownerId: "g1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "3" },
          { label: "ATK", value: "5000" },
          { label: "DEF", value: "4000" },
        ],
        traits: ["Mobile Suit", "Federation"],
        frameStyle: { color: "#1f5faa" },
      },
      {
        id: "gm3",
        title: "MS-06S Zaku II",
        subtitle: "Red Comet",
        kind: "unit",
        ownerId: "g2",
        face: "public",
        states: ["active"],
        stats: [
          { label: "Cost", value: "4" },
          { label: "ATK", value: "7000" },
          { label: "DEF", value: "5000" },
        ],
        traits: ["Mobile Suit", "Zeon"],
        frameStyle: { color: "#c02664" },
        overlayBadges: [{ label: "DMG", color: "#dc2626", position: "tr" }],
      },
    ],
    interactions: [
      {
        id: "attack-prompt",
        label: "Declare Attack",
        prompt: "Select a target for RX-78-2 Gundam's attack.",
        sourceEntityId: "gm1",
        input: {
          kind: "single-target",
          candidateEntityIds: ["gm3"],
          targetZoneIds: ["g2-field"],
          options: [],
        },
        movePreview: {
          engine: "gundam",
          command: "attack",
          payload: '{"attacker":"gm1","target":"gm3"}',
        },
      },
    ],
    guideSteps: [
      { title: "Targeting overlay", body: "SVG arrows connect attacker to target." },
      { title: "Chess clock", body: "Timers show remaining time per player." },
    ],
    agentChecks: ["Targeting arrows render correctly", "Timer counts down"],
    coreComponents,
    eventLog: [
      {
        id: "ge1",
        turn: 1,
        phase: "Deploy",
        seatId: "g1",
        timestamp: "2024-01-01T11:00:00Z",
        message: "Federation deployed RX-78-2 Gundam",
        tags: ["move"],
        entityIds: ["gm1"],
      },
      {
        id: "ge2",
        turn: 2,
        phase: "Battle",
        seatId: "g2",
        timestamp: "2024-01-01T11:01:00Z",
        message: "Zeon attacked with Red Comet",
        tags: ["combat"],
        entityIds: ["gm3", "gm1"],
      },
      {
        id: "ge3",
        turn: 3,
        phase: "Battle",
        seatId: "g1",
        timestamp: "2024-01-01T11:02:00Z",
        message: "Federation is selecting attack target",
        tags: ["system"],
      },
    ],
    targetingIntents: [
      {
        id: "gti1",
        sourceEntityId: "gm1",
        targetEntityIds: ["gm3"],
        targetZoneIds: [],
        preview: { damage: 2000, banish: false },
      },
    ],
  },
  {
    id: "cyberpunk-choice-demo",
    gameSlug: "cyberpunk",
    name: "Cyberpunk Choice Demo",
    summary: "Demonstrates choice modals, chips, payment input, and ordering.",
    adapterGoal: "Showcase all interaction input kinds.",
    table: {
      status: {
        activeSeatId: "c1",
        phase: "Action",
        turn: 4,
        stateVersion: 22,
      },
      seats: [
        {
          id: "c1",
          label: "Netrunner",
          role: "human",
          perspective: "bottom",
          counters: [
            { label: "Eddies", value: "4500" },
            { label: "Street Cred", value: "12" },
          ],
          timerMs: 60000,
          timerState: "paused",
          connectionStatus: "online",
        },
        {
          id: "c2",
          label: "Corp",
          role: "agent",
          perspective: "top",
          counters: [
            { label: "Eddies", value: "8000" },
            { label: "Street Cred", value: "8" },
          ],
          connectionStatus: "offline",
        },
      ],
      zones: [
        {
          id: "c1-hand",
          label: "Grip",
          role: "hand",
          ownerId: "c1",
          visibility: "owner",
          entityIds: ["cy1", "cy2", "cy3"],
          layoutHint: "fan",
          hint: "Cyberpunk hand zone",
        },
        {
          id: "c1-board",
          label: "Street",
          role: "battlefield",
          ownerId: "c1",
          visibility: "public",
          entityIds: ["cy4"],
          hint: "Active runner cards",
        },
      ],
    },
    boardLayout: {
      title: "Cyberpunk Demo Board",
      summary: "Choice resolution and payment demo.",
      appearance: { variant: "dashboard", density: "normal", labelPlacement: "top" },
      buildingBlocks: boardBuildingBlocks,
      sections: [
        {
          id: "corp",
          label: "Corp",
          role: "opponent",
          blocks: [{ id: "c2-seat", kind: "seat", label: "Corp", size: "wide" }],
        },
        {
          id: "runner",
          label: "Runner",
          role: "player",
          blocks: [
            { id: "c1-board", kind: "zone", label: "Street", size: "wide", zoneId: "c1-board" },
            { id: "c1-hand", kind: "zone", label: "Grip", size: "full", zoneId: "c1-hand" },
            { id: "c1-seat", kind: "seat", label: "Netrunner", size: "wide" },
          ],
        },
      ],
    },
    entities: [
      {
        id: "cy1",
        title: "Quickhack",
        subtitle: "Short Circuit",
        kind: "card",
        ownerId: "c1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "2" },
          { label: "RAM", value: "3" },
        ],
        traits: ["Quickhack", "Damage"],
        frameStyle: { color: "#f5e642" },
      },
      {
        id: "cy2",
        title: "Weapon",
        subtitle: "Monowire",
        kind: "card",
        ownerId: "c1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "4" },
          { label: "DMG", value: "8" },
        ],
        traits: ["Weapon", "Melee"],
        frameStyle: { color: "#4ad9ff" },
      },
      {
        id: "cy3",
        title: "Program",
        subtitle: "Ping",
        kind: "card",
        ownerId: "c1",
        face: "public",
        states: ["ready"],
        stats: [
          { label: "Cost", value: "1" },
          { label: "RAM", value: "1" },
        ],
        traits: ["Quickhack", "Recon"],
        frameStyle: { color: "#f5e642" },
      },
      {
        id: "cy4",
        title: "V",
        subtitle: "Mercenary",
        kind: "character",
        ownerId: "c1",
        face: "public",
        states: ["active"],
        stats: [
          { label: "Health", value: "20" },
          { label: "Armor", value: "4" },
        ],
        traits: ["Mercenary", "Legend"],
        frameStyle: { color: "#b47919" },
      },
    ],
    interactions: [
      {
        id: "choice-binary",
        label: "Run the Gig?",
        prompt: "Do you want to attempt this netrun?",
        input: {
          kind: "option",
          options: [
            { id: "yes", label: "Yes, jack in" },
            { id: "no", label: "No, too risky" },
          ],
          candidateEntityIds: [],
          targetZoneIds: [],
        },
        movePreview: { engine: "cyberpunk", command: "choice", payload: '{"choice":"yes"}' },
      },
      {
        id: "payment-select",
        label: "Pay Eddies",
        prompt: "Select resources to pay the cost.",
        input: {
          kind: "payment",
          min: 1,
          max: 2,
          candidateEntityIds: ["cy1", "cy2", "cy3"],
          targetZoneIds: [],
          options: [],
        },
        movePreview: { engine: "cyberpunk", command: "pay", payload: "{}" },
      },
      {
        id: "ordering-select",
        label: "Stack Order",
        prompt: "Order your quickhacks for resolution.",
        input: {
          kind: "ordering",
          min: 2,
          max: 3,
          candidateEntityIds: ["cy1", "cy2", "cy3"],
          targetZoneIds: [],
          options: [],
        },
        movePreview: { engine: "cyberpunk", command: "order", payload: "[]" },
      },
    ],
    guideSteps: [
      { title: "Choice modal", body: "Binary choices rendered as modal options." },
      { title: "Payment input", body: "Click resources to mark as payment." },
      { title: "Ordering input", body: "Drag or click to set resolution order." },
    ],
    agentChecks: ["Choice chips are selectable", "Payment shows running total"],
    coreComponents,
    eventLog: [
      {
        id: "ce1",
        turn: 1,
        phase: "Setup",
        seatId: "c1",
        timestamp: "2024-01-01T12:00:00Z",
        message: "Netrunner drew starting hand",
        tags: ["system"],
      },
      {
        id: "ce2",
        turn: 2,
        phase: "Action",
        seatId: "c1",
        timestamp: "2024-01-01T12:01:00Z",
        message: "V deployed to the Street",
        tags: ["move"],
        entityIds: ["cy4"],
      },
      {
        id: "ce3",
        turn: 3,
        phase: "Action",
        seatId: "c2",
        timestamp: "2024-01-01T12:02:00Z",
        message: "Corp triggered ICE: Black ICE",
        tags: ["ability"],
      },
      {
        id: "ce4",
        turn: 4,
        phase: "Action",
        seatId: "c1",
        timestamp: "2024-01-01T12:03:00Z",
        message: "Netrunner is choosing actions",
        tags: ["system"],
      },
    ],
  },
];
