// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swu4lomBountyHunterForHire = {
  title: "4-LOM",
  subtitle: "Bounty Hunter for Hire",
  cost: 4,
  hp: 4,
  power: 4,
  text: "Ambush (When you play this unit, it may ready and attack an enemy unit.)\nEach friendly unit named Zuckuss gets +1/+1 and gains Ambush.",
  unique: true,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "6097248635",
  rarity: "uncommon",
  aspects: ["cunning", "villainy"],
  traits: ["underworld", "droid", "bounty hunter"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 188,
  },
  setCodes: [
    {
      set: "SHD",
      number: 188,
    },
  ],
  internalName: "4lom#bounty-hunter-for-hire",
  cardType: "unit",
  canonicalId: "4lom#bounty-hunter-for-hire",
  slug: "4lom-bounty-hunter-for-hire",
  name: "4-LOM",
  printings: [
    {
      id: "SHD_188",
      artId: "8138",
      setCode: "SHD",
      collectorNumber: "188",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0201188_EN_4_LOM_e3aa3f4030.png",
    },
    {
      id: "4401880694",
      artId: "8138",
      setCode: "SHD",
      collectorNumber: "188",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0231188_EN_4_LOM_2c246b13fa.png",
    },
    {
      id: "0403653124",
      artId: "8138",
      setCode: "SHD",
      collectorNumber: "457",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0202457_EN_4_LOM_e65de4cde1.png",
    },
    {
      id: "6313639866",
      artId: "8138",
      setCode: "SHD",
      collectorNumber: "457",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0232457_EN_4_LOM_8ba0bf57c5.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swu4lomBountyHunterForHire;
