// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuChainCodeCollector = {
  title: "Chain Code Collector",
  cost: 4,
  hp: 2,
  power: 4,
  text: "Ambush (When you play this unit, it may ready and attack an enemy unit.)\nOn Attack: If the defender has a Bounty, it gets –4/–0 for this attack.",
  unique: false,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "7171636330",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  keywords: ["ambush", "bounty"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 216,
  },
  setCodes: [
    {
      set: "SHD",
      number: 216,
    },
  ],
  internalName: "chain-code-collector",
  cardType: "unit",
  canonicalId: "chain-code-collector",
  slug: "chain-code-collector",
  name: "Chain Code Collector",
  printings: [
    {
      id: "SHD_216",
      artId: "6376",
      setCode: "SHD",
      collectorNumber: "216",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0201216_EN_Chain_Code_Collector_61afb80991.png",
    },
    {
      id: "0623634680",
      artId: "6376",
      setCode: "SHD",
      collectorNumber: "216",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0231216_EN_Chain_Code_Collector_971c399749.png",
    },
    {
      id: "0399224225",
      artId: "6376",
      setCode: "SHD",
      collectorNumber: "484",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202484_EN_Chain_Code_Collector_8a0da6fcdf.png",
    },
    {
      id: "2129402522",
      artId: "6376",
      setCode: "SHD",
      collectorNumber: "484",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0232484_EN_Chain_Code_Collector_6018af49fd.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
    {
      kind: "keyword",
      text: "Bounty",
      keyword: "bounty",
    },
  ],
} satisfies SwuUnitCard;

export default swuChainCodeCollector;
