// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCriminalMuscle = {
  title: "Criminal Muscle",
  cost: 1,
  hp: 1,
  power: 2,
  text: "When Played: You may return a non-unique upgrade to its owner's hand.",
  unique: false,
  rules:
    "Abilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "6475868209",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["underworld"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 209,
  },
  setCodes: [
    {
      set: "SHD",
      number: 209,
    },
  ],
  internalName: "criminal-muscle",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may return a non-unique upgrade to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "move",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["upgrade"],
                limit: 1,
              },
              to: "hand",
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuCriminalMuscle;
