// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuEnfysNestMarauder = {
  title: "Enfys Nest",
  subtitle: "Marauder",
  cost: 6,
  hp: 4,
  power: 5,
  text: "Ambush (When you play this unit, it may ready and attack an enemy unit.)\nWhile a friendly unit (including this one) is attacking using Ambush, the defender gets –3/–0.",
  unique: true,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "8107876051",
  rarity: "uncommon",
  aspects: ["cunning"],
  traits: ["underworld"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 219,
  },
  setCodes: [
    {
      set: "SHD",
      number: 219,
    },
  ],
  internalName: "enfys-nest#marauder",
  cardType: "unit",
  canonicalId: "enfys-nest#marauder",
  slug: "enfys-nest-marauder",
  name: "Enfys Nest",
  printings: [
    {
      id: "SHD_219",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "219",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0201219_EN_Enfys_Nest_a15f35b1a8.png",
    },
    {
      id: "3760476921",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "15",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0260015_EN_Enfys_Nest_a122108586.png",
    },
    {
      id: "7992663626",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "15",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0235015_EN_Enfys_Nest_f4c54bf0ab.png",
    },
    {
      id: "3681016965",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "219",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0231219_EN_Enfys_Nest_0f3d83c2a4.png",
    },
    {
      id: "2165962254",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "487",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0202487_EN_Enfys_Nest_e8e949edb2.png",
    },
    {
      id: "5268234983",
      artId: "8183",
      setCode: "SHD",
      collectorNumber: "487",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0232487_EN_Enfys_Nest_135aba9767.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuEnfysNestMarauder;
