// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuFugitiveWookiee = {
  title: "Fugitive Wookiee",
  cost: 2,
  hp: 3,
  power: 3,
  text: "Bounty — Exhaust a unit. (When this unit is defeated or captured, your opponent collects its bounty.)",
  unique: false,
  id: "6947306017",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["wookiee"],
  arena: "ground",
  keywords: ["bounty"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 211,
  },
  setCodes: [
    {
      set: "SHD",
      number: 211,
    },
  ],
  internalName: "fugitive-wookiee",
  cardType: "unit",
  canonicalId: "fugitive-wookiee",
  slug: "fugitive-wookiee",
  name: "Fugitive Wookiee",
  printings: [
    {
      id: "SHD_211",
      artId: "6351",
      setCode: "SHD",
      collectorNumber: "211",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0201211_EN_Fugitive_Wookiee_0aee6739fa.png",
    },
    {
      id: "4968605293",
      artId: "6351",
      setCode: "SHD",
      collectorNumber: "211",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0231211_EN_Fugitive_Wookiee_3142860814.png",
    },
    {
      id: "0966510450",
      artId: "6351",
      setCode: "SHD",
      collectorNumber: "479",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0232479_EN_Fugitive_Wookiee_aa5e37056e.png",
    },
    {
      id: "7390819087",
      artId: "6351",
      setCode: "SHD",
      collectorNumber: "479",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202479_EN_Fugitive_Wookiee_b73a299910.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Bounty",
      keyword: "bounty",
    },
  ],
} satisfies SwuUnitCard;

export default swuFugitiveWookiee;
