// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuGentleGiant = {
  title: "Gentle Giant",
  cost: 6,
  hp: 8,
  power: 2,
  text: "Grit (This unit gets +1/+0 for each damage on it.)\nOn Attack: You may heal damage from another unit equal to the damage on this unit.",
  unique: false,
  rules: "If the chosen unit has less damage on it than Gentle Giant, heal all damage on it.\n",
  id: "8190373087",
  rarity: "common",
  aspects: ["heroism", "vigilance"],
  traits: ["wookiee"],
  arena: "ground",
  keywords: ["grit"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 48,
  },
  setCodes: [
    {
      set: "SHD",
      number: 48,
    },
  ],
  internalName: "gentle-giant",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Grit",
      keyword: "grit",
    },
  ],
} satisfies SwuUnitCard;

export default swuGentleGiant;
