// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHunterOfTheHaxionBrood = {
  title: "Hunter of the Haxion Brood",
  cost: 3,
  hp: 3,
  power: 4,
  text: "While an enemy unit has a Bounty, this unit gains Shielded. (When you play this unit, give a Shield token to it.)",
  unique: false,
  id: "6939947927",
  rarity: "common",
  aspects: ["cunning", "villainy"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  keywords: ["bounty", "shielded"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 186,
  },
  setCodes: [
    {
      set: "SHD",
      number: 186,
    },
  ],
  internalName: "hunter-of-the-haxion-brood",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Bounty",
      keyword: "bounty",
    },
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
  ],
} satisfies SwuUnitCard;

export default swuHunterOfTheHaxionBrood;
