// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

const damageFriendlyAndEnemyGroundUnits = [
  effect.sequential([
    effect.damage(
      target.unit({ controller: "friendly", arena: "ground", excludeSelf: true, limit: 1 }),
      3,
    ),
    effect.damage(target.unit({ controller: "opponent", arena: "ground", limit: 1 }), 3),
  ]),
];

export const swuJabbasRancorPateesa = {
  title: "Jabba's Rancor",
  subtitle: "Pateesa",
  cost: 8,
  hp: 9,
  power: 9,
  text: "If you control Jabba the Hutt (as a leader or unit), this unit costs 1 resource less to play.\nWhen Played/On Attack: Deal 3 damage to another friendly ground unit and 3 damage to an enemy ground unit.",
  unique: true,
  id: "8380936981",
  rarity: "uncommon",
  aspects: ["command", "villainy"],
  traits: ["underworld", "creature"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 91,
  },
  setCodes: [
    {
      set: "SHD",
      number: 91,
    },
  ],
  internalName: "jabbas-rancor#pateesa",
  cardType: "unit",
  canonicalId: "jabbas-rancor#pateesa",
  slug: "jabbas-rancor-pateesa",
  name: "Jabba's Rancor",
  printings: [
    {
      id: "SHD_091",
      artId: "8043",
      setCode: "SHD",
      collectorNumber: "91",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0201091_EN_Jabbas_Rancor_84d48e1b0b.png",
    },
    {
      id: "6178606148",
      artId: "8043",
      setCode: "SHD",
      collectorNumber: "91",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0231091_EN_Jabbas_Rancor_ced4ace88c.png",
    },
    {
      id: "6420467779",
      artId: "8043",
      setCode: "SHD",
      collectorNumber: "360",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0232360_EN_Jabbas_Rancor_4e6e53e63f.png",
    },
    {
      id: "9646356444",
      artId: "8043",
      setCode: "SHD",
      collectorNumber: "360",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0202360_EN_Jabbas_Rancor_dfbddfe580.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played/On Attack: Deal 3 damage to another friendly ground unit and 3 damage to an enemy ground unit.",
      effects: damageFriendlyAndEnemyGroundUnits,
    }),
    ability.onAttack({
      text: "When Played/On Attack: Deal 3 damage to another friendly ground unit and 3 damage to an enemy ground unit.",
      effects: damageFriendlyAndEnemyGroundUnits,
    }),
  ],
} satisfies SwuUnitCard;

export default swuJabbasRancorPateesa;
