// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuKraytDragon = {
  title: "Krayt Dragon",
  cost: 9,
  hp: 10,
  power: 10,
  text: "Overwhelm\nWhen an opponent plays a card: You may deal damage equal to that card's cost to their base or a ground unit they control.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\nShields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\nIf Krayt Dragon is defeated by your opponent playing a card, its ability still triggers.\n",
  id: "4935319539",
  rarity: "legendary",
  aspects: ["aggression"],
  traits: ["creature"],
  arena: "ground",
  keywords: ["overwhelm"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 172,
  },
  setCodes: [
    {
      set: "SHD",
      number: 172,
    },
  ],
  internalName: "krayt-dragon",
  cardType: "unit",
  canonicalId: "krayt-dragon",
  slug: "krayt-dragon",
  name: "Krayt Dragon",
  printings: [
    {
      id: "SHD_172",
      artId: "6166",
      setCode: "SHD",
      collectorNumber: "172",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0201172_EN_Krayt_Dragon_a706ab6c21.png",
    },
    {
      id: "7190955170",
      artId: "6166",
      setCode: "SHD",
      collectorNumber: "172",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0231172_EN_Krayt_Dragon_3c5c85f891.png",
    },
    {
      id: "7031116483",
      artId: "6166",
      setCode: "SHD",
      collectorNumber: "441",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0232441_EN_Krayt_Dragon_cfae581930.png",
    },
    {
      id: "9703237388",
      artId: "6166",
      setCode: "SHD",
      collectorNumber: "441",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0202441_EN_Krayt_Dragon_d28ad41421.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
  ],
} satisfies SwuUnitCard;

export default swuKraytDragon;
