// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuPrincipledOutlaw = {
  title: "Principled Outlaw",
  cost: 4,
  hp: 4,
  power: 4,
  text: "On Attack: You may exhaust a ground unit.\nSmuggle [6 resources Cunning Heroism] (If this card is a resource, you may play it for its smuggle cost. Replace it with the top card of your deck.)",
  unique: false,
  id: "9040137775",
  rarity: "common",
  aspects: ["cunning", "heroism"],
  traits: ["underworld"],
  arena: "ground",
  keywords: ["smuggle"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 201,
  },
  setCodes: [
    {
      set: "SHD",
      number: 201,
    },
  ],
  internalName: "principled-outlaw",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Smuggle",
      keyword: "smuggle",
    },
    {
      kind: "triggered",
      text: "On Attack: You may exhaust a ground unit.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "exhaust",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuPrincipledOutlaw;
