// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheArmorerSurvivalIsStrength = {
  title: "The Armorer",
  subtitle: "Survival Is Strength",
  cost: 5,
  hp: 5,
  power: 3,
  text: "When Played: Give a Shield token to each of up to 3 Mandalorian units.",
  unique: true,
  id: "2560835268",
  rarity: "uncommon",
  aspects: ["heroism", "vigilance"],
  traits: ["mandalorian"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 47,
  },
  setCodes: [
    {
      set: "SHD",
      number: 47,
    },
  ],
  internalName: "the-armorer#survival-is-strength",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Give a Shield token to each of up to 3 Mandalorian units.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "shield",
          amount: 1,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuTheArmorerSurvivalIsStrength;
