// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuTheMarauderShuttlingTheBadBatch = {
  title: "The Marauder",
  subtitle: "Shuttling the Bad Batch",
  cost: 5,
  hp: 5,
  power: 4,
  text: "Ambush\nWhen Played: Choose a card in your discard pile. Put it into play as a resource if it shares a name with a unit you control.",
  unique: true,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\nAbilities that refer to a card’s “name” do not include the subtitle of the card.\nA card put into play as a resource enters play exhausted.\n",
  id: "2143627819",
  rarity: "rare",
  aspects: ["command", "heroism"],
  traits: ["fringe", "vehicle", "transport"],
  arena: "space",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 102,
  },
  setCodes: [
    {
      set: "SHD",
      number: 102,
    },
  ],
  internalName: "the-marauder#shuttling-the-bad-batch",
  cardType: "unit",
  canonicalId: "the-marauder#shuttling-the-bad-batch",
  slug: "the-marauder-shuttling-the-bad-batch",
  name: "The Marauder",
  printings: [
    {
      id: "SHD_102",
      artId: "8058",
      setCode: "SHD",
      collectorNumber: "102",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0201102_EN_The_Marauder_bf5262ebea.png",
    },
    {
      id: "4734342958",
      artId: "8058",
      setCode: "SHD",
      collectorNumber: "102",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0231102_EN_The_Marauder_bd9586e218.png",
    },
    {
      id: "6368736794",
      artId: "8058",
      setCode: "SHD",
      collectorNumber: "371",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0232371_EN_The_Marauder_8dde0c05c3.png",
    },
    {
      id: "6972231148",
      artId: "8058",
      setCode: "SHD",
      collectorNumber: "371",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0202371_EN_The_Marauder_1dc7aef3c3.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuTheMarauderShuttlingTheBadBatch;
