// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuWantedInsurgents = {
  title: "Wanted Insurgents",
  cost: 3,
  hp: 4,
  power: 4,
  text: "Bounty — Deal 2 damage to a unit. (When this unit is defeated or captured, your opponent collects its bounty.)",
  unique: false,
  id: "8679638018",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["rebel"],
  arena: "ground",
  keywords: ["bounty"],
  types: ["unit"],
  setId: {
    set: "SHD",
    number: 167,
  },
  setCodes: [
    {
      set: "SHD",
      number: 167,
    },
  ],
  internalName: "wanted-insurgents",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Bounty",
      keyword: "bounty",
    },
  ],
} satisfies SwuUnitCard;

export default swuWantedInsurgents;
