// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuFinnThisIsARescue = {
  title: "Finn",
  subtitle: "This is a Rescue",
  cost: 5,
  hp: 6,
  power: 4,
  text: "Action [Exhaust]: Defeat a friendly upgrade on a unit. If you do, give a Shield token to that unit.",
  deployBox:
    "On Attack: You may defeat a friendly upgrade on a unit. If you do, give a Shield token to that unit.",
  epicAction: "Epic Action: If you control 5 or more resources, deploy this leader.",
  unique: true,
  id: "9596662994",
  rarity: "rare",
  aspects: ["heroism", "vigilance"],
  traits: ["fringe", "trooper"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "SHD",
    number: 3,
  },
  setCodes: [
    {
      set: "SHD",
      number: 3,
    },
  ],
  internalName: "finn#this-is-a-rescue",
  cardType: "leader",
  abilities: [
    {
      kind: "action",
      text: "Action [Exhaust]: Defeat a friendly upgrade on a unit. If you do, give a Shield token to that unit.",
      trigger: {
        event: "action",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["upgrade"],
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "On Attack: You may defeat a friendly upgrade on a unit. If you do, give a Shield token to that unit.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "defeat",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["upgrade"],
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
    {
      kind: "action",
      text: "Epic Action: If you control 5 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuFinnThisIsARescue;
