// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuGovernorPryceTyrantOfLothal = {
  title: "Governor Pryce",
  subtitle: "Tyrant of Lothal",
  cost: 6,
  hp: 6,
  power: 4,
  text: "Action [1 resource, Exhaust]: Ready a token unit.",
  deployBox:
    "This unit gets +1/+0 for each ready friendly token unit.\nOn Attack: Create a Spy token.",
  epicAction: "Epic Action: If you control 6 or more resources, deploy this leader.",
  unique: true,
  id: "3669925252",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["imperial", "official"],
  arena: "ground",
  types: ["leader"],
  setId: {
    set: "SEC",
    number: 11,
  },
  setCodes: [
    {
      set: "SEC",
      number: 11,
    },
  ],
  internalName: "governor-pryce#tyrant-of-lothal",
  cardType: "leader",
  canonicalId: "governor-pryce#tyrant-of-lothal",
  slug: "governor-pryce-tyrant-of-lothal",
  name: "Governor Pryce",
  printings: [
    {
      id: "SEC_011",
      artId: "39430",
      setCode: "SEC",
      collectorNumber: "11",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06010011_EN_Governor_Pryce_Leader_02b3384dd0.png",
    },
    {
      id: "1796275948",
      artId: "39430",
      setCode: "SEC",
      collectorNumber: "275",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06020275_EN_Governor_Pryce_Leader_94a2c433c7.png",
    },
    {
      id: "1312177629",
      artId: "39430",
      setCode: "SEC",
      collectorNumber: "1031",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//06031031_EN_Governor_Pryce_Leader_3c386f609e.png",
    },
  ],
  abilities: [
    {
      kind: "action",
      text: "Action [1 resource, Exhaust]: Ready a token unit.",
      trigger: {
        event: "action",
      },
      effects: [
        {
          type: "ready",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "On Attack: Create a Spy token.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "createToken",
          token: "spy",
          amount: 1,
        },
      ],
    },
    {
      kind: "action",
      text: "Epic Action: If you control 6 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuGovernorPryceTyrantOfLothal;
