import type { UnitCard } from "@tcg/gundam-types";

export const gd04GmIii005: UnitCard = {
  cardNumber: "GD04-005",
  name: "GM III",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "GD04-005",
  externalId: "gundam:gd04-005",
  slug: "gm-iii-gd04-005",
  displayName: "GM III",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-005",
  printings: [
    {
      id: "GD04-005",
      collectorNumber: "GD04-005",
      cardNumber: "GD04-005",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-005.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-005.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
