import type { UnitCard } from "@tcg/gundam-types";

export const gd04Gaplant010: UnitCard = {
  cardNumber: "GD04-010",
  name: "Gaplant",
  type: "unit",
  color: "blue",
  traits: ["titans"],
  id: "GD04-010",
  externalId: "gundam:gd04-010",
  slug: "gaplant-gd04-010",
  displayName: "Gaplant",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-010",
  printings: [
    {
      id: "GD04-010",
      collectorNumber: "GD04-010",
      cardNumber: "GD04-010",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-010.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-010.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-010",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-010.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-010.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "(Titans) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
