import type { UnitCard } from "@tcg/gundam-types";

export const gd04CoreBooster005CoreBooster006012: UnitCard = {
  cardNumber: "GD04-012",
  name: "Core Booster (005) & Core Booster (006)",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "GD04-012",
  externalId: "gundam:gd04-012",
  slug: "core-booster-005-core-booster-006-gd04-012",
  displayName: "Core Booster (005) & Core Booster (006)",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-012",
  printings: [
    {
      id: "GD04-012",
      collectorNumber: "GD04-012",
      cardNumber: "GD04-012",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-012.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-012.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-012",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-012.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-012.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  linkCondition: "[Sleggar Law] / [Sayla Mass]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
