import type { UnitCard } from "@tcg/gundam-types";

export const gd04Shokew014: UnitCard = {
  cardNumber: "GD04-014",
  name: "Shokew",
  type: "unit",
  color: "blue",
  traits: ["league militaire", "zanscare"],
  id: "GD04-014",
  externalId: "gundam:gd04-014",
  slug: "shokew-gd04-014",
  displayName: "Shokew",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-014",
  printings: [
    {
      id: "GD04-014",
      collectorNumber: "GD04-014",
      cardNumber: "GD04-014",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-014.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-014.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-014",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-014.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-014.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
