import type { UnitCard } from "@tcg/gundam-types";

export const gd04Bigro027: UnitCard = {
  cardNumber: "GD04-027",
  name: "Bigro",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD04-027",
  externalId: "gundam:gd04-027",
  slug: "bigro-gd04-027",
  displayName: "Bigro",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-027",
  printings: [
    {
      id: "GD04-027",
      collectorNumber: "GD04-027",
      cardNumber: "GD04-027",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-027.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-027.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-027",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-027.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-027.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Tokwan]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
