import type { UnitCard } from "@tcg/gundam-types";

export const gd04Heindree031: UnitCard = {
  cardNumber: "GD04-031",
  name: "Heindree",
  type: "unit",
  color: "green",
  traits: ["academy"],
  id: "GD04-031",
  externalId: "gundam:gd04-031",
  slug: "heindree-gd04-031",
  displayName: "Heindree",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-031",
  printings: [
    {
      id: "GD04-031",
      collectorNumber: "GD04-031",
      cardNumber: "GD04-031",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-031.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-031.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-031",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-031.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-031.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
