import type { UnitCard } from "@tcg/gundam-types";

export const gd04XavierSGyanHakujiPacksGq032: UnitCard = {
  cardNumber: "GD04-032",
  name: "Xavier's Gyan Hakuji-Packs (GQ)",
  type: "unit",
  color: "green",
  traits: ["zeon"],
  id: "GD04-032",
  externalId: "gundam:gd04-032",
  slug: "xavier-s-gyan-hakuji-packs-gq-gd04-032",
  displayName: "Xavier's Gyan Hakuji-Packs (GQ)",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-032",
  printings: [
    {
      id: "GD04-032",
      collectorNumber: "GD04-032",
      cardNumber: "GD04-032",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-032.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-032.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-032",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-032.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-032.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 4,
  hp: 5,
  linkCondition: "[Xavier Olivette]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
