import type { UnitCard } from "@tcg/gundam-types";

export const gd04SchuzrumGalluss040: UnitCard = {
  cardNumber: "GD04-040",
  name: "Schuzrum-Galluss",
  type: "unit",
  color: "red",
  traits: ["neo zeon"],
  id: "GD04-040",
  externalId: "gundam:gd04-040",
  slug: "schuzrum-galluss-gd04-040",
  displayName: "Schuzrum-Galluss",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-040",
  printings: [
    {
      id: "GD04-040",
      collectorNumber: "GD04-040",
      cardNumber: "GD04-040",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-040.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-040.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-040",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-040.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-040.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Neo Zeon) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
