import type { UnitCard } from "@tcg/gundam-types";

export const gd04GundamVirtue047: UnitCard = {
  cardNumber: "GD04-047",
  name: "Gundam Virtue",
  type: "unit",
  color: "red",
  traits: ["cb", "gn drive"],
  id: "GD04-047",
  externalId: "gundam:gd04-047",
  slug: "gundam-virtue-gd04-047",
  displayName: "Gundam Virtue",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-047",
  printings: [
    {
      id: "GD04-047",
      collectorNumber: "GD04-047",
      cardNumber: "GD04-047",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-047.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-047.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-047",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-047.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-047.webp?260424",
  legality: "legal",
  level: 3,
  cost: 1,
  ap: 3,
  hp: 1,
  linkCondition: "[Tieria Erde]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
