import type { UnitCard } from "@tcg/gundam-types";

export const gd04HambrabiGq048: UnitCard = {
  cardNumber: "GD04-048",
  name: "Hambrabi (GQ)",
  type: "unit",
  color: "red",
  traits: ["earth federation"],
  id: "GD04-048",
  externalId: "gundam:gd04-048",
  slug: "hambrabi-gq-gd04-048",
  displayName: "Hambrabi (GQ)",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-048",
  printings: [
    {
      id: "GD04-048",
      collectorNumber: "GD04-048",
      cardNumber: "GD04-048",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-048.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-048.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-048",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-048.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-048.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 4,
  hp: 4,
  linkCondition: "(Earth Federation) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
