import type { UnitCard } from "@tcg/gundam-types";

export const gd04HeineSGoufIgnited055: UnitCard = {
  cardNumber: "GD04-055",
  name: "Heine's Gouf Ignited",
  type: "unit",
  color: "purple",
  traits: ["zaft", "minerva squad"],
  id: "GD04-055",
  externalId: "gundam:gd04-055",
  slug: "heine-s-gouf-ignited-gd04-055",
  displayName: "Heine's Gouf Ignited",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-055",
  printings: [
    {
      id: "GD04-055",
      collectorNumber: "GD04-055",
      cardNumber: "GD04-055",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-055.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-055.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-055",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-055.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-055.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Heine Westenfluss]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
