import type { UnitCard } from "@tcg/gundam-types";

export const gd04DaughtressHighMobilityCommandWiseWallaby059: UnitCard = {
  cardNumber: "GD04-059",
  name: "Daughtress High Mobility Command Wise Wallaby",
  type: "unit",
  color: "purple",
  traits: ["vulture"],
  id: "GD04-059",
  externalId: "gundam:gd04-059",
  slug: "daughtress-high-mobility-command-wise-wallaby-gd04-059",
  displayName: "Daughtress High Mobility Command Wise Wallaby",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-059",
  printings: [
    {
      id: "GD04-059",
      collectorNumber: "GD04-059",
      cardNumber: "GD04-059",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-059.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-059.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-059",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-059.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-059.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  linkCondition: "(Vulture) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
