import type { UnitCard } from "@tcg/gundam-types";

export const gd04LunamariaSGunnerZakuWarrior062: UnitCard = {
  cardNumber: "GD04-062",
  name: "Lunamaria's Gunner Zaku Warrior",
  type: "unit",
  color: "purple",
  traits: ["zaft", "minerva squad"],
  id: "GD04-062",
  externalId: "gundam:gd04-062",
  slug: "lunamaria-s-gunner-zaku-warrior-gd04-062",
  displayName: "Lunamaria's Gunner Zaku Warrior",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-062",
  printings: [
    {
      id: "GD04-062",
      collectorNumber: "GD04-062",
      cardNumber: "GD04-062",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-062.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-062.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-062",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-062.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-062.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 4,
  linkCondition: "(Minerva Squad) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
