import type { UnitCard } from "@tcg/gundam-types";

export const gd04GundamExia064: UnitCard = {
  cardNumber: "GD04-064",
  name: "Gundam Exia",
  type: "unit",
  color: "purple",
  traits: ["cb", "gn drive"],
  id: "GD04-064",
  externalId: "gundam:gd04-064",
  slug: "gundam-exia-gd04-064",
  displayName: "Gundam Exia",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-064",
  printings: [
    {
      id: "GD04-064",
      collectorNumber: "GD04-064",
      cardNumber: "GD04-064",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-064.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-064.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-064",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-064.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-064.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
