import type { UnitCard } from "@tcg/gundam-types";

export const gd04Hipheavy076: UnitCard = {
  cardNumber: "GD04-076",
  name: "Hipheavy",
  type: "unit",
  color: "white",
  traits: ["militia"],
  id: "GD04-076",
  externalId: "gundam:gd04-076",
  slug: "hipheavy-gd04-076",
  displayName: "Hipheavy",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-076",
  printings: [
    {
      id: "GD04-076",
      collectorNumber: "GD04-076",
      cardNumber: "GD04-076",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-076.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-076.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-076",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-076.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-076.webp?260424",
  legality: "legal",
  level: 1,
  cost: 1,
  ap: 1,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
