import type { UnitCard } from "@tcg/gundam-types";

export const gd04FlatMilitia077: UnitCard = {
  cardNumber: "GD04-077",
  name: "Flat (Militia)",
  type: "unit",
  color: "white",
  traits: ["militia"],
  id: "GD04-077",
  externalId: "gundam:gd04-077",
  slug: "flat-militia-gd04-077",
  displayName: "Flat (Militia)",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-077",
  printings: [
    {
      id: "GD04-077",
      collectorNumber: "GD04-077",
      cardNumber: "GD04-077",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-077.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-077.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-077",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-077.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-077.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 2,
  hp: 4,
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
