import type { UnitCard } from "@tcg/gundam-types";

export const gd04Borjarnon078: UnitCard = {
  cardNumber: "GD04-078",
  name: "Borjarnon",
  type: "unit",
  color: "white",
  traits: ["militia"],
  id: "GD04-078",
  externalId: "gundam:gd04-078",
  slug: "borjarnon-gd04-078",
  displayName: "Borjarnon",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-078",
  printings: [
    {
      id: "GD04-078",
      collectorNumber: "GD04-078",
      cardNumber: "GD04-078",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-078.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-078.webp?260424",
      productName: "Phantom Aria [GD04]",
    },
  ],
  selectedPrintingId: "GD04-078",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd04/GD04-078.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD04-078.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
