import type { UnitCard } from "@tcg/gundam-types";

export const gd04Agrissa079: UnitCard = {
  cardNumber: "GD04-079",
  name: "Agrissa",
  type: "unit",
  color: "white",
  traits: ["superpower bloc"],
  id: "GD04-079",
  canonicalId: "GD04-079",
  externalIds: { bandai: "gundam:gd04-079" },
  slug: "agrissa/gd04-079",
  displayName: "Agrissa",
  set: { code: "GD04", name: "Phantom Aria [GD04]", packageId: "616104" },
  printNumber: "GD04-079",
  printings: [
    {
      id: "GD04-079",
      artId: "GD04-079",
      setCode: "GD04",
      collectorNumber: "GD04-079",
      cardNumber: "GD04-079",
      set: {
        code: "GD04",
        name: "Phantom Aria [GD04]",
        packageId: "616104",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd04/GD04-079.webp",
      productName: "Phantom Aria [GD04]",
    },
  ],
  reprints: ["GD04-079"],
  selectedPrintingId: "GD04-079",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd04/GD04-079.webp",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Ali al-Saachez]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
