// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAllianceDispatcher = {
  title: "Alliance Dispatcher",
  cost: 1,
  hp: 2,
  power: 1,
  text: "Action [exhaust]: Play a unit from your hand. It costs [1 resource] less.",
  unique: false,
  id: "2756312994",
  rarity: "common",
  aspects: ["heroism", "command"],
  traits: ["rebel"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 93,
  },
  setCodes: [
    {
      set: "SOR",
      number: 93,
    },
  ],
  internalName: "alliance-dispatcher",
  cardType: "unit",
  canonicalId: "alliance-dispatcher",
  slug: "alliance-dispatcher",
  name: "Alliance Dispatcher",
  printings: [
    {
      id: "SOR_093",
      artId: "938",
      setCode: "SOR",
      collectorNumber: "93",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_093_Alliance_Dispatcher_fe21f2cebe.png",
    },
    {
      id: "8576516692",
      artId: "938",
      setCode: "SOR",
      collectorNumber: "93",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131093en_Alliance_Dispatcher_Foil_e9fab91b6d.png",
    },
    {
      id: "3947315264",
      artId: "938",
      setCode: "SOR",
      collectorNumber: "357",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132357en_Alliance_Dispatcher_HYP_Foil_db63fafeb3.png",
    },
    {
      id: "6223362580",
      artId: "938",
      setCode: "SOR",
      collectorNumber: "357",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01_357_Alliance_Dispatcher_HYP_3716191a4e.png",
    },
  ],
  abilities: [
    {
      kind: "action",
      text: "Action [exhaust]: Play a unit from your hand. It costs [1 resource] less.",
      trigger: {
        event: "action",
      },
      effects: [
        {
          type: "play",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["hand"],
            cardTypes: ["unit"],
            limit: 1,
          },
          free: false,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuAllianceDispatcher;
