// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuAvengerHuntingStarDestroyer = {
  title: "Avenger",
  subtitle: "Hunting Star Destroyer",
  cost: 9,
  hp: 8,
  power: 8,
  text: "When Played/On Attack: An opponent chooses a non‑leader unit they control. Defeat that unit.",
  unique: true,
  rules:
    "If there are multiple opponents, the controlling player chooses which one will be “an opponent.”\n",
  id: "8240629990",
  rarity: "legendary",
  aspects: ["villainy", "vigilance"],
  traits: ["imperial", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 40,
  },
  setCodes: [
    {
      set: "SOR",
      number: 40,
    },
  ],
  internalName: "avenger#hunting-star-destroyer",
  cardType: "unit",
  abilities: [
    {
      kind: "triggered",
      text: "When Played/On Attack: An opponent chooses a non‑leader unit they control. Defeat that unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "When Played/On Attack: An opponent chooses a non‑leader unit they control. Defeat that unit.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuAvengerHuntingStarDestroyer;
