// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuBlizzardAssaultAtat = {
  title: "Blizzard Assault AT-AT",
  cost: 8,
  hp: 9,
  power: 9,
  text: "When this unit attacks and defeats a unit: You may deal the excess damage from this attack to an enemy ground unit.",
  unique: false,
  rules:
    "(ERRATA) While attacking, this unit may deal its excess damage to an enemy ground unit.\nIf Blizzard Assault AT-AT is given Overwhelm, its controller chooses whether to apply the excess damage from its attack to a unit or to the defending player's base.\n",
  id: "3830969722",
  rarity: "uncommon",
  aspects: ["command", "villainy"],
  traits: ["imperial", "vehicle", "walker"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 88,
  },
  setCodes: [
    {
      set: "SOR",
      number: 88,
    },
  ],
  internalName: "blizzard-assault-atat",
  cardType: "unit",
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "When this unit attacks and defeats a unit: You may deal the excess damage from this attack to an enemy ground unit.",
        effects: [
          effect.optional([
            effect.damage(target.unit({ controller: "opponent", arena: "ground", limit: 1 }), 2),
          ]),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuBlizzardAssaultAtat;
