// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuBountyHunterCrew = {
  title: "Bounty Hunter Crew",
  cost: 6,
  hp: 4,
  power: 4,
  text: "Ambush (After you play this unit, it may ready and attack an enemy unit.)\n\nWhen Played: You may return an event from a discard pile to its owner's hand.",
  unique: false,
  rules:
    "Ambush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "3684950815",
  rarity: "common",
  aspects: ["villainy", "cunning"],
  traits: ["underworld", "bounty hunter"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 183,
  },
  setCodes: [
    {
      set: "SOR",
      number: 183,
    },
  ],
  internalName: "bounty-hunter-crew",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuBountyHunterCrew;
