// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCountDookuDarthTyranus = {
  title: "Count Dooku",
  subtitle: "Darth Tyranus",
  cost: 7,
  hp: 4,
  power: 5,
  text: "Shielded (When you play this unit, give him a Shield token.)\n\nWhen Played: You may defeat a unit with 4 or less remaining HP.",
  unique: true,
  id: "9624333142",
  rarity: "rare",
  aspects: ["villainy", "vigilance"],
  traits: ["force", "sith", "separatist"],
  arena: "ground",
  keywords: ["shielded"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 38,
  },
  setCodes: [
    {
      set: "SOR",
      number: 38,
    },
  ],
  internalName: "count-dooku#darth-tyranus",
  cardType: "unit",
  canonicalId: "count-dooku#darth-tyranus",
  slug: "count-dooku-darth-tyranus",
  name: "Count Dooku",
  printings: [
    {
      id: "SOR_038",
      artId: "315",
      setCode: "SOR",
      collectorNumber: "38",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_038_Count_Dooku_ca0953bc50.png",
    },
    {
      id: "5985347994",
      artId: "315",
      setCode: "SOR",
      collectorNumber: "38",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0131038en_Count_Dooku_Foil_da61b18400.png",
    },
    {
      id: "1333926733",
      artId: "315",
      setCode: "SOR",
      collectorNumber: "304",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0132304en_Count_Dooku_HYP_Foil_4635bdb5d0.png",
    },
    {
      id: "2989758026",
      artId: "315",
      setCode: "SOR",
      collectorNumber: "304",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_304_Count_Dooku_HYP_d683fa1dae.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Shielded",
      keyword: "shielded",
    },
    {
      kind: "triggered",
      text: "When Played: You may defeat a unit with 4 or less remaining HP.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "defeat",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
                hp: {
                  operator: "lte",
                  value: 4,
                },
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuCountDookuDarthTyranus;
