// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuDelMeekoProvidingOverwatch = {
  title: "Del Meeko",
  subtitle: "Providing Overwatch",
  cost: 3,
  hp: 3,
  power: 3,
  text: "Restore 1 (When this unit attacks, heal 1 damage from your base.)\n\nEach event an opponent plays costs [1 resource] more.",
  unique: true,
  id: "9412277544",
  rarity: "rare",
  aspects: ["vigilance", "villainy"],
  traits: ["imperial", "trooper"],
  arena: "ground",
  keywords: ["restore"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 34,
  },
  setCodes: [
    {
      set: "SOR",
      number: 34,
    },
  ],
  internalName: "del-meeko#providing-overwatch",
  cardType: "unit",
  canonicalId: "del-meeko#providing-overwatch",
  slug: "del-meeko-providing-overwatch",
  name: "Del Meeko",
  printings: [
    {
      id: "SOR_034",
      artId: "393",
      setCode: "SOR",
      collectorNumber: "34",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_034_Del_Meeko_b5f3fa0f46.png",
    },
    {
      id: "6368641736",
      artId: "393",
      setCode: "SOR",
      collectorNumber: "34",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0131034en_Del_Meeko_Foil_0ef68ccf59.png",
    },
    {
      id: "1704585645",
      artId: "393",
      setCode: "SOR",
      collectorNumber: "300",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0132300en_Del_Meeko_HYP_Foil_9cab0e825d.png",
    },
    {
      id: "7826218312",
      artId: "393",
      setCode: "SOR",
      collectorNumber: "300",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_300_Del_Meeko_HYP_f39d63e95d.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
  ],
} satisfies SwuUnitCard;

export default swuDelMeekoProvidingOverwatch;
