// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuJedhaAgitator = {
  title: "Jedha Agitator",
  cost: 2,
  hp: 1,
  power: 2,
  text: "Saboteur (When this unit attacks, ignore Sentinel and defeat the defender's Shields.)\n\nOn Attack: If you control a leader unit, deal 2 damage to a ground unit or a base.",
  unique: false,
  id: "1746195484",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["rebel"],
  arena: "ground",
  keywords: ["saboteur"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 158,
  },
  setCodes: [
    {
      set: "SOR",
      number: 158,
    },
  ],
  internalName: "jedha-agitator",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Saboteur",
      keyword: "saboteur",
    },
  ],
} satisfies SwuUnitCard;

export default swuJedhaAgitator;
