// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuPartisanInsurgent = {
  title: "Partisan Insurgent",
  cost: 2,
  hp: 4,
  power: 1,
  text: "While you control another [Aggression] unit, this unit gains Raid 2. (It gets +2/+0 while attacking.)",
  unique: false,
  id: "4642322279",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["rebel", "trooper"],
  arena: "ground",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 159,
  },
  setCodes: [
    {
      set: "SOR",
      number: 159,
    },
  ],
  internalName: "partisan-insurgent",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
  ],
} satisfies SwuUnitCard;

export default swuPartisanInsurgent;
