// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRedemptionMedicalFrigate = {
  title: "Redemption",
  subtitle: "Medical Frigate",
  cost: 8,
  hp: 9,
  power: 6,
  text: "Sentinel (Units in this arena can't attack your non-Sentinel units or your base.)\n\nWhen Played: Heal up to 8 total damage from any number of units and/or bases. Deal that much damage to this unit.",
  unique: true,
  id: "3896582249",
  rarity: "rare",
  aspects: ["vigilance", "heroism"],
  traits: ["rebel", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 52,
  },
  setCodes: [
    {
      set: "SOR",
      number: 52,
    },
  ],
  internalName: "redemption#medical-frigate",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuRedemptionMedicalFrigate;
