// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRogueSquadronSkirmisher = {
  title: "Rogue Squadron Skirmisher",
  cost: 6,
  hp: 6,
  power: 4,
  text: "Ambush (After you play this unit, it may ready and attack an enemy unit.)\n\nWhen Played: Return a unit that costs 2 or less from your discard pile to your hand.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\nAmbush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does not ready.\n",
  id: "3377409249",
  rarity: "uncommon",
  aspects: ["command", "heroism"],
  traits: ["rebel", "vehicle", "speeder"],
  arena: "ground",
  keywords: ["ambush"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 101,
  },
  setCodes: [
    {
      set: "SOR",
      number: 101,
    },
  ],
  internalName: "rogue-squadron-skirmisher",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
  ],
} satisfies SwuUnitCard;

export default swuRogueSquadronSkirmisher;
