// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRuggedSurvivors = {
  title: "Rugged Survivors",
  cost: 5,
  hp: 5,
  power: 3,
  text: "Grit (This unit gets +1/+0 for each damage on it.)\n\nOn Attack: If you control a leader unit, you may draw a card.",
  unique: false,
  id: "4599464590",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["fringe"],
  arena: "ground",
  keywords: ["grit"],
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 67,
  },
  setCodes: [
    {
      set: "SOR",
      number: 67,
    },
  ],
  internalName: "rugged-survivors",
  cardType: "unit",
  canonicalId: "rugged-survivors",
  slug: "rugged-survivors",
  name: "Rugged Survivors",
  printings: [
    {
      id: "SOR_067",
      artId: "327",
      setCode: "SOR",
      collectorNumber: "67",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_067_Rugged_Survivors_f9ab35178a.png",
    },
    {
      id: "2831131518",
      artId: "327",
      setCode: "SOR",
      collectorNumber: "67",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0131067en_Rugged_Survivors_Foil_2f60ee0473.png",
    },
    {
      id: "5730679165",
      artId: "327",
      setCode: "SOR",
      collectorNumber: "332",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_332_Rugged_Survivors_HYP_970a06d3ed.png",
    },
    {
      id: "8019819428",
      artId: "327",
      setCode: "SOR",
      collectorNumber: "332",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132332en_Rugged_Survivors_HYP_Foil_9efb41ab8f.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Grit",
      keyword: "grit",
    },
  ],
} satisfies SwuUnitCard;

export default swuRuggedSurvivors;
