// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSeasonedShoretrooper = {
  title: "Seasoned Shoretrooper",
  cost: 2,
  hp: 3,
  power: 2,
  text: "While you control 6 or more resources, this unit gets +2/+0.",
  unique: false,
  id: "3988315236",
  rarity: "common",
  aspects: ["villainy", "command"],
  traits: ["imperial", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "SOR",
    number: 81,
  },
  setCodes: [
    {
      set: "SOR",
      number: 81,
    },
    {
      set: "SHD",
      number: 83,
    },
  ],
  internalName: "seasoned-shoretrooper",
  cardType: "unit",
  canonicalId: "seasoned-shoretrooper",
  slug: "seasoned-shoretrooper",
  name: "Seasoned Shoretrooper",
  printings: [
    {
      id: "SOR_081",
      artId: "334",
      setCode: "SOR",
      collectorNumber: "81",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_081_Seasoned_Shoretrooper_1899d2dcf2.png",
    },
    {
      id: "SHD_083",
      artId: "334",
      setCode: "SHD",
      collectorNumber: "83",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_081_Seasoned_Shoretrooper_1899d2dcf2.png",
    },
    {
      id: "8258516559",
      artId: "334",
      setCode: "SOR",
      collectorNumber: "81",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131081en_Seasoned_Shoretrooper_Foil_a08a7b60c4.png",
    },
    {
      id: "0904421047",
      artId: "334",
      setCode: "SOR",
      collectorNumber: "346",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01_346_Seasoned_Shoretrooper_HYP_db8a1dc235.png",
    },
    {
      id: "3953039583",
      artId: "334",
      setCode: "SOR",
      collectorNumber: "346",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132346en_Seasoned_Shoretrooper_HYP_Foil_3dbb67eafc.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "While you control 6 or more resources, this unit gets +2/+0.",
      conditions: [
        {
          type: "resources",
          controller: "friendly",
          comparison: {
            operator: "gte",
            value: 6,
          },
        },
      ],
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "self",
          },
          power: 2,
          hp: 0,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuSeasonedShoretrooper;
