packages:
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24.13.3
  "@typescript/native": npm:typescript@7.0.2
  "typescript": npm:@typescript/typescript6@6.0.2
  "vite-plus": 0.2.4
  "vitest": npm:@voidzero-dev/vite-plus-test@0.1.24

catalogMode: prefer
onlyBuiltDependencies:
  - esbuild
