// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuExperience = {
  title: "Experience",
  cost: 0,
  unique: false,
  upgradePower: 1,
  upgradeHp: 1,
  id: "2503144758",
  rarity: "common",
  traits: ["learned"],
  types: ["upgrade", "token"],
  setId: {
    set: "SEC",
  },
  internalName: "experience",
  cardType: "upgrade",
} satisfies SwuUpgradeCard;

export default swuExperience;
