export type GundamAnimationFamily =
  | "setup"
  | "zone-transfer"
  | "command-effect"
  | "combat"
  | "state-economy"
  | "flow"
  | "interaction";

export type GundamAnimationCoverage = "browser-validated" | "automated-only" | "implementation-gap";

export interface GundamAnimationInventoryEntry {
  readonly id: string;
  readonly family: GundamAnimationFamily;
  readonly playerSignal: string;
  readonly engineTrigger: string;
  readonly implementation: string;
  readonly visualFixture: string | null;
  readonly exercise: string;
  readonly coverage: GundamAnimationCoverage;
}

/**
 * Canonical inventory for Gundam simulator motion.
 *
 * Keep this list source-derived: move-log variants come from GundamMoveLog,
 * outcome variants come from GundamMoveOutcomes, and interaction-only rows
 * identify their owning UI component. A row may be marked browser-validated
 * only after the deterministic fixture has been exercised in the in-app
 * browser at the representative viewport(s).
 */
export const GUNDAM_ANIMATION_INVENTORY = [
  entry(
    "setup-opening-hand",
    "setup",
    "Five concealed cards deal from deck into each hand.",
    "choose-first-player -> mulligan onEnter",
    "setup zone-delta plans",
    "setup-default-opponent-keeps",
    "Choose who goes first and observe both opening hands.",
    "browser-validated",
  ),
  entry(
    "setup-mulligan-redraw",
    "setup",
    "The kept hand clears and five replacements deal in as one readable sequence.",
    "alterHand { wantsRedraw: true }",
    "setup zone-delta plans",
    "setup-default-opponent-keeps",
    "Choose Redraw Hand.",
    "browser-validated",
  ),
  entry(
    "setup-shield-deal",
    "setup",
    "Six concealed shields populate without exposing identity.",
    "mulligan onExit -> post-mulligan setup",
    "setup zone-delta plans",
    "setup-default-opponent-keeps",
    "Finish mulligans and observe shield counters populate.",
    "browser-validated",
  ),
  entry(
    "draw-owner",
    "zone-transfer",
    "A hidden deck card travels to the viewer hand and reveals only at arrival.",
    "outcomes.cardsDrawn",
    "shared moveEntity deck -> hand",
    "attack-trigger-draw-demo",
    "Declare the attack and observe the triggered draw.",
    "browser-validated",
  ),
  entry(
    "draw-private-observer",
    "zone-transfer",
    "Opponent and spectator draws remain card backs throughout motion.",
    "outcomes.cardsDrawn + viewer projection",
    "shared moveEntity with hidden entity projection",
    "bot-vs-bot",
    "Observe either bot draw from the spectator route.",
    "browser-validated",
  ),
  entry(
    "deploy-unit",
    "zone-transfer",
    "A Unit moves from hand to the battle area.",
    "moveLog.deployUnit",
    "shared moveEntity hand -> battleArea",
    "deploy-unit-demo",
    "Play RX-78-2.",
    "browser-validated",
  ),
  entry(
    "deploy-base",
    "zone-transfer",
    "A Base moves from hand to the base section.",
    "moveLog.deployBase",
    "shared moveEntity hand -> baseSection",
    "deploy-base-demo",
    "Play White Base.",
    "browser-validated",
  ),
  entry(
    "assign-pilot",
    "zone-transfer",
    "A Pilot moves from hand onto its paired Unit.",
    "moveLog.assignPilot",
    "shared moveEntity hand -> battleArea plus paired layout",
    "pilot-pair-demo",
    "Play Amuro Ray and select Guncannon.",
    "browser-validated",
  ),
  entry(
    "discard-from-hand",
    "zone-transfer",
    "Discarded cards visibly leave hand for Scrap.",
    "outcomes.cardsDiscarded",
    "shared moveEntity hand -> trash",
    "discard-limit-demo",
    "Select two cards for the hand-limit discard.",
    "browser-validated",
  ),
  entry(
    "return-to-hand",
    "zone-transfer",
    "A field card returns to its owner's hand.",
    "outcomes.cardsReturnedToHand",
    "shared moveEntity play zone -> hand",
    "return-to-hand-demo",
    "Play The Witch and the Bride, choose Zaku II, and confirm.",
    "browser-validated",
  ),
  entry(
    "defeated-to-scrap",
    "zone-transfer",
    "A defeated Unit leaves the battle area for Scrap after impact.",
    "outcomes.unitsDefeated",
    "shared moveEntity battleArea -> trash",
    "mutual-destruction-demo",
    "Attack Aggressor with Jet and resolve combat.",
    "browser-validated",
  ),
  entry(
    "shield-to-scrap",
    "zone-transfer",
    "A broken shield travels concealed from the shield area into its owner's Scrap.",
    "outcomes.shieldsRemoved",
    "shared moveEntity shieldArea -> trash",
    "burst-shield-demo",
    "Pass Block and resolve the direct hit.",
    "browser-validated",
  ),
  entry(
    "resource-placement",
    "zone-transfer",
    "A new resource travels from deck into the resource row.",
    "resource-area projection delta or outcomes.resourcesPlaced",
    "shared moveEntity concealed stack -> resourceArea plus resource delta",
    "multi-turn-demo",
    "Pass through the opponent turn into the viewer resource phase.",
    "browser-validated",
  ),
  entry(
    "generic-zone-move",
    "zone-transfer",
    "Effect-driven movement visibly connects its real source and destination zones.",
    "outcomes.cardsMoved",
    "shared moveEntity source -> destination",
    "return-to-deck-demo",
    "Play Strategic Redeployment and return GM from hand to deck.",
    "browser-validated",
  ),
  entry(
    "command-automatic",
    "command-effect",
    "A Command moves hand -> focus, spotlights, then focus -> Scrap.",
    "moveLog.playCommand with no unresolved effect",
    "command focus anchor plan",
    "command-auto-resolve-demo",
    "Play Supply Drop.",
    "browser-validated",
  ),
  entry(
    "command-targeted",
    "command-effect",
    "A Command waits in focus while its target is selected, then resolves to Scrap.",
    "playCommand -> resolveEffect",
    "command focus anchor plus effect beam",
    "command-rest-demo",
    "Play Stand By, choose the enemy Unit, and confirm.",
    "browser-validated",
  ),
  entry(
    "command-multi-stage",
    "command-effect",
    "A Command remains focused across every target group and scraps only after the final group.",
    "multiple resolveEffect logs while source remains in removalArea",
    "retained command focus anchor",
    "command-multi-target-demo",
    "Resolve both Extreme Hatred target groups.",
    "browser-validated",
  ),
  entry(
    "effect-targeted",
    "command-effect",
    "An effect beam connects its public source to selected targets.",
    "moveLog.resolveEffect with targets",
    "shared effect step",
    "support-ability-demo",
    "Activate Support and choose the receiving Unit.",
    "browser-validated",
  ),
  entry(
    "effect-targetless",
    "command-effect",
    "A targetless effect spotlights its source card.",
    "moveLog.resolveEffect without targets",
    "shared spotlightEntity step",
    "activate-ability-demo",
    "Activate Scout Drone's draw ability.",
    "browser-validated",
  ),
  entry(
    "attack-unit",
    "combat",
    "A declaration beam establishes attacker and defending Unit.",
    "moveLog.attack target card",
    "shared combat declared step",
    "battle-ready-demo",
    "Choose the attacker and the rested enemy Unit.",
    "browser-validated",
  ),
  entry(
    "attack-direct",
    "combat",
    "A declaration beam points from attacker to the opponent base section.",
    "moveLog.attack target direct",
    "shared combat declared step",
    "suppression-demo",
    "Declare the direct attack.",
    "browser-validated",
  ),
  entry(
    "block-declared",
    "combat",
    "A blocker beam clearly redirects combat to the attacking Unit.",
    "moveLog.block",
    "shared combat declared step",
    "block-step-demo",
    "Choose Guncannon Blocker and confirm.",
    "browser-validated",
  ),
  entry(
    "combat-damage",
    "combat",
    "Impact motion identifies source, target, and resolved damage amount.",
    "outcomes.damageDealt",
    "shared combat resolved step with detailLabel",
    "first-strike-demo",
    "Resolve the attack through damage.",
    "browser-validated",
  ),
  entry(
    "resource-spend",
    "state-economy",
    "A resource delta calls out the amount paid at the resource row.",
    "outcomes.resourcesSpent",
    "shared resourceDelta step",
    "deploy-unit-demo",
    "Play the cost-1 Unit.",
    "browser-validated",
  ),
  entry(
    "card-rest",
    "state-economy",
    "The card rotates to rested and receives a short REST spotlight.",
    "outcomes.unitsRested or cardsExhausted",
    "CardFace transform transition plus spotlightEntity",
    "command-multi-target-demo",
    "Choose Zaku II and Dom for Extreme Hatred's rest cost.",
    "browser-validated",
  ),
  entry(
    "card-ready",
    "state-economy",
    "The card rotates upright and receives a short READY spotlight.",
    "projected exhausted -> ready delta or outcomes.cardsReadied",
    "CardFace transform transition plus projected READY spotlight",
    "multi-turn-demo",
    "Pass turns until the viewer's next start phase readies Guncannon.",
    "browser-validated",
  ),
  entry(
    "phase-change",
    "flow",
    "A concise banner names the new game phase without blocking the field.",
    "projected status label change",
    "shared phaseChange step",
    "multi-turn-demo",
    "Pass Turn and observe phase progression.",
    "browser-validated",
  ),
  entry(
    "turn-change",
    "flow",
    "A turn banner identifies the new turn and active player.",
    "projected status.turn change or moveLog.turnStart",
    "shared phaseChange variant turn from projected lifecycle status",
    "multi-turn-demo",
    "Complete the opponent turn.",
    "browser-validated",
  ),
  entry(
    "game-end",
    "flow",
    "The result overlay enters with winner, reason, and exit actions.",
    "moveLog.gameEnd / projected gameover status",
    "Match end modal transition",
    "main-phase-demo",
    "Choose Eject and observe the defeat result overlay.",
    "browser-validated",
  ),
  entry(
    "playable-pulse",
    "interaction",
    "Legal cards pulse subtly so the player can find available actions.",
    "selectableCardIds",
    "gd-pulse-playable CSS animation",
    "deploy-unit-demo",
    "Observe RX-78-2 before selecting it.",
    "browser-validated",
  ),
  entry(
    "target-feedback",
    "interaction",
    "Candidates pulse and selected targets settle into a distinct selected state.",
    "pending target selection",
    "gd-target-candidate and gd-target-selected CSS animations",
    "command-multi-target-demo",
    "Select the two friendly Units, then the enemy Unit.",
    "browser-validated",
  ),
  entry(
    "hand-focus",
    "interaction",
    "Hover, keyboard focus, and selection lift a hand card without reflow jitter.",
    "pointer/focus interaction",
    "HandZone transform/filter transition",
    "main-phase-demo",
    "Hover and keyboard-focus each hand card.",
    "browser-validated",
  ),
  entry(
    "urgent-timer",
    "interaction",
    "A low clock pulses red without moving surrounding controls.",
    "remaining time <= urgency threshold",
    "PlayerTimer pulse animation",
    "urgent-timer-demo",
    "Observe the viewer clock inside its final ten seconds.",
    "browser-validated",
  ),
] as const satisfies readonly GundamAnimationInventoryEntry[];

function entry(
  id: string,
  family: GundamAnimationFamily,
  playerSignal: string,
  engineTrigger: string,
  implementation: string,
  visualFixture: string | null,
  exercise: string,
  coverage: GundamAnimationCoverage,
): GundamAnimationInventoryEntry {
  return {
    id,
    family,
    playerSignal,
    engineTrigger,
    implementation,
    visualFixture,
    exercise,
    coverage,
  };
}
