import { repairAbility } from "~/game-engine/engines/gundam/src/abilities/abilities";
import type { GundamitoUnitCard } from "../../cardTypes";

export const guncacconRx77: GundamitoUnitCard = {
  id: "GD01-004",
  implemented: true,
  cost: 2,
  level: 3,
  number: 4,
  type: "unit",
  name: "Guncannon | RX-77",
  color: "blue",
  set: "GD01",
  rarity: "rare",
  zones: ["space", "earth"],
  traits: ["earth federation", "white base team"],
  linkRequirement: ["white base team"],
  ap: 2,
  hp: 3,
  abilities: [
    repairAbility(1),
    {
      type: "when-paired",
      text: "Choose 1 enemy Unit with 2 or less HP. Rest it.",
      effects: [
        {
          type: "rest",
          rest: true,
          target: {
            type: "card",
            value: 1,
            filters: [
              { filter: "zone", value: "battle" },
              { filter: "owner", value: "opponent" },
              {
                filter: "attribute",
                value: "hp",
                comparison: { operator: "lte", value: 2 },
              },
            ],
          },
        },
      ],
    },
  ],
};

export const unicornGundamRx0: GundamitoUnitCard = {
  id: "GD01-005",
  implemented: true,
  cost: 4,
  level: 5,
  number: 5,
  type: "unit",
  name: "Unicorn Gundam (Unicorn Mode) | RX-0",
  color: "blue",
  set: "GD01",
  rarity: "rare",
  zones: ["space", "earth"],
  traits: ["civilian"],
  linkRequirement: ["banagher links"],
  ap: 4,
  hp: 3,
  abilities: [
    {
      type: "destroyed",
      conditions: [{ type: "during-pair", onlyLinked: true }],
      effects: [
        {
          type: "move",
          to: "hand",
          target: {
            type: "card",
            value: "all",
            filters: [
              { filter: "paired-with", value: "source" },
              { filter: "owner", value: "self" },
              { filter: "type", value: "pilot" },
            ],
          },
        },
      ],
    },
  ],
};

export const gundamRx782: GundamitoUnitCard = {
  id: "GD01-013",
  implemented: true,
  cost: 2,
  level: 4,
  number: 13,
  type: "unit",
  name: "Gundam | RX-78-2",
  color: "blue",
  set: "GD01",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["earth federation", "white base team"],
  linkRequirement: ["amuro ray"],
  ap: 3,
  hp: 4,
  abilities: [],
};

export const ballRB79: GundamitoUnitCard = {
  id: "GD01-015",
  implemented: true,
  cost: 1,
  level: 1,
  number: 15,
  type: "unit",
  name: "Ball | RB-79",
  color: "blue",
  set: "GD01",
  rarity: "common",
  zones: ["space"],
  traits: ["earth federation"],
  linkRequirement: [],
  ap: 1,
  hp: 1,
  abilities: [
    {
      type: "attack",
      text: "Choose one of your Units. It recover 1 HP.",
      effects: [
        {
          type: "heal",
          amount: 1,
          target: {
            type: "card",
            value: 1,
            filters: [
              { filter: "zone", value: "battle" },
              { filter: "owner", value: "self" },
              { filter: "type", value: "unit" },
            ],
          },
        },
      ],
    },
  ],
};

export const charsZakuIIMS065: GundamitoUnitCard = {
  id: "GD01-026",
  implemented: true,
  cost: 2,
  level: 3,
  number: 26,
  type: "unit",
  name: "Char's Zaku II | MS-065",
  color: "green",
  set: "GD01",
  rarity: "rare",
  zones: ["space", "earth"],
  traits: ["zeon"],
  linkRequirement: ["char aznable"],
  ap: 3,
  hp: 2,
  abilities: [],
};

export const gundamSandrockXXXG01SR: GundamitoUnitCard = {
  id: "GD01-028",
  implemented: true,
  cost: 3,
  level: 5,
  number: 28,
  type: "unit",
  name: "Gundam Sandrock | XXXG-01SR",
  color: "green",
  set: "GD01",
  rarity: "rare",
  zones: ["earth"],
  traits: ["operation meteor"],
  linkRequirement: ["quatre raberba winner"],
  ap: 4,
  hp: 4,
  abilities: [],
};

export const gelgoogMS14S: GundamitoUnitCard = {
  id: "GD01-031",
  implemented: true,
  cost: 2,
  level: 4,
  number: 31,
  type: "unit",
  name: "Gelgoog | MS-14",
  color: "green",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space", "earth"],
  traits: ["zeon"],
  linkRequirement: ["zeon trait"],
  ap: 4,
  hp: 3,
  abilities: [],
};

export const wingGundamXXX01W: GundamitoUnitCard = {
  id: "GD01-040",
  implemented: true,
  cost: 2,
  level: 5,
  number: 40,
  type: "unit",
  name: "Wing Gundam | XXXG-01W",
  color: "green",
  set: "GD01",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["operation meteor"],
  linkRequirement: ["heero yuy"],
  ap: 4,
  hp: 3,
  abilities: [],
};

export const gundamAerialXVX016: GundamitoUnitCard = {
  id: "GD01-070",
  implemented: true,
  cost: 3,
  level: 5,
  number: 70,
  type: "unit",
  name: "Gundam Aerial | XVX-016",
  color: "white",
  set: "GD01",
  rarity: "rare",
  zones: ["space", "earth"],
  traits: ["earth alliance"],
  linkRequirement: ["suletta mercury"],
  ap: 3,
  hp: 3,
  abilities: [],
};

export const laucherStrikeGundamGATX105: GundamitoUnitCard = {
  id: "GD01-072",
  implemented: true,
  cost: 3,
  level: 4,
  number: 72,
  type: "unit",
  name: "Launcher Strike Gundam | GAT-X105+AQM/E-X03",
  color: "white",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space", "earth"],
  traits: ["earth alliance"],
  linkRequirement: ["earth alliance trait"],
  ap: 3,
  hp: 4,
  abilities: [],
};

export const michaelisCFK029: GundamitoUnitCard = {
  id: "GD01-076",
  implemented: true,
  cost: 2,
  level: 3,
  number: 76,
  type: "unit",
  name: "Michaelis | CFK-029",
  color: "white",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space", "earth"],
  traits: ["academy"],
  linkRequirement: ["academy trait"],
  ap: 3,
  hp: 3,
  abilities: [],
};

export const strikeDaggerGATX105: GundamitoUnitCard = {
  id: "GD01-077",
  implemented: true,
  cost: 2,
  level: 4,
  number: 77,
  type: "unit",
  name: "Strike Gundam | GAT-X105",
  color: "white",
  set: "GD01",
  rarity: "common",
  zones: ["space", "earth"],
  traits: ["earth alliance"],
  linkRequirement: ["kira yamato"],
  ap: 3,
  hp: 4,
  abilities: [],
};

export const lotoD50C: GundamitoUnitCard = {
  id: "GD01-011",
  implemented: true,
  cost: 2,
  level: 2,
  number: 11,
  type: "unit",
  name: "Loto | D-50C",
  color: "blue",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space", "earth"],
  traits: ["earth federation"],
  linkRequirement: ["earth federation trait"],
  ap: 2,
  hp: 2,
  abilities: [],
};

export const darilbaldeMD0064: GundamitoUnitCard = {
  id: "GD01-075",
  implemented: true,
  cost: 2,
  level: 3,
  number: 75,
  type: "unit",
  name: "Darilbalde | MD-0064",
  color: "white",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space", "earth"],
  traits: ["academy"],
  linkRequirement: ["academy trait"],
  ap: 4,
  hp: 2,
  abilities: [],
};

export const rickDomMS09R: GundamitoUnitCard = {
  id: "GD01-030",
  implemented: true,
  cost: 2,
  level: 3,
  number: 30,
  type: "unit",
  name: "Rick Dom | MS-09R",
  color: "green",
  set: "GD01",
  rarity: "uncommon",
  zones: ["space"],
  traits: ["zeon"],
  linkRequirement: [""],
  ap: 3,
  hp: 3,
  abilities: [],
};

export const gundamHeavyarmsXXXG01H: GundamitoUnitCard = {
  id: "GD01-034",
  implemented: true,
  cost: 2,
  level: 4,
  number: 34,
  type: "unit",
  name: "Gundam Heavyarms | XXXG-01H",
  color: "green",
  set: "GD01",
  rarity: "uncommon",
  zones: ["earth"],
  traits: ["operation meteor"],
  linkRequirement: ["trowa barton"],
  ap: 3,
  hp: 4,
  abilities: [],
};

export const shenlongGundamXXXG01S: GundamitoUnitCard = {
  id: "GD01-041",
  implemented: true,
  cost: 3,
  level: 4,
  number: 41,
  type: "unit",
  name: "Shenlong Gundam | XXXG-01S",
  color: "green",
  set: "GD01",
  rarity: "common",
  zones: ["earth"],
  traits: ["operation meteor"],
  linkRequirement: ["chang wufei"],
  ap: 4,
  hp: 3,
  abilities: [],
};
