// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuFallenLightsaber = {
  title: "Fallen Lightsaber",
  cost: 3,
  text: 'Attach to a non-Vehicle unit. \n\nIf attached unit is a Force unit, it gains: "On Attack: Deal 1 damage to each ground unit the defending player controls."',
  unique: false,
  upgradePower: 3,
  upgradeHp: 3,
  id: "0160548661",
  rarity: "rare",
  aspects: ["aggression", "villainy"],
  traits: ["item", "weapon", "lightsaber"],
  types: ["upgrade"],
  setId: {
    set: "SOR",
    number: 137,
  },
  setCodes: [
    {
      set: "SOR",
      number: 137,
    },
  ],
  internalName: "fallen-lightsaber",
  cardType: "upgrade",
  canonicalId: "fallen-lightsaber",
  slug: "fallen-lightsaber",
  name: "Fallen Lightsaber",
  printings: [
    {
      id: "SOR_137",
      artId: "240",
      setCode: "SOR",
      collectorNumber: "137",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_137_Fallen_Lightsaber_64ca62f967.png",
    },
    {
      id: "1289424150",
      artId: "240",
      setCode: "SOR",
      collectorNumber: "137",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131137en_Fallen_Lightsaber_Foil_ac60a301f1.png",
    },
    {
      id: "1262247627",
      artId: "240",
      setCode: "SOR",
      collectorNumber: "400",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132400en_Fallen_Lightsaber_HYP_Foil_4db12a50b1.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "Attach to a non-Vehicle unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuFallenLightsaber;
