// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuSmugglingCompartment = {
  title: "Smuggling Compartment",
  cost: 1,
  text: 'Attach to a VEHICLE unit.\n\nAttached unit gains: "On Attack: Ready a resource."',
  unique: false,
  upgradePower: 1,
  upgradeHp: 1,
  id: "7280213969",
  rarity: "uncommon",
  aspects: ["cunning"],
  traits: ["modification"],
  types: ["upgrade"],
  setId: {
    set: "SOR",
    number: 214,
  },
  setCodes: [
    {
      set: "SOR",
      number: 214,
    },
  ],
  internalName: "smuggling-compartment",
  cardType: "upgrade",
  canonicalId: "smuggling-compartment",
  slug: "smuggling-compartment",
  name: "Smuggling Compartment",
  printings: [
    {
      id: "SOR_214",
      artId: "378",
      setCode: "SOR",
      collectorNumber: "214",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_214_Smuggling_Compartment_af5217ef68.png",
    },
    {
      id: "9108483550",
      artId: "378",
      setCode: "SOR",
      collectorNumber: "214",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131214en_Smuggling_Compartment_Foil_d87af9ceb0.png",
    },
    {
      id: "2599797802",
      artId: "378",
      setCode: "SOR",
      collectorNumber: "476",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01_476_Smuggling_Compartment_HYP_f93727bfc8.png",
    },
    {
      id: "9077156033",
      artId: "378",
      setCode: "SOR",
      collectorNumber: "476",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132476en_Smuggling_Compartment_HYP_Foil_e38eb77bdf.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "Attach to a VEHICLE unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        traits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuSmugglingCompartment;
