// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuTraitorous = {
  title: "Traitorous",
  cost: 5,
  text: "When this upgrade becomes attached to a non‑leader unit that costs 3 or less: Take control of that unit.\n\nWhen this upgrade becomes unattached from a unit: That unit's owner takes control of it.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\n",
  upgradePower: 0,
  upgradeHp: 0,
  id: "8055390529",
  rarity: "rare",
  aspects: ["command"],
  traits: ["innate"],
  types: ["upgrade"],
  setId: {
    set: "SOR",
    number: 122,
  },
  setCodes: [
    {
      set: "SOR",
      number: 122,
    },
  ],
  internalName: "traitorous",
  cardType: "upgrade",
  canonicalId: "traitorous",
  slug: "traitorous",
  name: "Traitorous",
  printings: [
    {
      id: "SOR_122",
      artId: "948",
      setCode: "SOR",
      collectorNumber: "122",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_122_Traitorous_a95670f273.png",
    },
    {
      id: "4837971647",
      artId: "948",
      setCode: "SOR",
      collectorNumber: "122",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0131122en_Traitorous_Foil_e9e0b72d39.png",
    },
    {
      id: "2398178224",
      artId: "948",
      setCode: "SOR",
      collectorNumber: "386",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_386_Traitorous_HYP_81721e7f8f.png",
    },
    {
      id: "3049677806",
      artId: "948",
      setCode: "SOR",
      collectorNumber: "386",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0132386en_Traitorous_HYP_Foil_98f0e4ba8f.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When this upgrade becomes attached to a non-leader unit that costs 3 or less: Take control of that unit.",
      effects: [effect.takeControl(target.attachedUnit())],
    }),
  ],
} satisfies SwuUpgradeCard;

export default swuTraitorous;
