import type { PromoCardDefinition } from "@tcg/cyberpunk-types";

export const promoLucynaKushinada = {
  id: "3f2e5d58-dea3-4090-8fe7-0f5f4af2d333",
  externalId: "cyberpunk:lucyna-kushinada",
  slug: "lucyna-kushinada",
  name: "Lucyna Kushinada",
  subname: null,
  displayName: "Lucyna Kushinada",
  rulesText: null,
  flavorText: null,
  color: "blue",
  classifications: ["Overclocking"],
  set: {
    code: "promo",
    name: "Promo Cards",
  },
  printNumber: "N001",
  printings: [
    {
      id: "14dc2e38-a373-4b25-be12-e74b1f79e3b2",
      collectorNumber: "N001",
      imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/promo/n001.webp",
      sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/n001.webp",
      set: {
        code: "promo",
        name: "Promo Cards",
      },
      rarity: null,
      finish: "standard",
      artist: "Pandart Studio",
    },
  ],
  selectedPrintingId: "14dc2e38-a373-4b25-be12-e74b1f79e3b2",
  artist: "Pandart Studio",
  imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/promo/n001.webp",
  sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/n001.webp",
  rarity: null,
  legality: "legal",
  hasSellTag: false,
  ram: 2,
  timingTriggers: [],
  keywords: [],
  type: "legend",
  cost: null,
  power: 0,
  abilities: [],
  reminderText: [],
} satisfies PromoCardDefinition;
