import type { CardEffect, CommandCard } from "@tcg/gundam-types";

export const st01KaiSResolve013: CommandCard = {
  cardNumber: "ST01-013",
  name: "Kai's Resolve",
  type: "command",
  color: "blue",
  traits: ["earth federation", "white base team"],
  id: "ST01-013",
  externalId: "gundam:st01-013",
  slug: "kai-s-resolve-st01-013",
  displayName: "Kai's Resolve",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "ST01-013",
  printings: [
    {
      id: "ST01-013",
      collectorNumber: "ST01-013",
      cardNumber: "ST01-013",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-013.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-013.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "ST01-013_p1",
      collectorNumber: "ST01-013_p1",
      cardNumber: "ST01-013",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01] Bonus Pack",
        packageId: "616001",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-013_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-013_p1.webp?260424",
      productName: "Heroic Beginnings [ST01] Bonus Pack",
    },
    {
      id: "ST01-013_p2",
      collectorNumber: "ST01-013_p2",
      cardNumber: "ST01-013",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/beta/ST01-013_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-013_p2.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "ST01-013",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st01/ST01-013.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST01-013.webp?260424",
  legality: "legal",
  level: 3,
  cost: 1,
  pilotName: "Kai Shiden",
  apBonus: 1,
  hpBonus: 0,
  effect: "【Main】Choose 1 friendly Unit. It recovers 3 HP.<br>【Pilot】[Kai Shiden]<br>",
  effects: [
    {
      type: "command",
      activation: {
        timing: ["main"],
      },
      directives: [
        {
          action: {
            action: "recoverHP",
            amount: 3,
            target: {
              owner: "friendly",
              cardType: "unit",
              count: 1,
            },
          },
        },
      ],
      sourceText: "【Main】Choose 1 friendly Unit. It recovers 3 HP. 【Pilot】[Kai Shiden]",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "common",
};
