import type { ResourceCard } from "@tcg/gundam-types";

export const rpResource003: ResourceCard = {
  cardNumber: "RP-003",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "RP-003",
  canonicalId: "RP-003",
  externalIds: { bandai: "gundam:rp-003" },
  slug: "resource/rp-003",
  displayName: "Resource",
  set: { code: "RP", name: "Resource Pack", packageId: "616901" },
  printNumber: "RP-003",
  printings: [
    {
      id: "RP-003",
      artId: "RP-003",
      setCode: "RP",
      collectorNumber: "RP-003",
      cardNumber: "RP-003",
      set: {
        code: "RP",
        name: "Resource Pack",
        packageId: "616901",
      },
      rarity: "promo",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/rp/RP-003.webp",
      productName: "Resource Pack",
    },
  ],
  reprints: ["RP-003"],
  selectedPrintingId: "RP-003",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/rp/RP-003.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "promo",
};
