import type { ResourceCard } from "@tcg/gundam-types";

export const rpResource021: ResourceCard = {
  cardNumber: "RP-021",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "RP-021",
  canonicalId: "RP-021",
  externalIds: { bandai: "gundam:rp-021" },
  slug: "resource/rp-021",
  displayName: "Resource",
  set: { code: "RP", name: "Events", packageId: "616901" },
  printNumber: "RP-021",
  printings: [
    {
      id: "RP-021",
      artId: "RP-021",
      setCode: "RP",
      collectorNumber: "RP-021",
      cardNumber: "RP-021",
      set: {
        code: "RP",
        name: "Events",
        packageId: "616901",
      },
      rarity: "promo",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/rp/RP-021.webp",
      productName: "Events",
    },
  ],
  reprints: ["RP-021"],
  selectedPrintingId: "RP-021",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/rp/RP-021.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "promo",
};
