import type { ResourceCard } from "@tcg/gundam-types";

export const rpResource022: ResourceCard = {
  cardNumber: "RP-022",
  name: "Resource",
  type: "resource",
  traits: [],
  id: "RP-022",
  externalId: "gundam:rp-022",
  slug: "resource-rp-022",
  displayName: "Resource",
  set: { code: "RP", name: "Events", packageId: "616901" },
  printNumber: "RP-022",
  printings: [
    {
      id: "RP-022",
      collectorNumber: "RP-022",
      cardNumber: "RP-022",
      set: {
        code: "RP",
        name: "Events",
        packageId: "616901",
      },
      rarity: "promo",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/rp/RP-022.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/RP-022.webp?260424",
      productName: "Events",
    },
  ],
  selectedPrintingId: "RP-022",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/rp/RP-022.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/RP-022.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  effect: "(Rest a Resource when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "promo",
};
