export const FIXTURE_BOARD_CARD_DEFINITIONS = {
  "fixture-victor-goldmane": {
    canonicalId: "fixture-victor-goldmane",
    name: "Victor Goldmane, High and Mighty",
    types: ["Guardian", "Hero"],
    health: 40,
    intelligence: 4,
  },
  "fixture-titans-fist": {
    canonicalId: "fixture-titans-fist",
    name: "Titan's Fist",
    types: ["Guardian", "Weapon", "Hammer", "1H"],
    power: 3,
  },
  "fixture-aurum-aegis": {
    canonicalId: "fixture-aurum-aegis",
    name: "Aurum Aegis",
    types: ["Guardian", "Equipment", "Off-Hand"],
    defense: 2,
  },
  "fixture-tectonic-plating": {
    canonicalId: "fixture-tectonic-plating",
    name: "Tectonic Plating",
    types: ["Guardian", "Equipment", "Chest"],
    defense: 2,
  },
  "fixture-crater-fist": {
    canonicalId: "fixture-crater-fist",
    name: "Crater Fist",
    types: ["Guardian", "Equipment", "Arms"],
    defense: 1,
  },
  "fixture-craterhoof": {
    canonicalId: "fixture-craterhoof",
    name: "Craterhoof",
    types: ["Guardian", "Equipment", "Legs"],
    defense: 1,
  },
  "fixture-azalea-ace-in-the-hole": {
    canonicalId: "fixture-azalea-ace-in-the-hole",
    name: "Azalea, Ace in the Hole",
    types: ["Ranger", "Hero"],
    health: 40,
    intelligence: 4,
  },
  "fixture-death-dealer": {
    canonicalId: "fixture-death-dealer",
    name: "Death Dealer",
    types: ["Ranger", "Weapon", "Bow", "2H"],
  },
  "fixture-new-horizon": {
    canonicalId: "fixture-new-horizon",
    name: "New Horizon",
    types: ["Ranger", "Equipment", "Head"],
    defense: 2,
    unparsedSegments: [
      "If you have a face up card in your arsenal, you have an additional arsenal zone.",
      "When this is destroyed, destroy all cards in your arsenal.",
      "Blade Break",
    ],
  },
  "fixture-trench-of-sunken-treasure": {
    canonicalId: "fixture-trench-of-sunken-treasure",
    name: "Trench of Sunken Treasure",
    types: ["Ranger", "Equipment", "Chest"],
    defense: 1,
  },
  "fixture-bulls-eye-bracers": {
    canonicalId: "fixture-bulls-eye-bracers",
    name: "Bull's Eye Bracers",
    types: ["Ranger", "Equipment", "Arms"],
  },
  "fixture-perch-grapplers": {
    canonicalId: "fixture-perch-grapplers",
    name: "Perch Grapplers",
    types: ["Ranger", "Equipment", "Legs"],
    defense: 1,
  },
  "fixture-red-in-the-ledger": {
    canonicalId: "fixture-red-in-the-ledger",
    name: "Red in the Ledger",
    types: ["Ranger", "Action", "Attack", "Arrow"],
    pitch: 1,
    cost: 0,
    power: 4,
    defense: 3,
  },
  "fixture-searing-shot": {
    canonicalId: "fixture-searing-shot",
    name: "Searing Shot",
    types: ["Ranger", "Action", "Attack", "Arrow"],
    pitch: 1,
    cost: 0,
    power: 4,
    defense: 3,
  },
} as const;
