import type { ResourceCard } from "@tcg/gundam-types";

export const exrExResource001: ResourceCard = {
  cardNumber: "EXR-001",
  name: "EX Resource",
  type: "resource",
  traits: [],
  id: "EXR-001_p6",
  canonicalId: "EXR-001",
  externalIds: { bandai: "gundam:exr-001_p6" },
  slug: "ex-resource-exr-001-p6",
  displayName: "EX Resource",
  set: { code: "EXR", name: "Included in Booster Packs", packageId: "616801" },
  printNumber: "EXR-001_p6",
  printings: [
    {
      id: "EXR-001_p5",
      artId: "EXR-001_p5",
      setCode: "BETA",
      collectorNumber: "EXR-001_p5",
      cardNumber: "EXR-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exr/EXR-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p5.webp?260715",
      productName: "Edition Beta",
    },
    {
      id: "EXR-001_p6",
      artId: "EXR-001_p6",
      setCode: "EXR",
      collectorNumber: "EXR-001_p6",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Included in Booster Packs",
        packageId: "616801",
      },
      rarity: "common",
      // Standard finish: the booster-pack art is the free default EX
      // Resource token art (platform setup-slot default). The BETA (_p5)
      // and SC01 (_p7) printings stay parallel (ownable alt-art).
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exr/EXR-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p6.webp?260715",
      productName: "Included in Booster Packs",
    },
    {
      id: "EXR-001_p7",
      artId: "EXR-001_p7",
      setCode: "SC01",
      collectorNumber: "EXR-001_p7",
      cardNumber: "EXR-001",
      set: {
        code: "SC01",
        name: "Deck Build Box Freedom Ascension [SC01]",
        packageId: "616301",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/exr/EXR-001_p7.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p7.webp?260715",
      productName: "Deck Build Box Freedom Ascension [SC01]",
    },
  ],
  reprints: ["EXR-001_p5", "EXR-001_p6", "EXR-001_p7"],
  selectedPrintingId: "EXR-001_p6",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/exr/EXR-001_p6.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p6.webp?260715",
  legality: "legal",
  level: 0,
  cost: 0,
  effect:
    "(At the start of the game, the second-turn player places 1 active EX Resource into their resource area.)\n(Rest an EX Resource then exile it from the game when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
