import type { ResourceCard } from "@tcg/gundam-types";

export const exrExResource001: ResourceCard = {
  cardNumber: "EXR-001",
  name: "EX Resource",
  type: "resource",
  traits: [],
  id: "EXR-001",
  externalId: "gundam:exr-001",
  slug: "ex-resource-exr-001",
  displayName: "EX Resource",
  set: { code: "EXR", name: "Basic Cards" },
  printNumber: "EXR-001",
  printings: [
    {
      id: "EXR-001",
      collectorNumber: "EXR-001",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXR-001_p1",
      collectorNumber: "EXR-001_p1",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p1.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p1.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXR-001_p2",
      collectorNumber: "EXR-001_p2",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p2.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p2.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXR-001_p3",
      collectorNumber: "EXR-001_p3",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p3.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p3.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXR-001_p4",
      collectorNumber: "EXR-001_p4",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Basic Cards",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p4.webp",
      sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p4.webp",
      productName: "Basic Cards",
    },
    {
      id: "EXR-001_p5",
      collectorNumber: "EXR-001_p5",
      cardNumber: "EXR-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p5.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p5.webp?260424",
      productName: "Edition Beta",
    },
    {
      id: "EXR-001_p6",
      collectorNumber: "EXR-001_p6",
      cardNumber: "EXR-001",
      set: {
        code: "EXR",
        name: "Included in Booster Packs",
        packageId: "616801",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001_p6.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/EXR-001_p6.webp?260424",
      productName: "Included in Booster Packs",
    },
  ],
  selectedPrintingId: "EXR-001",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001.webp",
  sourceImageUrl: "https://r2.tcg.online/public/gundam/cards/exr/EXR-001.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  effect:
    "(At the start of the game, the second-turn player places 1 active EX Resource into their resource area.)\n(Rest an EX Resource then remove it from the game when paying a cost.)",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
