import type { LorcanaCardDefinition } from "~/game-engine/engines/lorcana/src/cards/lorcana-card-repository";
import {
  allFunnedOut,
  blastFromYourPast,
  breakFree,
  dontLetTheFrostbiteBite,
  duckForCover,
  everAsBefore,
  evilComesPrepared,
  findersKeepers,
  foodFight,
  gatheringKnowledgeAndWisdom,
  glimmerVsGlimmer,
  healingTouch,
  hideAway,
  hypnoticDeduction,
  hypnoticStrength,
  invitedToTheBallAction,
  magicalAid,
  nightHowlerRage,
  rememberWhoYouAre,
  revive,
  royalTantrum,
  tryEverything,
  tugofwar,
  visionOfTheFuture,
  weKnowTheWay,
  whenWillMyLifeBegin,
  whosWithMe,
  youreWelcome,
} from "./actions";

export const allSSKCards: LorcanaCardDefinition[] = [
  allFunnedOut,
  blastFromYourPast,
  breakFree,
  dontLetTheFrostbiteBite,
  duckForCover,
  everAsBefore,
  evilComesPrepared,
  findersKeepers,
  foodFight,
  gatheringKnowledgeAndWisdom,
  glimmerVsGlimmer,
  healingTouch,
  hideAway,
  hypnoticDeduction,
  hypnoticStrength,
  invitedToTheBallAction,
  magicalAid,
  nightHowlerRage,
  rememberWhoYouAre,
  revive,
  royalTantrum,
  tryEverything,
  tugofwar,
  visionOfTheFuture,
  weKnowTheWay,
  whenWillMyLifeBegin,
  whosWithMe,
  youreWelcome,
];

export const allSSKCardsById: Record<string, LorcanaCardDefinition> = {};
for (const card of allSSKCards) {
  allSSKCardsById[card.id] = card;
}
