// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuCorruptedSaber = {
  title: "Corrupted Saber",
  cost: 2,
  text: "Attach to a non-Vehicle unit.\nIf attached unit is a Force unit, it gains: “On Attack: The defender gets –2/–0 for this attack.”",
  unique: false,
  upgradePower: 2,
  upgradeHp: 1,
  id: "8085392838",
  rarity: "common",
  aspects: ["cunning", "villainy"],
  traits: ["item", "weapon", "lightsaber"],
  types: ["upgrade"],
  setId: {
    set: "LOF",
    number: 187,
  },
  setCodes: [
    {
      set: "LOF",
      number: 187,
    },
  ],
  internalName: "corrupted-saber",
  cardType: "upgrade",
  canonicalId: "corrupted-saber",
  slug: "corrupted-saber",
  name: "Corrupted Saber",
  printings: [
    {
      id: "LOF_187",
      artId: "27959",
      setCode: "LOF",
      collectorNumber: "187",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05010187_EN_Corrupted_Saber_e88fd8ea69.png",
    },
    {
      id: "0505326661",
      artId: "27959",
      setCode: "LOF",
      collectorNumber: "451",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05020451_EN_Corrupted_Saber_8d06bd6d5f.png",
    },
    {
      id: "7857262896",
      artId: "27959",
      setCode: "LOF",
      collectorNumber: "689",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05310689_EN_Corrupted_Saber_96aa6b45c7.png",
    },
    {
      id: "6048829525",
      artId: "27959",
      setCode: "LOF",
      collectorNumber: "927",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//05320927_EN_Corrupted_Saber_042803b5f0.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "Attach to a non-Vehicle unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuCorruptedSaber;
