// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuDarthMaulsLightsaber = {
  title: "Darth Maul's Lightsaber",
  cost: 3,
  text: "Attach to a friendly non-Vehicle unit.\nWhen Played: If attached unit is Darth Maul, you may attack with him. For this attack, he gains Overwhelm and can't attack bases.",
  unique: true,
  rules:
    'If the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\nShields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nThe attached unit must be named exactly "Darth Maul" in order to benefit from the "When Played" ability.\nUnits must be ready in order to attack.\nUnits that can’t attack bases can still damage bases through other abilities, like Overwhelm.\n',
  upgradePower: 4,
  upgradeHp: 2,
  id: "2167393423",
  rarity: "special",
  aspects: ["aggression", "villainy"],
  traits: ["item", "weapon", "lightsaber"],
  keywords: ["overwhelm"],
  types: ["upgrade"],
  setId: {
    set: "LOF",
    number: 140,
  },
  setCodes: [
    {
      set: "LOF",
      number: 140,
    },
  ],
  internalName: "darth-mauls-lightsaber",
  cardType: "upgrade",
  canonicalId: "darth-mauls-lightsaber",
  slug: "darth-mauls-lightsaber",
  name: "Darth Maul's Lightsaber",
  printings: [
    {
      id: "LOF_140",
      artId: "27724",
      setCode: "LOF",
      collectorNumber: "140",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05010140_EN_Darth_Maul_s_Lightsaber_da55e52459.png",
    },
    {
      id: "8578657207",
      artId: "27724",
      setCode: "LOF",
      collectorNumber: "404",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05020404_EN_Darth_Maul_s_Lightsaber_eab7c0f064.png",
    },
    {
      id: "6659669510",
      artId: "27724",
      setCode: "LOF",
      collectorNumber: "642",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05310642_EN_Darth_Maul_s_Lightsaber_c1dcc0ac40.png",
    },
    {
      id: "2646357987",
      artId: "27724",
      setCode: "LOF",
      collectorNumber: "880",
      rarity: "special",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05320880_EN_Darth_Maul_s_Lightsaber_cd4495e2a5.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
    {
      kind: "constant",
      text: "Attach to a friendly non-Vehicle unit.",
      target: {
        type: "card",
        controller: "friendly",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuDarthMaulsLightsaber;
