// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuInquisitorsLightsaber = {
  title: "Inquisitor's Lightsaber",
  cost: 2,
  text: "Attach to a non-Vehicle unit.\nAttached unit gains: “While attacking a Force unit, this unit gets +2/+0.”",
  unique: false,
  upgradePower: 1,
  upgradeHp: 3,
  id: "3895004077",
  rarity: "common",
  aspects: ["command", "villainy"],
  traits: ["item", "weapon", "lightsaber"],
  types: ["upgrade"],
  setId: {
    set: "LOF",
    number: 90,
  },
  setCodes: [
    {
      set: "LOF",
      number: 90,
    },
  ],
  internalName: "inquisitors-lightsaber",
  cardType: "upgrade",
  canonicalId: "inquisitors-lightsaber",
  slug: "inquisitors-lightsaber",
  name: "Inquisitor's Lightsaber",
  printings: [
    {
      id: "LOF_090",
      artId: "27474",
      setCode: "LOF",
      collectorNumber: "90",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05010090_EN_Inquisitor_s_Lightsaber_9434ca176f.png",
    },
    {
      id: "2791116926",
      artId: "27474",
      setCode: "LOF",
      collectorNumber: "354",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05020354_EN_Inquisitor_s_Lightsaber_1c4318bab6.png",
    },
    {
      id: "4041818958",
      artId: "27474",
      setCode: "LOF",
      collectorNumber: "592",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05310592_EN_Inquisitor_s_Lightsaber_cdb12db5c8.png",
    },
    {
      id: "4043344663",
      artId: "27474",
      setCode: "LOF",
      collectorNumber: "830",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05320830_EN_Inquisitor_s_Lightsaber_d52d3157fd.png",
    },
  ],
  abilities: [
    {
      kind: "constant",
      text: "Attach to a non-Vehicle unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuInquisitorsLightsaber;
