// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuJediTrials = {
  title: "Jedi Trials",
  cost: 1,
  text: "Attach to a Force unit.\nAttached unit gains: “On Attack: Give an Experience token to this unit.”\nWhile attached unit has 4 or more upgrades on it, it gains the Jedi trait.",
  unique: false,
  upgradePower: 0,
  upgradeHp: 0,
  id: "0545149763",
  rarity: "rare",
  aspects: ["vigilance", "heroism"],
  traits: ["jedi", "learned"],
  types: ["upgrade"],
  setId: {
    set: "LOF",
    number: 52,
  },
  setCodes: [
    {
      set: "LOF",
      number: 52,
    },
  ],
  internalName: "jedi-trials",
  cardType: "upgrade",
  abilities: [
    {
      kind: "constant",
      text: "Attach to a Force unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        traits: ["Force"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuJediTrials;
