// Generated by tools/import-card-data. Do not edit manually.
import type { SwuLeaderCard } from "@tcg/star-wars-unlimited-types";

export const swuYodaSensingDarkness = {
  title: "Yoda",
  subtitle: "Sensing Darkness",
  cost: 7,
  hp: 9,
  power: 4,
  text: "Action [Exhaust]: If a unit left play this phase, draw a card, then put a card from your hand on the top or bottom of your deck.",
  deployBox:
    "Restore 2\nWhen Deployed: You may discard a card from your deck. If you do, defeat an enemy non-leader unit that costs the same as or less than the discarded card.",
  epicAction: "Epic Action: If you control 7 or more resources, deploy this leader.",
  unique: true,
  rules:
    "Abilities that refer to a card's cost always refer to its printed cost, regardless of modifiers.\nYoda's leader ability still can be used as an action even if no unit left play this phase (but you don't resolve any of the listed effects).\nAlways discard from the top of a deck, unless an ability specifies otherwise.\n",
  id: "2847868671",
  rarity: "rare",
  aspects: ["vigilance", "heroism"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  keywords: ["restore"],
  types: ["leader"],
  setId: {
    set: "TWI",
    number: 4,
  },
  setCodes: [
    {
      set: "TWI",
      number: 4,
    },
  ],
  internalName: "yoda#sensing-darkness",
  cardType: "leader",
  canonicalId: "yoda#sensing-darkness",
  slug: "yoda-sensing-darkness",
  name: "Yoda",
  printings: [
    {
      id: "TWI_004",
      artId: "14231",
      setCode: "TWI",
      collectorNumber: "4",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301004_EN_Yoda_Leader_4e14297628.png",
    },
    {
      id: "0799652080",
      artId: "14231",
      setCode: "TWI",
      collectorNumber: "261",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0303261_EN_Yoda_Leader_6396bde2e6.png",
    },
    {
      id: "5543794830",
      artId: "14231",
      setCode: "TWI",
      collectorNumber: "279",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302279_EN_Yoda_Leader_a3ce11d58c.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Restore",
      keyword: "restore",
    },
    {
      kind: "action",
      text: "Epic Action: If you control 7 or more resources, deploy this leader.",
      trigger: {
        event: "epicAction",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "self",
          },
          to: "groundArena",
        },
      ],
    },
  ],
} satisfies SwuLeaderCard;

export default swuYodaSensingDarkness;
