// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuCommand = {
  title: "Command",
  cost: 4,
  text: "Choose two, in any order:\n\nGive 2 Experience tokens to a unit.\nA friendly unit deals damage equal to its power to a non-unique enemy unit.\nPut this event into play as a resource.\nReturn a unit from your discard pile to your hand.",
  unique: false,
  rules: "A card put into play as a resource enters play exhausted.\n",
  id: "0073206444",
  rarity: "legendary",
  aspects: ["command", "command"],
  traits: ["innate"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 107,
  },
  setCodes: [
    {
      set: "SOR",
      number: 107,
    },
  ],
  internalName: "command",
  cardType: "event",
  canonicalId: "command",
  slug: "command",
  name: "Command",
  printings: [
    {
      id: "SOR_107",
      artId: "215",
      setCode: "SOR",
      collectorNumber: "107",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_107_Command_122a2a1778.png",
    },
    {
      id: "4601267627",
      artId: "215",
      setCode: "SOR",
      collectorNumber: "107",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0131107en_Command_Foil_d317436327.png",
    },
    {
      id: "2333682124",
      artId: "215",
      setCode: "SOR",
      collectorNumber: "371",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0132371en_Command_HYP_Foil_57390bbaf9.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Give 2 Experience tokens to a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "distribute",
          mode: "experience",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
    {
      kind: "triggered",
      text: "Put this event into play as a resource.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "resource",
          target: {
            type: "self",
          },
          ready: false,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuCommand;
