// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuForACauseIBelieveIn = {
  title: "For a Cause I Believe In",
  cost: 3,
  text: "Reveal the top 4 cards of your deck. For each [Heroism] card revealed this way, deal 1 damage to an enemy base. You may discard any of the revealed cards and put the rest back on top of your deck in any order.",
  unique: false,
  id: "5767546527",
  rarity: "rare",
  aspects: ["aggression", "heroism"],
  traits: ["innate"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 152,
  },
  setCodes: [
    {
      set: "SOR",
      number: 152,
    },
  ],
  internalName: "for-a-cause-i-believe-in",
  cardType: "event",
  canonicalId: "for-a-cause-i-believe-in",
  slug: "for-a-cause-i-believe-in",
  name: "For a Cause I Believe In",
  printings: [
    {
      id: "SOR_152",
      artId: "408",
      setCode: "SOR",
      collectorNumber: "152",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com/SWH_01_152_For_A_Cause_I_Believe_In_f234f48322.png",
    },
    {
      id: "7666398323",
      artId: "408",
      setCode: "SOR",
      collectorNumber: "152",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131152en_For_A_Cause_I_Believe_In_Foil_56b3405f57.png",
    },
    {
      id: "0394046085",
      artId: "408",
      setCode: "SOR",
      collectorNumber: "415",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01_415_For_A_Cause_I_Believe_In_HYP_1d9b65c87c.png",
    },
    {
      id: "5013056643",
      artId: "408",
      setCode: "SOR",
      collectorNumber: "415",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132415en_For_A_Cause_I_Believe_In_HYP_Foil_f9928f5893.png",
    },
  ],
  abilities: [
    ability.action({
      text: "Reveal the top 4 cards of your deck. For each [Heroism] card revealed this way, deal 1 damage to an enemy base. You may discard any of the revealed cards and put the rest back on top of your deck in any order.",
      effects: [
        effect.reveal(target.card({ controller: "friendly", zones: ["deck"], limit: 4 })),
        effect.damage(target.base("opponent"), 1),
        effect.reorder(
          target.card({ controller: "friendly", zones: ["deck"], limit: 4 }),
          "topOfDeck",
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuForACauseIBelieveIn;
