// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuOpenFire = {
  title: "Open Fire",
  cost: 3,
  text: "Deal 4 damage to a unit.",
  unique: false,
  id: "8148673131",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 172,
  },
  setCodes: [
    {
      set: "SOR",
      number: 172,
    },
    {
      set: "TWI",
      number: 174,
    },
  ],
  internalName: "open-fire",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Deal 4 damage to a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "damage",
          amount: 4,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuOpenFire;
