// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuOverwhelmingBarrage = {
  title: "Overwhelming Barrage",
  cost: 5,
  text: "Give a friendly unit +2/+2 for this phase. Then, it deals damage equal to its power divided as you choose among any number of other units.",
  unique: false,
  rules:
    "You can choose to assign more damage to a unit than it has remaining HP.\nAll damage dealt by a single ability is dealt simultaneously.\n",
  id: "1900571801",
  rarity: "uncommon",
  aspects: ["command", "villainy"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 92,
  },
  setCodes: [
    {
      set: "SOR",
      number: 92,
    },
  ],
  internalName: "overwhelming-barrage",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Give a friendly unit +2/+2 for this phase. Then, it deals damage equal to its power divided as you choose among any number of other units.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          power: 2,
          hp: 2,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuOverwhelmingBarrage;
