// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuRallyingCry = {
  title: "Rallying Cry",
  cost: 3,
  text: "Each friendly unit gains Raid 2 this phase. (They get +2/+0 while attacking.)",
  unique: false,
  id: "1208707254",
  rarity: "uncommon",
  aspects: ["aggression", "aggression"],
  traits: ["tactic"],
  keywords: ["raid"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 154,
  },
  setCodes: [
    {
      set: "SOR",
      number: 154,
    },
  ],
  internalName: "rallying-cry",
  cardType: "event",
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "triggered",
      text: "Each friendly unit gains Raid 2 this phase. (They get +2/+0 while attacking.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "gainKeyword",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
          keyword: "raid",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuRallyingCry;
