// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuRallyingCry = {
  title: "Rallying Cry",
  cost: 3,
  text: "Each friendly unit gains Raid 2 this phase. (They get +2/+0 while attacking.)",
  unique: false,
  id: "1208707254",
  rarity: "uncommon",
  aspects: ["aggression", "aggression"],
  traits: ["tactic"],
  keywords: ["raid"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 154,
  },
  setCodes: [
    {
      set: "SOR",
      number: 154,
    },
  ],
  internalName: "rallying-cry",
  cardType: "event",
  canonicalId: "rallying-cry",
  slug: "rallying-cry",
  name: "Rallying Cry",
  printings: [
    {
      id: "SOR_154",
      artId: "1232",
      setCode: "SOR",
      collectorNumber: "154",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_154_Rallying_Cry_7d8a1c2db5.png",
    },
    {
      id: "2486910828",
      artId: "1232",
      setCode: "SOR",
      collectorNumber: "154",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0131154en_Rallying_Cry_Foil_ff67c0088d.png",
    },
    {
      id: "1309174148",
      artId: "1232",
      setCode: "SOR",
      collectorNumber: "417",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//0132417en_Rallying_Cry_HYP_Foil_5459f8113f.png",
    },
    {
      id: "8578453935",
      artId: "1232",
      setCode: "SOR",
      collectorNumber: "417",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_01_417_Rallying_Cry_HYP_b8a5c158b7.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "triggered",
      text: "Each friendly unit gains Raid 2 this phase. (They get +2/+0 while attacking.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "gainKeyword",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
          keyword: "raid",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuRallyingCry;
