// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuSearchYourFeelings = {
  title: "Search Your Feelings",
  cost: 4,
  text: "Search your deck for a card and draw it. (Then, shuffle your deck.)",
  unique: false,
  rules: "After searching your deck, shuffle it.\n",
  id: "7485151088",
  rarity: "rare",
  aspects: ["villainy", "vigilance"],
  traits: ["innate"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 42,
  },
  setCodes: [
    {
      set: "SOR",
      number: 42,
    },
  ],
  internalName: "search-your-feelings",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Search your deck for a card and draw it. (Then, shuffle your deck.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "search",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          destination: "hand",
          reveal: true,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuSearchYourFeelings;
