// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuTheForceIsWithMe = {
  title: "The Force Is With Me",
  cost: 4,
  text: "Choose a friendly unit and give 2 Experience tokens to it. If you control a FORCE unit, also give a Shield token to the chosen unit. You may attack with the chosen unit.",
  unique: false,
  rules: "Units must be ready in order to attack.\n",
  id: "7861932582",
  rarity: "uncommon",
  aspects: ["vigilance", "heroism"],
  traits: ["force"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 55,
  },
  setCodes: [
    {
      set: "SOR",
      number: 55,
    },
  ],
  internalName: "the-force-is-with-me",
  cardType: "event",
  canonicalId: "the-force-is-with-me",
  slug: "the-force-is-with-me",
  name: "The Force Is With Me",
  printings: [
    {
      id: "SOR_055",
      artId: "1260",
      setCode: "SOR",
      collectorNumber: "55",
      rarity: "uncommon",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_055_The_Force_Is_With_Me_bde94ded40.png",
    },
    {
      id: "9279827313",
      artId: "1260",
      setCode: "SOR",
      collectorNumber: "55",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0131055en_The_Force_Is_With_Me_Foil_1788d5a1ee.png",
    },
    {
      id: "1032732321",
      artId: "1260",
      setCode: "SOR",
      collectorNumber: "320",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//SWH_01_320_The_Force_Is_With_Me_HYP_13fb487f6d.png",
    },
    {
      id: "3937915154",
      artId: "1260",
      setCode: "SOR",
      collectorNumber: "320",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0132320en_The_Force_Is_With_Me_HYP_Foil_d0731c5798.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Choose a friendly unit and give 2 Experience tokens to it. If you control a FORCE unit, also give a Shield token to the chosen unit. You may attack with the chosen unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "sequential",
          effects: [
            {
              type: "distribute",
              mode: "experience",
              amount: 2,
              target: {
                type: "card",
                controller: "friendly",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                limit: 1,
              },
            },
            {
              type: "conditional",
              condition: {
                type: "controlsTrait",
                controller: "friendly",
                trait: "force",
              },
              ifTrue: [
                {
                  type: "createToken",
                  token: "shield",
                  amount: 1,
                  target: {
                    type: "card",
                    controller: "friendly",
                    zones: ["groundArena", "spaceArena"],
                    cardTypes: ["unit", "token"],
                    limit: 1,
                  },
                },
              ],
            },
            {
              type: "optional",
              effects: [
                {
                  type: "attack",
                  attacker: {
                    type: "card",
                    controller: "friendly",
                    zones: ["groundArena", "spaceArena"],
                    cardTypes: ["unit", "token"],
                    limit: 1,
                  },
                  defender: {
                    type: "base",
                    controller: "opponent",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuTheForceIsWithMe;
