// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuWaylay = {
  title: "Waylay",
  cost: 3,
  text: "Return a non-leader unit to its owner's hand.",
  unique: false,
  rules:
    "Abilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "7202133736",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 222,
  },
  setCodes: [
    {
      set: "SOR",
      number: 222,
    },
    {
      set: "TWI",
      number: 226,
    },
  ],
  internalName: "waylay",
  cardType: "event",
  canonicalId: "waylay",
  slug: "waylay",
  name: "Waylay",
  printings: [
    {
      id: "SOR_222",
      artId: "272",
      setCode: "SOR",
      collectorNumber: "222",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_222_Waylay_cccabd353c.png",
    },
    {
      id: "TWI_226",
      artId: "272",
      setCode: "TWI",
      collectorNumber: "226",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com/SWH_01_222_Waylay_cccabd353c.png",
    },
    {
      id: "1576585935",
      artId: "272",
      setCode: "SOR",
      collectorNumber: "222",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0131222en_Waylay_Foil_13572decf4.png",
    },
    {
      id: "1974392350",
      artId: "272",
      setCode: "SOR",
      collectorNumber: "484",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0132484en_Waylay_HYP_Foil_c5e1adf624.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Return a non-leader unit to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          to: "hand",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuWaylay;
