// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuYoureMyOnlyHope = {
  title: "You're My Only Hope",
  cost: 3,
  text: "Look at the top card of your deck. You may play it. It costs [5 resources] less. If your base has 5 or less remaining HP, you may play it for free instead.",
  unique: false,
  rules:
    "“Play for free” ignores all resource costs, including the aspect penalty, but not other additional costs.\n",
  id: "3509161777",
  rarity: "rare",
  aspects: ["heroism"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "SOR",
    number: 246,
  },
  setCodes: [
    {
      set: "SOR",
      number: 246,
    },
  ],
  internalName: "youre-my-only-hope",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Look at the top card of your deck. You may play it. It costs [5 resources] less. If your base has 5 or less remaining HP, you may play it for free instead.",
      optional: true,
      effects: [
        effect.lookAt(target.card({ controller: "friendly", zones: ["deck"], limit: 1 })),
        effect.play(target.card({ controller: "friendly", zones: ["deck"], limit: 1 }), true),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuYoureMyOnlyHope;
