// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuNevarroCity = {
  title: "Nevarro City",
  hp: 30,
  unique: false,
  id: "5662039114",
  rarity: "common",
  aspects: ["command"],
  types: ["base"],
  setId: {
    set: "SHD",
    number: 22,
  },
  setCodes: [
    {
      set: "SHD",
      number: 22,
    },
  ],
  internalName: "nevarro-city",
  cardType: "base",
  canonicalId: "nevarro-city",
  slug: "nevarro-city",
  name: "Nevarro City",
  printings: [
    {
      id: "SHD_022",
      artId: "5451",
      setCode: "SHD",
      collectorNumber: "22",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0201022_EN_Nevarro_City_Base_f2d3666e68.png",
    },
    {
      id: "3795981604",
      artId: "5451",
      setCode: "SHD",
      collectorNumber: "300",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202300_EN_Nevarro_City_Base_a19fa2b1b3.png",
    },
  ],
} satisfies SwuBaseCard;

export default swuNevarroCity;
