// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuStarlightTemple = {
  title: "Starlight Temple",
  hp: 28,
  text: "When a friendly Force unit attacks: The Force is with you (create your Force token).",
  unique: false,
  id: "2945340801",
  rarity: "common",
  aspects: ["command"],
  types: ["base"],
  setId: {
    set: "LOF",
    number: 24,
  },
  setCodes: [
    {
      set: "LOF",
      number: 24,
    },
  ],
  internalName: "starlight-temple",
  cardType: "base",
  abilities: [
    {
      kind: "triggered",
      text: "When a friendly Force unit attacks: The Force is with you (create your Force token).",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "createToken",
          token: "force",
          amount: 1,
        },
      ],
      conditions: [
        {
          type: "hasTarget",
          target: {
            type: "choice",
            id: "attacker",
            controller: "friendly",
            traits: ["Force"],
          },
        },
      ],
    },
  ],
} satisfies SwuBaseCard;

export default swuStarlightTemple;
