import type { UnitCard } from "@tcg/gundam-types";

export const gd05StrikeRougeOotori005: UnitCard = {
  cardNumber: "GD05-005",
  name: "Strike Rouge (Ootori)",
  type: "unit",
  color: "blue",
  traits: ["orb"],
  id: "GD05-005",
  canonicalId: "GD05-005",
  externalIds: { bandai: "gundam:gd05-005" },
  slug: "strike-rouge-ootori-gd05-005",
  displayName: "Strike Rouge (Ootori)",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-005",
  printings: [
    {
      id: "GD05-005",
      artId: "GD05-005",
      setCode: "GD05",
      collectorNumber: "GD05-005",
      cardNumber: "GD05-005",
      set: {
        code: "GD05",
        name: "Freedom Ascension [GD05]",
        packageId: "616105",
      },
      rarity: "rare",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD05-005.webp?260715",
      productName: "Freedom Ascension [GD05]",
    },
    {
      id: "GD05-005_p1",
      artId: "GD05-005_p1",
      setCode: "GD05",
      collectorNumber: "GD05-005_p1",
      cardNumber: "GD05-005",
      set: {
        code: "GD05",
        name: "Freedom Ascension [GD05]",
        packageId: "616105",
      },
      rarity: "rare",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD05-005_p1.webp?260715",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  reprints: ["GD05-005", "GD05-005_p1"],
  selectedPrintingId: "GD05-005",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD05-005.webp?260715",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam SEED Destiny",
  level: 4,
  cost: 3,
  ap: 3,
  hp: 4,
  linkCondition: "(Orb) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "rare",
};
