import type { UnitCard } from "@tcg/gundam-types";

export const gd05GunBlaster009: UnitCard = {
  cardNumber: "GD05-009",
  name: "Gun Blaster",
  type: "unit",
  color: "blue",
  traits: ["league militaire"],
  id: "GD05-009",
  canonicalId: "GD05-009",
  externalIds: { bandai: "gundam:gd05-009" },
  slug: "gun-blaster-gd05-009",
  displayName: "Gun Blaster",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-009",
  printings: [
    {
      id: "GD05-009",
      artId: "GD05-009",
      setCode: "GD05",
      collectorNumber: "GD05-009",
      cardNumber: "GD05-009",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-009.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-009",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-009.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit V Gundam",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "(League Militaire) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
