import type { UnitCard } from "@tcg/gundam-types";

export const gd05KiraSStrikeRouge010: UnitCard = {
  cardNumber: "GD05-010",
  name: "Kira's Strike Rouge",
  type: "unit",
  color: "blue",
  traits: ["orb"],
  id: "GD05-010",
  canonicalId: "GD05-010",
  externalIds: { bandai: "gundam:gd05-010" },
  slug: "kira-s-strike-rouge-gd05-010",
  displayName: "Kira's Strike Rouge",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-010",
  printings: [
    {
      id: "GD05-010",
      artId: "GD05-010",
      setCode: "GD05",
      collectorNumber: "GD05-010",
      cardNumber: "GD05-010",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-010.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-010",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-010.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam SEED Destiny",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "(Orb) Trait / [Kira Yamato]",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
