import type { UnitCard } from "@tcg/gundam-types";

export const gd05GunEz013: UnitCard = {
  cardNumber: "GD05-013",
  name: "Gun EZ",
  type: "unit",
  color: "blue",
  traits: ["league militaire", "shrike team"],
  id: "GD05-013",
  canonicalId: "GD05-013",
  externalIds: { bandai: "gundam:gd05-013" },
  slug: "gun-ez-gd05-013",
  displayName: "Gun EZ",
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-013",
  printings: [
    {
      id: "GD05-013",
      artId: "GD05-013",
      setCode: "GD05",
      collectorNumber: "GD05-013",
      cardNumber: "GD05-013",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-013.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-013",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-013.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit V Gundam",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 1,
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "common",
};
