import type { UnitCard } from "@tcg/gundam-types";

export const gd05Javelin014: UnitCard = {
  cardNumber: "GD05-014",
  name: "Javelin",
  type: "unit",
  color: "blue",
  traits: ["earth federation", "league militaire"],
  id: "GD05-014",
  canonicalId: "GD05-014",
  externalIds: { bandai: "gundam:gd05-014" },
  slug: "javelin-gd05-014",
  displayName: "Javelin",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-014",
  printings: [
    {
      id: "GD05-014",
      artId: "GD05-014",
      setCode: "GD05",
      collectorNumber: "GD05-014",
      cardNumber: "GD05-014",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-014.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-014",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-014.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit V Gundam",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
