import type { UnitCard } from "@tcg/gundam-types";

export const gd05Jegan027: UnitCard = {
  cardNumber: "GD05-027",
  name: "Jegan",
  type: "unit",
  color: "green",
  traits: ["earth federation", "londo bell"],
  id: "GD05-027",
  canonicalId: "GD05-027",
  externalIds: { bandai: "gundam:gd05-027" },
  slug: "jegan-gd05-027",
  displayName: "Jegan",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-027",
  printings: [
    {
      id: "GD05-027",
      artId: "GD05-027",
      setCode: "GD05",
      collectorNumber: "GD05-027",
      cardNumber: "GD05-027",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-027.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-027",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-027.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam: Char's Counterattack",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
