import type { UnitCard } from "@tcg/gundam-types";

export const gd05GuelSDilanza031: UnitCard = {
  cardNumber: "GD05-031",
  name: "Guel's Dilanza",
  type: "unit",
  color: "green",
  traits: ["academy"],
  id: "GD05-031",
  canonicalId: "GD05-031",
  externalIds: { bandai: "gundam:gd05-031" },
  slug: "guel-s-dilanza-gd05-031",
  displayName: "Guel's Dilanza",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-031",
  printings: [
    {
      id: "GD05-031",
      artId: "GD05-031",
      setCode: "GD05",
      collectorNumber: "GD05-031",
      cardNumber: "GD05-031",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-031.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-031",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-031.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam the Witch from Mercury",
  level: 5,
  cost: 3,
  ap: 4,
  hp: 4,
  linkCondition: "(Academy) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
