import type { UnitCard } from "@tcg/gundam-types";

export const gd05Desultor032: UnitCard = {
  cardNumber: "GD05-032",
  name: "Desultor",
  type: "unit",
  color: "green",
  traits: ["dawn of fold"],
  id: "GD05-032",
  canonicalId: "GD05-032",
  externalIds: { bandai: "gundam:gd05-032" },
  slug: "desultor-gd05-032",
  displayName: "Desultor",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-032",
  printings: [
    {
      id: "GD05-032",
      artId: "GD05-032",
      setCode: "GD05",
      collectorNumber: "GD05-032",
      cardNumber: "GD05-032",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-032.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-032",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-032.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam the Witch from Mercury",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Dawn of Fold) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
