import type { UnitCard } from "@tcg/gundam-types";

export const gd05ShiningGundam042: UnitCard = {
  cardNumber: "GD05-042",
  name: "Shining Gundam",
  type: "unit",
  color: "red",
  traits: ["mf", "shuffle alliance"],
  id: "GD05-042",
  canonicalId: "GD05-042",
  externalIds: { bandai: "gundam:gd05-042" },
  slug: "shining-gundam-gd05-042",
  displayName: "Shining Gundam",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-042",
  printings: [
    {
      id: "GD05-042",
      artId: "GD05-042",
      setCode: "GD05",
      collectorNumber: "GD05-042",
      cardNumber: "GD05-042",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-042.webp",
      productName: "Freedom Ascension [GD05]",
    },
    {
      id: "GD05-042-p1",
      artId: "GD05-042_p1",
      setCode: "GD05",
      collectorNumber: "GD05-042-p1",
      cardNumber: "GD05-042",
      set: { code: "GD05", name: "Promotion card", packageId: "616901" },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-042_p1.webp",
      productName:
        "Booster Pack Freedom Ascension [GD05] Release Event Commemorative Items for Participants",
    },
  ],
  selectedPrintingId: "GD05-042",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-042.webp",
  legality: "legal",
  sourceTitle: "Mobile Fighter G Gundam",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
