import type { UnitCard } from "@tcg/gundam-types";

export const gd05NerosGundam043: UnitCard = {
  cardNumber: "GD05-043",
  name: "Neros Gundam",
  type: "unit",
  color: "red",
  traits: ["mf"],
  id: "GD05-043",
  canonicalId: "GD05-043",
  externalIds: { bandai: "gundam:gd05-043" },
  slug: "neros-gundam-gd05-043",
  displayName: "Neros Gundam",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-043",
  printings: [
    {
      id: "GD05-043",
      artId: "GD05-043",
      setCode: "GD05",
      collectorNumber: "GD05-043",
      cardNumber: "GD05-043",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-043.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-043",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-043.webp",
  legality: "legal",
  sourceTitle: "Mobile Fighter G Gundam",
  level: 2,
  cost: 2,
  ap: 3,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
