import type { UnitCard } from "@tcg/gundam-types";

export const gd05Exass047: UnitCard = {
  cardNumber: "GD05-047",
  name: "Exass",
  type: "unit",
  color: "red",
  traits: ["earth alliance", "phantom pain"],
  id: "GD05-047",
  canonicalId: "GD05-047",
  externalIds: { bandai: "gundam:gd05-047" },
  slug: "exass-gd05-047",
  displayName: "Exass",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-047",
  printings: [
    {
      id: "GD05-047",
      artId: "GD05-047",
      setCode: "GD05",
      collectorNumber: "GD05-047",
      cardNumber: "GD05-047",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-047.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-047",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-047.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam SEED Destiny",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 2,
  linkCondition: "(Earth Alliance) Trait",
  battlefieldZones: ["space"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
