import type { UnitCard } from "@tcg/gundam-types";

export const gd05RezinSGearaDoga056: UnitCard = {
  cardNumber: "GD05-056",
  name: "Rezin's Geara Doga",
  type: "unit",
  color: "purple",
  traits: ["neo zeon"],
  id: "GD05-056",
  canonicalId: "GD05-056",
  externalIds: { bandai: "gundam:gd05-056" },
  slug: "rezin-s-geara-doga-gd05-056",
  displayName: "Rezin's Geara Doga",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-056",
  printings: [
    {
      id: "GD05-056",
      artId: "GD05-056",
      setCode: "GD05",
      collectorNumber: "GD05-056",
      cardNumber: "GD05-056",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-056.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-056",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-056.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam: Char's Counterattack",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  linkCondition: "(Neo Zeon) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "uncommon",
};
