import type { UnitCard } from "@tcg/gundam-types";

export const gd05ShidenCustomRyuseiGo058: UnitCard = {
  cardNumber: "GD05-058",
  name: "Shiden Custom (Ryusei-Go)",
  type: "unit",
  color: "purple",
  traits: ["tekkadan"],
  id: "GD05-058",
  canonicalId: "GD05-058",
  externalIds: { bandai: "gundam:gd05-058" },
  slug: "shiden-custom-ryusei-go-gd05-058",
  displayName: "Shiden Custom (Ryusei-Go)",
  rulesText: "<Blocker> (Rest this Unit to change the attack target to it.)",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-058",
  printings: [
    {
      id: "GD05-058",
      artId: "GD05-058",
      setCode: "GD05",
      collectorNumber: "GD05-058",
      cardNumber: "GD05-058",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "uncommon",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-058.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-058",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-058.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam: Iron-Blooded Orphans",
  level: 4,
  cost: 3,
  ap: 4,
  hp: 3,
  linkCondition: "(Tekkadan) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "<Blocker> (Rest this Unit to change the attack target to it.)",
  effects: [],
  keywordEffects: [{ keyword: "Blocker" }],
  rarity: "uncommon",
};
