import type { UnitCard } from "@tcg/gundam-types";

export const gd05HobbyHizack062: UnitCard = {
  cardNumber: "GD05-062",
  name: "Hobby Hizack",
  type: "unit",
  color: "purple",
  traits: ["neo zeon"],
  id: "GD05-062",
  canonicalId: "GD05-062",
  externalIds: { bandai: "gundam:gd05-062" },
  slug: "hobby-hizack-gd05-062",
  displayName: "Hobby Hizack",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-062",
  printings: [
    {
      id: "GD05-062",
      artId: "GD05-062",
      setCode: "GD05",
      collectorNumber: "GD05-062",
      cardNumber: "GD05-062",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-062.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-062",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-062.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam: Char's Counterattack",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
