import type { UnitCard } from "@tcg/gundam-types";

export const gd05GyuneiSJagdDoga063: UnitCard = {
  cardNumber: "GD05-063",
  name: "Gyunei's Jagd Doga",
  type: "unit",
  color: "purple",
  traits: ["neo zeon"],
  id: "GD05-063",
  canonicalId: "GD05-063",
  externalIds: { bandai: "gundam:gd05-063" },
  slug: "gyunei-s-jagd-doga-gd05-063",
  displayName: "Gyunei's Jagd Doga",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-063",
  printings: [
    {
      id: "GD05-063",
      artId: "GD05-063",
      setCode: "GD05",
      collectorNumber: "GD05-063",
      cardNumber: "GD05-063",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-063.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-063",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-063.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam: Char's Counterattack",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 2,
  linkCondition: "(Neo Zeon) Trait",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
