import type { UnitCard } from "@tcg/gundam-types";

export const gd05Leo077: UnitCard = {
  cardNumber: "GD05-077",
  name: "Leo",
  type: "unit",
  color: "white",
  traits: ["g team"],
  id: "GD05-077",
  canonicalId: "GD05-077",
  externalIds: { bandai: "gundam:gd05-077" },
  slug: "leo-gd05-077",
  displayName: "Leo",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-077",
  printings: [
    {
      id: "GD05-077",
      artId: "GD05-077",
      setCode: "GD05",
      collectorNumber: "GD05-077",
      cardNumber: "GD05-077",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-077.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-077",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-077.webp",
  legality: "legal",
  sourceTitle: "Mobile Suit Gundam Wing: Endless Waltz",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
