import type { UnitCard } from "@tcg/gundam-types";

export const gd05GavaneSBorjarnon080: UnitCard = {
  cardNumber: "GD05-080",
  name: "Gavane's Borjarnon",
  type: "unit",
  color: "white",
  traits: ["militia"],
  id: "GD05-080",
  canonicalId: "GD05-080",
  externalIds: { bandai: "gundam:gd05-080" },
  slug: "gavane-s-borjarnon-gd05-080",
  displayName: "Gavane's Borjarnon",
  rulesText: "-",
  set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
  printNumber: "GD05-080",
  printings: [
    {
      id: "GD05-080",
      artId: "GD05-080",
      setCode: "GD05",
      collectorNumber: "GD05-080",
      cardNumber: "GD05-080",
      set: { code: "GD05", name: "Freedom Ascension [GD05]", packageId: "616105" },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-080.webp",
      productName: "Freedom Ascension [GD05]",
    },
  ],
  selectedPrintingId: "GD05-080",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/gd05/GD05-080.webp",
  legality: "legal",
  sourceTitle: "∀ Gundam",
  level: 3,
  cost: 1,
  ap: 1,
  hp: 3,
  linkCondition: "[Gavane Goonny]",
  battlefieldZones: ["space", "earth"],
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
