import type { UnitCard } from "@tcg/gundam-types";

export const st08MesserTypeFNakedCommanderType003: UnitCard = {
  cardNumber: "ST08-003",
  name: "Messer (Type-F Naked) (Commander Type)",
  type: "unit",
  color: "red",
  traits: ["mafty"],
  id: "ST08-003",
  externalId: "gundam:st08-003",
  slug: "messer-type-f-naked-commander-type-st08-003",
  displayName: "Messer (Type-F Naked) (Commander Type)",
  set: { code: "ST08", name: "Flash of Radiance [ST08]", packageId: "616008" },
  printNumber: "ST08-003",
  printings: [
    {
      id: "ST08-003",
      collectorNumber: "ST08-003",
      cardNumber: "ST08-003",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08]",
        packageId: "616008",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-003.webp?260424",
      productName: "Flash of Radiance [ST08]",
    },
    {
      id: "ST08-003_p1",
      collectorNumber: "ST08-003_p1",
      cardNumber: "ST08-003",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08] Bonus Pack",
        packageId: "616008",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-003_p1.webp?260424",
      productName: "Flash of Radiance [ST08] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST08-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-003.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 4,
  hp: 3,
  linkCondition: "(Mafty) Trait",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
