import type { UnitCard } from "@tcg/gundam-types";

export const st08MesserTypeF02Minelayer005: UnitCard = {
  cardNumber: "ST08-005",
  name: "Messer Type-F02 Minelayer",
  type: "unit",
  color: "red",
  traits: ["mafty"],
  id: "ST08-005",
  externalId: "gundam:st08-005",
  slug: "messer-type-f02-minelayer-st08-005",
  displayName: "Messer Type-F02 Minelayer",
  set: { code: "ST08", name: "Flash of Radiance [ST08]", packageId: "616008" },
  printNumber: "ST08-005",
  printings: [
    {
      id: "ST08-005",
      collectorNumber: "ST08-005",
      cardNumber: "ST08-005",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08]",
        packageId: "616008",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-005.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-005.webp?260424",
      productName: "Flash of Radiance [ST08]",
    },
    {
      id: "ST08-005_p1",
      collectorNumber: "ST08-005_p1",
      cardNumber: "ST08-005",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08] Bonus Pack",
        packageId: "616008",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-005_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-005_p1.webp?260424",
      productName: "Flash of Radiance [ST08] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST08-005",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-005.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-005.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 4,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
