import type { UnitCard } from "@tcg/gundam-types";

export const st08Penelope007: UnitCard = {
  cardNumber: "ST08-007",
  name: "Penelope",
  type: "unit",
  color: "blue",
  traits: ["earth federation"],
  id: "ST08-007",
  externalId: "gundam:st08-007",
  slug: "penelope-st08-007",
  displayName: "Penelope",
  set: { code: "ST08", name: "Flash of Radiance [ST08]", packageId: "616008" },
  printNumber: "ST08-007",
  printings: [
    {
      id: "ST08-007",
      collectorNumber: "ST08-007",
      cardNumber: "ST08-007",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08]",
        packageId: "616008",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-007.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-007.webp?260424",
      productName: "Flash of Radiance [ST08]",
    },
    {
      id: "ST08-007_p1",
      collectorNumber: "ST08-007_p1",
      cardNumber: "ST08-007",
      set: {
        code: "ST08",
        name: "Flash of Radiance [ST08] Bonus Pack",
        packageId: "616008",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-007_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-007_p1.webp?260424",
      productName: "Flash of Radiance [ST08] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST08-007",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st08/ST08-007.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST08-007.webp?260424",
  legality: "legal",
  level: 5,
  cost: 3,
  ap: 5,
  hp: 4,
  linkCondition: "[Lane Aim]",
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
