// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuCalculatedLethality = {
  title: "Calculated Lethality",
  cost: 4,
  text: "Defeat a non-leader unit that costs 3 or less. For each upgrade that was on that unit, give an Experience token to a friendly unit.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\nEach Experience token can be given to any friendly unit.\n",
  id: "0302968596",
  rarity: "special",
  aspects: ["vigilance", "villainy"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 39,
  },
  setCodes: [
    {
      set: "SHD",
      number: 39,
    },
  ],
  internalName: "calculated-lethality",
  cardType: "event",
  canonicalId: "calculated-lethality",
  slug: "calculated-lethality",
  name: "Calculated Lethality",
  printings: [
    {
      id: "SHD_039",
      artId: "2757",
      setCode: "SHD",
      collectorNumber: "39",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//SWH_02_039_Calculated_Lethality_2c1cf668d0.png",
    },
    {
      id: "9981343822",
      artId: "2757",
      setCode: "SHD",
      collectorNumber: "10",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202010_EN_Calculated_Lethality_e12ffdb63f.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Defeat a non-leader unit that costs 3 or less. For each upgrade that was on that unit, give an Experience token to a friendly unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuCalculatedLethality;
