// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuConfiscate = {
  title: "Confiscate",
  cost: 1,
  text: "Defeat an upgrade.",
  unique: false,
  id: "1630144142",
  rarity: "special",
  traits: ["law"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 262,
  },
  setCodes: [
    {
      set: "SHD",
      number: 262,
    },
  ],
  internalName: "confiscate",
  cardType: "event",
  canonicalId: "confiscate",
  slug: "confiscate",
  name: "Confiscate",
  printings: [
    {
      id: "SHD_262",
      artId: "6591",
      setCode: "SHD",
      collectorNumber: "262",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//0201262_EN_Confiscate_696bd9ccc5.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Defeat an upgrade.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "defeat",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["upgrade"],
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuConfiscate;
