// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuEvacuate = {
  title: "Evacuate",
  cost: 6,
  text: "Return each non-leader unit to its owner's hand.",
  unique: false,
  rules:
    "Abilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "8261033110",
  rarity: "legendary",
  aspects: ["cunning"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 233,
  },
  setCodes: [
    {
      set: "SHD",
      number: 233,
    },
  ],
  internalName: "evacuate",
  cardType: "event",
  canonicalId: "evacuate",
  slug: "evacuate",
  name: "Evacuate",
  printings: [
    {
      id: "SHD_233",
      artId: "6456",
      setCode: "SHD",
      collectorNumber: "233",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0201233_EN_Evacuate_9ad43bf5ae.png",
    },
    {
      id: "7003320341",
      artId: "6456",
      setCode: "SHD",
      collectorNumber: "233",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0231233_EN_Evacuate_9faf3398eb.png",
    },
    {
      id: "0515526931",
      artId: "6456",
      setCode: "SHD",
      collectorNumber: "500",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0202500_EN_Evacuate_f3c0647c5e.png",
    },
    {
      id: "9146151430",
      artId: "6456",
      setCode: "SHD",
      collectorNumber: "500",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0232500_EN_Evacuate_5f2dff5f42.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Return each non-leader unit to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
          },
          to: "hand",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuEvacuate;
