// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuEvidenceOfTheCrime = {
  title: "Evidence of the Crime",
  cost: 3,
  text: "Take control of an upgrade that costs 3 or less and attach it to an eligible unit of your choice.",
  unique: false,
  rules:
    "Abilities that refer to a card’s cost always refer to its printed cost, regardless of modifiers.\n",
  id: "6452159858",
  rarity: "rare",
  aspects: ["vigilance"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 77,
  },
  setCodes: [
    {
      set: "SHD",
      number: 77,
    },
  ],
  internalName: "evidence-of-the-crime",
  cardType: "event",
  canonicalId: "evidence-of-the-crime",
  slug: "evidence-of-the-crime",
  name: "Evidence of the Crime",
  printings: [
    {
      id: "SHD_077",
      artId: "5706",
      setCode: "SHD",
      collectorNumber: "77",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0201077_EN_Evidence_of_the_Crime_7aca8c5279.png",
    },
    {
      id: "9935649904",
      artId: "5706",
      setCode: "SHD",
      collectorNumber: "77",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0231077_EN_Evidence_of_the_Crime_7e27e8eba4.png",
    },
    {
      id: "0925221150",
      artId: "5706",
      setCode: "SHD",
      collectorNumber: "350",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0232350_EN_Evidence_of_the_Crime_5c6031c2f8.png",
    },
    {
      id: "3475938160",
      artId: "5706",
      setCode: "SHD",
      collectorNumber: "350",
      rarity: "rare",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0202350_EN_Evidence_of_the_Crime_a37459ef90.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Take control of an upgrade that costs 3 or less and attach it to an eligible unit of your choice.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "takeControl",
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["upgrade"],
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuEvidenceOfTheCrime;
