// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuMaKlounkee = {
  title: "Ma Klounkee",
  cost: 1,
  text: "Return a friendly non-leader Underworld unit to its owner's hand. If you do, deal 3 damage to a unit.",
  unique: false,
  rules:
    "Abilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "0931441928",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["underworld", "trick"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 229,
  },
  setCodes: [
    {
      set: "SHD",
      number: 229,
    },
  ],
  internalName: "ma-klounkee",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Return a friendly non-leader Underworld unit to its owner's hand. If you do, deal 3 damage to a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "move",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
          to: "hand",
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuMaKlounkee;
