// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuNoBargain = {
  title: "No Bargain",
  cost: 3,
  text: "Each opponent discards a card from their hand. Draw a card.",
  unique: false,
  id: "7354795397",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["trick"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 244,
  },
  setCodes: [
    {
      set: "SHD",
      number: 244,
    },
  ],
  internalName: "no-bargain",
  cardType: "event",
  canonicalId: "no-bargain",
  slug: "no-bargain",
  name: "No Bargain",
  printings: [
    {
      id: "SHD_244",
      artId: "6506",
      setCode: "SHD",
      collectorNumber: "244",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0201244_EN_No_Bargain_32ff6a87e5.png",
    },
    {
      id: "6086775186",
      artId: "6506",
      setCode: "SHD",
      collectorNumber: "244",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0231244_EN_No_Bargain_130bce3f53.png",
    },
    {
      id: "5183058389",
      artId: "6506",
      setCode: "SHD",
      collectorNumber: "507",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0232507_EN_No_Bargain_9a47cb69ac.png",
    },
    {
      id: "9549633221",
      artId: "6506",
      setCode: "SHD",
      collectorNumber: "507",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202507_EN_No_Bargain_64615ae8c0.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Each opponent discards a card from their hand. Draw a card.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "discard",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["hand"],
            limit: 1,
          },
          amount: 1,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuNoBargain;
