// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuRuleWithRespect = {
  title: "Rule with Respect",
  cost: 4,
  text: "A friendly unit captures each enemy non-leader unit that attacked your base this phase.",
  unique: false,
  id: "8080818347",
  rarity: "legendary",
  aspects: ["command", "heroism"],
  traits: ["plan"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 106,
  },
  setCodes: [
    {
      set: "SHD",
      number: 106,
    },
  ],
  internalName: "rule-with-respect",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "A friendly unit captures each enemy non-leader unit that attacked your base this phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "capture",
          target: {
            type: "base",
            controller: "friendly",
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuRuleWithRespect;
