// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuTimelyIntervention = {
  title: "Timely Intervention",
  cost: 1,
  text: "Play a unit from your hand. Give it Ambush for this phase. (When you play it, it may ready and attack an enemy unit.)\n\nSmuggle [2 resources, command] (If this card is a resource, you may play it for its smuggle cost. Replace it with the top card of your deck.)",
  unique: false,
  rules:
    "Abilities that let you play a card require you to pay that card’s cost unless specified otherwise.\nAmbush is an ability that triggers at the same time as “When Played” abilities. If there is no enemy unit that can be attacked, the unit does boba not ready.\n",
  id: "6847268098",
  rarity: "common",
  aspects: ["command"],
  traits: ["tactic"],
  keywords: ["ambush", "smuggle"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 129,
  },
  setCodes: [
    {
      set: "SHD",
      number: 129,
    },
  ],
  internalName: "timely-intervention",
  cardType: "event",
  canonicalId: "timely-intervention",
  slug: "timely-intervention",
  name: "Timely Intervention",
  printings: [
    {
      id: "SHD_129",
      artId: "2806",
      setCode: "SHD",
      collectorNumber: "129",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0201129_EN_Timely_Intervention_547009e09d.png",
    },
    {
      id: "4977844391",
      artId: "2806",
      setCode: "SHD",
      collectorNumber: "129",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0231129_EN_Timely_Intervention_fc58614333.png",
    },
    {
      id: "6735161634",
      artId: "2806",
      setCode: "SHD",
      collectorNumber: "398",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0202398_EN_Timely_Intervention_8b9ce7514a.png",
    },
    {
      id: "8081208065",
      artId: "2806",
      setCode: "SHD",
      collectorNumber: "398",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0232398_EN_Timely_Intervention_d64cb585d7.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Ambush",
      keyword: "ambush",
    },
    {
      kind: "keyword",
      text: "Smuggle",
      keyword: "smuggle",
    },
    {
      kind: "triggered",
      text: "Play a unit from your hand. Give it Ambush for this phase. (When you play it, it may ready and attack an enemy unit.)",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "play",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["hand"],
            cardTypes: ["unit"],
            limit: 1,
          },
          free: false,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuTimelyIntervention;
