// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuTripleDarkRaid = {
  title: "Triple Dark Raid",
  cost: 3,
  text: "Search the top 7 cards of your deck for a Vehicle and play it. (Put the other cards on the bottom of your deck in a random order.) It costs 5 resources less and enters play ready. Return it to its owner's hand at the end of the phase.",
  unique: false,
  rules:
    "After searching, put any cards not chosen on the bottom of your deck in a random order.\nAbilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "5696041568",
  rarity: "rare",
  aspects: ["cunning", "villainy"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "SHD",
    number: 194,
  },
  setCodes: [
    {
      set: "SHD",
      number: 194,
    },
  ],
  internalName: "triple-dark-raid",
  cardType: "event",
  canonicalId: "triple-dark-raid",
  slug: "triple-dark-raid",
  name: "Triple Dark Raid",
  printings: [
    {
      id: "SHD_194",
      artId: "6271",
      setCode: "SHD",
      collectorNumber: "194",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0201194_EN_Triple_Dark_Raid_55ca143163.png",
    },
    {
      id: "2303572686",
      artId: "6271",
      setCode: "SHD",
      collectorNumber: "194",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0231194_EN_Triple_Dark_Raid_796276fe21.png",
    },
    {
      id: "7679930554",
      artId: "6271",
      setCode: "SHD",
      collectorNumber: "463",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0232463_EN_Triple_Dark_Raid_6ec30d1a22.png",
    },
    {
      id: "7967304865",
      artId: "6271",
      setCode: "SHD",
      collectorNumber: "463",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0202463_EN_Triple_Dark_Raid_d308b9db9b.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Search the top 7 cards of your deck for a Vehicle and play it. (Put the other cards on the bottom of your deck in a random order.) It costs 5 resources less and enters play ready. Return it to its owner's hand at the end of the phase.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "play",
          target: {
            type: "card",
            controller: "friendly",
            zones: ["deck"],
            limit: 1,
          },
          free: false,
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuTripleDarkRaid;
