// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuIveFoundThem = {
  title: "I've Found Them",
  cost: 2,
  text: "Reveal the top 3 cards of your deck. Draw a unit revealed this way, then discard the other revealed cards.",
  unique: false,
  id: "0434810928",
  rarity: "special",
  aspects: ["command"],
  traits: ["gambit"],
  types: ["event"],
  setId: {
    set: "IBH",
    number: 25,
  },
  setCodes: [
    {
      set: "IBH",
      number: 25,
    },
  ],
  internalName: "ive-found-them",
  cardType: "event",
  canonicalId: "ive-found-them",
  slug: "ive-found-them",
  name: "I've Found Them",
  printings: [
    {
      id: "IBH_025",
      artId: "38955",
      setCode: "IBH",
      collectorNumber: "25",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//I01010025_EN_I_ve_Found_Them_ce97546e50.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Reveal the top 3 cards of your deck. Draw a unit revealed this way, then discard the other revealed cards.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "sequential",
          effects: [
            {
              type: "reveal",
              target: {
                type: "card",
                controller: "friendly",
                zones: ["deck"],
                limit: 3,
              },
            },
            {
              type: "search",
              target: {
                type: "card",
                controller: "friendly",
                zones: ["deck"],
                cardTypes: ["unit"],
                limit: 1,
              },
              destination: "hand",
              reveal: false,
            },
            {
              type: "discard",
              target: {
                type: "card",
                controller: "friendly",
                zones: ["deck"],
                limit: 2,
              },
              amount: 2,
            },
          ],
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuIveFoundThem;
