// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuTooStrongForBlasters = {
  title: "Too Strong for Blasters",
  cost: 1,
  text: "Heal 2 damage from a unit.",
  unique: false,
  id: "7014669428",
  rarity: "special",
  aspects: ["vigilance"],
  traits: ["innate"],
  types: ["event"],
  setId: {
    set: "IBH",
    number: 66,
  },
  setCodes: [
    {
      set: "IBH",
      number: 66,
    },
  ],
  internalName: "too-strong-for-blasters",
  cardType: "event",
  abilities: [
    {
      kind: "triggered",
      text: "Heal 2 damage from a unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "heal",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuTooStrongForBlasters;
