// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUpgradeCard } from "@tcg/star-wars-unlimited-types";

export const swuTheDarksaberIconOfLeadership = {
  title: "The Darksaber",
  subtitle: "Icon of Leadership",
  cost: 4,
  text: "Attach to a <uq> non-Vehicle unit.\nAttached unit is a leader unit and gains the Mandalorian trait.\nAttached unit gains: “While you are paying costs, this unit provides its aspect icons.”",
  unique: true,
  upgradePower: 4,
  upgradeHp: 2,
  id: "3629508713",
  rarity: "legendary",
  aspects: ["command"],
  traits: ["mandalorian", "item", "weapon"],
  types: ["upgrade"],
  setId: {
    set: "ASH",
    number: 135,
  },
  setCodes: [
    {
      set: "ASH",
      number: 135,
    },
  ],
  internalName: "the-darksaber#icon-of-leadership",
  cardType: "upgrade",
  abilities: [
    {
      kind: "constant",
      text: "Attach to a <uq> non-Vehicle unit.",
      target: {
        type: "card",
        controller: "any",
        zones: ["groundArena", "spaceArena"],
        cardTypes: ["unit", "token"],
        limit: 1,
        withoutTraits: ["Vehicle"],
      },
    },
  ],
} satisfies SwuUpgradeCard;

export default swuTheDarksaberIconOfLeadership;
