import type { AlphaCardDefinition } from "@tcg/cyberpunk-types";

export const alphaDelamainCab = {
  id: "5dba6f6d-b7da-46a7-946d-670bdfb1fe6f",
  externalId: "cyberpunk:delamain-cab",
  slug: "delamain-cab",
  name: "Delamain Cab",
  subname: null,
  displayName: "Delamain Cab",
  rulesText: null,
  flavorText: null,
  color: "blue",
  classifications: ["Vehicle"],
  set: {
    code: "alpha",
    name: "Alpha Kit Set",
  },
  printNumber: "α010",
  printings: [
    {
      id: "f85fb4f8-2e61-4dea-9b9c-d02aece7b280",
      collectorNumber: "α010",
      imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/alpha/a010.webp",
      sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/a010.webp",
      set: {
        code: "alpha",
        name: "Alpha Kit Set",
      },
      rarity: null,
      finish: "standard",
      artist: "Daniel Valaisis",
    },
  ],
  selectedPrintingId: "f85fb4f8-2e61-4dea-9b9c-d02aece7b280",
  artist: "Daniel Valaisis",
  imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/alpha/a010.webp",
  sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/a010.webp",
  rarity: null,
  legality: "legal",
  hasSellTag: false,
  ram: 3,
  timingTriggers: [],
  keywords: [],
  type: "unit",
  cost: 4,
  power: 7,
  abilities: [],
  reminderText: [],
} satisfies AlphaCardDefinition;
