import type { AlphaCardDefinition } from "@tcg/cyberpunk-types";

export const alphaTBugAmateurPhilosopher = {
  id: "07d0d80a-6a86-40b7-9dd5-8401700667ec",
  externalId: "cyberpunk:t-bug-amateur-philosopher",
  slug: "t-bug-amateur-philosopher",
  name: "T-Bug",
  subname: "Amateur Philosopher",
  displayName: "T-Bug - Amateur Philosopher",
  rulesText: null,
  flavorText: null,
  color: "yellow",
  classifications: ["Netrunner", "Merc"],
  set: {
    code: "alpha",
    name: "Alpha Kit Set",
  },
  printNumber: "α015",
  printings: [
    {
      id: "826619c7-98c3-4d2d-a278-a2e089469682",
      collectorNumber: "α015",
      imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/alpha/a015.webp",
      sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/a015.webp",
      set: {
        code: "alpha",
        name: "Alpha Kit Set",
      },
      rarity: null,
      finish: "standard",
      artist: "CD PROJEKT RED",
    },
  ],
  selectedPrintingId: "826619c7-98c3-4d2d-a278-a2e089469682",
  artist: "CD PROJEKT RED",
  imageUrl: "https://r2.tcg.online/public/cyberpunk/cards/alpha/a015.webp",
  sourceImageUrl: "https://dstcynss47vun.cloudfront.net/prod/cyberpunk/a015.webp",
  rarity: null,
  legality: "legal",
  hasSellTag: false,
  ram: 1,
  timingTriggers: [],
  keywords: [],
  type: "unit",
  cost: 3,
  power: 5,
  abilities: [],
  reminderText: [],
} satisfies AlphaCardDefinition;
