/**
 * Hand-authored archetype decks for bot-lab training, paired evaluation, and
 * the practice catalog. Single source shared by the ai-runner bench, the
 * server-adapter practice catalog, and the simulator practice fixtures.
 *
 * Card names use catalog display names (`Name: Subtitle`); legends sit
 * outside the 40-card main deck, matching the print-and-play list format.
 * Resolution against the structured catalog happens in
 * `resolveAuthoredBotLabDeck`, so an unresolvable or illegal list fails
 * loudly at construction instead of producing a padded or silently trimmed
 * deck.
 */
export interface AuthoredBotLabDeckSpec {
  readonly id: string;
  /** Human-readable deck title (English). */
  readonly title: string;
  readonly legends: readonly [string, string, string];
  /** Display name -> copy count; insertion order is the deck's card order. */
  readonly mainDeck: Readonly<Record<string, number>>;
}

export const authoredBotLabDeckSpecs = [
  {
    id: "authored-overwatch-recharge-control",
    title: "Overwatch — Recharge Control",
    legends: [
      "Hanako Arasaka: Daughter of the Emperor",
      "Goro Takemura: Hands Unclean",
      "Viktor Vektor: Sit Down and Relax",
    ],
    mainDeck: {
      "Corpo Security": 3,
      "MaxTac Squadron": 3,
      "Goro Takemura: Losing His Way": 3,
      "Panam Palmer: Strength Through Family": 3,
      "Sandayu Oda: Hanako's Guardian": 2,
      "MaxTac Suppression Team": 2,
      "Overwatch: Panam's Gift": 3,
      Sandevistan: 3,
      "Zetatech Faceplate": 3,
      "Riot Shield": 2,
      "Peace Offering": 3,
      "Corporate Surveillance": 3,
      "Afterparty at Lizzie's": 3,
      "Synapse Burnout": 2,
      "The Heist": 2,
    },
  },
  {
    id: "authored-alt-gears-multiplied-economy",
    title: "Alt + Gears — Multiplied Economy",
    legends: [
      "Viktor Vektor: Sit Down and Relax",
      "River Ward: Detective on the Hunt",
      "Jackie Welles: Pour One Out For Me",
    ],
    mainDeck: {
      "Secondhand Bombus": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Hanako Arasaka: In a Gilded Cage": 3,
      "Alt Cunningham: Mother of Daemons": 3,
      "MaxTac Suppression Team": 2,
      "Placide: Voodoo Sentinel": 2,
      "Zetatech Faceplate": 3,
      "NetWatch Netdriver": 3,
      "Kiroshi Optics": 3,
      "Mandibular Upgrade": 2,
      "The Heist": 3,
      "Afterparty at Lizzie's": 3,
      "Floor It": 3,
      "Reboot Optics": 2,
      "Trust No One": 2,
    },
  },
  {
    id: "authored-yorinobu-two-units-for-one",
    title: "Yorinobu — Two Units for the Price of One",
    legends: [
      "V: Streetkid",
      "Yorinobu Arasaka: Embracing Destruction",
      "Viktor Vektor: Sit Down and Relax",
    ],
    mainDeck: {
      "Yorinobu Arasaka: Steel Dragon": 3,
      "Kerry Eurodyne: The Last Rockerboy": 3,
      "Meredith Stout: Stone Cold Corpo": 3,
      "Swordwise Huscle": 3,
      "6th Street Recruits": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Hanako Arasaka: In a Gilded Cage": 2,
      "Johnny Silverhand: Never Stop Fighting": 3,
      "Mantis Blades": 3,
      "Zetatech Faceplate": 3,
      "Satori: Sword of Saburo": 2,
      "Industrial Assembly": 3,
      "The Heist": 3,
      "Afterparty at Lizzie's": 3,
    },
  },
  {
    id: "authored-cyberpsychosis-deadman-burst-insurance",
    title: "Cyberpsychosis + Deadman — Burst with Insurance",
    legends: [
      "V: Streetkid",
      "Yorinobu Arasaka: Embracing Destruction",
      "Dum Dum: Maelstrom Triggerman",
    ],
    mainDeck: {
      "Swordwise Huscle": 3,
      "6th Street Recruits": 3,
      "Johnny Silverhand: Never Stop Fighting": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Yorinobu Arasaka: Steel Dragon": 2,
      "Dexter DeShawn: One Last Chance": 2,
      "Mantis Blades": 3,
      "Kiroshi Optics": 3,
      "Zetatech Faceplate": 3,
      "Deadman Transmitter": 3,
      "Mandibular Upgrade": 2,
      "Satori: Sword of Saburo": 2,
      Cyberpsychosis: 3,
      "The Heist": 3,
      "Afterparty at Lizzie's": 2,
    },
  },
  {
    id: "authored-johnny-fight-ready-steal",
    title: "Johnny — Fight, Ready and Steal",
    legends: ["V: Streetkid", "Saburo Arasaka: Stubborn Patriarch", "Goro Takemura: Hands Unclean"],
    mainDeck: {
      "Johnny Silverhand: Never Stop Fighting": 3,
      "Swordwise Huscle": 3,
      "Goro Takemura: Losing His Way": 3,
      "MaxTac Squadron": 3,
      "Corpo Security": 3,
      Minotaur: 2,
      "Sandayu Oda: Hanako's Guardian": 2,
      "Satori: Sword of Saburo": 3,
      "Mantis Blades": 3,
      Sandevistan: 3,
      "Riot Shield": 2,
      "Corporate Surveillance": 3,
      "Industrial Assembly": 3,
      "Synapse Burnout": 2,
      "Peace Offering": 2,
    },
  },
  {
    id: "authored-hanako-netdriver-gigs-draw-engine",
    title: "Hanako + Netdriver — Gigs as Draw Engine",
    legends: [
      "Hanako Arasaka: Daughter of the Emperor",
      "Goro Takemura: Hands Unclean",
      "Alt Cunningham: Soulkiller Architect",
    ],
    mainDeck: {
      "Corpo Security": 3,
      "MaxTac Squadron": 3,
      "Goro Takemura: Losing His Way": 3,
      "Panam Palmer: Strength Through Family": 3,
      "Sandayu Oda: Hanako's Guardian": 2,
      "Jacked-In Voodoo Boy": 2,
      "NetWatch Netdriver": 3,
      Sandevistan: 3,
      "Overwatch: Panam's Gift": 2,
      "Riot Shield": 2,
      "Peace Offering": 3,
      "Trust No One": 3,
      "Chrome Reverie": 3,
      "Floor It": 3,
      "Reboot Optics": 2,
    },
  },
  {
    id: "authored-oda-industrial-assembly-pairs-plateaus",
    title: "Oda + Industrial Assembly — Pairs and Plateaus",
    legends: [
      "Hanako Arasaka: Daughter of the Emperor",
      "Saburo Arasaka: Stubborn Patriarch",
      "Yorinobu Arasaka: Embracing Destruction",
    ],
    mainDeck: {
      "Sandayu Oda: Hanako's Guardian": 3,
      "Goro Takemura: Losing His Way": 3,
      "6th Street Recruits": 3,
      "Kerry Eurodyne: The Last Rockerboy": 3,
      "MaxTac Squadron": 3,
      Minotaur: 2,
      "Corpo Security": 2,
      "Panam Palmer: Strength Through Family": 2,
      "Mantis Blades": 3,
      "Satori: Sword of Saburo": 2,
      Sandevistan: 2,
      "Industrial Assembly": 3,
      "Peace Offering": 3,
      "Corporate Surveillance": 3,
      "Synapse Burnout": 3,
    },
  },
  {
    id: "authored-judy-top-deck-discount",
    title: "Judy — Top-of-Deck Discount, Not a Guaranteed Top",
    legends: [
      "Alt Cunningham: Soulkiller Architect",
      "Jackie Welles: Pour One Out For Me",
      "Judy Álvarez: Braindance Maestro",
    ],
    mainDeck: {
      "Evelyn Parker: Scheming Siren": 3,
      "Jacked-In Voodoo Boy": 3,
      "MT0D12 Flathead": 3,
      "Judy Álvarez: Nothing to Doubt": 3,
      "Placide: Voodoo Sentinel": 3,
      "Misty Olszewski: Mender of Broken Spirits": 2,
      "NetWatch Netdriver": 3,
      "Trust No One": 3,
      "Chrome Reverie": 3,
      "Pyramid Song": 3,
      Towerfall: 3,
      "Floor It": 3,
      "Les Élémens": 3,
      "Reboot Optics": 2,
    },
  },
  {
    id: "authored-relic-placide-surgical-reanimation",
    title: "Relic + Placide — Surgical Reanimation",
    legends: [
      "Viktor Vektor: Sit Down and Relax",
      "River Ward: Detective on the Hunt",
      "Alt Cunningham: Soulkiller Architect",
    ],
    mainDeck: {
      "Secondhand Bombus": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Hanako Arasaka: In a Gilded Cage": 3,
      "Placide: Voodoo Sentinel": 3,
      "Alt Cunningham: Mother of Daemons": 2,
      "MaxTac Suppression Team": 2,
      "The Relic: Experimental Biochip": 3,
      "Zetatech Faceplate": 3,
      "Kiroshi Optics": 3,
      "NetWatch Netdriver": 2,
      "The Heist": 3,
      "Live with the Aftermath": 3,
      "Floor It": 3,
      "Trust No One": 2,
      "Afterparty at Lizzie's": 2,
    },
  },
  {
    id: "authored-relic-smasher-total-sweep",
    title: "Relic + Smasher — Total Sweep",
    legends: [
      "Viktor Vektor: Sit Down and Relax",
      "River Ward: Detective on the Hunt",
      "Dum Dum: Maelstrom Triggerman",
    ],
    mainDeck: {
      "Secondhand Bombus": 3,
      "Dexter DeShawn: One Last Chance": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Hanako Arasaka: In a Gilded Cage": 3,
      "Adam Smasher: Metal Over Meat": 3,
      "MaxTac Suppression Team": 2,
      "The Relic: Experimental Biochip": 3,
      "Zetatech Faceplate": 3,
      "Kiroshi Optics": 3,
      "Mandibular Upgrade": 2,
      "The Heist": 3,
      "Live with the Aftermath": 3,
      "Afterparty at Lizzie's": 3,
      "Safety Override": 2,
      Cyberpsychosis: 1,
    },
  },
  {
    id: "authored-ryg-low-cost-value",
    title: "Red/Yellow/Green — Low-Cost Value",
    legends: [
      "Yorinobu Arasaka: Embracing Destruction",
      "Viktor Vektor: Sit Down and Relax",
      "Goro Takemura: Hands Unclean",
    ],
    mainDeck: {
      "Swordwise Huscle": 3,
      "Kerry Eurodyne: The Last Rockerboy": 3,
      "6th Street Recruits": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Gilded Matón": 3,
      "Field Operator": 3,
      "Mantis Blades": 3,
      "Zetatech Faceplate": 3,
      "Satori: Sword of Saburo": 2,
      "Arasaka Emergency Radioport": 2,
      "Industrial Assembly": 3,
      "Peace Offering": 3,
      "Corporate Surveillance": 3,
      "Afterparty at Lizzie's": 3,
    },
  },
  {
    id: "authored-ryb-low-cost-tempo",
    title: "Red/Yellow/Blue — Low-Cost Tempo",
    legends: [
      "Yorinobu Arasaka: Embracing Destruction",
      "Viktor Vektor: Sit Down and Relax",
      "Alt Cunningham: Soulkiller Architect",
    ],
    mainDeck: {
      "Swordwise Huscle": 3,
      "Kerry Eurodyne: The Last Rockerboy": 3,
      "Viktor Vektor: You Might Feel a Little Pinch": 3,
      "Gilded Matón": 3,
      "Psycho Squad": 3,
      "Delamain Cab": 3,
      "Mantis Blades": 3,
      "Zetatech Faceplate": 3,
      "Kiroshi Optics": 2,
      "Satori: Sword of Saburo": 2,
      "Industrial Assembly": 3,
      "Afterparty at Lizzie's": 3,
      "Floor It": 3,
      "Trust No One": 3,
    },
  },
] as const satisfies readonly AuthoredBotLabDeckSpec[];
