// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuAlwaysTwo = {
  title: "Always Two",
  cost: 4,
  text: "Choose 2 friendly <uq> Sith units. If you do, give 2 Shield tokens and 2 Experience tokens to each chosen unit. Defeat all other friendly units.",
  unique: false,
  id: "0463147975",
  rarity: "legendary",
  aspects: ["vigilance", "villainy"],
  traits: ["sith"],
  types: ["event"],
  setId: {
    set: "LOF",
    number: 42,
  },
  setCodes: [
    {
      set: "LOF",
      number: 42,
    },
  ],
  internalName: "always-two",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Choose 2 friendly <uq> Sith units. If you do, give 2 Shield tokens and 2 Experience tokens to each chosen unit. Defeat all other friendly units.",
      effects: [
        effect.ifYouDo(
          effect.createToken(
            "shield",
            2,
            target.unit({ controller: "friendly", traits: ["sith"], limit: 2 }),
          ),
          [
            effect.distribute(
              "experience",
              target.unit({ controller: "friendly", traits: ["sith"], limit: 2 }),
              2,
            ),
            effect.defeat(target.unit({ controller: "friendly", withoutTraits: ["sith"] })),
          ],
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuAlwaysTwo;
