// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";

export const swuConsumedByTheDarkSide = {
  title: "Consumed by the Dark Side",
  cost: 2,
  text: "Give 2 Experience tokens to a unit, then deal 2 damage to it.",
  unique: false,
  id: "8621390428",
  rarity: "common",
  aspects: ["villainy"],
  traits: ["force"],
  types: ["event"],
  setId: {
    set: "LOF",
    number: 239,
  },
  setCodes: [
    {
      set: "LOF",
      number: 239,
    },
  ],
  internalName: "consumed-by-the-dark-side",
  cardType: "event",
  canonicalId: "consumed-by-the-dark-side",
  slug: "consumed-by-the-dark-side",
  name: "Consumed by the Dark Side",
  printings: [
    {
      id: "LOF_239",
      artId: "28219",
      setCode: "LOF",
      collectorNumber: "239",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05010239_EN_Consumed_by_the_Dark_Side_3ead6a2df3.png",
    },
    {
      id: "1464873524",
      artId: "28219",
      setCode: "LOF",
      collectorNumber: "503",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05020503_EN_Consumed_by_the_Dark_Side_676a91a5a2.png",
    },
    {
      id: "6749331334",
      artId: "28219",
      setCode: "LOF",
      collectorNumber: "741",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05310741_EN_Consumed_by_the_Dark_Side_e1290512b5.png",
    },
    {
      id: "8515216992",
      artId: "28219",
      setCode: "LOF",
      collectorNumber: "979",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05320979_EN_Consumed_by_the_Dark_Side_b3c67b4031.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "Give 2 Experience tokens to a unit, then deal 2 damage to it.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "distribute",
          mode: "experience",
          amount: 2,
          target: {
            type: "card",
            controller: "any",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            excludeSelf: false,
            limit: 1,
          },
        },
      ],
    },
  ],
} satisfies SwuEventCard;

export default swuConsumedByTheDarkSide;
