// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuFlightOfTheInquisitor = {
  title: "Flight of the Inquisitor",
  cost: 2,
  text: "You may return a Force unit and a Lightsaber upgrade from your discard pile to your hand.",
  unique: false,
  id: "1393713161",
  rarity: "uncommon",
  aspects: ["villainy"],
  traits: ["tactic"],
  types: ["event"],
  setId: {
    set: "LOF",
    number: 240,
  },
  setCodes: [
    {
      set: "LOF",
      number: 240,
    },
  ],
  internalName: "flight-of-the-inquisitor",
  cardType: "event",
  canonicalId: "flight-of-the-inquisitor",
  slug: "flight-of-the-inquisitor",
  name: "Flight of the Inquisitor",
  printings: [
    {
      id: "LOF_240",
      artId: "28224",
      setCode: "LOF",
      collectorNumber: "240",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05010240_EN_Flight_of_the_Inquisitor_bc6aab565c.png",
    },
    {
      id: "2844757936",
      artId: "28224",
      setCode: "LOF",
      collectorNumber: "504",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05020504_EN_Flight_of_the_Inquisitor_dadcd4b791.png",
    },
    {
      id: "5517871944",
      artId: "28224",
      setCode: "LOF",
      collectorNumber: "742",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05310742_EN_Flight_of_the_Inquisitor_0dd3165f57.png",
    },
    {
      id: "4126632717",
      artId: "28224",
      setCode: "LOF",
      collectorNumber: "980",
      rarity: "uncommon",
      imageUrl:
        "https://cdn.starwarsunlimited.com//05320980_EN_Flight_of_the_Inquisitor_572c4d3a57.png",
    },
  ],
  abilities: [
    ability.action({
      text: "You may return a Force unit and a Lightsaber upgrade from your discard pile to your hand.",
      optional: true,
      effects: [
        effect.move(
          target.unit({ controller: "friendly", zones: ["discard"], traits: ["force"], limit: 1 }),
          "hand",
        ),
        effect.move(
          target.card({
            controller: "friendly",
            zones: ["discard"],
            cardTypes: ["upgrade"],
            traits: ["lightsaber"],
            limit: 1,
          }),
          "hand",
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuFlightOfTheInquisitor;
