// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuForceSpeed = {
  title: "Force Speed",
  cost: 1,
  text: "Attack with a unit. For this attack, it gains: “On Attack: Return any number of non-<uq> (non-unique) upgrades attached to the defender to their owners' hands.”",
  unique: false,
  rules:
    "If you play Forse Speed, you must attack with a unit, if able. Units must be ready in order to attack.\n",
  id: "6551214763",
  rarity: "uncommon",
  aspects: ["cunning", "cunning"],
  traits: ["force"],
  types: ["event"],
  setId: {
    set: "LOF",
    number: 205,
  },
  setCodes: [
    {
      set: "LOF",
      number: 205,
    },
  ],
  internalName: "force-speed",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Attack with a unit. For this attack, it gains: “On Attack: Return any number of non-unique upgrades attached to the defender to their owners' hands.”",
      effects: [
        effect.attack({
          attacker: target.unit({ controller: "friendly", limit: 1 }),
          defender: target.base("opponent"),
        }),
        effect.move(
          target.card({ controller: "opponent", cardTypes: ["upgrade"], unique: false }),
          "hand",
        ),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuForceSpeed;
