// Generated by tools/import-card-data. Do not edit manually.
import type { SwuEventCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuLuminousBeings = {
  title: "Luminous Beings",
  cost: 6,
  text: "Put up to 3 Force units from your discard pile on the bottom of your deck in a random order. Give that many units +4/+4 for this phase.",
  unique: false,
  id: "6801641285",
  rarity: "rare",
  aspects: ["command", "heroism"],
  traits: ["force"],
  types: ["event"],
  setId: {
    set: "LOF",
    number: 104,
  },
  setCodes: [
    {
      set: "LOF",
      number: 104,
    },
  ],
  internalName: "luminous-beings",
  cardType: "event",
  abilities: [
    ability.action({
      text: "Put up to 3 Force units from your discard pile on the bottom of your deck in a random order. Give that many units +4/+4 for this phase.",
      effects: [
        effect.sequential([
          effect.reorder(
            target.unit({
              controller: "friendly",
              zones: ["discard"],
              traits: ["force"],
              limit: 1,
            }),
            "bottomOfDeck",
            "random",
          ),
          effect.modifyStats(target.unit({ controller: "friendly", limit: 1 }), {
            power: 4,
            hp: 4,
            duration: "phase",
          }),
        ]),
      ],
    }),
  ],
} satisfies SwuEventCard;

export default swuLuminousBeings;
