import type { UnitCard } from "@tcg/gundam-types";

export const st06GaiaSRickDomGq003: UnitCard = {
  cardNumber: "ST06-003",
  name: "Gaia's Rick Dom (GQ)",
  type: "unit",
  color: "red",
  traits: ["clan"],
  id: "ST06-003",
  externalId: "gundam:st06-003",
  slug: "gaia-s-rick-dom-gq-st06-003",
  displayName: "Gaia's Rick Dom (GQ)",
  set: { code: "ST06", name: "Clan Unity [ST06]", packageId: "616006" },
  printNumber: "ST06-003",
  printings: [
    {
      id: "ST06-003",
      collectorNumber: "ST06-003",
      cardNumber: "ST06-003",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06]",
        packageId: "616006",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-003.webp?260424",
      productName: "Clan Unity [ST06]",
    },
    {
      id: "ST06-003_p1",
      collectorNumber: "ST06-003_p1",
      cardNumber: "ST06-003",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06] Bonus Pack",
        packageId: "616006",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-003_p1.webp?260424",
      productName: "Clan Unity [ST06] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST06-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-003.webp?260424",
  legality: "legal",
  level: 2,
  cost: 2,
  ap: 2,
  hp: 2,
  effect:
    "【Activate･Main】&lt;Support 1&gt; (Rest this Unit. 1 other friendly Unit gets AP+(specified amount) during this turn.)<br>",
  keywordEffects: [{ keyword: "Support", value: 1 }],
  rarity: "common",
};
