import type { UnitCard } from "@tcg/gundam-types";

export const st06GelgoogGq004: UnitCard = {
  cardNumber: "ST06-004",
  name: "Gelgoog (GQ)",
  type: "unit",
  color: "red",
  traits: ["zeon"],
  id: "ST06-004",
  externalId: "gundam:st06-004",
  slug: "gelgoog-gq-st06-004",
  displayName: "Gelgoog (GQ)",
  set: { code: "ST06", name: "Clan Unity [ST06]", packageId: "616006" },
  printNumber: "ST06-004",
  printings: [
    {
      id: "ST06-004",
      collectorNumber: "ST06-004",
      cardNumber: "ST06-004",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06]",
        packageId: "616006",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-004.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-004.webp?260424",
      productName: "Clan Unity [ST06]",
    },
    {
      id: "ST06-004_p1",
      collectorNumber: "ST06-004_p1",
      cardNumber: "ST06-004",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06] Bonus Pack",
        packageId: "616006",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-004_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-004_p1.webp?260424",
      productName: "Clan Unity [ST06] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST06-004",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-004.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-004.webp?260424",
  legality: "legal",
  level: 2,
  cost: 1,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
