import type { UnitCard } from "@tcg/gundam-types";

export const st06RedGundam006: UnitCard = {
  cardNumber: "ST06-006",
  name: "Red Gundam",
  type: "unit",
  color: "green",
  traits: ["clan"],
  id: "ST06-006",
  externalId: "gundam:st06-006",
  slug: "red-gundam-st06-006",
  displayName: "Red Gundam",
  set: { code: "ST06", name: "Clan Unity [ST06]", packageId: "616006" },
  printNumber: "ST06-006",
  printings: [
    {
      id: "ST06-006",
      collectorNumber: "ST06-006",
      cardNumber: "ST06-006",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06]",
        packageId: "616006",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-006.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-006.webp?260424",
      productName: "Clan Unity [ST06]",
    },
    {
      id: "ST06-006_p1",
      collectorNumber: "ST06-006_p1",
      cardNumber: "ST06-006",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06] Bonus Pack",
        packageId: "616006",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-006_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-006_p1.webp?260424",
      productName: "Clan Unity [ST06] Bonus Pack",
    },
    {
      id: "ST06-006_p2",
      collectorNumber: "ST06-006_p2",
      cardNumber: "ST06-006",
      set: {
        code: "ST06",
        name: "Boost Kit 01",
        packageId: "616901",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-006_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-006_p2.webp?260424",
      productName: "Boost Kit 01",
    },
  ],
  selectedPrintingId: "ST06-006",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-006.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-006.webp?260424",
  legality: "legal",
  level: 4,
  cost: 2,
  ap: 3,
  hp: 4,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
