import type { UnitCard } from "@tcg/gundam-types";

export const st06SugaiSGelgoogGq008: UnitCard = {
  cardNumber: "ST06-008",
  name: "Sugai's Gelgoog (GQ)",
  type: "unit",
  color: "green",
  traits: ["clan"],
  id: "ST06-008",
  externalId: "gundam:st06-008",
  slug: "sugai-s-gelgoog-gq-st06-008",
  displayName: "Sugai's Gelgoog (GQ)",
  set: { code: "ST06", name: "Clan Unity [ST06]", packageId: "616006" },
  printNumber: "ST06-008",
  printings: [
    {
      id: "ST06-008",
      collectorNumber: "ST06-008",
      cardNumber: "ST06-008",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06]",
        packageId: "616006",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-008.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-008.webp?260424",
      productName: "Clan Unity [ST06]",
    },
    {
      id: "ST06-008_p1",
      collectorNumber: "ST06-008_p1",
      cardNumber: "ST06-008",
      set: {
        code: "ST06",
        name: "Clan Unity [ST06] Bonus Pack",
        packageId: "616006",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-008_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-008_p1.webp?260424",
      productName: "Clan Unity [ST06] Bonus Pack",
    },
  ],
  selectedPrintingId: "ST06-008",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/st06/ST06-008.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/ST06-008.webp?260424",
  legality: "legal",
  level: 3,
  cost: 2,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
