import type {
  AnimationStepV2,
  AnimationEntityRef,
  SceneTrack,
  EffectStepV2,
} from "@tcg/protocol/animations";
import type { CinematicRecipe } from "./cinematic-recipes";
const source = { kind: "entity", id: "cinematic-source" } as const;
const target = { kind: "entity", id: "cinematic-target" } as const;
const other = { kind: "entity", id: "cinematic-other" } as const;
const from = { kind: "zone", id: "cinematic-origin" } as const;
const to = { kind: "zone", id: "cinematic-destination" } as const;
const discard = { kind: "zone", id: "cinematic-discard" } as const;
const board = { kind: "anchor", id: "cinematic-board" } as const;
const gold = "#e0b967",
  teal = "#78d8c2",
  red = "#ef927e";
const pSource = { ref: source },
  pTarget = { ref: target };
function scene(id: string, tracks: SceneTrack[], durationMs = 3200): EffectStepV2 {
  return {
    id,
    type: "effect",
    showText: false,
    durationMs,
    source,
    targets: [target, other],
    scene: { board, tracks },
  };
}
function background(pattern: "sky" | "grid" | "mist" | "embers" = "sky"): SceneTrack {
  return {
    id: "backdrop",
    kind: "backdrop",
    begin: 0,
    end: 1,
    color: "#17263b",
    accent: teal,
    pattern,
    opacity: 0.55,
  };
}
function burst(at = pTarget, color = gold, begin = 0.55): SceneTrack {
  return {
    id: "impact",
    kind: "particles",
    begin,
    end: Math.min(0.95, begin + 0.2),
    at,
    color,
    count: 32,
    spread: 0.25,
    motion: "burst",
    seed: 17,
  };
}
function recoil(begin = 0.56, at = target): SceneTrack {
  return {
    id: "recoil",
    kind: "reaction",
    at,
    begin,
    end: begin + 0.1,
    motion: "recoil",
    strength: 1,
  };
}
function exit(entity: AnimationEntityRef = target, startAtMs = 2500): AnimationStepV2 {
  return {
    id: `exit:${entity.id}`,
    type: "entityTransfer",
    entity,
    from: entity,
    to: discard,
    sourceFace: "public",
    destinationFace: "public",
    sourcePresentation: "hold",
    startAtMs,
    durationMs: 600,
  };
}
const val: AnimationStepV2 = {
  id: "value",
  type: "valueDelta",
  subject: target,
  delta: -5,
  fromValue: 8,
  toValue: 3,
  startAtMs: 1800,
  durationMs: 900,
  tone: "negative",
};
export const SCENE_RECIPES: readonly CinematicRecipe[] = [
  {
    id: "scene-breath",
    title: "Environment → actor → breath → burn → exit",
    category: "Complete scenes",
    description:
      "Original winged construct, environment buildup, curved breath, card burn and discard handoff.",
    exited: [target.id],
    steps: [
      scene("breath", [
        background("embers"),
        {
          id: "wing",
          kind: "actor",
          asset: "wing",
          color: gold,
          begin: 0.08,
          end: 0.9,
          from: { x: 0.85, y: 0.1 },
          to: { x: 0.72, y: 0.3 },
          size: 0.4,
          rotation: 20,
          motion: "rear",
        },
        {
          id: "gather",
          kind: "particles",
          begin: 0.1,
          end: 0.32,
          at: { x: 0.72, y: 0.3 },
          color: gold,
          count: 36,
          spread: 0.35,
          motion: "converge",
          seed: 4,
        },
        {
          id: "breath-path",
          kind: "travel",
          begin: 0.3,
          end: 0.56,
          from: { x: 0.72, y: 0.3 },
          to: pTarget,
          path: "arc",
          color: gold,
          count: 18,
          stagger: 0.4,
          trail: true,
          shape: "orb",
        },
        burst(),
        recoil(),
        {
          id: "burn",
          kind: "material",
          begin: 0.57,
          end: 0.79,
          at: target,
          treatment: "burn",
          color: red,
        },
        { id: "camera", kind: "camera", begin: 0.55, end: 0.64, motion: "shake", strength: 1 },
      ]),
      exit(),
    ],
  },
  {
    id: "scene-resonance",
    title: "Gather → travelling rings → cracks → exit",
    category: "Complete scenes",
    description: "A directed sonic sequence with synchronized recoil, cracks, spray and removal.",
    exited: [target.id],
    steps: [
      scene("resonance", [
        background("mist"),
        {
          id: "gather",
          kind: "particles",
          begin: 0.05,
          end: 0.3,
          at: pSource,
          color: teal,
          count: 48,
          spread: 0.35,
          motion: "converge",
          seed: 3,
        },
        {
          id: "rings",
          kind: "travel",
          begin: 0.3,
          end: 0.57,
          from: pSource,
          to: pTarget,
          path: "straight",
          color: teal,
          count: 6,
          stagger: 0.3,
          trail: true,
          shape: "ring",
        },
        burst(pTarget, teal),
        recoil(),
        {
          id: "crack",
          kind: "material",
          begin: 0.55,
          end: 0.78,
          at: target,
          treatment: "cracks",
          color: teal,
        },
        {
          id: "shock",
          kind: "area",
          begin: 0.57,
          end: 0.8,
          color: teal,
          motion: "wave",
          direction: "left",
        },
      ]),
      exit(),
    ],
  },
  {
    id: "scene-wipe",
    title: "Full-board sweep → ordered discard",
    category: "Complete scenes",
    description:
      "A clipped board-wide wave removes both targets in order while retained clones preserve their identities.",
    exited: [target.id, other.id],
    steps: [
      scene(
        "wipe",
        [
          background("mist"),
          {
            id: "sweep",
            kind: "area",
            begin: 0.15,
            end: 0.7,
            color: teal,
            motion: "sweep",
            direction: "left",
          },
          burst(pTarget, teal, 0.5),
        ],
        2800,
      ),
      exit(target, 1900),
      exit(other, 2200),
    ],
  },
  {
    id: "scene-volley",
    title: "Backdrop → counted volley → impact → counter",
    category: "Complete scenes",
    description:
      "Exactly five arrows travel on a ballistic arc; one impact beat drives reaction and value feedback.",
    steps: [
      scene("volley", [
        background(),
        {
          id: "cannon",
          kind: "actor",
          asset: "cannon",
          color: gold,
          begin: 0.05,
          end: 0.85,
          from: { x: -0.1, y: 0.7 },
          to: { x: 0.2, y: 0.68 },
          size: 0.25,
          rotation: 0,
          motion: "glide",
        },
        {
          id: "arrows",
          kind: "travel",
          begin: 0.22,
          end: 0.56,
          from: pSource,
          to: pTarget,
          path: "arc",
          color: gold,
          count: 5,
          stagger: 0.35,
          trail: true,
          shape: "arrow",
        },
        burst(),
        recoil(),
        {
          id: "flash",
          kind: "material",
          begin: 0.56,
          end: 0.66,
          at: target,
          treatment: "flash",
          color: gold,
        },
      ]),
      val,
    ],
  },
  {
    id: "scene-orbit",
    title: "Orbit scan → hit → return stream → recovery",
    category: "Complete scenes",
    description:
      "Discs orbit the target before a reverse stream returns to the source and grants a resolved value.",
    steps: [
      scene("orbit", [
        background("grid"),
        {
          id: "discs",
          kind: "travel",
          begin: 0.08,
          end: 0.5,
          from: pSource,
          to: pTarget,
          path: "orbit",
          color: teal,
          count: 3,
          stagger: 0.2,
          trail: true,
          shape: "disc",
        },
        burst(pTarget, teal, 0.48),
        {
          id: "return",
          kind: "travel",
          begin: 0.58,
          end: 0.85,
          from: pTarget,
          to: pSource,
          path: "arc",
          color: gold,
          count: 12,
          stagger: 0.4,
          trail: true,
          shape: "orb",
        },
        {
          id: "heal",
          kind: "material",
          begin: 0.85,
          end: 1,
          at: source,
          treatment: "heal",
          color: teal,
        },
      ]),
      {
        ...val,
        id: "recovered",
        subject: source,
        delta: 3,
        tone: "positive",
        fromValue: 2,
        toValue: 5,
        startAtMs: 2720,
      },
    ],
  },
  ...[1, 2, 3, 4].map((weight): CinematicRecipe => ({
    id: `scene-landing-${weight}`,
    title: `Weighted landing: tier ${weight}`,
    category: "Landing and stacks",
    description: "Travel, lift/drop, compression, bounce, dust and shadow use separate tracks.",
    moved: true,
    steps: [
      {
        id: "travel",
        type: "entityTransfer",
        entity: source,
        from,
        to,
        sourceFace: "public",
        destinationFace: "public",
        durationMs: 460,
      },
      scene(
        "landing",
        [
          {
            id: "land",
            kind: "reaction",
            begin: 0.2,
            end: 0.5,
            at: source,
            motion: "landing",
            strength: weight,
          },
          {
            id: "dust",
            kind: "particles",
            begin: 0.36,
            end: 0.63,
            at: { ref: to },
            color: gold,
            count: 12 * weight,
            spread: 0.1 * weight,
            motion: "dust",
            seed: weight,
          },
        ],
        2500,
      ),
    ],
  })),
  {
    id: "scene-legend",
    title: "Large reveal → ring → return",
    category: "Landing and stacks",
    description:
      "The original card is lifted and turned; a board-local ring peaks during the reveal, then all layers return.",
    steps: [
      scene("legend", [
        background(),
        {
          id: "reveal",
          kind: "reaction",
          begin: 0.1,
          end: 0.78,
          at: source,
          motion: "reveal",
          strength: 2,
        },
        {
          id: "ring",
          kind: "area",
          begin: 0.28,
          end: 0.78,
          color: gold,
          motion: "wave",
          direction: "left",
        },
        {
          id: "sparkles",
          kind: "particles",
          begin: 0.25,
          end: 0.72,
          at: pSource,
          color: gold,
          count: 40,
          spread: 0.3,
          motion: "rise",
          seed: 19,
        },
      ]),
    ],
  },
  {
    id: "scene-dice",
    title: "Die throw → tumble → bounce → settled result",
    category: "Complete scenes",
    description:
      "An original die throws with a shadow and settles on the authoritative value four.",
    steps: [
      scene("dice", [
        background("grid"),
        {
          id: "die",
          kind: "die",
          begin: 0.05,
          end: 0.72,
          from: { x: 0.1, y: 0.9 },
          to: { x: 0.5, y: 0.5 },
          value: 4,
          color: gold,
          size: 0.16,
        },
      ]),
      {
        id: "result",
        type: "randomization",
        kind: "die",
        at: board,
        resultLabel: "4",
        startAtMs: 2300,
        durationMs: 900,
      },
    ],
  },
  {
    id: "scene-freeze",
    title: "Cold front → snow → freeze → thaw",
    category: "Materials",
    description:
      "The target image itself changes during the effect, then restores its original appearance.",
    steps: [
      scene("freeze", [
        background("mist"),
        {
          id: "cold",
          kind: "travel",
          begin: 0.1,
          end: 0.4,
          from: { x: 1.1, y: 0.2 },
          to: pTarget,
          path: "zigzag",
          color: teal,
          count: 8,
          stagger: 0.3,
          trail: true,
          shape: "orb",
        },
        {
          id: "snow",
          kind: "particles",
          begin: 0.35,
          end: 0.85,
          at: pTarget,
          color: "#d9f3ff",
          count: 64,
          spread: 0.4,
          motion: "snow",
          seed: 24,
        },
        {
          id: "frozen",
          kind: "material",
          begin: 0.4,
          end: 0.95,
          at: target,
          treatment: "freeze",
          color: teal,
        },
      ]),
    ],
  },
  ...(["stone", "dissolve", "glitch", "shield", "heal"] as const).map(
    (treatment): CinematicRecipe => ({
      id: `scene-material-${treatment}`,
      title: `Card image: ${treatment}`,
      category: "Materials",
      description:
        "Timed treatment of the actual card surface, framed by buildup, particles and cleanup.",
      steps: [
        scene(treatment, [
          background(treatment === "glitch" ? "grid" : "mist"),
          {
            id: "buildup",
            kind: "particles",
            begin: 0,
            end: 0.3,
            at: pTarget,
            color: teal,
            count: 24,
            spread: 0.2,
            motion: "converge",
            seed: 7,
          },
          {
            id: "surface",
            kind: "material",
            begin: 0.3,
            end: 0.86,
            at: target,
            treatment,
            color: teal,
          },
          burst(pTarget, teal, 0.6),
        ]),
      ],
    }),
  ),
  {
    id: "scene-strike",
    title: "Anticipation → lunge → contact → return",
    category: "Complete scenes",
    description:
      "A 485 ms card strike has 150/140/75/120 ms beats, target recoil, flash and camera contact.",
    steps: [
      scene(
        "strike",
        [
          {
            id: "lunge",
            kind: "reaction",
            begin: 0,
            end: 1,
            at: source,
            toward: target,
            motion: "lunge",
            strength: 1,
          },
          {
            id: "recoil",
            kind: "reaction",
            begin: 290 / 485,
            end: 1,
            at: target,
            motion: "recoil",
            strength: 1,
          },
          {
            id: "contact",
            kind: "material",
            begin: 290 / 485,
            end: 365 / 485,
            at: target,
            treatment: "flash",
            color: gold,
          },
          {
            id: "camera-contact",
            kind: "camera",
            begin: 290 / 485,
            end: 365 / 485,
            motion: "shake",
            strength: 0.5,
          },
          {
            id: "stop",
            kind: "reaction",
            begin: 290 / 485,
            end: 365 / 485,
            at: target,
            motion: "hitstop",
            strength: 1,
          },
        ],
        485,
      ),
    ],
  },
  ...(["zoom", "pixel", "shake"] as const).map((motion): CinematicRecipe => ({
    id: `scene-camera-${motion}`,
    title: `Board camera: ${motion}`,
    category: "Camera",
    description: "A bounded treatment of the real board, with environment entrance and exit.",
    steps: [
      scene(motion, [
        background("grid"),
        { id: "camera", kind: "camera", begin: 0.25, end: 0.7, motion, strength: 1.5 },
      ]),
    ],
  })),
  {
    id: "scene-snapback",
    title: "Invalid release → snapback → settle",
    category: "Movement",
    description: "Temporary displacement returns the source card to its registered slot.",
    steps: [
      scene(
        "snapback",
        [
          {
            id: "return",
            kind: "reaction",
            begin: 0,
            end: 1,
            at: source,
            motion: "snapback",
            strength: 1,
          },
        ],
        600,
      ),
    ],
  },
];
