// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuKcmMiningFacility = {
  title: "KCM Mining Facility",
  hp: 30,
  unique: false,
  id: "0109520913",
  rarity: "common",
  aspects: ["aggression"],
  types: ["base"],
  setId: {
    set: "TWI",
    number: 26,
  },
  setCodes: [
    {
      set: "TWI",
      number: 26,
    },
  ],
  internalName: "kcm-mining-facility",
  cardType: "base",
} satisfies SwuBaseCard;

export default swuKcmMiningFacility;
