// Generated by tools/import-card-data. Do not edit manually.
import type { SwuBaseCard } from "@tcg/star-wars-unlimited-types";

export const swuTipocaCity = {
  title: "Tipoca City",
  hp: 30,
  unique: false,
  id: "0348855629",
  rarity: "common",
  aspects: ["command"],
  types: ["base"],
  setId: {
    set: "TWI",
    number: 24,
  },
  setCodes: [
    {
      set: "TWI",
      number: 24,
    },
  ],
  internalName: "tipoca-city",
  cardType: "base",
} satisfies SwuBaseCard;

export default swuTipocaCity;
