import type { CardEffect, PilotCard } from "@tcg/gundam-types";

export const gd01DuoMaxwell090: PilotCard = {
  cardNumber: "GD01-090",
  name: "Duo Maxwell",
  type: "pilot",
  color: "green",
  traits: ["operation meteor"],
  id: "GD01-090",
  externalId: "gundam:gd01-090",
  slug: "duo-maxwell-gd01-090",
  displayName: "Duo Maxwell",
  set: { code: "GD01", name: "Newtype Rising [GD01]", packageId: "616101" },
  printNumber: "GD01-090",
  printings: [
    {
      id: "GD01-090",
      collectorNumber: "GD01-090",
      cardNumber: "GD01-090",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "rare",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-090.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-090.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-090_p1",
      collectorNumber: "GD01-090_p1",
      cardNumber: "GD01-090",
      set: {
        code: "GD01",
        name: "Newtype Rising [GD01]",
        packageId: "616101",
      },
      rarity: "rare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-090_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-090_p1.webp?260424",
      productName: "Newtype Rising [GD01]",
    },
    {
      id: "GD01-090_p2",
      collectorNumber: "GD01-090_p2",
      cardNumber: "GD01-090",
      set: {
        code: "GD01",
        name: "Store Tournament Participant Pack 01",
        packageId: "616901",
      },
      rarity: "rare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-090_p2.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-090_p2.webp?260424",
      productName: "Store Tournament Participant Pack 01",
    },
    {
      id: "GD01-090_p3",
      collectorNumber: "GD01-090_p3",
      cardNumber: "GD01-090",
      set: {
        code: "GD01",
        name: "Store Tournament Winner Pack 01",
        packageId: "616901",
      },
      rarity: "rare",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-090_p3.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-090_p3.webp?260424",
      productName: "Store Tournament Winner Pack 01",
    },
  ],
  selectedPrintingId: "GD01-090",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/gd01/GD01-090.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/GD01-090.webp?260424",
  legality: "legal",
  level: 4,
  cost: 1,
  apBonus: 1,
  hpBonus: 2,
  effect:
    "【Burst】Add this card to your hand.<br>【During Link】This Unit's AP can't be reduced by enemy effects.<br>",
  effects: [
    {
      type: "triggered",
      activation: { timing: ["burst"] },
      directives: [{ action: { action: "addSelfToHand" } }],
      sourceText: "【Burst】Add this card to your hand.",
    },
    {
      type: "constant",
      activation: { conditions: [{ type: "duringLink" }] },
      directives: [
        {
          action: {
            action: "preventStatReduction",
            stat: "ap",
            target: { owner: "self" },
            source: "enemy",
          },
        },
      ],
      sourceText: "【During Link】This Unit's AP can't be reduced by enemy effects.",
    },
  ] as CardEffect[],
  keywordEffects: [],
  rarity: "rare",
};
