name: CI
on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]
jobs:
  build:
    name: Build, Type Check, Format, Lint, and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      BUN_INSTALL_CACHE_DIR: ~/.bun/install/cache
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Cache the Bun global cache directory
      # - name: Cache Bun dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.bun/install/cache
      #       node_modules/.cache
      #     key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bun-

      # Cache all Turbo folders for reusing build artifacts
      # - name: Cache all Turbo folders
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       .turbo
      #       **/node_modules/.cache/turbo
      #       **/.turbo
      #     key: ${{ runner.os }}-turbo-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-turbo-

      # Use hardlink backend for faster installation
      - name: Install dependencies
        run: bun install --backend=hardlink --frozen-lockfile

      - name: Run format
        run: bun run format

      - name: Run type checking
        run: bun run check-types

      - name: Run tests
        run: bun run test
