// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuB1AttackPlatform = {
  title: "B1 Attack Platform",
  cost: 3,
  hp: 2,
  power: 5,
  unique: false,
  id: "1313247160",
  rarity: "common",
  aspects: ["aggression", "villainy"],
  traits: ["separatist", "droid", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 133,
  },
  setCodes: [
    {
      set: "TWI",
      number: 133,
    },
  ],
  internalName: "b1-attack-platform",
  cardType: "unit",
  canonicalId: "b1-attack-platform",
  slug: "b1-attack-platform",
  name: "B1 Attack Platform",
  printings: [
    {
      id: "TWI_133",
      artId: "14851",
      setCode: "TWI",
      collectorNumber: "133",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301133_EN_B1_Attack_Platform_1cba259037.png",
    },
    {
      id: "9938200312",
      artId: "14851",
      setCode: "TWI",
      collectorNumber: "133",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0331133_EN_B1_Attack_Platform_e64e8ad764.png",
    },
    {
      id: "0824370922",
      artId: "14851",
      setCode: "TWI",
      collectorNumber: "401",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302401_EN_B1_Attack_Platform_2d77e858c5.png",
    },
    {
      id: "8773160569",
      artId: "14851",
      setCode: "TWI",
      collectorNumber: "401",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0332401_EN_B1_Attack_Platform_e27b16c9b1.png",
    },
  ],
} satisfies SwuUnitCard;

export default swuB1AttackPlatform;
