// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuB1SecurityTeam = {
  title: "B1 Security Team",
  cost: 2,
  hp: 1,
  power: 3,
  text: "Sentinel (Units in this arena can't attack your non-Sentinel units or your base.)",
  unique: false,
  id: "6257858302",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["separatist", "droid", "trooper"],
  arena: "ground",
  keywords: ["sentinel"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 207,
  },
  setCodes: [
    {
      set: "TWI",
      number: 207,
    },
  ],
  internalName: "b1-security-team",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
  ],
} satisfies SwuUnitCard;

export default swuB1SecurityTeam;
