// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuB2Legionnaires = {
  title: "B2 Legionnaires",
  cost: 5,
  hp: 4,
  power: 5,
  text: "Sentinel (Units in this arena can't attack your non-Sentinel units or your base.)\nOverwhelm (When attacking an enemy unit, deal excess damage to the opponent's base.)",
  unique: false,
  rules:
    "Shields prevent all damage from a unit with Overwhelm. There is no excess damage since the defender is not defeated.\nIf the defender is defeated during an attack before combat damage is dealt, all combat damage is considered excess damage for Overwhelm.\n",
  id: "6330903136",
  rarity: "common",
  aspects: ["command"],
  traits: ["separatist", "droid", "trooper"],
  arena: "ground",
  keywords: ["sentinel", "overwhelm"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 113,
  },
  setCodes: [
    {
      set: "TWI",
      number: 113,
    },
  ],
  internalName: "b2-legionnaires",
  cardType: "unit",
  canonicalId: "b2-legionnaires",
  slug: "b2-legionnaires",
  name: "B2 Legionnaires",
  printings: [
    {
      id: "TWI_113",
      artId: "14751",
      setCode: "TWI",
      collectorNumber: "113",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301113_EN_B2_Legionnaires_0a4b6af516.png",
    },
    {
      id: "8753305210",
      artId: "14751",
      setCode: "TWI",
      collectorNumber: "113",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0331113_EN_B2_Legionnaires_7eef7aca23.png",
    },
    {
      id: "6881272867",
      artId: "14751",
      setCode: "TWI",
      collectorNumber: "383",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302383_EN_B2_Legionnaires_0b57f2f11c.png",
    },
    {
      id: "9928388344",
      artId: "14751",
      setCode: "TWI",
      collectorNumber: "383",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0332383_EN_B2_Legionnaires_8b1ca9d396.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Sentinel",
      keyword: "sentinel",
    },
    {
      kind: "keyword",
      text: "Overwhelm",
      keyword: "overwhelm",
    },
  ],
} satisfies SwuUnitCard;

export default swuB2Legionnaires;
