// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuBarrissOffeeUnassumingApprentice = {
  title: "Barriss Offee",
  subtitle: "Unassuming Apprentice",
  cost: 1,
  hp: 1,
  power: 1,
  text: "Each friendly unit that was healed this phase gets +1/+0.",
  unique: true,
  id: "7924172103",
  rarity: "rare",
  aspects: ["vigilance", "heroism"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 42,
  },
  setCodes: [
    {
      set: "TWI",
      number: 42,
    },
  ],
  internalName: "barriss-offee#unassuming-apprentice",
  cardType: "unit",
  canonicalId: "barriss-offee#unassuming-apprentice",
  slug: "barriss-offee-unassuming-apprentice",
  name: "Barriss Offee",
  printings: [
    {
      id: "TWI_042",
      artId: "14411",
      setCode: "TWI",
      collectorNumber: "42",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301042_EN_Barriss_Offee_eeeecda964.png",
    },
    {
      id: "8861098409",
      artId: "14411",
      setCode: "TWI",
      collectorNumber: "42",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0331042_EN_Barriss_Offee_db57b6b091.png",
    },
    {
      id: "0378068103",
      artId: "14411",
      setCode: "TWI",
      collectorNumber: "315",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0332315_EN_Barriss_Offee_de887bba9b.png",
    },
    {
      id: "1011219594",
      artId: "14411",
      setCode: "TWI",
      collectorNumber: "315",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302315_EN_Barriss_Offee_b880ed6e21.png",
    },
  ],
  abilities: [
    ability.constant({
      text: "Each friendly unit that was healed this phase gets +1/+0.",
      effects: [effect.modifyStats(target.unit({ controller: "friendly" }), { power: 1 })],
    }),
  ],
} satisfies SwuUnitCard;

export default swuBarrissOffeeUnassumingApprentice;
