// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCaptainRexLeadByExample = {
  title: "Captain Rex",
  subtitle: "Lead by Example",
  cost: 6,
  hp: 4,
  power: 4,
  text: "When Played: Create 2 Clone Trooper tokens.",
  unique: true,
  id: "0511508627",
  rarity: "special",
  aspects: ["command", "heroism"],
  traits: ["republic", "clone", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 97,
  },
  setCodes: [
    {
      set: "TWI",
      number: 97,
    },
  ],
  internalName: "captain-rex#lead-by-example",
  cardType: "unit",
  canonicalId: "captain-rex#lead-by-example",
  slug: "captain-rex-lead-by-example",
  name: "Captain Rex",
  printings: [
    {
      id: "TWI_097",
      artId: "13995",
      setCode: "TWI",
      collectorNumber: "97",
      rarity: "special",
      imageUrl: "https://cdn.starwarsunlimited.com//0301097_EN_Captain_Rex_3ec03d8486.png",
    },
    {
      id: "1841169962",
      artId: "13995",
      setCode: "TWI",
      collectorNumber: "9",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302009_EN_Captain_Rex_1fcec01f1d.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: Create 2 Clone Trooper tokens.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "createToken",
          token: "cloneTrooper",
          amount: 2,
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuCaptainRexLeadByExample;
