// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuCloneDiveTrooper = {
  title: "Clone Dive Trooper",
  cost: 1,
  hp: 1,
  power: 2,
  text: "Coordinate — While this unit is attacking, the defender gets –2/–0. (Gain this ability while you control 3 or more units.)",
  unique: false,
  id: "5445166624",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["republic", "clone", "trooper"],
  arena: "ground",
  keywords: ["coordinate"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 205,
  },
  setCodes: [
    {
      set: "TWI",
      number: 205,
    },
  ],
  internalName: "clone-dive-trooper",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Coordinate",
      keyword: "coordinate",
    },
  ],
} satisfies SwuUnitCard;

export default swuCloneDiveTrooper;
