// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuDarthMaulRevengeAtLast = {
  title: "Darth Maul",
  subtitle: "Revenge At Last",
  cost: 5,
  hp: 6,
  power: 5,
  text: "This unit can attack 2 units instead of 1.  (This unit deals its combat damage to both defenders and they both deal their combat damage to this unit. All damage is dealt simultaneously.)",
  unique: true,
  rules:
    "If Darth Maul attacks two units instead of one, both units are considered defenders of one attack. Each step of the attack and any triggered abilities only occur once, as usual. Darth Maul deals combat damage equal to his power to both defenders, and both defenders deal combat damage to Darth Maul. All combat damage is dealt simultaneously.\nDarth Maul may not attack a base and a unit simultaneously.\nIf Darth Maul has Overwhelm, he may deal damage to the defending player's base equal to the combined excess damage of his attack on both defenders.\nIf the defending player controls at least one unit with Sentinel, Darth Maul may only choose Sentinels as the defenders for his attack, unless he has Saboteur.\n",
  id: "8613680163",
  rarity: "legendary",
  aspects: ["aggression", "villainy"],
  traits: ["force", "sith"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 135,
  },
  setCodes: [
    {
      set: "TWI",
      number: 135,
    },
  ],
  internalName: "darth-maul#revenge-at-last",
  cardType: "unit",
  canonicalId: "darth-maul#revenge-at-last",
  slug: "darth-maul-revenge-at-last",
  name: "Darth Maul",
  printings: [
    {
      id: "TWI_135",
      artId: "14861",
      setCode: "TWI",
      collectorNumber: "135",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0301135_EN_Darth_Maul_e55c9f5f02.png",
    },
    {
      id: "8055041305",
      artId: "14861",
      setCode: "TWI",
      collectorNumber: "135",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0331135_EN_Darth_Maul_2b875f7b6e.png",
    },
    {
      id: "4695901435",
      artId: "14861",
      setCode: "TWI",
      collectorNumber: "403",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0332403_EN_Darth_Maul_592f4bbf63.png",
    },
    {
      id: "9955988380",
      artId: "14861",
      setCode: "TWI",
      collectorNumber: "403",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0302403_EN_Darth_Maul_3233df4aeb.png",
    },
  ],
  abilities: [
    ability.onAttack({
      text: "This unit can attack 2 units instead of 1.",
      effects: [effect.damage(target.unit({ controller: "opponent", limit: 2 }), 2)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuDarthMaulRevengeAtLast;
