// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuFinnOnTheRun = {
  title: "Finn",
  subtitle: "On the Run",
  cost: 3,
  hp: 4,
  power: 3,
  text: "When this unit completes an attack: Choose a unique unit. For this phase, if damage would be dealt to that unit, prevent 1 of that damage.",
  unique: true,
  rules:
    "A unit must survive an attack to trigger its “when this unit completes an attack” abilities.\n",
  id: "7244268162",
  rarity: "rare",
  aspects: ["vigilance", "vigilance"],
  traits: ["fringe", "trooper"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 53,
  },
  setCodes: [
    {
      set: "TWI",
      number: 53,
    },
  ],
  internalName: "finn#on-the-run",
  cardType: "unit",
  canonicalId: "finn#on-the-run",
  slug: "finn-on-the-run",
  name: "Finn",
  printings: [
    {
      id: "TWI_053",
      artId: "14466",
      setCode: "TWI",
      collectorNumber: "53",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301053_EN_Finn_f83ea5e8d9.png",
    },
    {
      id: "5391372921",
      artId: "14466",
      setCode: "TWI",
      collectorNumber: "53",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0331053_EN_Finn_775f91ae01.png",
    },
    {
      id: "3543568972",
      artId: "14466",
      setCode: "TWI",
      collectorNumber: "326",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0332326_EN_Finn_8628ec805d.png",
    },
    {
      id: "8086858751",
      artId: "14466",
      setCode: "TWI",
      collectorNumber: "326",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302326_EN_Finn_71b6022a23.png",
    },
  ],
  abilities: [
    ability.triggered(
      { event: "attackEnds" },
      {
        text: "When this unit completes an attack: Choose a unique unit. For this phase, if damage would be dealt to that unit, prevent 1 of that damage.",
        effects: [
          effect.preventDamage(target.unit({ controller: "any", unique: true, limit: 1 }), "phase"),
        ],
      },
    ),
  ],
} satisfies SwuUnitCard;

export default swuFinnOnTheRun;
