// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuGeonosisPatrolFighter = {
  title: "Geonosis Patrol Fighter",
  cost: 5,
  hp: 2,
  power: 3,
  text: "Exploit 2 (While playing this card, defeat up to 2 units you control. This card costs 2 resources less for each unit defeated this way.)\nWhen Played: You may return a non-leader unit that costs 3 or less to its owner's hand.",
  unique: false,
  rules:
    "Abilities that refer to a card's cost always refer to its printed cost, regardless of modifiers.\nAbilities that return a card to hand must choose a card in play unless otherwise specified.\n",
  id: "3348783048",
  rarity: "common",
  aspects: ["cunning"],
  traits: ["separatist", "vehicle", "fighter"],
  arena: "space",
  keywords: ["exploit"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 215,
  },
  setCodes: [
    {
      set: "TWI",
      number: 215,
    },
  ],
  internalName: "geonosis-patrol-fighter",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Exploit",
      keyword: "exploit",
    },
    {
      kind: "triggered",
      text: "When Played: You may return a non-leader unit that costs 3 or less to its owner's hand.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "move",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
              to: "hand",
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuGeonosisPatrolFighter;
