// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuHeavyPersuaderTank = {
  title: "Heavy Persuader Tank",
  cost: 7,
  hp: 5,
  power: 6,
  text: "Exploit 2 (While playing this card, defeat up to 2 units you control. This card costs 2 resources less for each unit defeated this way.)\nWhen Played: You may deal 2 damage to a ground unit.",
  unique: false,
  id: "4210027426",
  rarity: "common",
  aspects: ["aggression"],
  traits: ["separatist", "droid", "vehicle", "tank"],
  arena: "ground",
  keywords: ["exploit"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 167,
  },
  setCodes: [
    {
      set: "TWI",
      number: 167,
    },
  ],
  internalName: "heavy-persuader-tank",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Exploit",
      keyword: "exploit",
    },
    {
      kind: "triggered",
      text: "When Played: You may deal 2 damage to a ground unit.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "damage",
              amount: 2,
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                arena: "ground",
                excludeSelf: false,
                limit: 1,
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuHeavyPersuaderTank;
