// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuKiadimundiComposedAndConfident = {
  title: "Ki-Adi-Mundi",
  subtitle: "Composed and Confident",
  cost: 5,
  hp: 7,
  power: 5,
  text: "Coordinate — When an opponent plays their second card each phase: You may draw 2 cards.",
  unique: true,
  id: "7200475001",
  rarity: "legendary",
  aspects: ["vigilance"],
  traits: ["force", "jedi", "republic"],
  arena: "ground",
  keywords: ["coordinate"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 64,
  },
  setCodes: [
    {
      set: "TWI",
      number: 64,
    },
  ],
  internalName: "kiadimundi#composed-and-confident",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Coordinate",
      keyword: "coordinate",
    },
  ],
} satisfies SwuUnitCard;

export default swuKiadimundiComposedAndConfident;
