// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuObedientVanguard = {
  title: "Obedient Vanguard",
  cost: 1,
  hp: 1,
  power: 1,
  text: "Raid 1 (This unit gets +1/+0 while attacking.)\nWhen Defeated: You may give a Trooper unit +2/+2 for this phase.",
  unique: false,
  id: "0249398533",
  rarity: "common",
  aspects: ["command"],
  traits: ["separatist", "droid", "trooper"],
  arena: "ground",
  keywords: ["raid"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 104,
  },
  setCodes: [
    {
      set: "TWI",
      number: 104,
    },
  ],
  internalName: "obedient-vanguard",
  cardType: "unit",
  canonicalId: "obedient-vanguard",
  slug: "obedient-vanguard",
  name: "Obedient Vanguard",
  printings: [
    {
      id: "TWI_104",
      artId: "14711",
      setCode: "TWI",
      collectorNumber: "104",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301104_EN_Obedient_Vanguard_92c56eb95d.png",
    },
    {
      id: "7768612862",
      artId: "14711",
      setCode: "TWI",
      collectorNumber: "104",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0331104_EN_Obedient_Vanguard_8b2931014c.png",
    },
    {
      id: "5182164727",
      artId: "14711",
      setCode: "TWI",
      collectorNumber: "375",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0332375_EN_Obedient_Vanguard_37173930dd.png",
    },
    {
      id: "8974741727",
      artId: "14711",
      setCode: "TWI",
      collectorNumber: "375",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302375_EN_Obedient_Vanguard_5bdcaac51b.png",
    },
  ],
  abilities: [
    {
      kind: "keyword",
      text: "Raid",
      keyword: "raid",
    },
    {
      kind: "triggered",
      text: "When Defeated: You may give a Trooper unit +2/+2 for this phase.",
      trigger: {
        event: "defeated",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "modifyStats",
              target: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
              power: 2,
              hp: 2,
              duration: "phase",
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuObedientVanguard;
