// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers/index.ts";

export const swuPadawanStarfighter = {
  title: "Padawan Starfighter",
  cost: 2,
  hp: 3,
  power: 1,
  text: "While you control a Force unit or a Force upgrade, this unit gets +1/+1.",
  unique: false,
  rules: "Padawan Starfighter gets +1/+1 while you control a Force unit or a Force upgrade.\n",
  id: "4718895864",
  rarity: "common",
  aspects: ["vigilance"],
  traits: ["jedi", "republic", "vehicle", "fighter"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 58,
  },
  setCodes: [
    {
      set: "TWI",
      number: 58,
    },
    {
      set: "LOF",
      number: 60,
    },
  ],
  internalName: "padawan-starfighter",
  cardType: "unit",
  canonicalId: "padawan-starfighter",
  slug: "padawan-starfighter",
  name: "Padawan Starfighter",
  printings: [
    {
      id: "TWI_058",
      artId: "14491",
      setCode: "TWI",
      collectorNumber: "58",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301058_EN_Padawan_Starfighter_b52f316cc9.png",
    },
    {
      id: "LOF_060",
      artId: "14491",
      setCode: "LOF",
      collectorNumber: "60",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0301058_EN_Padawan_Starfighter_b52f316cc9.png",
    },
    {
      id: "7968116546",
      artId: "14491",
      setCode: "TWI",
      collectorNumber: "58",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0331058_EN_Padawan_Starfighter_c1c3323f9b.png",
    },
    {
      id: "3962462232",
      artId: "14491",
      setCode: "TWI",
      collectorNumber: "331",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0332331_EN_Padawan_Starfighter_50ae63a34f.png",
    },
    {
      id: "5454380041",
      artId: "14491",
      setCode: "TWI",
      collectorNumber: "331",
      rarity: "common",
      imageUrl: "https://cdn.starwarsunlimited.com//0302331_EN_Padawan_Starfighter_9b447b5a2b.png",
    },
  ],
  abilities: [
    ability.constant({
      text: "While you control a Force unit or a Force upgrade, this unit gets +1/+1.",
      conditions: [
        {
          type: "controlsTrait",
          controller: "friendly",
          trait: "Force",
        },
      ],
      effects: [effect.modifyStats(target.self(), { power: 1, hp: 1, duration: "continuous" })],
    }),
  ],
} satisfies SwuUnitCard;

export default swuPadawanStarfighter;
