// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuProvidenceDestroyer = {
  title: "Providence Destroyer",
  cost: 8,
  hp: 7,
  power: 5,
  text: "Exploit 2 (While playing this card, defeat up to 2 units you control. This card costs 2 resources less for each unit defeated this way.)\nOn Attack: Give an enemy space unit –2/–2 for this phase.",
  unique: false,
  id: "6436543702",
  rarity: "uncommon",
  aspects: ["villainy", "vigilance"],
  traits: ["separatist", "vehicle", "capital ship"],
  arena: "space",
  keywords: ["exploit"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 38,
  },
  setCodes: [
    {
      set: "TWI",
      number: 38,
    },
  ],
  internalName: "providence-destroyer",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Exploit",
      keyword: "exploit",
    },
    {
      kind: "triggered",
      text: "On Attack: Give an enemy space unit -2/-2 for this phase.",
      trigger: {
        event: "attack",
      },
      effects: [
        {
          type: "modifyStats",
          target: {
            type: "card",
            controller: "opponent",
            zones: ["groundArena", "spaceArena"],
            cardTypes: ["unit", "token"],
            arena: "space",
            excludeSelf: false,
            limit: 1,
          },
          power: -2,
          hp: -2,
          duration: "phase",
        },
      ],
    },
  ],
} satisfies SwuUnitCard;

export default swuProvidenceDestroyer;
