// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuRepublicTacticalOfficer = {
  title: "Republic Tactical Officer",
  cost: 2,
  hp: 4,
  power: 1,
  text: "When Played: You may attack with a Republic unit. It gets +2/+0 for this attack.",
  unique: false,
  rules: "Units must be ready in order to attack.\n",
  id: "2395430106",
  rarity: "common",
  aspects: ["command", "heroism"],
  traits: ["republic", "clone"],
  arena: "ground",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 91,
  },
  setCodes: [
    {
      set: "TWI",
      number: 91,
    },
  ],
  internalName: "republic-tactical-officer",
  cardType: "unit",
  canonicalId: "republic-tactical-officer",
  slug: "republic-tactical-officer",
  name: "Republic Tactical Officer",
  printings: [
    {
      id: "TWI_091",
      artId: "14651",
      setCode: "TWI",
      collectorNumber: "91",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0301091_EN_Republic_Tactical_Officer_c9fae21418.png",
    },
    {
      id: "9043774961",
      artId: "14651",
      setCode: "TWI",
      collectorNumber: "91",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0331091_EN_Republic_Tactical_Officer_da6278dbef.png",
    },
    {
      id: "0709854090",
      artId: "14651",
      setCode: "TWI",
      collectorNumber: "363",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0332363_EN_Republic_Tactical_Officer_5705dafc12.png",
    },
    {
      id: "1756367363",
      artId: "14651",
      setCode: "TWI",
      collectorNumber: "363",
      rarity: "common",
      imageUrl:
        "https://cdn.starwarsunlimited.com//0302363_EN_Republic_Tactical_Officer_97bb240456.png",
    },
  ],
  abilities: [
    {
      kind: "triggered",
      text: "When Played: You may attack with a Republic unit. It gets +2/+0 for this attack.",
      trigger: {
        event: "played",
      },
      effects: [
        {
          type: "optional",
          effects: [
            {
              type: "attack",
              attacker: {
                type: "card",
                controller: "any",
                zones: ["groundArena", "spaceArena"],
                cardTypes: ["unit", "token"],
                excludeSelf: false,
                limit: 1,
              },
              defender: {
                type: "base",
                controller: "opponent",
              },
            },
          ],
        },
      ],
      optional: true,
    },
  ],
} satisfies SwuUnitCard;

export default swuRepublicTacticalOfficer;
