// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuResoluteUnderAnakinsCommand = {
  title: "Resolute",
  subtitle: "Under Anakin's Command",
  cost: 10,
  hp: 8,
  power: 8,
  text: "This unit costs 1 resource less to play for every 5 damage on your base.\nWhen Played/On Attack: Deal 2 damage to an enemy unit and each other enemy unit with the same name as that unit.",
  unique: true,
  rules: "Abilities that refer to a card's “name” do not include the subtitle of the card.\n",
  id: "2585318816",
  rarity: "legendary",
  aspects: ["aggression", "heroism"],
  traits: ["republic", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 151,
  },
  setCodes: [
    {
      set: "TWI",
      number: 151,
    },
  ],
  internalName: "resolute#under-anakins-command",
  cardType: "unit",
  canonicalId: "resolute#under-anakins-command",
  slug: "resolute-under-anakins-command",
  name: "Resolute",
  printings: [
    {
      id: "TWI_151",
      artId: "14936",
      setCode: "TWI",
      collectorNumber: "151",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0301151_EN_Resolute_7d617fc5c3.png",
    },
    {
      id: "6748526848",
      artId: "14936",
      setCode: "TWI",
      collectorNumber: "151",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0331151_EN_Resolute_dac8c2636c.png",
    },
    {
      id: "1823196456",
      artId: "14936",
      setCode: "TWI",
      collectorNumber: "418",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0302418_EN_Resolute_042fdb2037.png",
    },
    {
      id: "2768424298",
      artId: "14936",
      setCode: "TWI",
      collectorNumber: "418",
      rarity: "legendary",
      imageUrl: "https://cdn.starwarsunlimited.com//0332418_EN_Resolute_4ebd95c280.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played: Deal 2 damage to an enemy unit and each other enemy unit with the same name as that unit.",
      effects: [effect.damage(target.unit({ controller: "opponent", limit: 1 }), 2)],
    }),
    ability.onAttack({
      text: "On Attack: Deal 2 damage to an enemy unit and each other enemy unit with the same name as that unit.",
      effects: [effect.damage(target.unit({ controller: "opponent", limit: 1 }), 2)],
    }),
  ],
} satisfies SwuUnitCard;

export default swuResoluteUnderAnakinsCommand;
