// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";

export const swuSanHillChairmanOfTheBankingClan = {
  title: "San Hill",
  subtitle: "Chairman of the Banking Clan",
  cost: 6,
  hp: 7,
  power: 3,
  text: "Exploit 3 (While playing this card, defeat up to 3 units you control. This card costs 2 resources less for each unit defeated this way.)\nOn Attack: For each friendly unit that was defeated this phase, ready a friendly resource.",
  unique: true,
  id: "0021045666",
  rarity: "rare",
  aspects: ["villainy", "cunning"],
  traits: ["separatist", "official"],
  arena: "ground",
  keywords: ["exploit"],
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 186,
  },
  setCodes: [
    {
      set: "TWI",
      number: 186,
    },
  ],
  internalName: "san-hill#chairman-of-the-banking-clan",
  cardType: "unit",
  abilities: [
    {
      kind: "keyword",
      text: "Exploit",
      keyword: "exploit",
    },
  ],
} satisfies SwuUnitCard;

export default swuSanHillChairmanOfTheBankingClan;
