// Generated by tools/import-card-data. Do not edit manually.
import type { SwuUnitCard } from "@tcg/star-wars-unlimited-types";
import { ability, effect, target } from "../../../helpers";

export const swuTranquilityInspiringFlagship = {
  title: "Tranquility",
  subtitle: "Inspiring Flagship",
  cost: 7,
  hp: 6,
  power: 7,
  text: "When Played: You may return a Republic unit from your discard pile to your hand.\nOn Attack: Each of the next 3 Republic cards you play this phase costs 1 resource less.",
  unique: true,
  rules:
    "The cost reduction from Tranquility's “On Attack” ability remains active even if Tranquility is defeated.\n",
  id: "6570091935",
  rarity: "rare",
  aspects: ["heroism"],
  traits: ["republic", "vehicle", "capital ship"],
  arena: "space",
  types: ["unit"],
  setId: {
    set: "TWI",
    number: 246,
  },
  setCodes: [
    {
      set: "TWI",
      number: 246,
    },
  ],
  internalName: "tranquility#inspiring-flagship",
  cardType: "unit",
  canonicalId: "tranquility#inspiring-flagship",
  slug: "tranquility-inspiring-flagship",
  name: "Tranquility",
  printings: [
    {
      id: "TWI_246",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "246",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0301246_EN_Tranquility_8a59a18e3c.png",
    },
    {
      id: "3628987731",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "2",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0363002b_EN_Tranquility_7897367d9f.png",
    },
    {
      id: "4384520773",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "2",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0362002b_EN_Tranquility_88d5ab39a6.png",
    },
    {
      id: "5723448268",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "2",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0364002b_EN_Tranquility_7ca63fc3de.png",
    },
    {
      id: "7275733525",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "2",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0365002b_EN_Tranquility_b227d0e0bf.png",
    },
    {
      id: "9207608938",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "2",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0366002b_EN_Tranquility_73c24ad496.png",
    },
    {
      id: "6749870022",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "246",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0331246_EN_Tranquility_d347ae0dbb.png",
    },
    {
      id: "3373779372",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "507",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0332507_EN_Tranquility_f6ff19ef62.png",
    },
    {
      id: "8118431686",
      artId: "15391",
      setCode: "TWI",
      collectorNumber: "507",
      rarity: "rare",
      imageUrl: "https://cdn.starwarsunlimited.com//0302507_EN_Tranquility_c6b5e7aadf.png",
    },
  ],
  abilities: [
    ability.whenPlayed({
      text: "When Played: You may return a Republic unit from your discard pile to your hand.",
      optional: true,
      effects: [
        effect.move(
          target.unit({
            controller: "friendly",
            zones: ["discard"],
            traits: ["republic"],
            limit: 1,
          }),
          "hand",
        ),
      ],
    }),
  ],
} satisfies SwuUnitCard;

export default swuTranquilityInspiringFlagship;
