import type { UnitCard } from "@tcg/gundam-types";

export const tGundam001: UnitCard = {
  cardNumber: "T-001",
  name: "Gundam",
  type: "unit",
  traits: ["white base team"],
  id: "T-001",
  externalId: "gundam:t-001",
  slug: "gundam-t-001",
  displayName: "Gundam",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "T-001",
  printings: [
    {
      id: "T-001",
      collectorNumber: "T-001",
      cardNumber: "T-001",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-001.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-001.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "T-001_p1",
      collectorNumber: "T-001_p1",
      cardNumber: "T-001",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-001_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-001_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "T-001",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-001.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-001.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 3,
  hp: 3,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st01Gundam001 = tGundam001;
