import type { UnitCard } from "@tcg/gundam-types";

export const tGuncannon002: UnitCard = {
  cardNumber: "T-002",
  name: "Guncannon",
  type: "unit",
  traits: ["white base team"],
  id: "T-002",
  externalId: "gundam:t-002",
  slug: "guncannon-t-002",
  displayName: "Guncannon",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "T-002",
  printings: [
    {
      id: "T-002",
      collectorNumber: "T-002",
      cardNumber: "T-002",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-002.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-002.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "T-002_p1",
      collectorNumber: "T-002_p1",
      cardNumber: "T-002",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-002_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-002_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "T-002",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-002.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-002.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 2,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st01Guncannon002 = tGuncannon002;
