import type { UnitCard } from "@tcg/gundam-types";

export const tGuntank003: UnitCard = {
  cardNumber: "T-003",
  name: "Guntank",
  type: "unit",
  traits: ["white base team"],
  id: "T-003",
  externalId: "gundam:t-003",
  slug: "guntank-t-003",
  displayName: "Guntank",
  set: { code: "ST01", name: "Heroic Beginnings [ST01]", packageId: "616001" },
  printNumber: "T-003",
  printings: [
    {
      id: "T-003",
      collectorNumber: "T-003",
      cardNumber: "T-003",
      set: {
        code: "ST01",
        name: "Heroic Beginnings [ST01]",
        packageId: "616001",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-003.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-003.webp?260424",
      productName: "Heroic Beginnings [ST01]",
    },
    {
      id: "T-003_p1",
      collectorNumber: "T-003_p1",
      cardNumber: "T-003",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-003_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-003_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "T-003",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-003.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-003.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 1,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st01Guntank003 = tGuntank003;
