import type { UnitCard } from "@tcg/gundam-types";

export const tLeo004: UnitCard = {
  cardNumber: "T-004",
  name: "Leo",
  type: "unit",
  traits: ["oz"],
  id: "T-004",
  canonicalId: "T-004",
  externalIds: { bandai: "gundam:t-004" },
  slug: "leo/t-004",
  displayName: "Leo",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "T-004",
  printings: [
    {
      id: "T-004",
      artId: "T-004",
      setCode: "ST02",
      collectorNumber: "T-004",
      cardNumber: "T-004",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-004.webp",
      productName: "Wings of Advance [ST02]",
    },
  ],
  reprints: ["T-004"],
  selectedPrintingId: "T-004",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-004.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 1,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st02Leo004 = tLeo004;
