import type { UnitCard } from "@tcg/gundam-types";

export const tTallgeese005: UnitCard = {
  cardNumber: "T-005",
  name: "Tallgeese",
  type: "unit",
  traits: ["oz"],
  id: "T-005",
  canonicalId: "T-005",
  externalIds: { bandai: "gundam:t-005" },
  slug: "tallgeese/t-005",
  displayName: "Tallgeese",
  set: { code: "ST02", name: "Wings of Advance [ST02]", packageId: "616002" },
  printNumber: "T-005",
  printings: [
    {
      id: "T-005",
      artId: "T-005",
      setCode: "ST02",
      collectorNumber: "T-005",
      cardNumber: "T-005",
      set: {
        code: "ST02",
        name: "Wings of Advance [ST02]",
        packageId: "616002",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-005.webp",
      productName: "Wings of Advance [ST02]",
    },
  ],
  reprints: ["T-005"],
  selectedPrintingId: "T-005",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-005.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 4,
  hp: 2,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st02Tallgeese005 = tTallgeese005;
