import type { UnitCard } from "@tcg/gundam-types";

export const tCharSZaku006: UnitCard = {
  cardNumber: "T-006",
  name: "Char's Zaku Ⅱ",
  type: "unit",
  traits: ["zeon"],
  id: "T-006",
  externalId: "gundam:t-006",
  slug: "char-s-zaku-t-006",
  displayName: "Char's Zaku Ⅱ",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "T-006",
  printings: [
    {
      id: "T-006",
      collectorNumber: "T-006",
      cardNumber: "T-006",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-006.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-006.webp?260424",
      productName: "Zeon's Rush [ST03]",
    },
    {
      id: "T-006_p1",
      collectorNumber: "T-006_p1",
      cardNumber: "T-006",
      set: {
        code: "BETA",
        name: "Edition Beta",
        packageId: "616000",
      },
      rarity: "common",
      finish: "parallel",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-006_p1.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-006_p1.webp?260424",
      productName: "Edition Beta",
    },
  ],
  selectedPrintingId: "T-006",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-006.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-006.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 3,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st03CharSZaku006 = tCharSZaku006;
