import type { UnitCard } from "@tcg/gundam-types";

export const tZaku007: UnitCard = {
  cardNumber: "T-007",
  name: "Zaku Ⅱ",
  type: "unit",
  traits: ["zeon"],
  id: "T-007",
  canonicalId: "T-007",
  externalIds: { bandai: "gundam:t-007" },
  slug: "zaku-ii/t-007",
  displayName: "Zaku Ⅱ",
  set: { code: "ST03", name: "Zeon's Rush [ST03]", packageId: "616003" },
  printNumber: "T-007",
  printings: [
    {
      id: "T-007",
      artId: "T-007",
      setCode: "ST03",
      collectorNumber: "T-007",
      cardNumber: "T-007",
      set: {
        code: "ST03",
        name: "Zeon's Rush [ST03]",
        packageId: "616003",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-007.webp",
      productName: "Zeon's Rush [ST03]",
    },
  ],
  reprints: ["T-007"],
  selectedPrintingId: "T-007",
  imageUrl: "https://cdn.tcg.online/public/gundam/cards/t/T-007.webp",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 1,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const st03Zaku007 = tZaku007;
