import type { UnitCard } from "@tcg/gundam-types";

export const tDaughtress012: UnitCard = {
  cardNumber: "T-012",
  name: "Daughtress",
  type: "unit",
  traits: ["new une"],
  id: "T-012",
  canonicalId: "T-012",
  externalIds: { bandai: "gundam:t-012" },
  slug: "daughtress/t-012",
  displayName: "Daughtress",
  set: { code: "GD02", name: "-", packageId: "616102" },
  printNumber: "T-012",
  printings: [
    {
      id: "T-012",
      artId: "T-012",
      setCode: "GD02",
      collectorNumber: "T-012",
      cardNumber: "T-012",
      set: {
        code: "GD02",
        name: "-",
        packageId: "616102",
      },
      rarity: "common",
      finish: "standard",
      imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-012.webp",
      sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-012.webp?260424",
    },
  ],
  reprints: ["T-012"],
  selectedPrintingId: "T-012",
  imageUrl: "https://r2.tcg.online/public/gundam/cards/t/T-012.webp",
  sourceImageUrl: "https://www.gundam-gcg.com/en/images/cards/card/T-012.webp?260424",
  legality: "legal",
  level: 0,
  cost: 0,
  ap: 0,
  hp: 1,
  effect: "-",
  effects: [],
  keywordEffects: [],
  rarity: "common",
};
export const gd02Daughtress012 = tDaughtress012;
